const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {createAIRouter,endpoint}=require('../electron/ai-router.cjs');
const vault={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from('test-vault:'+s),decryptString:b=>b.toString().slice(11)};
async function setup(t,fetchImpl){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-router-test-'));const router=createAIRouter({directory,safeStorage:vault,modelHub:{state:()=>({models:[]})},fetchImpl});t.after(async()=>{await router.stop();if(path.dirname(directory)===os.tmpdir())fs.rmSync(directory,{recursive:true,force:true})});return {router,directory}}
async function port(){const s=http.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const value=s.address().port;await new Promise(r=>s.close(r));return value}
const reply=()=>Response.json({choices:[{message:{role:'assistant',content:'Hello'},finish_reason:'stop'}]});
function connect(router,name='Account',baseURL='https://example.com/v1'){return router.saveAccount({name,baseURL,protocol:'openai',key:'private-account-secret'})}
test('connections encrypt credentials and clear them when endpoint changes',async t=>{const {router,directory}=await setup(t,async()=>reply());const id=connect(router);assert.ok(!JSON.stringify(router.state()).includes('private-account-secret'));assert.ok(!fs.readFileSync(path.join(directory,'ai-router.json'),'utf8').includes('private-account-secret'));router.saveAccount({id,name:'Changed',protocol:'openai',baseURL:'https://other.example/v1'});assert.equal(router.state().accounts[0].hasKey,false);assert.throws(()=>endpoint('http://remote.example/v1'));assert.throws(()=>endpoint('https://u:pass@example.com/v1'))});
test('API always requires key including spoofed Host; lists routes, not credentials',async t=>{const {router}=await setup(t,async()=>reply());const id=connect(router);router.saveRoute({name:'work',strategy:'fallback',targets:[{accountId:id,model:'upstream-model'}]});await router.start(await port());const url=router.state().baseURL;assert.equal((await fetch(url+'/models',{headers:{Host:'localhost'}})).status,401);const result=await fetch(url+'/models',{headers:{Authorization:'Bearer '+router.key()}});assert.equal((await result.json()).data[0].id,'work');const key=router.key();router.rotateKey();assert.equal((await fetch(url+'/models',{headers:{Authorization:'Bearer '+key}})).status,401)});
test('fallback carries complete tool messages to next account after quota failure',async t=>{const calls=[];const {router}=await setup(t,async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return calls.length===1?new Response('',{status:429}):reply()});const a=connect(router,'Primary'),b=connect(router,'Secondary','https://second.example/v1');router.saveRoute({name:'work',strategy:'fallback',targets:[{accountId:a,model:'one'},{accountId:b,model:'two'}]});const messages=[{role:'tool',tool_call_id:'call-1',content:'File written'}];const result=await router.complete({model:'work',messages,tools:[{type:'function',function:{name:'write_file'}}]});assert.equal(result.status,200);assert.deepEqual(calls[1].body.messages,messages);assert.equal(calls[1].body.model,'two');assert.equal(calls[1].body.tools[0].function.name,'write_file');assert.equal(router.state().events.length,2)});
test('round-robin alternates accounts and disabled accounts are skipped',async t=>{const calls=[];const {router}=await setup(t,async(url)=>{calls.push(url);return reply()});const a=connect(router),b=connect(router,'Second','https://second.example/v1');router.saveRoute({name:'pool',strategy:'round-robin',targets:[{accountId:a,model:'a'},{accountId:b,model:'b'}]});const request={model:'pool',messages:[{role:'user',content:'Hi'}]};await router.complete(request);await router.complete(request);assert.notEqual(calls[0],calls[1]);router.saveAccount({...router.state().accounts[0],enabled:false});await router.complete(request);assert.match(calls[2],/second/)});
test('native SSE reaches HTTP client intact and non-streaming responses have OpenAI envelope',async t=>{const {router}=await setup(t,async(url,options)=>JSON.parse(options.body).stream?new Response('data: {"choices":[{"delta":{"content":"Hi"}}]}\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}}):reply());const a=connect(router);router.saveRoute({name:'work',strategy:'fallback',targets:[{accountId:a,model:'one'}]});await router.start(await port());const send=stream=>fetch(router.state().baseURL+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+router.key(),'Content-Type':'application/json'},body:JSON.stringify({model:'work',messages:[{role:'user',content:'Hi'}],stream})});const streamed=await send(true);assert.match(await streamed.text(),/data: \[DONE\]/);const result=await (await send(false)).json();assert.equal(result.object,'chat.completion');assert.equal(result.model,'work');assert.ok(result.id)});
test('Anthropic tool responses convert to OpenAI tool calls and buffered SSE',async t=>{const {router}=await setup(t,async()=>Response.json({content:[{type:'tool_use',id:'call-1',name:'write_file',input:{path:'a.txt'}}],stop_reason:'tool_use'}));const a=router.saveAccount({name:'Claude',protocol:'anthropic',baseURL:'https://api.anthropic.com/v1',key:'key'});router.saveRoute({name:'claude',strategy:'fallback',targets:[{accountId:a,model:'claude-test'}]});await router.start(await port());const r=await fetch(router.state().baseURL+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+router.key(),'Content-Type':'application/json'},body:JSON.stringify({model:'claude',messages:[{role:'user',content:'Write'}],stream:true})});const body=await r.text();assert.match(body,/tool_calls/);assert.match(body,/write_file/);assert.match(body,/"index":0/)});
test('caller cancellation does not trigger a fallback request',async t=>{let calls=0;const {router}=await setup(t,async(_url,{signal})=>{calls++;return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('Aborted')),{once:true}))});const a=connect(router),b=connect(router,'Second');router.saveRoute({name:'work',strategy:'fallback',targets:[{accountId:a,model:'a'},{accountId:b,model:'b'}]});const control=new AbortController();const result=router.complete({model:'work',messages:[{role:'user',content:'Hi'}]},control.signal);await new Promise(r=>setImmediate(r));control.abort();await assert.rejects(result);assert.equal(calls,1)});
test('models endpoint discovers and publishes upstream and manual models for browser clients',async t=>{let discovery=0,lastModel;const {router}=await setup(t,async(url,options)=>{if(url.endsWith('/models')){discovery++;return Response.json({data:[{id:'discovered-model'}]})}lastModel=JSON.parse(options.body).model;return reply()});router.saveAccount({name:'Provider',baseURL:'https://example.com/v1',protocol:'openai',manualModels:['manual-model']});await router.start(await port());const base=router.state().baseURL;const preflight=await fetch(base+'/models',{method:'OPTIONS',headers:{Origin:'https://client.example','Access-Control-Request-Method':'GET','Access-Control-Request-Headers':'authorization'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),'*');const response=await fetch(base+'/models',{headers:{Authorization:'Bearer '+router.key(),Origin:'https://client.example'}});assert.equal(response.status,200);assert.deepEqual((await response.json()).data.map(m=>m.id),['discovered-model','manual-model']);await fetch(base+'/models',{headers:{Authorization:'Bearer '+router.key()}});assert.equal(discovery,1);assert.equal((await router.complete({model:'discovered-model',messages:[{role:'user',content:'Hi'}]})).status,200);assert.equal(lastModel,'discovered-model')});
test('manually registered models remain discoverable when upstream has no catalog',async t=>{const {router}=await setup(t,async()=>new Response('',{status:404}));router.saveAccount({name:'No catalog',baseURL:'https://example.com/v1',protocol:'openai',manualModels:'custom-a\ncustom-b'});await router.start(await port());const r=await fetch(router.state().baseURL+'/models',{headers:{Authorization:'Bearer '+router.key()}});assert.equal(r.status,200);assert.deepEqual((await r.json()).data.map(m=>m.id),['custom-a','custom-b'])});
test('installed local models are published without manual routes and API check verifies HTTP',async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-local-router-'));let installed=[{id:'qwen-small',kind:'chat',installed:true},{id:'qwen-coder',kind:'chat',installed:true},{id:'not-downloaded',kind:'chat',installed:false},{id:'image-model',kind:'image',installed:true}];
 const router=createAIRouter({directory,safeStorage:vault,modelHub:{state:()=>({models:installed}),complete:async()=>reply()}});
 t.after(async()=>{await router.stop();fs.rmSync(directory,{recursive:true,force:true})});
 router.saveAccount({name:'Orvio local models',protocol:'local'});
 await assert.rejects(router.check(),/Start the API/);await router.start(await port());
 assert.deepEqual((await router.check()).models,['qwen-small','qwen-coder']);
 const response=await fetch(router.state().baseURL+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+router.key(),'Content-Type':'application/json'},body:JSON.stringify({model:'qwen-small',messages:[{role:'user',content:'Hi'}]})});assert.equal(response.status,200);
 installed=[];await assert.rejects(router.check(),/no models/);
});
test('Anthropic model discovery follows pagination without publishing duplicate IDs',async t=>{
 const urls=[];const {router}=await setup(t,async url=>{urls.push(url);return Response.json(url.includes('after_id')?{data:[{id:'model-b'},{id:'model-a'}],has_more:false}:{data:[{id:'model-a'}],last_id:'model-a',has_more:true})});
 const id=router.saveAccount({name:'Claude API',protocol:'anthropic',baseURL:'https://api.anthropic.com/v1',key:'test'});assert.deepEqual(await router.models(id),['model-a','model-b']);assert.match(urls[1],/after_id=model-a/);
});
test('refresh reports provider errors and retains previously discovered models',async t=>{
 let fail=false;const {router}=await setup(t,async()=>fail?new Response('',{status:401}):Response.json({data:[{id:'cached-model'}]}));connect(router);await router.refresh();fail=true;const results=await router.refresh();assert.equal(results[0].ok,false);assert.match(router.state().accounts[0].health.message,/401/);assert.equal(router.state().availableModels[0].id,'cached-model');
});

test('native OAuth account discovers and routes using its refreshed token without exposing credentials',async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-native-route-'));let calls=[];
 const router=createAIRouter({directory,safeStorage:vault,modelHub:{state:()=>({models:[]})},nativeAuth:{token:async()=> 'refreshed-private',remove:()=>{}},fetchImpl:async(url,options)=>{calls.push(options);return url.endsWith('/models')?Response.json({data:[{id:'native-model'}]}):reply()}});
 t.after(async()=>{await router.stop();fs.rmSync(directory,{recursive:true,force:true})});const id=router.attachOAuth({providerId:'openrouter',authId:'auth-ref',name:'My account'});await router.models(id);assert.equal(router.state().availableModels[0].id,'native-model');assert.equal((await router.complete({model:'native-model',messages:[{role:'user',content:'Hi'}]})).status,200);assert.equal(calls[1].headers.Authorization,'Bearer refreshed-private');assert.ok(!JSON.stringify(router.state()).includes('refreshed-private'));
});
test('access-denied native accounts stop publishing stale models until discovery succeeds',async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-denied-'));let denied=false;
 const router=createAIRouter({directory,safeStorage:vault,modelHub:{state:()=>({models:[]})},nativeAuth:{token:async()=> 'token'},fetchImpl:async()=>denied?Response.json({error:{}},{status:403}):Response.json({models:{'native-model':{}}})});
 t.after(async()=>{await router.stop();fs.rmSync(directory,{recursive:true,force:true})});const id=router.attachOAuth({providerId:'antigravity',authId:'ref',project:'project'});await router.models(id);assert.equal(router.state().availableModels.length,1);denied=true;await assert.rejects(router.test(id),/Google denied/);assert.equal(router.state().availableModels.length,0);assert.equal(router.state().accounts[0].discoveryDenied,true);denied=false;await router.models(id);assert.equal(router.state().availableModels.length,1);
});
