const {test}=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {createDictation}=require('../electron/dictation.cjs'),{keyGroups}=require('../electron/dictation-hotkey.cjs'),{applySnippets}=require('../electron/dictation-text.cjs');
function fixture(t,{live=true,changed=false,config={},recognize,fieldRequest,platform='win32'}={}){const handlers={},requests=[],copied=[],pasted=[],windows=[];let release,stopCount=0;
 class Window extends EventEmitter{constructor(){super();this.webContents=new EventEmitter();this.webContents.mainFrame={};this.webContents.setWindowOpenHandler=()=>{};this.webContents.send=(name)=>requests.push(name);windows.push(this)}loadURL(){}showInactive(){}destroy(){if(this.closed)return;this.closed=true;this.emit('closed')}}
 const field={close(){},async request(action,text){requests.push([action,text]);if(fieldRequest)return fieldRequest(action,text);if(action==='capture')return {live,tracked:true};return {ok:!changed}}};
 const api=createDictation({app:{isPackaged:false},BrowserWindow:Window,screen:{getCursorScreenPoint:()=>({x:0,y:0}),getDisplayNearestPoint:()=>({workArea:{x:0,y:0,width:1200,height:800}})},ipcMain:{handle:(name,fn)=>handlers[name]=fn},clipboard:{writeText:t=>copied.push(t)},systemPreferences:{},localStudio:{state:()=>({models:[{id:'whisper',installed:true}]}),dictationTranscribe:recognize|| (async()=>({segments:[{text:'Hello there.'}]}))},modelHub:{},settings:{state:()=>({dictationModel:'whisper',dictationLanguage:'auto',dictationMode:'hold',liveInsert:true,rewrite:false,voiceCommands:true,shortcuts:{dictation:'Control+Shift+Space'},...config})},pausePet(){},resumePet(){},python:'unused',resources:'unused',platform,fieldFactory:()=>field,watch:options=>{release=options.onRelease;return()=>stopCount++},getForeground:async()=>({identity:'1',name:'Test editor'}),sendKey:async c=>requests.push(['key',c]),pasteText:async(_,text)=>{pasted.push(text);return 'Paste requested'},waitKeys:async()=>true});
 t.after(()=>api.close());const call=(name,...args)=>handlers['dictation:'+name]({sender:windows.at(-1).webContents,senderFrame:windows.at(-1).webContents.mainFrame},...args);
 return {api,call,requests,copied,pasted,windows,release:()=>release(),stopCount:()=>stopCount};
}
test('hold shortcut maps physical keys for Mac and Windows',()=>{assert.deepEqual(keyGroups('CommandOrControl+Shift+Space','darwin'),[[55,54],[56,60],[49]]);assert.deepEqual(keyGroups('CommandOrControl+Shift+Space','win32'),[[162,163],[160,161],[32]]);assert.throws(()=>keyGroups('Control+VolumeUp','win32'),/hold-to-talk/)});
test('release before microphone arm is remembered; release while armed signals finish',async t=>{const f=fixture(t);await f.api.shortcut();f.release();assert.equal((await f.call('arm')).released,true);await f.call('idle');await f.api.shortcut();await f.call('arm');f.release();assert.ok(f.requests.includes('dictation:finish'))});
test('live partial and final replace the same owned field without duplicate paste',async t=>{const f=fixture(t);await f.api.shortcut();await f.call('arm');const bytes=new ArrayBuffer(100);await f.call('partial',bytes);const result=await f.call('finish',bytes);assert.match(result,/Inserted/);assert.equal(f.pasted.length,0);assert.deepEqual(f.requests.filter(r=>Array.isArray(r)&&r[0]==='replace'),[['replace','Hello there.'],['replace','Hello there.']]);assert.equal(f.copied[0],'Hello there.')});
test('unsupported live field falls back to automatic paste on release',async t=>{const f=fixture(t,{live:false});await f.api.shortcut();await f.call('arm');await f.call('finish',new ArrayBuffer(100));assert.deepEqual(f.pasted,['Hello there.'])});
test('changed target copies text without overwriting another field',async t=>{const f=fixture(t,{changed:true});await f.api.shortcut();await f.call('arm');await f.call('partial',new ArrayBuffer(100));await f.call('finish',new ArrayBuffer(100));assert.equal(f.pasted.length,0);assert.deepEqual(f.copied,['Hello there.'])});
test('cancelling while inference runs never inserts its late result',async t=>{let resolve;const f=fixture(t,{recognize:()=>new Promise(r=>resolve=r)});await f.api.shortcut();await f.call('arm');const partial=f.call('partial',new ArrayBuffer(100));f.api.close();resolve({segments:[{text:'Late speech'}]});await partial;assert.equal(f.requests.filter(r=>Array.isArray(r)&&r[0]==='replace').length,0);assert.equal(f.pasted.length,0);assert.equal(f.requests.filter(r=>Array.isArray(r)&&r[0]==='rollback').length,0)});
test('spoken shortcuts expand exact utterances only',()=>{const snippets=[{phrase:'my signature',text:'Naeem\nOrvio'}];assert.equal(applySnippets('My signature.',snippets),'Naeem\nOrvio');assert.equal(applySnippets('Please change my signature.',snippets),'Please change my signature.')});
test('PCM encoder produces valid mono 16kHz WAV and clamps samples',()=>{const fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/dictation-audio.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports});const wav=Buffer.from(module.exports.pcmWave([new Float32Array([-2,0,2])]));assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(wav.readUInt32LE(24),16000);assert.equal(wav.readUInt32LE(40),6);assert.equal(wav.readInt16LE(44),-32768);assert.equal(wav.readInt16LE(48),32767)});

test('macOS final paste uses native keyboard delivery without AppleScript automation',async t=>{const f=fixture(t,{live:false,platform:'darwin'});await f.api.shortcut();await f.call('arm');const result=await f.call('finish',new ArrayBuffer(100));assert.match(result,/Inserted/);assert.ok(f.requests.some(r=>Array.isArray(r)&&r[0]==='paste'));assert.equal(f.pasted.length,0)});
test('holding a single key ignores OS repeat and finishes only on release',async t=>{assert.deepEqual(keyGroups('Space','darwin'),[[49]]);assert.deepEqual(keyGroups('Space','win32'),[[32]]);const f=fixture(t,{live:false,config:{shortcuts:{dictation:'Space'}}});await f.api.shortcut();await f.call('arm');for(let i=0;i<5;i++)await f.api.shortcut();assert.equal(f.requests.filter(r=>r==='dictation:finish').length,0);f.release();assert.equal(f.requests.filter(r=>r==='dictation:finish').length,1);await f.call('finish',new ArrayBuffer(100));assert.deepEqual(f.pasted,['Hello there.'])});

test('destination capture completes before the recording overlay is created',async t=>{let captured;const f=fixture(t,{fieldRequest:action=>action==='capture'?new Promise(resolve=>captured=resolve):Promise.resolve({ok:true})});const opening=f.api.shortcut();assert.equal(f.windows.length,0);captured({live:false,tracked:true});await opening;assert.equal(f.windows.length,1)});
test('native helper failure is not mislabeled as focus loss',async t=>{const f=fixture(t,{platform:'darwin',fieldRequest:async action=>action==='capture'?{live:false,tracked:false}:action==='paste'?{ok:false,reason:'unavailable'}:{ok:true}});await f.api.shortcut();await f.call('arm');const result=await f.call('finish',new ArrayBuffer(100));assert.match(result,/Typing connection unavailable/);assert.doesNotMatch(result,/no longer focused/)});

test('completed sessions can be restarted repeatedly before their popup closes',async t=>{const f=fixture(t,{live:false});for(let i=0;i<4;i++){await f.api.shortcut();await f.call('arm');await f.call('finish',new ArrayBuffer(100));await f.call('idle');}assert.equal(f.windows.length,4);assert.equal(f.pasted.length,4);assert.equal(f.requests.filter(r=>Array.isArray(r)&&r[0]==='capture').length,4);assert.equal(f.requests.filter(r=>Array.isArray(r)&&r[0]==='rollback').length,0)});
test('microphone startup failure releases the session for another attempt',async t=>{const f=fixture(t);await f.api.shortcut();await f.call('arm');await f.call('idle');await f.api.shortcut();assert.equal(f.windows.length,2);assert.equal((await f.call('arm')).released,false)});
test('unverified Mac delivery does not claim text was inserted',async t=>{const f=fixture(t,{platform:'darwin',fieldRequest:async action=>action==='capture'?{live:false,tracked:true}:action==='paste'?{ok:true,verified:false}:{ok:true}});await f.api.shortcut();await f.call('arm');const result=await f.call('finish',new ArrayBuffer(100));assert.match(result,/Paste requested/);assert.doesNotMatch(result,/Inserted/)});
