const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createDownloads}=require('../electron/downloads.cjs');
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-downloads-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return directory}
test('download history uses real byte counts and distinguishes setup, cancellation and completion',t=>{const directory=fixture(t);let cancelled=false;const downloads=createDownloads({directory});const id=downloads.begin({title:'Voice model',kind:'model',cancel:()=>cancelled=true});downloads.update(id,{received:25,total:100,speed:10});assert.equal(downloads.state()[0].percent,25);downloads.update(id,{message:'Installing',total:null,received:0});assert.equal(downloads.state()[0].percent,null);downloads.cancel(id);assert.equal(cancelled,true);assert.equal(downloads.state()[0].status,'active');downloads.finish(id,'cancelled',{message:'Cancelled'});assert.equal(downloads.state()[0].cancellable,false);const video=downloads.begin({title:'Video',kind:'video'});downloads.finish(video,'completed',{assetId:'saved-video'});assert.equal(downloads.state()[0].percent,100);assert.equal(downloads.state()[0].assetId,'saved-video');downloads.clear();assert.deepEqual(downloads.state(),[])});
test('reopening marks incomplete transfers interrupted without inventing completion',t=>{const directory=fixture(t);const first=createDownloads({directory});const id=first.begin({title:'Model',kind:'model',cancel:()=>{}});first.update(id,{received:10,total:100,url:'https://example.test/?token=secret'});const next=createDownloads({directory});assert.equal(next.state()[0].status,'interrupted');assert.equal(next.state()[0].cancellable,false);assert.ok(!fs.readFileSync(path.join(directory,'download-history.json'),'utf8').includes('secret'))});
const {recommendation}=require('../electron/hardware.cjs');
test('hardware recommendations distinguish memory pressure and actual runtime limits',()=>{assert.equal(recommendation({kind:'chat',ramGB:12},{ramGB:8}).level,'heavy');assert.match(recommendation({kind:'chat',ramGB:4},{ramGB:16,platform:'win32',arch:'x64'}).detail,/CPU/);assert.equal(recommendation({kind:'image',ramGB:8},{ramGB:16,platform:'darwin',arch:'arm64'}).level,'good');assert.equal(recommendation({kind:'video',ramGB:16},{ramGB:32,platform:'win32',arch:'x64'}).level,'slow')});
const {createModelHub}=require('../electron/model-hub.cjs');
test('online model discovery only accepts public GGUF files and trusted repository identifiers',async t=>{const directory=fixture(t);let requests=0;const hub=createModelHub({directory,python:'missing',localStudio:{state:()=>({models:[],active:null}),cancel(){}},fetchImpl:async url=>{requests++;return Response.json({cardData:{license:'apache-2.0'},siblings:[{rfilename:'model.gguf',size:100,lfs:{sha256:'a'.repeat(64)}},{rfilename:'model.py'},{rfilename:'folder/model.gguf'},{rfilename:'model-00001-of-00002.gguf'}]})}});await assert.rejects(()=>hub.remoteFiles('https://evil.example/repo'),/repository/);assert.equal(requests,0);const files=await hub.remoteFiles('owner/model');assert.equal(files.files.length,1);assert.equal(files.files[0].name,'model.gguf');assert.equal(files.license,'apache-2.0');await assert.rejects(()=>hub.installRemote({repo:'owner/model',filename:'model.py'}),/GGUF/);assert.equal(hub.state().models.find(m=>m.id==='qwen-small').installed,false)});
const {createDownloadQueue}=require('../electron/download-queue.cjs');
const {AsyncLocalStorage}=require('node:async_hooks');
test('three downloads run concurrently, queued cancellation is isolated, and each keeps its progress context',async()=>{const queue=createDownloadQueue(3),storage=new AsyncLocalStorage();let active=0,peak=0;const release=[];const observed=[];function submit(id,signal){return storage.run(id,()=>queue.run(async()=>{active++;peak=Math.max(peak,active);observed.push(storage.getStore());await new Promise(resolve=>release.push(resolve));observed.push(storage.getStore());active--;return id},signal))}const first=[submit('one'),submit('two'),submit('three')];const controller=new AbortController(),cancelled=submit('cancelled',controller.signal),last=submit('four');const rejected=assert.rejects(cancelled,/Cancelled/);await new Promise(resolve=>setImmediate(resolve));assert.equal(peak,3);controller.abort();await rejected;release.shift()();await new Promise(resolve=>setImmediate(resolve));assert.ok(observed.includes('four'));assert.ok(!observed.includes('cancelled'));for(const done of release)done();assert.deepEqual(await Promise.all([...first,last]),['one','two','three','four']);assert.equal(peak,3);for(const id of ['one','two','three','four'])assert.equal(observed.filter(x=>x===id).length,2)});
test('shared engine setup is serialized while independent models may download together',async()=>{const queue=createDownloadQueue();let writes=0,peak=0;await Promise.all([1,2,3].map(()=>queue.lock('same-engine',async()=>{writes++;peak=Math.max(peak,writes);await new Promise(resolve=>setTimeout(resolve,5));writes--})));assert.equal(peak,1)});
const {createWorkspace}=require('../electron/workspace.cjs');
test('local chat provider uses the embedded model transport without API credentials',async t=>{const directory=fixture(t);let request;const hub={state:()=>({models:[{id:'local-chat',kind:'chat',installed:true}]}),complete:async(id,payload)=>{request={id,payload};return Response.json({choices:[{message:{content:'A caption from this computer.'}}]})}};const workspace=createWorkspace({directory,modelHub:hub,safeStorage:{isEncryptionAvailable:()=>true,encryptString:Buffer.from,decryptString:x=>x.toString()},fetchImpl:()=>{throw Error('Cloud network must not be used')}});workspace.saveAI({provider:'local',model:'local-chat',key:'never-store-this'});assert.equal(workspace.snapshot().ai.hasKey,false);assert.deepEqual(await workspace.listModels({provider:'local'}),['local-chat']);assert.equal(await workspace.generate('A peaceful garden'),'A caption from this computer.');assert.equal(request.id,'local-chat');assert.ok(!fs.readFileSync(path.join(directory,'workspace-v3.json'),'utf8').includes('never-store-this'))});
test('paused downloads retain private retry information across restart and resume the same history entry',async t=>{const directory=fixture(t),first=createDownloads({directory});let id;first.registerRetry('video',async input=>{assert.equal(input.url,'https://example.test/video');id=first.begin({title:'Video',kind:'video',retry:{type:'video',input},cancel:()=>{}});return id});id=first.begin({title:'Video',kind:'video',retry:{type:'video',input:{url:'https://example.test/video'}},cancel:()=>{}});first.pause(id);first.finish(id,'cancelled');assert.equal(first.state()[0].status,'paused');assert.equal(first.state()[0].retryable,true);assert.ok(!JSON.stringify(first.state()).includes('https://'));const next=createDownloads({directory});next.registerRetry('video',async input=>{const resumed=next.begin({title:'Video',kind:'video',retry:{type:'video',input}});assert.equal(resumed,id);next.finish(resumed,'completed')});await next.retry(id);assert.equal(next.state().length,1);assert.equal(next.state()[0].status,'completed')});

test('download thumbnails update during transfer and survive completion and reopening',t=>{const directory=fixture(t),downloads=createDownloads({directory});const id=downloads.begin({title:'Video',kind:'video'});downloads.update(id,{thumbnail:'file:///private.jpg'});assert.equal(downloads.state()[0].thumbnail,undefined);downloads.update(id,{thumbnail:'https://example.com/cover.jpg'});assert.equal(downloads.state()[0].thumbnail,'https://example.com/cover.jpg');downloads.update(id,{thumbnail:null,message:'Converting'});downloads.finish(id,'completed');assert.equal(createDownloads({directory}).state()[0].thumbnail,'https://example.com/cover.jpg')});

test('shutdown preserves progress and restart recovers interrupted transfers but leaves paused jobs alone',async t=>{
 const directory=fixture(t),first=createDownloads({directory});
 const id=first.begin({title:'GPU runtime',kind:'runtime',retry:{type:'gpu-runtime',input:{id:'image'}}});
 first.update(id,{received:250,total:1000});
 const paused=first.begin({title:'Paused',kind:'file',retry:{type:'file',input:{}},cancel:()=>{}});
 first.pause(paused);first.finish(paused,'cancelled');
 first.prepareShutdown();first.finish(id,'cancelled');
 const next=createDownloads({directory});assert.equal(next.state().find(d=>d.id===id).received,250);
 next.registerRetry('file',()=>{throw Error('Paused transfer must stay paused')});
 next.registerRetry('gpu-runtime',input=>{const resumed=next.begin({title:'GPU runtime',kind:'runtime',retry:{type:'gpu-runtime',input}});assert.equal(resumed,id);next.finish(resumed,'completed')});
 await next.resumeInterrupted();assert.equal(next.state().find(d=>d.id===id).status,'completed');assert.equal(next.state().find(d=>d.id===paused).status,'paused');
});

test('model aggregate progress survives finishing messages and reserves 100 for completion',t=>{const downloads=createDownloads({directory:fixture(t)}),id=downloads.begin({title:'Model',kind:'model'});downloads.update(id,{stage:'dependency',received:90,total:100});assert.equal(downloads.state()[0].percent,null);downloads.update(id,{progressScope:'model',stage:'model',received:700,total:1000});assert.equal(downloads.state()[0].percent,70);downloads.update(id,{message:'Verifying model'});assert.equal(downloads.state()[0].percent,70);downloads.update(id,{received:1000});assert.equal(downloads.state()[0].percent,99.9);downloads.finish(id,'completed');assert.equal(downloads.state()[0].percent,100)});
