const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createLocalStudio,catalog}=require('../electron/local-studio.cjs');
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-local-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return {directory,studio:createLocalStudio({directory,resources:directory,python:path.join(directory,'missing-python')})}}
test('GPU preflight offers setup without silently downloading an absent engine',async t=>{const {studio}=fixture(t);const model=catalog.find(m=>m.engine==='diffusion');const result=await studio.acceleration(model.id);assert.equal(result.ready,false);assert.equal(result.canRepair,true);assert.equal(studio.state().active,null);await assert.rejects(()=>studio.acceleration('video'),/Choose an image/);assert.equal(studio.state().active,null)});
test('local asset registry persists and never resolves unregistered paths',t=>{const {directory,studio}=fixture(t);const source=path.join(directory,'input.mp4');fs.writeFileSync(source,'fixture');const a=studio.import(source,'video');assert.equal(fs.readFileSync(studio.file(a.id),'utf8'),'fixture');assert.throws(()=>studio.file('../input.mp4'),/available/);assert.equal(studio.state().assets[0].file,undefined);const next=createLocalStudio({directory,resources:directory,python:'missing'});assert.equal(next.state().assets[0].id,a.id)});
test('invalid operations fail before starting a subprocess and clear busy state',async t=>{const {studio}=fixture(t);await assert.rejects(()=>studio.clip({start:NaN,end:20}),/valid/);await assert.rejects(()=>studio.voice({model:'unknown',text:'hello'}),/voice/);await assert.rejects(()=>studio.download({url:'file:///etc/passwd'}),/website/);await assert.rejects(()=>studio.install('video'),/Bundled Python/);assert.equal(studio.state().active,null);assert.ok(catalog.some(m=>m.id==='hi_IN-pratham-medium'))});
const {createWorkspace}=require('../electron/workspace.cjs');
test('AI highlights are parsed and impossible clip ranges are discarded',async t=>{const {directory}=fixture(t);const workspace=createWorkspace({directory,safeStorage:{isEncryptionAvailable:()=>true,encryptString:x=>Buffer.from(x),decryptString:x=>x.toString()},fetchImpl:async()=>Response.json({choices:[{message:{content:JSON.stringify([{start:4,end:24,title:'Good',reason:'Complete thought'},{start:-1,end:20},{start:10,end:200}])}}]})});workspace.saveAI({provider:'openai',baseURL:'https://api.openai.com/v1',model:'test-model',key:'test'});const clips=await workspace.suggestClips({segments:[{start:0,end:30,text:'A useful story.'}],duration:30});assert.equal(clips.length,1);assert.equal(clips[0].start,4)});
test('account session cookies stay out of snapshots and are forgotten explicitly',t=>{const {studio,directory}=fixture(t);const cookie=path.join(directory,'session.txt');fs.writeFileSync(cookie,'# Netscape HTTP Cookie File\nexample.com\tTRUE\t/\tTRUE\t0\tsecret\ttest-session\n');studio.setSession(cookie);assert.equal(studio.state().hasSession,true);assert.ok(!JSON.stringify(studio.state()).includes('test-session'));studio.setSession(null);assert.equal(studio.state().hasSession,false)});
test('assistant invokes local speech and opens its result library',async t=>{const {directory}=fixture(t);let calls=0,spoken;const workspace=createWorkspace({directory,localStudio:{voice:async args=>{spoken=args;return {id:'voice-result',title:'Hello'}}},safeStorage:{isEncryptionAvailable:()=>true,encryptString:x=>Buffer.from(x),decryptString:x=>x.toString()},fetchImpl:async()=>Response.json({choices:[{message:++calls===1?{content:null,tool_calls:[{id:'voice-call',type:'function',function:{name:'generate_speech',arguments:JSON.stringify({text:'Hello',model:'en_US-amy-medium'})}}]}:{content:'Your speech is ready.'}}]})});workspace.saveAI({provider:'openai',baseURL:'https://api.openai.com/v1',model:'test-model',key:'test'});const result=await workspace.chat({messages:[{role:'user',content:'Generate speech saying Hello'}],agent:'studio'});assert.equal(spoken.text,'Hello');assert.equal(result.actions[0].type,'open_voice')});
test('relocated studios use real disk paths for newly created assets',t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-relocated-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const data=path.join(directory,'data'),target=path.join(directory,'disk','local-studio');fs.mkdirSync(data);fs.mkdirSync(target,{recursive:true});fs.symlinkSync(target,path.join(data,'local-studio'),process.platform==='win32'?'junction':'dir');const studio=createLocalStudio({directory:data,resources:directory,python:'missing'}),input=path.join(directory,'input.mp4');fs.writeFileSync(input,'fixture');const asset=studio.import(input,'video');assert.equal(path.dirname(studio.file(asset.id)),fs.realpathSync(target));});
test('caption transcription validates the chosen model and language before installation',async t=>{
 const {studio,directory}=fixture(t),source=path.join(directory,'caption.mp4');fs.writeFileSync(source,'fixture');const asset=studio.import(source,'video');
 await assert.rejects(()=>studio.transcribe(asset.id,{model:'unknown'}),/supported transcription model/);
 await assert.rejects(()=>studio.transcribe(asset.id,{model:'whisper-base',language:'../../x'}),/language/);
 await assert.rejects(()=>studio.transcribe(asset.id,{model:'whisper-small',language:'ur'}),/Bundled Python/);
 assert.equal(studio.state().active,null);
});
