const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createPCHelper,walk}=require('../electron/pc-helper.cjs');
const {createModelDiscovery,defaultRoots}=require('../electron/model-discovery.cjs');
function root(t){const p=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-discovery-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p}
function gguf(architecture='llama',name='Test chat'){const string=s=>{const len=Buffer.alloc(8);len.writeBigUInt64LE(BigInt(Buffer.byteLength(s)));return Buffer.concat([len,Buffer.from(s)])};const header=Buffer.alloc(24);header.write('GGUF');header.writeUInt32LE(3,4);header.writeBigUInt64LE(2n,16);return Buffer.concat([header,...[['general.architecture',architecture],['general.name',name]].flatMap(([k,v])=>[string(k),Buffer.from([8,0,0,0]),string(v)]),Buffer.alloc(2048)])}
test('Ollama manifests supply readable names and non-chat GGUF weights cannot be imported as chat',async t=>{
 const p=root(t),modelRoot=path.join(p,'models'),blob='sha256-'+'a'.repeat(64);fs.mkdirSync(path.join(modelRoot,'blobs'),{recursive:true});fs.mkdirSync(path.join(modelRoot,'manifests/registry.ollama.ai/library/qwen3'),{recursive:true});fs.writeFileSync(path.join(modelRoot,'blobs',blob),gguf());fs.writeFileSync(path.join(modelRoot,'manifests/registry.ollama.ai/library/qwen3/latest'),JSON.stringify({layers:[{mediaType:'application/vnd.ollama.image.model',digest:'sha256:'+'a'.repeat(64)}]}));fs.writeFileSync(path.join(modelRoot,'image.gguf'),gguf('z_image','Image model'));
 const result=await createModelDiscovery({directory:p,walk,home:p,env:{}}).scan({folder:modelRoot});assert.equal(result.models.find(m=>m.kind==='chat').name,'qwen3:latest');assert.equal(result.models.find(m=>m.name==='Image model').usable,false);
});
test('folder additions preserve earlier discoveries, remember roots and follow junctions without looping',async t=>{
 const p=root(t),a=path.join(p,'first'),b=path.join(p,'second');fs.mkdirSync(a);fs.mkdirSync(b);fs.writeFileSync(path.join(a,'chat.gguf'),gguf());fs.writeFileSync(path.join(b,'image.safetensors'),Buffer.alloc(1024**2));fs.writeFileSync(path.join(b,'installer.bin'),Buffer.alloc(1024**2));fs.symlinkSync(a,path.join(b,'linked'),process.platform==='win32'?'junction':'dir');fs.symlinkSync(b,path.join(a,'loop'),process.platform==='win32'?'junction':'dir');const helper=createPCHelper({directory:p});await helper.scanModels(a);const result=await helper.scanModels(b);assert.equal(result.models.filter(m=>m.kind==='chat').length,1);assert.ok(result.models.some(m=>m.name==='image.safetensors'));assert.ok(!result.models.some(m=>m.name==='installer.bin'));const saved=JSON.parse(fs.readFileSync(path.join(p,'model-scan-folders.json'),'utf8'));assert.deepEqual(saved,[a,b]);assert.throws(()=>helper.modelInfo(result.models.find(m=>m.name==='image.safetensors').id),/Standalone/);
});
test('cache and redirected folders precede broad document scanning',()=>{const roots=defaultRoots({home:'/home/test',env:{HF_HOME:'/custom/hf',OLLAMA_MODELS:'/custom/ollama',OneDrive:'/onedrive'},directory:'/app',knownFolders:['/redirected/Desktop']});assert.ok(roots.includes(path.resolve('/custom/hf/hub')));assert.ok(roots.includes(path.resolve('/onedrive/Desktop')));assert.ok(roots.indexOf(path.resolve('/home/test/ComfyUI-Shared/models'))<roots.indexOf(path.resolve('/home/test/Documents')))});
