const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {createNativeAuth}=require('../electron/native-auth.cjs');
const {oauthExternalURL}=require('../electron/security.cjs');
const vault={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).map(b=>b^73),decryptString:b=>Buffer.from(b.map(x=>x^73)).toString()};
async function setup(t,provider='gemini'){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-oauth-'));let resolveURL,connected,calls=[];const url=new Promise(r=>resolveURL=r);const auth=createNativeAuth({directory:dir,safeStorage:vault,openExternal:u=>resolveURL(new URL(oauthExternalURL(u))),onConnected:a=>{connected=a},fetchImpl:async(u,o)=>{calls.push({u,o});return Response.json(provider==='openrouter'?{key:'private-access-token'}:calls.length===1?{access_token:'private-access-token',refresh_token:'private-refresh',expires_in:1}:{access_token:'refreshed-token',expires_in:3600})}});t.after(()=>{auth.cancel();fs.rmSync(dir,{recursive:true,force:true})});return {auth,url,calls,dir,get connected(){return connected}}}
test('native Google PKCE validates state, encrypts tokens and refreshes once for concurrent calls',async t=>{const x=await setup(t);const login=x.auth.login({providerId:'gemini',clientId:'own-client',clientSecret:'own-secret',project:'test-project'});const url=await x.url;assert.equal(url.origin,'https://accounts.google.com');assert.equal(url.searchParams.get('code_challenge_method'),'S256');const callback=new URL(url.searchParams.get('redirect_uri'));callback.searchParams.set('code','test-code');callback.searchParams.set('state','wrong');assert.equal((await fetch(callback)).status,400);callback.searchParams.set('state',url.searchParams.get('state'));assert.equal((await fetch(callback)).status,200);await login;const body=new URLSearchParams(x.calls[0].o.body);assert.equal(crypto.createHash('sha256').update(body.get('code_verifier')).digest('base64url'),url.searchParams.get('code_challenge'));assert.ok(!fs.readFileSync(path.join(x.dir,'router-oauth.json'),'utf8').includes('private-access-token'));assert.ok(!JSON.stringify(x.auth.state()).includes('private'));assert.deepEqual(await Promise.all([x.auth.token(x.connected.authId),x.auth.token(x.connected.authId)]),['refreshed-token','refreshed-token']);assert.equal(x.calls.length,2);x.auth.remove(x.connected.authId);await assert.rejects(x.auth.token(x.connected.authId),/Sign in again/)});
test('OpenRouter native login uses PKCE key exchange and random callback path',async t=>{const x=await setup(t,'openrouter');const login=x.auth.login({providerId:'openrouter'});const url=await x.url;assert.equal(url.origin,'https://openrouter.ai');const callback=new URL(url.searchParams.get('callback_url'));assert.match(callback.pathname,/oauth\/callback\/[a-f0-9]{48}/);callback.searchParams.set('code','code');await fetch(callback);await login;assert.equal(await x.auth.token(x.connected.authId),'private-access-token');assert.equal(JSON.parse(x.calls[0].o.body).code_challenge_method,'S256')});
test('native sign-in can be cancelled and unknown providers cannot start a browser flow',async t=>{const x=await setup(t);await assert.rejects(x.auth.login({providerId:'cursor'}),/not implemented/);const login=x.auth.login({providerId:'gemini',clientId:'client'});await x.url;const rejected=assert.rejects(login,/cancelled/);x.auth.cancel();await rejected;assert.equal(x.auth.state(),null);assert.equal(x.calls.length,0)});
for(const asynchronous of [false,true])test(`browser launch ${asynchronous?'rejection':'synchronous throw'} is contained and releases the callback`,async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-launch-error-'));let callback;
 const auth=createNativeAuth({directory,safeStorage:vault,openExternal:url=>{callback=new URL(url).searchParams.get('redirect_uri');if(asynchronous)return Promise.reject(Error('Browser unavailable'));throw Error('Destination blocked')},onConnected:()=>assert.fail('must not connect')});
 t.after(()=>{auth.cancel();fs.rmSync(directory,{recursive:true,force:true})});
 await assert.rejects(auth.login({providerId:'antigravity',clientId:'test-client',project:'test-project'}),/Could not open the sign-in browser/);assert.equal(auth.state(),null);
 await assert.rejects(fetch(callback,{signal:AbortSignal.timeout(1000)}));
 await assert.rejects(auth.login({providerId:'gemini',clientId:'test-client'}),/Could not open the sign-in browser/);assert.equal(auth.state(),null);
});
