const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createPets,wakeCommand}=require('../electron/pets.cjs');
function fixture(t,complete){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-pet-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const modelHub={state:()=>({models:[{id:'qwen-small',kind:'chat',installed:true},{id:'missing',kind:'chat',installed:false}]}),complete:complete||(async()=>Response.json({choices:[{message:{content:'Hello from your companion.'}}]}))};const localStudio={state:()=>({models:[{id:'en_US-amy-medium',name:'Amy',engine:'piper',installed:true},{id:'whisper',installed:true}]}),petVoice:async input=>Buffer.from(input.text),petTranscribe:async()=>({segments:[]})};return {directory,pet:createPets({directory,modelHub,localStudio}),modelHub,localStudio}}
test('wake phrase matches whole Unicode words and requires the configured phrase',()=>{assert.equal(wakeCommand('HELLO, Orvio! Tell me a story.','Hello Orvio'),'tell me a story');assert.equal(wakeCommand('Hello, or VO, tell me a story','Hello Orvio'),'tell me a story');assert.equal(wakeCommand('hello orviology','hello orvio'),null);assert.equal(wakeCommand('Hello Orvio','hello orvio'),'');assert.equal(wakeCommand('مرحبا أورفيو كيف حالك','مرحبا أورفيو'),'كيف حالك');assert.equal(wakeCommand('hello',''),null)});
test('pet starts disabled, validates settings, persists preferences and clears local history',async t=>{const {pet,directory,modelHub,localStudio}=fixture(t);assert.equal(pet.state().settings.enabled,false);assert.throws(()=>pet.save({animal:'../cat'}),/pet/);assert.throws(()=>pet.save({wakePhrase:'   '}),/phrase/);assert.throws(()=>pet.save({model:'cloud-api'}),/model/);pet.save({enabled:true,animal:'fox',name:'Ember',wakePhrase:'Hey Ember',speak:false});await pet.chat('Hello');assert.equal(pet.state().messages.length,2);assert.equal(await pet.speech('hello'),null);const restored=createPets({directory,modelHub,localStudio});assert.equal(restored.state().settings.name,'Ember');assert.equal(restored.state().messages.length,2);restored.clear();assert.equal(restored.state().messages.length,0)});
test('pet only uses selected installed local model and rejects concurrent replies',async t=>{let release,payload;const {pet}=fixture(t,async(id,input)=>{assert.equal(id,'qwen-small');payload=input;await new Promise(r=>release=r);return Response.json({choices:[{message:{content:'A local reply'}}]})});const work=pet.chat('Hi');assert.equal(pet.state().busy,true);await assert.rejects(()=>pet.chat('again'),/thinking/);assert.throws(()=>pet.save({animal:'dog'}),/finish/);release();await work;assert.equal(pet.state().busy,false);assert.match(payload.messages[0].content,/cannot perform app actions/);pet.save({model:'missing'});await assert.rejects(()=>pet.chat('Hi'),/Download/);assert.equal(pet.state().messages.length,2)});
test('failed inference leaves history unchanged and releases busy state',async t=>{const {pet}=fixture(t,async()=>new Response('',{status:500}));await assert.rejects(()=>pet.chat('Hi'),/could not answer/);assert.deepEqual(pet.state().messages,[]);assert.equal(pet.state().busy,false)});
test('pet microphone permission is scoped to its own window and explicit arming',async()=>{const handlers=new Map();let created;class Window{constructor(){this.webContents={setWindowOpenHandler(){},on(){},send(){},mainFrame:{}};created=this}once(){}on(){}loadURL(){}setBounds(){}showInactive(){}destroy(){}isDestroyed(){return false}}
 const pets={state:()=>({settings:{enabled:true,corner:'right'}})};const controller=require('../electron/pet-window.cjs').createPetWindow({app:{isPackaged:false},BrowserWindow:Window,screen:{getPrimaryDisplay:()=>({workArea:{x:0,y:0,width:1280,height:800}})},ipcMain:{handle:(name,fn)=>handlers.set(name,fn)},pets,open(){}});controller.show();const event={sender:created.webContents,senderFrame:created.webContents.mainFrame};assert.equal(controller.permission(created.webContents,'media',{mediaType:'audio'}),false);assert.throws(()=>handlers.get('pet:arm')({sender:{}}),/Untrusted/);handlers.get('pet:arm')(event);assert.equal(controller.permission(created.webContents,'media',{mediaTypes:['audio']}),true);assert.equal(controller.permission(created.webContents,'media',{mediaTypes:['video']}),false);assert.equal(controller.permission({},'media',{mediaType:'audio'}),false);handlers.get('pet:disarm')(event);assert.equal(controller.permission(created.webContents,'media',{mediaType:'audio'}),false);
});

test('late pet disarm is harmless across closing, reopening and frame replacement',()=>{
 const {EventEmitter}=require('node:events');const handlers=new Map();let created;
 class Window extends EventEmitter{
  constructor(){super();this.webContents=new EventEmitter();Object.assign(this.webContents,{mainFrame:{},setWindowOpenHandler(){},send(){}});created=this}
  loadURL(){}setBounds(){}showInactive(){}destroy(){this.emit('closed')}isDestroyed(){return false}
 }
 const controller=require('../electron/pet-window.cjs').createPetWindow({app:{isPackaged:false},BrowserWindow:Window,screen:{getPrimaryDisplay:()=>({workArea:{x:0,y:0,width:1280,height:800}})},ipcMain:{handle:(name,fn)=>handlers.set(name,fn)},pets:{state:()=>({settings:{enabled:true,corner:'right'}})},open(){}});
 const invoke=(name,event)=>handlers.get('pet:'+name)(event);
 controller.show();const original={sender:created.webContents,senderFrame:created.webContents.mainFrame};
 invoke('arm',original);controller.hide();assert.doesNotThrow(()=>invoke('disarm',original));assert.doesNotThrow(()=>invoke('disarm',{sender:original.sender,senderFrame:null}));
 controller.show();const current={sender:created.webContents,senderFrame:created.webContents.mainFrame};invoke('arm',current);
 invoke('disarm',original);assert.equal(controller.permission(current.sender,'media',{mediaType:'audio'}),true);
 assert.throws(()=>invoke('arm',original),/Untrusted/);assert.throws(()=>invoke('disarm',{sender:{},senderFrame:null}),/Untrusted/);
 assert.throws(()=>invoke('disarm',{sender:current.sender,senderFrame:{}}),/Untrusted/);
 current.sender.emit('did-start-navigation',{},'http://127.0.0.1:5188/#pet',false,true);
 assert.equal(controller.permission(current.sender,'media',{mediaType:'audio'}),false);
 current.sender.mainFrame={};const reloaded={sender:current.sender,senderFrame:current.sender.mainFrame};invoke('arm',reloaded);
 invoke('disarm',current);invoke('disarm',{sender:current.sender,senderFrame:null});assert.equal(controller.permission(current.sender,'media',{mediaType:'audio'}),true);
 invoke('disarm',reloaded);assert.equal(controller.permission(current.sender,'media',{mediaType:'audio'}),false);
});
test('code-drawn bot companions persist alongside existing pets',t=>{const {pet,directory,modelHub,localStudio}=fixture(t);for(const animal of ['chat','voice','recorder','video-editor','cat']){pet.save({animal});const restored=createPets({directory,modelHub,localStudio});assert.equal(restored.state().settings.animal,animal)}});
