const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {normalizeProject,rectangle,createRecorderProjects}=require('../electron/recorder-project.cjs');
const {createRecorderCapture}=require('../electron/recorder-capture.cjs');
const {createProduction}=require('../electron/production.cjs');
function directory(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-recorder-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir}
test('editing and shortcut workflow settings persist without altering originals',t=>{const dir=directory(t),id=randomUUID(),projects=createRecorderProjects(dir);projects.settings({editScreenshot:false,shortcutArea:false});const input={start:1,end:10,background:'solid',color:'#ffcc33',cameraId:randomUUID(),zooms:[{start:2,end:4,x:.3,y:.7,scale:2}]};projects.save(id,input);const reopened=createRecorderProjects(dir);assert.equal(reopened.get(id).cameraId,input.cameraId);assert.deepEqual(reopened.get(id).zooms,input.zooms);assert.equal(reopened.state().settings.editScreenshot,false);assert.deepEqual(reopened.state().recent,[id]);assert.throws(()=>projects.get('../secrets'),/saved capture/)});
test('invalid crop and zoom timing cannot reach a render',()=>{for(const crop of [{x:-.1,y:0,width:.5,height:.5},{x:1,y:0,width:.5,height:.5},{x:0,y:0,width:NaN,height:1}])assert.throws(()=>rectangle(crop));assert.deepEqual(rectangle({x:.1,y:.2,width:.4,height:.3}),{x:.1,y:.2,width:.4,height:.3});for(const input of [{end:1,start:2},{color:'red;evil'},{resolution:90000},{cameraId:'/etc/passwd'},{zooms:[null]},{zooms:[{start:0,end:2,x:.5,y:.5,scale:2},{start:1,end:3,x:.5,y:.5,scale:2}]}])assert.throws(()=>normalizeProject(input))});
test('screen and webcam chunks remain separate and both survive completion',t=>{const dir=directory(t),saved=[];const production=createProduction({directory:dir,localStudio:{import(file,kind){const asset={id:randomUUID(),kind,preview:'test'};saved.push({bytes:fs.readFileSync(file).toString(),asset});return asset}}});const {id}=production.beginRecording({camera:true});const backing=new Uint8Array([88,65,66,89]);production.appendRecording(id,backing.subarray(1,3),'screen');production.appendRecording(id,Buffer.from('camera'),'camera');assert.throws(()=>production.appendRecording(id,Buffer.from('x'),'other'));const result=production.finishRecording(id);assert.equal(saved[0].bytes,'camera');assert.equal(saved[1].bytes,'AB');assert.equal(result.cameraId,saved[0].asset.id);assert.equal(result.id,saved[1].asset.id);assert.deepEqual(fs.readdirSync(path.join(dir,'recordings')),[])});
test('quick screenshots copy once without creating an asset when editing is disabled',async t=>{const dir=directory(t),copied=[],imports=[];let cropped;const image={isEmpty:()=>false,getSize:()=>({width:200,height:100}),crop:rect=>{cropped=rect;return image},toPNG:()=>Buffer.from('PNG'),toDataURL:()=>''};const capture=createRecorderCapture({directory:dir,desktopCapturer:{getSources:async()=>[{id:'screen:1:0',display_id:'1',thumbnail:image}]},screen:{getAllDisplays:()=>[{id:1,size:{width:200,height:100},scaleFactor:1,bounds:{x:0,y:0,width:200,height:100}}],getDisplayNearestPoint:()=>({id:1}),getCursorScreenPoint:()=>({x:10,y:10})},clipboard:{writeImage:img=>copied.push(img)},nativeImage:{createFromDataURL:()=>image},localStudio:{import:(file,kind)=>{imports.push(file);return {id:randomUUID(),kind}}},ipcMain:{handle(){},on(){}}});capture.projects.settings({editScreenshot:false});await capture.capture({sourceId:'screen:1:0',crop:{x:.25,y:.1,width:.5,height:.8}});assert.deepEqual(cropped,{x:50,y:10,width:100,height:80});assert.equal(copied.length,1);assert.equal(imports.length,0);await capture.capture({edit:true});assert.equal(imports.length,1);assert.equal(capture.projects.state().recent.length,1);assert.deepEqual(fs.readdirSync(path.join(dir,'screenshots')),[])});
