const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createSEO,dates,opportunities,SCOPES}=require('../electron/seo.cjs');
const safeStorage={isEncryptionAvailable:()=>true,encryptString:value=>Buffer.from(value).reverse(),decryptString:value=>Buffer.from(value).reverse().toString()};
const json=value=>({ok:true,json:async()=>value});
function fixture(t,options={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-seo-'));let login;const api=createSEO({directory,safeStorage,openExternal:url=>{login=new URL(url)},analyze:async()=>'',...options});t.after(()=>{api.cancel();fs.rmSync(directory,{recursive:true,force:true})});api.importCredentials({installed:{client_id:'123.apps.googleusercontent.com',client_secret:'client-private'}});return {directory,api,login:()=>login}}
async function connect(f){await f.api.connect();const url=f.login(),callback=new URL(url.searchParams.get('redirect_uri'));callback.searchParams.set('state',url.searchParams.get('state'));callback.searchParams.set('code','fixture-code');const response=await fetch(callback);assert.equal(response.status,200)}
function google(url,init){if(url==='https://oauth2.googleapis.com/token')return json({access_token:'access-private',refresh_token:'refresh-private',expires_in:3600,scope:SCOPES.join(' ')});if(url.includes('accountSummaries'))return json({accountSummaries:[{displayName:'Account',propertySummaries:[{property:'properties/123',displayName:'Website'}]}]});if(url.includes('/dataStreams?'))return json({dataStreams:[{webStreamData:{defaultUri:'https://example.com'}}]});if(url.endsWith('/sites'))return json({siteEntry:[{siteUrl:'sc-domain:example.com',permissionLevel:'siteOwner'}]});if(url.includes('analyticsdata')){const body=JSON.parse(init.body),dims=body.dimensions.map(d=>d.name);return json({dimensionHeaders:dims.map(name=>({name})),metricHeaders:body.metrics,rows:[{dimensionValues:dims.map(name=>({value:name==='date'?'20260920':'Organic Search'})),metricValues:['100','150','80','0.53','12'].map(value=>({value}))}],rowCount:1,metadata:{subjectToThresholding:true}})}if(url.includes('searchAnalytics')){const body=JSON.parse(init.body);assert.equal(body.dataState,'final');assert.equal(body.type,'web');return json({rows:[{keys:body.dimensions.length?[body.dimensions[0]==='date'?'2026-09-20':'example query']:[],clicks:5,impressions:400,ctr:0.0125,position:8}]})}throw Error('Unexpected request '+url)}
test('SEO OAuth uses PKCE and read-only scopes; tokens and client secrets stay private',async t=>{let params;const f=fixture(t,{fetchImpl:async(url,init)=>{if(url.includes('/token'))params=init.body;return google(url,init)}});await connect(f);assert.equal(f.login().searchParams.get('code_challenge_method'),'S256');assert.deepEqual(f.login().searchParams.get('scope').split(' '),SCOPES);assert.ok(params.get('code_verifier'));assert.equal(params.get('client_secret'),'client-private');const publicState=JSON.stringify(f.api.state()),disk=fs.readFileSync(path.join(f.directory,'seo.json'),'utf8');for(const secret of ['access-private','refresh-private','client-private']){assert.ok(!publicState.includes(secret));assert.ok(!disk.includes(secret))}assert.equal(f.api.state().pending,false);assert.equal(f.api.state().connected,true)});
test('wrong OAuth state cannot exchange a token; cancellation closes callback',async t=>{let calls=0;const f=fixture(t,{fetchImpl:async()=>{calls++;return json({})}});await f.api.connect();const callback=new URL(f.login().searchParams.get('redirect_uri'));callback.searchParams.set('state','wrong');callback.searchParams.set('code','fake');assert.equal((await fetch(callback)).status,400);assert.equal(calls,0);f.api.cancel();assert.equal(f.api.state().pending,false);assert.equal(f.api.state().connected,false)});
test('discovers accessible sites and GA4 properties, generates current and previous reports',async t=>{const f=fixture(t,{fetchImpl:async(...args)=>google(...args)});await connect(f);await f.api.discover();assert.equal(f.api.state().property,'properties/123');const s=await f.api.report({property:'properties/123',site:'sc-domain:example.com',days:28});assert.equal(s.report.analytics.current.sessions,150);assert.deepEqual(s.report.analytics.websites,['https://example.com']);assert.equal(s.report.analytics.devices.length,1);assert.equal(s.report.analytics.warnings.length,0);assert.equal(s.report.search.current.clicks,5);assert.equal(s.report.search.opportunities.length,1);assert.equal(s.report.errors.length,0);assert.ok(!JSON.stringify(f.api.summary()).includes('private'));await assert.rejects(f.api.report({property:'properties/999',site:'',days:28}),/accessible/)});
test('partial Google API failures retain working reports and explain missing data',async t=>{const f=fixture(t,{fetchImpl:async(url,init)=>url.includes('analyticsdata')?{ok:false,status:403}:google(url,init)});await connect(f);await f.api.discover();const s=await f.api.report({property:'properties/123',site:'sc-domain:example.com',days:7});assert.equal(s.report.analytics,null);assert.equal(s.report.search.current.clicks,5);assert.match(s.report.errors[0],/Analytics.*denied/)});
test('analyst receives bounded report evidence only on request; disconnect clears reports',async t=>{let prompt='',calls=0;const f=fixture(t,{fetchImpl:async(...args)=>google(...args),analyze:async(text,structured)=>{prompt=text;calls++;assert.equal(structured,true);return 'Review the low-CTR query.'}});await connect(f);await f.api.discover();await f.api.report({property:'properties/123',site:'sc-domain:example.com',days:28});assert.equal(calls,0);assert.equal(await f.api.analysis('What next?'),'Review the low-CTR query.');assert.ok(prompt.includes('400'));assert.ok(prompt.includes('Do not invent'));assert.ok(!prompt.includes('private'));assert.ok(prompt.length<26000);f.api.disconnect();assert.equal(f.api.state().report,null);assert.equal(f.api.state().connected,false);assert.equal(f.api.state().analysis,'')});
test('report periods are equal length and lag three days; opportunities are evidence based',()=>{const r=dates(7,Date.parse('2026-09-28T12:00:00Z'));assert.deepEqual(r,{startDate:'2026-09-19',endDate:'2026-09-25',previousStart:'2026-09-12',previousEnd:'2026-09-18'});assert.throws(()=>dates(365));assert.equal(opportunities([{impressions:99,position:10,ctr:0.01},{impressions:900,position:25,ctr:0.01}]).length,0)});
const {compareRows,parseInsight,evidenceFor}=require('../electron/seo-insights.cjs');
test('query comparisons preserve unknown previous rows and show direction correctly',()=>{const result=compareRows([{keys:['known'],clicks:9,position:5},{keys:['missing'],clicks:4,position:8}],[{keys:['known'],clicks:5,position:8}]);assert.equal(result[0].clickChange,4);assert.equal(result[0].positionChange,3);assert.equal(result[1].clickChange,null);assert.equal(result[1].previous,null)});
test('focused evidence includes selected low-ranked rows and remains valid bounded JSON',()=>{const report={search:{queries:Array.from({length:200},(_,i)=>({keys:['query '+i],impressions:200-i,detail:'long '.repeat(400)})),pages:[]}};const evidence=evidenceFor(report,'query 199');assert.ok(evidence.length<=19000);assert.equal(JSON.parse(evidence).search.queries[0].keys[0],'query 199')});
test('structured reviews create deduplicated persistent action plans; incomplete reviews preserve last good result',async t=>{let output=JSON.stringify({summary:'Search clicks are steady.',findings:[{title:'CTR',evidence:'5 clicks from 400 impressions',interpretation:'Title relevance could be reviewed.'}],actions:[{title:'Review the title',priority:'high',steps:['Compare query intent'],measure:'CTR next month'}]});const f=fixture(t,{fetchImpl:async(...args)=>google(...args),analyze:async()=>output});await connect(f);await f.api.discover();await f.api.report({property:'properties/123',site:'sc-domain:example.com'});await f.api.analysis({mode:'quickwins',focus:'example query'});const insight=f.api.state().insight;assert.equal(insight.mode,'quickwins');f.api.addAction({analysisId:insight.id,index:0});f.api.addAction({analysisId:insight.id,index:0});assert.equal(f.api.state().plan.length,1);const id=f.api.state().plan[0].id;f.api.task({id,done:true});assert.equal(f.api.state().plan[0].done,true);assert.equal(JSON.parse(fs.readFileSync(path.join(f.directory,'seo.json'))).plan[0].done,true);output='{"summary":"unfinished';await assert.rejects(f.api.analysis({mode:'overview'}),/did not finish/);assert.equal(f.api.state().insight.id,insight.id);f.api.task({id,remove:true});assert.equal(f.api.state().plan.length,0);assert.throws(()=>f.api.addAction({analysisId:'stale',index:0}));assert.equal(parseInsight('{}',{}),null)});
test('optional dimension failures preserve source totals and other breakdowns',async t=>{const f=fixture(t,{fetchImpl:async(url,init)=>url.includes('analyticsdata')&&JSON.parse(init.body).dimensions.some(d=>d.name==='country')?{ok:false,status:429}:google(url,init)});await connect(f);await f.api.discover();const {report}=await f.api.report({property:'properties/123',site:'sc-domain:example.com'});assert.equal(report.analytics.current.sessions,150);assert.equal(report.analytics.devices.length,1);assert.equal(report.search.devices.length,1);assert.match(report.analytics.warnings.join(' '),/countries/)});
