const {test}=require('node:test');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {createUpdateController}=require('../electron/updates.cjs');
function fake(){const u=new EventEmitter();u.checkForUpdates=async()=>{u.emit('checking-for-update');u.emit('update-not-available');return {isUpdateAvailable:false};};u.quitAndInstall=()=>{u.installed=true};return u;}
test('packaged Windows checks, downloads and installs only when ready',async()=>{const u=fake();const c=createUpdateController({updater:u,packaged:true,platform:'win32'});assert.equal(u.autoDownload,true);assert.equal(u.autoInstallOnAppQuit,true);assert.throws(()=>c.install());await c.check();assert.equal(c.getState().phase,'current');u.emit('update-available',{version:'0.3.0'});assert.equal(c.getState().phase,'downloading');u.emit('download-progress',{percent:34.7});assert.equal(c.getState().percent,35);u.emit('update-downloaded',{version:'0.3.0'});c.install();assert.equal(u.installed,true);});
test('unsigned macOS discovers updates without attempting an unsupported installation',async()=>{const u=fake();u.checkForUpdates=async()=>{u.emit('update-available',{version:'0.3.0'});return {isUpdateAvailable:true}};const c=createUpdateController({updater:u,packaged:true,platform:'darwin'});assert.equal(u.autoDownload,false);assert.equal(u.autoInstallOnAppQuit,false);await c.check();assert.equal(c.getState().phase,'manual');assert.throws(()=>c.install());});
test('signed macOS enables the automatic path',()=>{const u=fake();createUpdateController({updater:u,packaged:true,platform:'darwin',macSigned:true});assert.equal(u.autoDownload,true);});
test('development never checks releases',async()=>{const u=fake();u.checkForUpdates=()=>{throw new Error('must not call')};const c=createUpdateController({updater:u,packaged:false,platform:'win32'});assert.equal((await c.check()).phase,'idle');});
test('network failure is visible and allows retry',async()=>{const u=fake();let fails=true;u.checkForUpdates=async()=>{if(fails)throw new Error('offline');u.emit('update-not-available');return {isUpdateAvailable:false};};const c=createUpdateController({updater:u,packaged:true,platform:'win32'});assert.equal((await c.check()).phase,'error');fails=false;assert.equal((await c.check()).phase,'current');});
test('concurrent checks share one request',async()=>{const u=fake();let calls=0,resolve;u.checkForUpdates=()=>{calls++;return new Promise(r=>{resolve=r})};const c=createUpdateController({updater:u,packaged:true,platform:'win32'});const a=c.check(),b=c.check();assert.equal(calls,1);resolve({isUpdateAvailable:false});await Promise.all([a,b]);});
