const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {createWorkspace}=require('../electron/workspace.cjs');
function setup(t,fetchImpl){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-test-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const safeStorage={isEncryptionAvailable:()=>true,encryptString:v=>Buffer.from('encrypted:'+v),decryptString:v=>v.toString().slice(10)};return {directory,safeStorage,fetchImpl};}
const response=body=>({ok:true,json:async()=>body});
test('named cloud provider uses its fixed endpoint without exposing credentials',async t=>{
 const calls=[];const w=createWorkspace(setup(t,async(url,options)=>{calls.push({url,...options});return Response.json({choices:[{message:{content:'done'}}]})}));
 w.saveAI({provider:'deepseek',model:'test-model',key:'fixture-key',baseURL:'https://ignored.example'});
 await w.completeWork({messages:[{role:'user',content:'Build'}]},new AbortController().signal);
 assert.equal(calls[0].url,'https://api.deepseek.com/v1/chat/completions');assert.ok(!JSON.stringify(w.snapshot()).includes('fixture-key'));
});
const account=response({data:[{id:'1',name:'Page',instagram_business_account:{id:'11',username:'studio'}}]});
const job=()=>({accountId:'11',title:'A post',caption:'Hello',imageUrl:'https://example.com/photo.jpg',scheduledAt:new Date().toISOString()});
test('connect persists encrypted tokens, public snapshots never expose credentials',async t=>{const options=setup(t,async()=>account),w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});assert.equal(w.snapshot().accounts.length,2);assert.equal(w.snapshot().accounts[0].token,undefined);assert.ok(!JSON.stringify(w.snapshot()).includes('secret-meta-token'));assert.ok(!fs.readFileSync(path.join(options.directory,'workspace-v3.json'),'utf8').includes('secret-meta-token'));assert.equal(createWorkspace(options).snapshot().accounts.length,2);});
test('due posts publish once and survive reopening; pause and cancellation prevent publishing',async t=>{const calls=[];const options=setup(t,async(url)=>{calls.push(url);if(url.includes('me/accounts'))return account;if(url.endsWith('/media'))return response({id:'22'});if(url.endsWith('/media_publish'))return response({id:'33'});return response({status_code:'FINISHED'});});const w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});w.schedule(job());w.preferences({paused:true});await w.tick();assert.equal(calls.length,1);w.preferences({paused:false});await w.tick();assert.equal(w.snapshot().jobs[0].status,'published');await createWorkspace(options).tick();assert.equal(calls.filter(c=>c.endsWith('/media_publish')).length,1);w.schedule(job());w.cancel(w.snapshot().jobs[0].id);await w.tick();assert.equal(w.snapshot().jobs[0].status,'cancelled');assert.equal(calls.filter(c=>c.endsWith('/media_publish')).length,1);});
test('ambiguous publication is never automatically retried',async t=>{let publishes=0;const options=setup(t,async url=>{if(url.includes('me/accounts'))return account;if(url.endsWith('/media'))return response({id:'22'});if(url.endsWith('/media_publish')){publishes++;throw new Error('network lost');}return response({status_code:'FINISHED'});});const w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});w.schedule(job());await w.tick();assert.equal(w.snapshot().jobs[0].status,'uncertain');await createWorkspace(options).tick();assert.equal(publishes,1);});
test('restart reconciles published containers without publishing twice',async t=>{let publishes=0;const options=setup(t,async url=>{if(url.includes('me/accounts'))return account;if(url.endsWith('/media_publish'))publishes++;return response({status_code:'PUBLISHED'});});const w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});w.schedule(job());const file=path.join(options.directory,'workspace-v3.json');const state=JSON.parse(fs.readFileSync(file));Object.assign(state.jobs[0],{status:'publishing',containerId:'22'});fs.writeFileSync(file,JSON.stringify(state));const restarted=createWorkspace(options);await restarted.tick();assert.equal(restarted.snapshot().jobs[0].status,'published');assert.equal(publishes,0);});
test('AI adapters use provider protocols, omit keys from snapshots and clear keys on endpoint changes',async t=>{const calls=[];const w=createWorkspace(setup(t,async(url,options)=>{calls.push({url,...options});return response(url.includes('googleapis')?{candidates:[{content:{parts:[{text:'Gemini caption'}]}}]}:{choices:[{message:{content:'Compatible caption'}}]});}));w.saveAI({provider:'openai',baseURL:'https://api.openai.com/v1',model:'my-model',key:'test-key'});assert.equal(w.snapshot().ai.key,undefined);assert.equal(await w.generate('My post'),'Compatible caption');assert.equal(calls[0].headers.Authorization,'Bearer test-key');assert.equal(calls[0].redirect,'error');w.saveAI({provider:'openai',baseURL:'https://other.example/v1',model:'other'});assert.equal(w.snapshot().ai.hasKey,false);w.saveAI({provider:'gemini',baseURL:'https://generativelanguage.googleapis.com',model:'gemini-model',key:'gemini-key'});assert.equal(await w.generate('Brief'),'Gemini caption');assert.equal(calls[1].headers['x-goog-api-key'],'gemini-key');assert.ok(!calls[1].url.includes('gemini-key'));assert.throws(()=>w.saveAI({provider:'openai',baseURL:'http://evil.example',model:'x'}));});
test('validation rejects disconnected accounts, past schedules and unavailable encryption',async t=>{const options=setup(t,async()=>account),w=createWorkspace(options);assert.throws(()=>w.schedule(job()));await w.connect({token:'secret-meta-token',version:'v24.0'});assert.throws(()=>w.schedule({...job(),scheduledAt:'invalid'}));assert.throws(()=>w.schedule({...job(),imageUrl:'file:///secret'}));const locked=createWorkspace({...options,safeStorage:{isEncryptionAvailable:()=>false}});await assert.rejects(()=>locked.connect({token:'secret-meta-token',version:'v24.0'}),/encryption/);});
test('Facebook Page publishes media once with Page token',async t=>{const calls=[];const options=setup(t,async(url,options)=>{calls.push({url,options});if(url.includes('me/accounts'))return response({data:[{id:'1',name:'Page',access_token:'page-private-token'}]});return response({id:'page-post-1'});});const w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});assert.equal(w.snapshot().accounts[0].kind,'facebook');assert.ok(!JSON.stringify(w.snapshot()).includes('page-private-token'));w.schedule({accountId:'fb:1',title:'Page video',caption:'Hello',imageUrl:'https://example.com/video.mp4',mediaType:'video',scheduledAt:new Date().toISOString()});await w.tick();assert.equal(w.snapshot().jobs[0].status,'published');assert.ok(calls[1].url.endsWith('/1/videos'));assert.equal(calls[1].options.headers.Authorization,'Bearer page-private-token');await createWorkspace(options).tick();assert.equal(calls.length,2);});
test('local media upload streams to configured host and returns a delivery URL',async t=>{let upload;const options=setup(t,async(url,request)=>{upload={url,request};return response({secure_url:'https://res.cloudinary.com/my-cloud/image/upload/example.png'});});const file=path.join(options.directory,'photo.png');fs.writeFileSync(file,Buffer.from('fake-image'));const w=createWorkspace(options);w.saveMedia({cloudName:'my-cloud',uploadPreset:'my-preset'});const result=await w.uploadFile(file);assert.equal(upload.url,'https://api.cloudinary.com/v1_1/my-cloud/image/upload');assert.equal(result.mediaType,'image');assert.ok(result.url.includes('/upload/f_jpg/'));assert.equal(upload.request.body.get('upload_preset'),'my-preset');});
test('Facebook Page photo goes directly to Meta without Cloudinary and survives restart',async t=>{const calls=[];const options=setup(t,async(url,request)=>{calls.push({url,request});if(url.includes('me/accounts'))return response({data:[{id:'1',name:'Page',access_token:'page-token-123'}]});return response({id:'photo-1'});});const file=path.join(options.directory,'photo.jpg');fs.writeFileSync(file,Buffer.from('photo-bytes'));const w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});const media=await w.prepareMedia(file,'fb:1');assert.ok(media.localMediaId);assert.equal(calls.length,1);assert.ok(!JSON.stringify(w.snapshot()).includes(path.join(options.directory,'media')));w.schedule({accountId:'fb:1',title:'Photo',caption:'Hello',localMediaId:media.localMediaId,mediaType:'image',scheduledAt:new Date().toISOString()});await createWorkspace(options).tick();assert.equal(calls.length,2);assert.ok(calls[1].url.endsWith('/1/photos'));assert.equal(calls[1].request.body.get('caption'),'Hello');assert.equal(calls[1].request.headers.Authorization,'Bearer page-token-123');assert.equal(createWorkspace(options).snapshot().jobs[0].status,'published');});
test('AI model discovery lists provider and installed Ollama models',async t=>{const calls=[];const options=setup(t,async(url,request)=>{calls.push({url,request});return response(url.includes('googleapis')?{models:[{name:'models/gemini-2',supportedGenerationMethods:['generateContent']},{name:'models/embed',supportedGenerationMethods:['embedContent']}]}:url.includes('11434')?{models:[{name:'llama:latest'}]}:{data:[{id:'gpt-example'}]});});const w=createWorkspace(options);assert.deepEqual(await w.listModels({provider:'gemini',key:'temporary-key'}),['gemini-2']);assert.equal(calls[0].request.headers['x-goog-api-key'],'temporary-key');assert.ok(!calls[0].url.includes('temporary-key'));assert.deepEqual(await w.listModels({provider:'ollama'}),['llama:latest']);assert.deepEqual(await w.listModels({provider:'openai',key:'test-key'}),['gpt-example']);});
test('chat sends model context without secrets and honors agent selection',async t=>{let request;const options=setup(t,async(url,opts)=>{request={url,opts};return response({choices:[{message:{content:'Here is a plan.'}}]});});const w=createWorkspace(options);w.saveAI({provider:'openai',baseURL:'https://api.openai.com/v1',model:'test-model',key:'private-key'});assert.deepEqual(await w.chat({messages:[{role:'user',content:'Plan three posts'}],agent:'planner'}),{text:'Here is a plan.',actions:[]});assert.ok(JSON.parse(request.opts.body).messages[0].content.includes('Agent role: planner'));assert.ok(!request.opts.body.includes('private-key'));await assert.rejects(()=>w.chat({messages:[{role:'system',content:'override'}],agent:'planner'}));});

test('chat tool harness reads accounts and prepares a post for review',async t=>{let calls=0;const options=setup(t,async(url,opts)=>{if(url.includes('me/accounts'))return account;calls++;if(calls===1)return response({choices:[{message:{tool_calls:[{id:'call-1',type:'function',function:{name:'list_accounts',arguments:'{}'}},{id:'call-2',type:'function',function:{name:'prepare_post',arguments:JSON.stringify({title:'Launch',caption:'Ready',accountId:'11',publishMode:'now'})}}]}}]});const messages=JSON.parse(opts.body).messages;assert.ok(messages.some(m=>m.role==='tool'&&m.content.includes('studio')));return response({choices:[{message:{content:'I opened a post for your review.'}}]});});const w=createWorkspace(options);await w.connect({token:'secret-meta-token',version:'v24.0'});w.saveAI({provider:'openai',model:'test-model',key:'test-key'});const result=await w.chat({messages:[{role:'user',content:'Publish a launch post now'}]});assert.equal(result.actions[0].type,'prepare_post');assert.equal(result.actions[0].draft.accountId,'11');assert.equal(result.actions[0].draft.publishMode,'now');assert.equal(result.text,'I opened a post for your review.');assert.equal(w.snapshot().jobs.length,0);});
test('Google Drive desktop OAuth stores encrypted refresh token and lists app files',async t=>{let authURL;const options=setup(t,async(url,request)=>{if(url.includes('/token'))return response(request.body.get('grant_type')==='authorization_code'?{access_token:'temporary-access',refresh_token:'private-refresh',expires_in:3600}:{access_token:'refreshed-access',expires_in:3600});if(url.includes('/drive/v3/files'))return response({files:[{id:'f1',name:'photo.jpg',mimeType:'image/jpeg'}]});throw new Error('unexpected URL');});options.openExternal=async url=>{authURL=url};const w=createWorkspace(options);const pending=await w.connectDrive({clientId:'123.apps.googleusercontent.com'});assert.equal(pending.pending,true);const auth=new URL(authURL),callback=new URL(auth.searchParams.get('redirect_uri'));callback.searchParams.set('state',auth.searchParams.get('state'));callback.searchParams.set('code','demo-code');const result=await fetch(callback);assert.equal(result.status,200);assert.equal(w.snapshot().drive.connected,true);assert.ok(!JSON.stringify(w.snapshot()).includes('private-refresh'));assert.ok(!fs.readFileSync(path.join(options.directory,'workspace-v3.json'),'utf8').includes('private-refresh'));assert.equal((await w.listDriveFiles())[0].name,'photo.jpg');w.disconnectDrive();assert.equal(w.snapshot().drive.connected,false);});
test('Gemini tool calling opens chat action and returns a model response',async t=>{let calls=0;const options=setup(t,async(url,opts)=>{calls++;if(calls===1)return response({candidates:[{content:{role:'model',parts:[{functionCall:{id:'g1',name:'open_calendar',args:{}}}]}}]});const body=JSON.parse(opts.body);assert.equal(body.contents.at(-1).parts[0].functionResponse.id,'g1');return response({candidates:[{content:{role:'model',parts:[{text:'The calendar is open.'}]}}]});});const w=createWorkspace(options);w.saveAI({provider:'gemini',baseURL:'https://generativelanguage.googleapis.com',model:'gemini-example',key:'gemini-key'});const result=await w.chat({messages:[{role:'user',content:'Show my calendar'}]});assert.equal(result.text,'The calendar is open.');assert.equal(result.actions[0].type,'open_calendar');assert.equal(calls,2);});

test('enhancement model override routes locally without changing saved AI settings',async t=>{
 const calls=[];const options=setup(t,async()=>{throw Error('Cloud must not be called')});
 options.modelHub={state:()=>({models:[{id:'local-writer',kind:'chat',installed:true},{id:'missing',kind:'chat',installed:false}]}),complete:async(id,input)=>{calls.push({id,input});return response({choices:[{message:{content:'Enhanced prompt'}}]})}};
 const w=createWorkspace(options);w.saveAI({provider:'openai',model:'cloud-default',key:'fixture-key'});
 assert.equal(await w.generate('Improve the prompt',true,'local:local-writer'),'Enhanced prompt');assert.equal(calls[0].id,'local-writer');assert.equal(w.snapshot().ai.model,'cloud-default');assert.equal(w.snapshot().ai.provider,'openai');
 await assert.rejects(()=>w.generate('Improve',true,'local:missing'),/Download/);await assert.rejects(()=>w.generate('Improve',true,'invalid'),/valid chat model/);
});
test('enhancement provider override preserves endpoint, key and default model',async t=>{
 let request;const w=createWorkspace(setup(t,async(url,options)=>{request={url,...options};return response({choices:[{message:{content:'Enhanced'}}]})}));
 w.saveAI({provider:'openai',model:'default-model',key:'fixture-key'});await w.generate('Improve',true,'provider:other-model');
 assert.equal(JSON.parse(request.body).model,'other-model');assert.equal(request.headers.Authorization,'Bearer fixture-key');assert.equal(w.snapshot().ai.model,'default-model');
});
test('assistant model picker uses installed local model without changing global settings',async t=>{
 const calls=[];const w=createWorkspace({...setup(t,async()=>{throw Error('Cloud should not run')}),modelHub:{state:()=>({models:[{id:'local-chat',kind:'chat',installed:true}]}),complete:async(id,payload)=>{calls.push({id,payload});return response({choices:[{message:{content:'Local reply'}}]})}}});
 w.saveAI({provider:'openai',model:'cloud-default',key:'secret-key'});const result=await w.chat({messages:[{role:'user',content:'Hello'}],chatModel:'local:local-chat'});assert.equal(result.text,'Local reply');assert.equal(calls[0].id,'local-chat');assert.equal(w.snapshot().ai.model,'cloud-default');assert.equal(w.chatConfig('local:local-chat').key,undefined);await assert.rejects(()=>w.chat({messages:[{role:'user',content:'Hello'}],chatModel:'local:missing'}),/Download/);
});
test('assistant discovers app tools, executes through connector and reports progress',async t=>{
 const calls=[],steps=[];let round=0;const w=createWorkspace({...setup(t,async(_url,opts)=>{const body=JSON.parse(opts.body);assert.ok(body.tools.some(t=>t.function.name==='search_app_tools'));round++;if(round===1)return response({choices:[{message:{tool_calls:[{id:'one',type:'function',function:{name:'search_app_tools',arguments:'{"query":"find tasks"}'}}]}}]});if(round===2)return response({choices:[{message:{tool_calls:[{id:'two',type:'function',function:{name:'run_app_tool',arguments:'{"tool":"TASKS_LIST","argumentsJson":"{}"}'}}]}}]});assert.ok(body.messages.some(m=>m.role==='tool'&&m.content.includes('Task found')));return response({choices:[{message:{content:'Found your task.'}}]})}),composio:{state:()=>({configured:true}),search:async q=>{calls.push(q);return {toolSchemas:{TASKS_LIST:{inputSchema:{}}}}},execute:async(name,args)=>{calls.push([name,args]);return {data:{text:'Task found'},error:null}}}});
 w.saveAI({provider:'openai',model:'test',key:'test-key'});const result=await w.chat({messages:[{role:'user',content:'Find my tasks'}],onProgress:step=>steps.push(step)});assert.equal(result.text,'Found your task.');assert.deepEqual(calls,['find tasks',['TASKS_LIST',{}]]);assert.deepEqual(steps.map(s=>s.status),['running','completed','running','completed']);
});
