const ENDPOINT='https://connect.composio.dev/mcp';
function unpack(result){if(result.isError)throw Error('Composio could not complete this request. Check your connection in its dashboard.');let value=result.structuredContent;if(!value){for(const part of result.content||[]){if(part.type!=='text')continue;try{const candidate=JSON.parse(part.text);if(candidate&&typeof candidate==='object'&&!Array.isArray(candidate)&&('data' in candidate||'successful' in candidate||'tool_schemas' in candidate)){value=candidate;break}}catch{}}}if(!value)throw Error('Composio returned an unreadable response. Please retry.');if(value.successful===false||value.error||value.data?.success===false||value.data?.error)throw Error('Composio could not complete this request. Check your app connection and permissions.');return value.data||value}

async function createConnectSession(key,{createTransport,createClient}={}){
 const {Client,StreamableHTTPClientTransport}=require('@modelcontextprotocol/client');
 const transport=createTransport?createTransport(ENDPOINT,{'x-consumer-api-key':key}):new StreamableHTTPClientTransport(new URL(ENDPOINT),{requestInit:{headers:{'x-consumer-api-key':key},redirect:'error'},fetch:(url,init)=>fetch(url,{...init,redirect:'error'})});
 const client=createClient?createClient():new Client({name:'orvio-studio',version:'0.9.0'});
 const apps=new Map(),toolSessions=new Map(),appSessions=new Map();let available=new Set();
 async function call(name,args){if(!available.has(name))throw Error('Composio does not expose the required tool: '+name);return unpack(await client.callTool({name,arguments:args},{timeout:90000}))}
 try{await client.connect(transport,{timeout:30000});let cursor;do{const page=await client.listTools(cursor?{cursor}:{},{timeout:30000});for(const tool of page.tools)available.add(tool.name);cursor=page.nextCursor}while(cursor);if(!available.has('COMPOSIO_SEARCH_TOOLS')||!available.has('COMPOSIO_MANAGE_CONNECTIONS')||!available.has('COMPOSIO_MULTI_EXECUTE_TOOL'))throw Error('The Connect endpoint does not expose the required app tools.')}catch(error){await client.close().catch(()=>{});throw error}
 const session={sessionId:'',mode:'connect',close:()=>client.close(),
  async search({query}){const data=await call('COMPOSIO_SEARCH_TOOLS',{queries:[{use_case:query}],session:{generate_id:true}});const schemas=data.tool_schemas||{};const sessionId=data.session?.id;for(const name of Object.keys(schemas))toolSessions.set(name,sessionId);for(const item of data.toolkit_connection_statuses||[]){appSessions.set(item.toolkit,sessionId);apps.set(item.toolkit,{slug:item.toolkit,name:item.toolkit.replaceAll('_',' '),connection:{isActive:!!item.has_active_connection},isNoAuth:false})}return {...data,toolSchemas:schemas}},
  async toolkits(options={}){let selected;if(options.search){const result=await session.search({query:'Find tools for '+options.search});selected=new Set((result.toolkit_connection_statuses||[]).map(item=>item.toolkit))}else if(apps.size)await session.search({query:'Check available tools and connection status for '+[...apps.keys()].slice(0,12).join(', ')});return {items:[...apps.values()].filter(a=>(!selected||selected.has(a.slug))&&(!options.isConnected||a.connection.isActive)),cursor:undefined}},
  async authorize(toolkit){const data=await call('COMPOSIO_MANAGE_CONNECTIONS',{toolkits:[toolkit],reinitiate_all:false,...(appSessions.get(toolkit)?{session_id:appSessions.get(toolkit)}:{})});const links=[];function walk(value){if(!value||typeof value!=='object')return;for(const [name,item] of Object.entries(value)){if(['redirect_url','redirectUrl','auth_url','authUrl','authentication_url'].includes(name)&&typeof item==='string')links.push(item);else if(typeof item==='object')walk(item)}}walk(data);if(links.length)return {redirectUrl:links[0]};const result=data.results?.[toolkit];if(result?.status==='ACTIVE'||result?.status==='active'||result?.is_active===true||result?.has_active_connection===true||data.summary?.active_connections===1)return {alreadyConnected:true};throw Error('Composio did not provide a sign-in link. Open Connect Apps in the Composio dashboard to finish connecting, then refresh.')},
  async execute(tool,args){if(tool==='COMPOSIO_GET_TOOL_SCHEMAS'){const data=await call(tool,{...args,...(toolSessions.get(args.tool_slugs?.[0])?{session_id:toolSessions.get(args.tool_slugs[0])}:{})});return {data,error:null}}if(!toolSessions.has(tool)||tool.startsWith('COMPOSIO_'))throw Error('Search for this app tool first.');const data=await call('COMPOSIO_MULTI_EXECUTE_TOOL',{tools:[{tool_slug:tool,arguments:args}],sync_response_to_workbench:false,current_step:'EXECUTING_APPROVED_ACTION',...(toolSessions.get(tool)?{session_id:toolSessions.get(tool)}:{})});return {data,error:(data.error_count>0||data.results?.some(r=>r.error||r.response?.successful===false))?'The app reported a failed action.':null}}
 };return session;
}
module.exports={createConnectSession,unpack,ENDPOINT};
