const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const slug=value=>{if(typeof value!=='string'||!/^[a-zA-Z0-9_-]{1,150}$/.test(value))throw Error('Choose a valid app or tool.');return value};
function credentialError(error){const status=Number(error?.status||error?.statusCode);if(status===401||/\b401\b/.test(String(error?.message)))return new Error('Composio rejected this key. Copy a current key from Composio and try again. Connect keys come from Sessions & API Key; Platform keys come from Project Settings.');if(status===403)return new Error('This Composio key does not have permission to create sessions. Check its project access.');if(status===429)return new Error('Composio is temporarily rate limiting requests. Please try again shortly.');return new Error('Could not connect to Composio. Check your connection and Composio API key, then try again.')}
function validateKey(value){if(typeof value!=='string'||value.trim().length<10||value.length>500)throw Error('Enter your Composio Connect or Platform API key.');const key=value.trim();if(key.startsWith('uak_')||key.startsWith('oak_'))throw Error('Use a Platform project API key for this integration, not a user or organization key.');return key}
function createComposio({directory,safeStorage,openExternal,notify=()=>{},makeConnect=require('./composio-connect.cjs').createConnectSession,makeClient=async key=>{const {Composio}=await import('@composio/core');return new Composio({apiKey:key,allowTracking:false})}}){
 const file=path.join(directory,'composio.json');let data={userId:'orvio-'+randomUUID(),key:'',sessionId:''};try{data={...data,...JSON.parse(fs.readFileSync(file,'utf8'))}}catch{}
 let client,session,loading,generation=0;const pending=new Map(),discovered=new Set(),history=[];
 const state=()=>({configured:!!data.key,mode:data.mode||'platform',pending:[...pending.values()].map(({resolve,timer,...item})=>item),history:history.slice(-20)});
 const emit=()=>notify(state());
 const save=()=>{fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(data),{mode:0o600});fs.renameSync(file+'.tmp',file)};
 async function getSession(){if(session)return session;if(loading)return loading;if(!data.key)throw Error('Connect Composio in Integrations first.');const revision=generation;loading=(async()=>{const key=safeStorage.decryptString(Buffer.from(data.key,'base64'));client=key.startsWith('ck_')?null:await makeClient(key);const next=key.startsWith('ck_')?await makeConnect(key):data.sessionId?await client.use(data.sessionId,{}, {signal:AbortSignal.timeout(30000)}):await client.create(data.userId,{}, {signal:AbortSignal.timeout(30000)});if(revision!==generation)throw Error('Connection settings changed. Please try again.');session=next;data.sessionId=next.sessionId;save();return next})().finally(()=>{loading=null});return loading}
 const api={state,
  async configure(key){key=validateKey(key);if(!safeStorage.isEncryptionAvailable())throw Error('Enable system credential storage before connecting.');let nextClient,next;try{if(key.startsWith('ck_')){next=await makeConnect(key);nextClient=null}else{nextClient=await makeClient(key);next=await nextClient.create(data.userId,{}, {signal:AbortSignal.timeout(30000)})}}catch(error){throw credentialError(error)};api.cancel();void session?.close?.().catch(()=>{});generation++;data.mode=key.startsWith('ck_')?'connect':'platform';data.key=safeStorage.encryptString(key.trim()).toString('base64');data.sessionId=next.sessionId;client=nextClient;session=next;discovered.clear();save();emit();return state()},
  async catalog(input={}){const s=await getSession();const result=await s.toolkits({limit:40,...(input.search?{search:String(input.search).slice(0,150)}:{}),...(input.cursor?{cursor:String(input.cursor).slice(0,1000)}:{}),...(input.connected?{isConnected:true}:{})},{signal:AbortSignal.timeout(30000)});return {items:result.items.map(t=>({slug:t.slug,name:t.name,logo:/^https:\/\//.test(t.logo||'')?t.logo:'',connected:!!t.connection?.isActive,noAuth:!!t.isNoAuth,accountId:t.connection?.connectedAccount?.id||''})),cursor:result.cursor||null}},
  async connect(toolkit){const link=await (await getSession()).authorize(slug(toolkit),{}, {signal:AbortSignal.timeout(30000)});if(link.alreadyConnected)return {status:'connected',message:'This app is already connected. Refresh to see its status.'};const url=new URL(link.redirectUrl);if(url.protocol!=='https:'||url.username||url.password)throw Error('The provider returned an invalid connection link.');await openExternal(url.href);return {status:'authorization_opened',message:'Finish signing in in your browser, then refresh connections.'}},
  async disconnect(toolkit){const s=await getSession();if(s.mode==='connect'){await openExternal('https://dashboard.composio.dev');return {message:'Manage this connection in Composio → Connect Apps.'}}const result=await s.toolkits({toolkits:[slug(toolkit)]});const account=result.items.find(t=>t.slug===toolkit)?.connection?.connectedAccount?.id;if(!account)throw Error('No connected account found for this app.');await client.connectedAccounts.delete(account);return {disconnected:true}},
  async search(query){if(typeof query!=='string'||!query.trim()||query.length>2000)throw Error('Describe the app action to find.');const result=await (await getSession()).search({query},{signal:AbortSignal.timeout(30000)});for(const name of Object.keys(result.toolSchemas||{}))if(!name.startsWith('COMPOSIO_'))discovered.add(name);return result},
  async schema(tool){slug(tool);if(!discovered.has(tool))throw Error('Search for this tool first.');return (await getSession()).execute('COMPOSIO_GET_TOOL_SCHEMAS',{tool_slugs:[tool]}, {}, {signal:AbortSignal.timeout(30000)})},
  async execute(tool,args){slug(tool);if(tool.startsWith('COMPOSIO_')||!discovered.has(tool))throw Error('Search for this app tool before running it.');if(!args||typeof args!=='object'||Array.isArray(args)||JSON.stringify(args).length>32000)throw Error('Tool arguments are too large or invalid.');if(pending.size>=8)throw Error('Review the pending actions first.');const executionSession=await getSession();const frozenArgs=JSON.parse(JSON.stringify(args)),id=randomUUID();const allowed=await new Promise(resolve=>{const timer=setTimeout(()=>{pending.delete(id);resolve(false);emit()},300000);timer.unref?.();pending.set(id,{id,tool,args:frozenArgs,createdAt:new Date().toISOString(),resolve,timer});emit()});if(!allowed)return {declined:true,message:'Action was not approved. Do not retry it without a new user request.'};let result;try{result=await executionSession.execute(tool,frozenArgs,{}, {signal:AbortSignal.timeout(90000),maxRetries:0});history.push({id,tool,status:result.error?'failed':'completed',at:new Date().toISOString()});return result}catch(error){history.push({id,tool,status:'unconfirmed',at:new Date().toISOString()});throw Error('The app did not confirm the outcome. Check the destination app before repeating this action.')}finally{if(history.length>20)history.shift();emit()}},
  approve(id,allow){const request=pending.get(id);if(!request)throw Error('This action has expired. Ask the assistant to prepare it again.');pending.delete(id);clearTimeout(request.timer);request.resolve(allow===true);emit();return state()},
  close(){api.cancel();void session?.close?.().catch(()=>{})},
  cancel(){for(const item of pending.values()){clearTimeout(item.timer);item.resolve(false)}pending.clear();emit()},
  forget(){api.cancel();void session?.close?.().catch(()=>{});generation++;data.mode='platform';data.key='';data.sessionId='';session=null;client=null;discovered.clear();save();emit();return state()}
 };return api;
}
module.exports={createComposio,validateKey,credentialError};
