const path=require('node:path'),{execFile}=require('node:child_process'),{promisify}=require('node:util');const execute=promisify(execFile);
const winFocus="Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class OrvioFocus { [DllImport(\"user32.dll\")] public static extern IntPtr GetForegroundWindow(); }'; [OrvioFocus]::GetForegroundWindow().ToInt64()";
async function foreground(){if(process.platform==='darwin'){const value=(await execute('/usr/bin/osascript',['-e','tell application "System Events" to tell first application process whose frontmost is true to return (unix id as text) & "|" & name'],{timeout:10000})).stdout.trim();const [identity,...name]=value.split('|');return {identity,name:name.join('|')}}if(process.platform==='win32'){const script=winFocus.replace('[OrvioFocus]::GetForegroundWindow().ToInt64()',"$h=[OrvioFocus]::GetForegroundWindow(); $p=Get-Process | Where-Object {$_.MainWindowHandle -eq $h} | Select-Object -First 1; @{identity=$h.ToInt64().ToString();name=$p.ProcessName} | ConvertTo-Json -Compress");return JSON.parse((await execute('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:10000})).stdout)}throw Error('Global dictation supports Windows and macOS.')}
async function key(command){const mac={paste:'keystroke "v" using command down',undo:'keystroke "z" using command down',redo:'keystroke "z" using {command down, shift down}','delete-word':'key code 51 using option down','select-all':'keystroke "a" using command down',backspace:'key code 51',bold:'keystroke "b" using command down',italic:'keystroke "i" using command down'};const win={paste:'^v',undo:'^z',redo:'^y','delete-word':'^{BACKSPACE}','select-all':'^a',backspace:'{BACKSPACE}',bold:'^b',italic:'^i'};if(!mac[command])throw Error('Unsupported edit command');if(process.platform==='darwin')await execute('/usr/bin/osascript',['-e','tell application "System Events" to '+mac[command]],{timeout:10000});else await execute('powershell.exe',['-NoProfile','-NonInteractive','-Command',"Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SendKeys]::SendWait('"+win[command]+"')"],{windowsHide:true,timeout:10000})}
async function paste(clipboard,text,target){let clean=String(text);if(!clean)return 'No speech was detected.';if(/terminal|powershell|cmd|iterm|console/i.test(target?.name||''))clean=clean.replace(/[\r\n]+/g,' ');clipboard.writeText(clean);if(!target||(await foreground()).identity!==target.identity)return 'Text copied. Your focused app changed; paste when ready.';await key('paste');return 'Paste requested · text is also on your clipboard.'}
function createDictation({app,BrowserWindow,screen,ipcMain,clipboard,systemPreferences,localStudio,modelHub,settings,pausePet,resumePet}){let window=null,target=null,armed=false,processing=false,opening=false;
 function close(){armed=false;window?.destroy();window=null;resumePet()}
 function permission(contents,permission,details){return !!window&&contents===window.webContents&&armed&&permission==='media'&&(!details?.mediaTypes||details.mediaTypes.every(t=>t==='audio'))&&(!details?.mediaType||details.mediaType==='audio')}
 async function toggle(){if(opening)return;if(window){window.webContents.send('dictation:finish');return}opening=true;try{pausePet();target=null;if(process.platform!=='darwin'||systemPreferences.isTrustedAccessibilityClient(false))try{target=await foreground()}catch{}const area=screen.getPrimaryDisplay().workArea;window=new BrowserWindow({x:Math.round(area.x+area.width/2-220),y:area.y+area.height-100,width:440,height:84,show:false,transparent:true,frame:false,alwaysOnTop:true,skipTaskbar:true,focusable:false,resizable:false,hasShadow:false,webPreferences:{autoplayPolicy:'no-user-gesture-required',preload:path.join(__dirname,'dictation-preload.cjs'),sandbox:true,nodeIntegration:false,contextIsolation:true}});window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.once('ready-to-show',()=>window?.showInactive());window.on('closed',()=>{window=null;armed=false;resumePet()});if(app.isPackaged)window.loadFile(path.join(__dirname,'../dist/index.html'),{hash:'dictation'});else window.loadURL('http://127.0.0.1:5188/#dictation')}finally{opening=false}}
 function handle(name,fn){ipcMain.handle(name,(event,...args)=>{if(!window||event.sender!==window.webContents||event.senderFrame!==window.webContents.mainFrame)throw Error('Untrusted dictation request');return fn(...args)})}
 handle('dictation:arm',()=>{const config=settings.state(),model=config.dictationModel;const ready=model==='mms'?localStudio.state().mmsInstalled.includes(config.mmsLanguage):localStudio.state().models.find(m=>m.id===model)?.installed;if(!ready)throw Error('Download the selected speech model in Settings → Desktop & shortcuts.');armed=true;return true});handle('dictation:cancel',close);
 handle('dictation:finish',async bytes=>{if(!armed||processing)throw Error('Dictation is not recording.');processing=true;armed=false;try{const config=settings.state();const result=await localStudio.petTranscribe(bytes,config.dictationModel,config.dictationModel==='mms'?config.mmsLanguage:config.dictationLanguage);if(!window)return 'Dictation cancelled.';const text=result.segments.map(s=>s.text).join(' ').trim();if(!text)return 'No speech detected. Try again.';const {editCommand,rewrite}=require('./dictation-text.cjs');const command=config.voiceCommands?editCommand(text):null;try{if(command&&command!=='newline'&&command!=='paragraph'){if(!target||(await foreground()).identity!==target.identity)return 'Command skipped because the focused app changed.';await key(command);return 'Edit command sent: '+command}let output,note='';if(command)output=command==='newline'?'\n':'\n\n';else{try{const edited=await rewrite({text,settings:config,appName:target?.name||'Unknown app',modelHub});output=edited.text;note=edited.note||''}catch{output=text;note='AI cleanup was unavailable; original transcript used.'}}if(!window)return 'Dictation cancelled.';const result=await paste(clipboard,output,target);return note?note+' '+result:result}catch{clipboard.writeText(text);return 'Text copied. Allow keyboard access in Settings to paste automatically.'}}finally{processing=false}});
 return {toggle,close,permission,busy:()=>!!window||processing,requestAccess(){return process.platform!=='darwin'||systemPreferences.isTrustedAccessibilityClient(true)}};
}
module.exports={createDictation};
