const {createServer}=require('node:http');
const {randomBytes,createHash}=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');

function createDriveConnector({getConfig,saveConfig,decrypt,encrypt,fetchImpl=fetch,openExternal}){
 let server=null,accessToken='',expiresAt=0;
 const safeId=id=>{if(!/^[\w.-]+\.apps\.googleusercontent\.com$/.test(id||''))throw new Error('Enter a Google OAuth Desktop client ID.');return id;};
 async function tokenRequest(params){let response;try{response=await fetchImpl('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams(params),redirect:'error',signal:AbortSignal.timeout(15000)});}catch{throw new Error('Google sign-in could not finish. Check your connection.');}const body=await response.json();if(!response.ok||!body.access_token)throw new Error(`Google sign-in failed (${body.error||response.status}). Check the Desktop client ID and Drive API setup.`);return body;}
 async function token(){if(accessToken&&Date.now()<expiresAt-60000)return accessToken;const config=getConfig();if(!config.refreshToken)throw new Error('Connect Google Drive first.');const result=await tokenRequest({client_id:safeId(config.clientId),refresh_token:decrypt(config.refreshToken),grant_type:'refresh_token'});accessToken=result.access_token;expiresAt=Date.now()+(result.expires_in||3600)*1000;return accessToken;}
 async function connect(clientId){safeId(clientId);if(server)throw new Error('Google sign-in is already open.');const verifier=randomBytes(48).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url'),state=randomBytes(24).toString('base64url');let redirectURI;
  server=createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname!=='/oauth/google'){res.writeHead(404).end();return;}if(url.searchParams.get('state')!==state){res.writeHead(400).end('Invalid sign-in state.');return;}const code=url.searchParams.get('code');if(!code){res.writeHead(400).end('Sign-in was cancelled.');server?.close();server=null;return;}try{const result=await tokenRequest({client_id:clientId,code,code_verifier:verifier,redirect_uri:redirectURI,grant_type:'authorization_code'});if(!result.refresh_token)throw new Error('Google did not return offline access. Reconnect and approve access.');accessToken=result.access_token;expiresAt=Date.now()+(result.expires_in||3600)*1000;saveConfig({clientId,refreshToken:encrypt(result.refresh_token),connectedAt:new Date().toISOString(),lastError:''});res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}).end('<!doctype html><title>Orvio Studio</title><p>Google Drive connected. Return to Orvio Studio; you can close this tab.</p>');}catch(error){saveConfig({clientId,refreshToken:'',connectedAt:'',lastError:error.message});res.writeHead(400,{'Content-Type':'text/plain; charset=utf-8'}).end('Google Drive connection failed. Return to Orvio Studio for details.');}finally{server?.close();server=null;}});
  try{await new Promise((resolve,reject)=>server.once('error',reject).listen(0,'127.0.0.1',resolve));redirectURI=`http://127.0.0.1:${server.address().port}/oauth/google`;const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');for(const [key,value] of Object.entries({client_id:clientId,redirect_uri:redirectURI,response_type:'code',scope:'https://www.googleapis.com/auth/drive.file',access_type:'offline',prompt:'consent',state,code_challenge:challenge,code_challenge_method:'S256'}))url.searchParams.set(key,value);await openExternal(url.href);setTimeout(()=>{if(server){server.close();server=null}},5*60*1000).unref();return {pending:true};}catch(error){server?.close();server=null;throw error;}
 }
 async function list(){const url=new URL('https://www.googleapis.com/drive/v3/files');url.searchParams.set('q','trashed = false');url.searchParams.set('fields','files(id,name,mimeType,size,webViewLink,modifiedTime),nextPageToken');url.searchParams.set('pageSize','50');url.searchParams.set('orderBy','modifiedTime desc');const response=await fetchImpl(url.href,{headers:{Authorization:`Bearer ${await token()}`},redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`Google Drive could not load files (${response.status}). Reconnect if access expired.`);return (await response.json()).files||[];}
 async function upload(filePath){const info=fs.statSync(filePath);if(!info.isFile()||info.size===0||info.size>25*1024*1024)throw new Error('Choose a file under 25 MB for Drive.');const name=path.basename(filePath),boundary='orvio-'+randomBytes(16).toString('hex');const mime={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.mp4':'video/mp4','.mov':'video/quicktime'}[path.extname(filePath).toLowerCase()]||'application/octet-stream';const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name})}\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`),fs.readFileSync(filePath),Buffer.from(`\r\n--${boundary}--`)]);const url='https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink';const response=await fetchImpl(url,{method:'POST',headers:{Authorization:`Bearer ${await token()}`,'Content-Type':`multipart/related; boundary=${boundary}`},body,redirect:'error',signal:AbortSignal.timeout(120000)});if(!response.ok)throw new Error(`Google Drive upload failed (${response.status}).`);return response.json();}
 function disconnect(){if(server){server.close();server=null;}accessToken='';expiresAt=0;saveConfig({clientId:'',refreshToken:'',connectedAt:'',lastError:''});}
 return {connect,list,upload,disconnect};
}
module.exports={createDriveConnector};
