const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{randomUUID}=require('node:crypto');
const voices=[['en_US-amy-medium','English · Amy'],['ar_JO-kareem-medium','Arabic · Kareem'],['hi_IN-pratham-medium','Hindi · Pratham'],['es_ES-davefx-medium','Spanish · Dave'],['fr_FR-mls-medium','French · MLS'],['de_DE-mls-medium','German · MLS'],['ru_RU-denis-medium','Russian · Denis']].map(([id,name])=>({id,name,engine:'piper',size:'~65–80 MB',license:'See voice model card',url:'https://huggingface.co/rhasspy/piper-voices'}));
const catalog=[...voices,{id:'chatterbox',name:'Chatterbox · voice cloning',engine:'chatterbox',size:'Several GB · 8 GB RAM recommended',license:'MIT',url:'https://github.com/resemble-ai/chatterbox'},{id:'whisper',name:'Whisper Tiny · multilingual transcription',engine:'whisper',size:'~75 MB + engine',license:'MIT',url:'https://github.com/SYSTRAN/faster-whisper'},{id:'video',name:'Video downloader & clip export',engine:'video',size:'~100 MB',license:'yt-dlp / FFmpeg notices',url:'https://github.com/yt-dlp/yt-dlp'}];
const packages={piper:['piper-tts==1.8.0'],chatterbox:['chatterbox-tts==0.1.7'],whisper:['faster-whisper==1.2.1'],video:['yt-dlp[default]==2026.8.19','imageio-ffmpeg==0.6.0']};
function createLocalStudio({directory,resources,python,notify=()=>{}}){
 const root=path.join(directory,'local-studio');fs.mkdirSync(root,{recursive:true});for(const name of fs.readdirSync(root)){if(/^[0-9a-f-]{36}\.cookies\.txt$/.test(name))try{fs.unlinkSync(path.join(root,name))}catch{}}const registry=path.join(root,'assets.json');let assets=[];try{assets=JSON.parse(fs.readFileSync(registry,'utf8'))}catch{}let active=null,child=null,cancelled=false,sessionCookies=null;
 const envPython=engine=>path.join(root,engine,process.platform==='win32'?'Scripts/python.exe':'bin/python');
 const signature=id=>JSON.stringify(packages[catalog.find(m=>m.id===id)?.engine]||[]);
 const ready=id=>{try{return fs.readFileSync(path.join(root,`${id}.ready`),'utf8')===signature(id)}catch{return false}};
 const state=()=>({hasSession:!!sessionCookies,models:catalog.map(m=>({...m,installed:ready(m.id),unsupported:m.id==='chatterbox'&&process.platform==='darwin'&&process.arch==='x64'?'Voice cloning requires Apple Silicon or Windows.':null})),active,assets:assets.map(({file,...a})=>({...a,preview:`orvio-media://asset/${a.id}`}))});
 function report(message){active={...active,message};notify(state())}
 function exec(file,args,input){return new Promise((resolve,reject)=>{if(cancelled)return reject(Error('Cancelled'));let result,buffer='',errors='';child=spawn(file,args,{windowsHide:true,detached:process.platform!=='win32',env:{...process.env,PYTHONNOUSERSITE:'1',PYTHONUNBUFFERED:'1',OMP_NUM_THREADS:'2',HF_HOME:path.join(root,'models/huggingface'),ELECTRON_RUN_AS_NODE:'1'}});child.stdout.on('data',data=>{buffer+=data;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.startsWith('ORVIO_RESULT '))result=JSON.parse(line.slice(13));else if(line.startsWith('ORVIO_PROGRESS '))report(JSON.parse(line.slice(15)));else if(line.startsWith('ORVIO_ERROR '))errors=JSON.parse(line.slice(12));else if(line.startsWith('Collecting '))report(line.slice(0,160));}});child.stderr.on('data',d=>{errors=(errors+d).slice(-2500)});child.on('error',reject);child.on('close',code=>{child=null;code===0?resolve(result):reject(Error(cancelled?'Cancelled':errors||`Local engine exited (${code})`))});child.stdin.on('error',()=>{});child.stdin.end(input?JSON.stringify(input):undefined)})}
 async function task(name,fn){if(active)throw Error('Wait for the current local task, or cancel it first.');cancelled=false;active={name,message:'Starting…'};notify(state());try{return await fn()}catch(error){if(/Requested format is not available/i.test(error.message))throw Error('The site did not offer a downloadable video stream. Try your own session file if sign-in is required, or another video link.');throw error}finally{active=null;notify(state())}}
 async function install(id){const model=catalog.find(m=>m.id===id);if(!model)throw Error('Unknown model');if(state().models.find(m=>m.id===id).unsupported)throw Error('This model is not supported on Intel Mac.');if(ready(id))return;if(!fs.existsSync(python))throw Error('Bundled Python is missing. Install the latest Orvio build. Developers: run npm run runtime:prepare.');const executable=envPython(model.engine);if(!fs.existsSync(executable)){report('Preparing private Python environment…');await exec(python,['-m','venv','--copies',path.join(root,model.engine)])}report('Downloading engine dependencies…');await exec(executable,['-m','pip','--isolated','install','--index-url','https://pypi.org/simple','--retries','4','--timeout','60','--disable-pip-version-check',...packages[model.engine]]);if(id!=='video'){report('Downloading model weights…');await worker(model.engine,{action:id==='whisper'?'install_whisper':'install_voice',model:id})}fs.writeFileSync(path.join(root,`${id}.ready`),signature(id));}
 const worker=async(engine,input)=>{const result=await exec(envPython(engine),[path.join(resources,'worker.py')],{...input,models:path.join(root,'models'),jsRuntime:process.execPath});if(!result)throw Error('Local engine returned no result. Please try again.');return result};
 function file(id){const a=assets.find(a=>a.id===id);if(!a||!fs.existsSync(a.file))throw Error('Media file is no longer available.');return a.file}
 function asset(file,kind,title,extra={}){const a={id:randomUUID(),file,kind,title,createdAt:new Date().toISOString(),...extra};assets.unshift(a);fs.writeFileSync(registry,JSON.stringify(assets));return {...a,preview:`orvio-media://asset/${a.id}`}}
 const output=ext=>path.join(root,randomUUID()+ext);
 return {state,file,videoRuntime:()=>task('Prepare video engine',async()=>{await install('video');return {python:envPython('video'),worker:path.join(resources,'broadcast.py')}}),setSession(filePath){if(!filePath){sessionCookies=null;notify(state());return}const info=fs.statSync(filePath);if(info.size>2*1024*1024)throw Error('Choose a Netscape cookie text file under 2 MB.');const content=fs.readFileSync(filePath,'utf8');if(!/^# (?:Netscape HTTP Cookie File|HTTP Cookie File)/.test(content))throw Error('Choose an exported Netscape-format cookie file.');sessionCookies=content;notify(state())},cancel(){cancelled=true;if(child){if(process.platform==='win32')spawn('taskkill',['/pid',String(child.pid),'/T','/F']);else try{process.kill(-child.pid,'SIGTERM')}catch{child.kill()}}},install:id=>task('Download model',()=>install(id)),import(filePath,kind){const ext=path.extname(filePath).toLowerCase();if(!(kind==='audio'?['.wav','.mp3','.m4a','.flac']:['.mp4','.mov','.webm','.mkv']).includes(ext))throw Error('Unsupported media file');const dest=output(ext);fs.copyFileSync(filePath,dest);const a=asset(dest,kind,path.basename(filePath));notify(state());return a},
 download:input=>task('Download video',async()=>{const url=new URL(input.url);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('Enter a valid video website link.');await install('video');report('Downloading video…');const dest=output('.mp4');const cookies=sessionCookies?output('.cookies.txt'):null;try{if(cookies)fs.writeFileSync(cookies,sessionCookies,{mode:0o600});const info=await worker('video',{action:'download',url:url.href,output:dest,cookies});return asset(dest,'video',info.title,info)}catch(error){for(const name of fs.readdirSync(root))if(name.startsWith(path.basename(dest)))try{fs.unlinkSync(path.join(root,name))}catch{}throw error}finally{if(cookies)try{fs.unlinkSync(cookies)}catch{}}}),
 voice:input=>task('Generate speech',async()=>{const m=catalog.find(m=>m.id===input.model&&['piper','chatterbox'].includes(m.engine));if(!m||typeof input.text!=='string'||!input.text.trim()||input.text.length>5000)throw Error('Choose a voice and enter up to 5,000 characters.');if(input.referenceId&&!input.consent)throw Error('Confirm you have permission to use this voice.');await install(m.id);report('Generating speech locally…');const dest=output('.wav');await worker(m.engine,{action:'voice',model:m.id,text:input.text,language:input.language||'en',reference:input.referenceId?file(input.referenceId):undefined,output:dest});return asset(dest,'audio',input.text.slice(0,60))}),
 transcribe:id=>task('Transcribe video',async()=>{const source=file(id);await install('whisper');report('Listening locally…');return worker('whisper',{action:'transcribe',source})}),
 captions:input=>task('Export captions',async()=>{if(!Array.isArray(input.segments)||input.segments.length>3000)throw Error('Add valid captions.');const source=file(input.id);await install('video');report(input.format==='srt'?'Preparing subtitle file…':'Rendering captions into video…');const subtitle=input.format==='srt';const dest=output(subtitle?'.srt':'.mp4');const result=await worker('video',{action:'captions',source,output:dest,segments:input.segments,style:input.style,size:input.size,position:input.position,format:subtitle?'srt':'video'});return asset(dest,subtitle?'subtitle':'video',subtitle?'Subtitle file':'Captioned video',result)}),
 clip:input=>task('Export clip',async()=>{const start=Number(input.start),end=Number(input.end);if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start||end-start>300)throw Error('Choose valid start/end times, up to five minutes.');const source=file(input.id);await install('video');report('Exporting clip…');const dest=output('.mp4');await worker('video',{action:'clip',source,output:dest,start,end,vertical:!!input.vertical});return asset(dest,'video',input.title||'Video clip',{duration:end-start})})};
}
module.exports={createLocalStudio,catalog};
