let fileDownloader,aiRouter,routerTunnel,nativeAuth;
const { app, Notification, BrowserWindow, ipcMain, shell, Tray, Menu, nativeImage, safeStorage, powerMonitor, dialog, protocol, net, desktopCapturer, powerSaveBlocker, screen, globalShortcut, clipboard, systemPreferences } = require('electron');
const path = require('node:path');
const { autoUpdater } = require('electron-updater');
const { externalURL,oauthExternalURL } = require('./security.cjs');
const { createUpdateController, RELEASES_URL } = require('./updates.cjs');
const {createWorkspace}=require('./workspace.cjs');
let seo,updateNotification,storageLocation,composio;
let pets,petWindow,desktopSettings,dictation,workAgent;
let localStudio,production,modelHub,downloads,updateDownloadId,pcHelper,modelScan;
let downloadBlocker=null,lastDownloadCount=-1,pendingDevRestart=false;
let productionBlocker=null,lastProductionStatus='';
let chatMicUntil=0,chatMicOwner=null,captureOwner=null;
let recorderCapture;
let captureUntil=0,captureSource='',captureSystemAudio=false;
// Canvas reads (AI image previews and video frames) need a CORS-enabled scheme.
protocol.registerSchemesAsPrivileged([{scheme:"orvio-media",privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true,corsEnabled:true}}]);
let mainWindow,tray,workspace,quitting=false,islandWindow,movingWindow;
const {bots,validateBot,parseBotArgs,createBotShortcuts}=require('./bot-shortcuts.cjs');
const botWindows=new Map(),workspaceWindows=new Set();
let pendingBot=parseBotArgs(process.argv),workspaceReady=false;
const trustedContents=contents=>[...workspaceWindows].some(win=>!win.isDestroyed()&&win.webContents===contents);
const activeWindow=()=>{const focused=BrowserWindow.getFocusedWindow();return workspaceWindows.has(focused)?focused:mainWindow||[...workspaceWindows][0]};
function broadcast(channel,...args){for(const win of workspaceWindows)if(!win.isDestroyed())win.webContents.send(channel,...args)}
function openBot(id){validateBot(id);if(!workspaceReady){pendingBot=id;return}const existing=botWindows.get(id);if(existing&&!existing.isDestroyed()){if(existing.isMinimized())existing.restore();existing.show();existing.focus();return}openWindow(id)}

if(!app.requestSingleInstanceLock())app.quit();
app.setAppUserModelId('com.orvio.studio');
if(!app.isPackaged&&process.send)process.on('message',message=>{if(message?.type==='orvio:dev-stop'){app.quit()}else if(message?.type==='orvio:dev-restart'){if(movingWindow||downloads?.state().some(d=>d.status==='active')){pendingDevRestart=true;process.send?.({type:'orvio:restart-deferred'})}else app.quit()}});
function showWindow(){if(movingWindow&&!movingWindow.isDestroyed()){movingWindow.show();movingWindow.focus();return}islandWindow?.hide();if(!mainWindow||mainWindow.isDestroyed())openWindow();else{mainWindow.show();mainWindow.focus();}}
function islandState(){return {downloads:downloads?.state().filter(d=>d.status==='active').length||0,recording:!!production?.state().recording,live:['connecting','sending'].includes(production?.state().live?.status),paused:!!workspace?.snapshot().paused}}
function refreshIsland(){if(islandWindow&&!islandWindow.isDestroyed()){islandWindow.webContents.send('island:changed',islandState());if(workspace?.snapshot().showIsland===false)islandWindow.hide()}}
function islandBounds(expanded){const area=screen.getPrimaryDisplay().workArea;const width=expanded?350:270;return {x:Math.round(area.x+(area.width-width)/2),y:desktopSettings?.state().islandPosition==='bottom'?area.y+area.height-74:area.y+10,width,height:64}}
function showIsland(){if(quitting||workspace?.snapshot().showIsland===false)return;if(!islandWindow){islandWindow=new BrowserWindow({...islandBounds(false),transparent:true,frame:false,resizable:false,alwaysOnTop:true,skipTaskbar:true,focusable:false,show:false,hasShadow:false,webPreferences:{preload:path.join(__dirname,'island-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});islandWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));islandWindow.webContents.on('will-navigate',event=>event.preventDefault());islandWindow.once('ready-to-show',()=>{if([...workspaceWindows].some(w=>!w.isDestroyed()&&w.isVisible()&&!w.isMinimized()))return;islandWindow.showInactive();refreshIsland()});if(app.isPackaged)islandWindow.loadFile(path.join(__dirname,'../dist/index.html'),{hash:'island'});else islandWindow.loadURL('http://127.0.0.1:5188/#island');islandWindow.on('closed',()=>islandWindow=null)}else{islandWindow.setBounds(islandBounds(false));islandWindow.showInactive();refreshIsland()}}
function islandHandle(channel,handler){ipcMain.handle(channel,(event,...args)=>{if(!islandWindow||event.sender!==islandWindow.webContents||event.senderFrame!==islandWindow.webContents.mainFrame)throw Error('Untrusted island request');return handler(...args)})}
islandHandle('island:state',islandState);
islandHandle('island:expand',expanded=>islandWindow.setBounds(islandBounds(!!expanded),process.platform==='darwin'));
islandHandle('island:action',action=>{if(action==='dictation')return dictation.toggle();if(action==='publishing'){workspace.preferences({paused:!workspace.snapshot().paused});return}if(action==='stop-recording'){broadcast('recorder:stop');return}if(!['Home','Chat','PC Helper','downloads'].includes(action))throw Error('Unknown shortcut');showWindow();if(action==='downloads')mainWindow.webContents.send('downloads:open');else mainWindow.webContents.send('workspace:navigate',action)});
app.on('second-instance',(_event,args)=>{const id=parseBotArgs(args);if(id)openBot(id);else if(workspaceReady)showWindow()});
ipcMain.on('storage:window-minimize',event=>{if(movingWindow&&event.sender===movingWindow.webContents&&event.senderFrame===movingWindow.webContents.mainFrame)movingWindow.minimize()});
app.on('before-quit',()=>{quitting=true;composio?.close();downloads?.prepareShutdown();if(downloadBlocker!==null)powerSaveBlocker.stop(downloadBlocker);seo?.cancel();routerTunnel?.stop();void nativeAuth?.cancel();aiRouter?.stop();globalShortcut.unregisterAll();dictation?.close();recorderCapture?.shutdown();petWindow?.hide();workAgent?.shutdown();localStudio?.shutdown();production?.shutdown();modelHub?.shutdown();});
function refreshTray(){if(!tray||!workspace)return;tray.setContextMenu(Menu.buildFromTemplate([{label:'Open Orvio Studio',click:showWindow},{label:`Downloads (${downloads?.state().filter(d=>d.status==='active').length||0} active)`,click:()=>{showWindow();mainWindow.webContents.send('downloads:open')}},{label:'Show companion',click:()=>{if(pets?.state().settings.enabled)petWindow.show();else{showWindow();mainWindow.webContents.send('workspace:navigate','Pets')}}},{label:'Pause automations',type:'checkbox',checked:workspace.snapshot().paused,click:item=>workspace.preferences({paused:item.checked})},...(production?.state().recording?[{label:'Stop and save recording',click:()=>broadcast('recorder:stop')}]:[]),...(['connecting','sending','stopping'].includes(production?.state().live?.status)?[{label:'Stop YouTube stream',click:()=>production.stop()}]:[]),{type:'separator'},{label:downloads?.state().some(d=>d.status==='active')?'Quit and resume downloads next launch':'Quit Orvio Studio',click:()=>app.quit()}]));}
const updates=createUpdateController({updater:autoUpdater,packaged:app.isPackaged,platform:process.platform,macSigned:false,alert:(kind,info)=>updateNotification?.(kind,info),send:state=>{if(downloads){if(state.phase==='downloading'){updateDownloadId ||= downloads.begin({title:'Orvio app update',kind:'update'});downloads.update(updateDownloadId,{message:state.message,received:state.received??state.percent,total:state.total??100,speed:state.speed})}else if(updateDownloadId&&['ready','error'].includes(state.phase)){downloads.finish(updateDownloadId,state.phase==='ready'?'completed':'failed',{message:state.message});updateDownloadId=null}}broadcast('update:status',state);}});
function openWindow(botId=null) {
 const win = new BrowserWindow({width:1280,height:850,minWidth:800,minHeight:650,title:botId?bots[botId]+' · Orvio':'Orvio Studio',icon:path.join(__dirname,botId?'../dist/bots/'+botId+'.png':'../dist/orvio-logo.png'),backgroundColor:'#f8f9fb',show:false,...(process.platform==='darwin'?{titleBarStyle:'hiddenInset'}:{frame:false}),webPreferences:{additionalArguments:app.isPackaged?[]:['--orvio-development'],preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
 workspaceWindows.add(win);if(botId)botWindows.set(botId,win);else mainWindow=win;
 win.on('closed',()=>{workspaceWindows.delete(win);if(botId)botWindows.delete(botId);else mainWindow=null});
 win.on('page-title-updated',event=>event.preventDefault());
 win.on('close',event=>{if(!quitting){event.preventDefault();win.hide();showIsland();}});
 win.on('minimize',showIsland);win.on('show',()=>islandWindow?.hide());win.on('restore',()=>islandWindow?.hide());
 win.once('ready-to-show',()=>win.show());
 let rendererRestarts=0;
 win.webContents.on('render-process-gone',(_event,details)=>{
  console.error('Orvio renderer exited:',details.reason);
  if(!quitting&&rendererRestarts++<1){win.webContents.reload();win.show()}
  else if(!quitting)dialog.showMessageBox(win,{type:'error',title:'Workspace stopped',message:'The workspace could not recover. Restart Orvio. If a local model was loading, choose a smaller model or a cloud provider.'});
 });
 win.webContents.setWindowOpenHandler(({url})=>{try{shell.openExternal(externalURL(url));}catch{}return {action:'deny'};});
 win.webContents.on('will-navigate',(event,url)=>{if(url!==win.webContents.getURL())event.preventDefault();});
 win.webContents.session.setPermissionRequestHandler((contents,permission,callback,details)=>callback((trustedContents(contents)&&contents===captureOwner&&Date.now()<captureUntil&&['media','display-capture'].includes(permission))||(trustedContents(contents)&&contents===chatMicOwner&&Date.now()<chatMicUntil&&permission==='media'&&(details.mediaTypes?.every(t=>t==='audio')||details.mediaType==='audio'))||petWindow?.permission(contents,permission,details)||dictation?.permission(contents,permission,details)||false));
 win.webContents.session.setPermissionCheckHandler((contents,permission,_origin,details)=>(trustedContents(contents)&&contents===captureOwner&&Date.now()<captureUntil&&['media','display-capture'].includes(permission))||(trustedContents(contents)&&contents===chatMicOwner&&Date.now()<chatMicUntil&&permission==='media'&&(details.mediaTypes?.every(t=>t==='audio')||details.mediaType==='audio'))||petWindow?.permission(contents,permission,details)||dictation?.permission(contents,permission,details)||false);
 win.webContents.session.setDisplayMediaRequestHandler(async(request,callback)=>{if(!trustedContents(captureOwner)||request.frame!==captureOwner.mainFrame||Date.now()>captureUntil||!captureSource)return callback({});try{const sources=await desktopCapturer.getSources({types:['screen','window']});const source=sources.find(s=>s.id===captureSource);if(!source)return callback({});callback({video:source,...(captureSystemAudio&&process.platform==='win32'?{audio:'loopback'}:{})});captureSource=''}catch{callback({})}},{useSystemPicker:false});
 win.webContents.session.webRequest.onHeadersReceived((details,callback)=>{callback({responseHeaders:{...details.responseHeaders,'Content-Security-Policy':["default-src 'self'; script-src 'self'"+(app.isPackaged?'':" 'unsafe-inline'")+"; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: https: orvio-media:; media-src 'self' blob: https: orvio-media:; connect-src 'self' ws://127.0.0.1:5188; object-src 'none'; base-uri 'self'; frame-src 'none'"]}})});
 if(app.isPackaged)win.loadFile(path.join(__dirname,'../dist/index.html'),botId?{hash:'bot='+botId}:{});else win.loadURL('http://127.0.0.1:5188/'+(botId?'#bot='+botId:''));
}
function handle(channel,action){ipcMain.handle(channel,(event,...args)=>{if(!trustedContents(event.sender)||event.senderFrame!==event.sender.mainFrame)throw new Error('Untrusted request');return action.apply(BrowserWindow.fromWebContents(event.sender),args);});}
handle('work:state',()=>workAgent.state());
handle('work:permissions',value=>workAgent.setPermissions(value));
handle('work:browse',url=>workAgent.openBrowser(url));
handle('work:stop-preview',()=>workAgent.stopPreview());
handle('work:choose',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{properties:['openDirectory']});return result.canceled?null:workAgent.choose(result.filePaths[0])});
handle('work:create',async name=>{if(typeof name!=='string'||!/^[a-zA-Z0-9][a-zA-Z0-9 _-]{0,63}$/.test(name))throw Error('Use a project name with letters, numbers, spaces or dashes.');const result=await dialog.showOpenDialog(activeWindow(),{title:'Choose the parent folder for your project',properties:['openDirectory']});if(result.canceled)return null;const folder=path.join(result.filePaths[0],name);await require('node:fs/promises').mkdir(folder);return workAgent.choose(folder)});
handle('work:select',id=>workAgent.select(id));
handle('work:run',input=>workAgent.run(input));
handle('work:cancel',()=>workAgent.cancel());
handle('work:approve',(id,allow)=>workAgent.approve(id,allow));
handle('work:review',id=>workAgent.review(id));
handle('work:undo',id=>workAgent.undo(id));
handle('desktop:state',()=>desktopSettings.state());
handle('desktop:save',input=>{const state=desktopSettings.save(input);if(islandWindow)islandWindow.setBounds(islandBounds(false));return state});
handle('dictation:access',()=>dictation.requestAccess());
handle('pets:state',()=>pets.state());
handle('pets:save',input=>{const result=pets.save(input);petWindow.show();return result});
handle('pets:show',()=>petWindow.show());
handle('workspace:state',()=>workspace.snapshot());
handle('window:minimize',function(){this.minimize()});
handle('window:maximize',function(){if(this.isMaximized())this.unmaximize();else this.maximize()});
handle('window:close',function(){this.close()});
handle('bots:shortcut',function(id){return createBotShortcuts({app,shell,dialog,nativeImage}).create(id,this)});
handle('bots:open',id=>openBot(id));
handle('bots:workspace',()=>showWindow());
handle('media:save',input=>workspace.saveMedia(input));
handle('media:choose',async accountId=>{const result=await dialog.showOpenDialog(activeWindow(),{properties:['openFile'],filters:[{name:'Images and videos',extensions:['jpg','jpeg','png','mp4','mov']}]});if(result.canceled)return null;return workspace.prepareMedia(result.filePaths[0],accountId);});
handle('media:generated',(id,accountId)=>workspace.prepareGenerated(id,accountId));
handle('images:models',input=>workspace.listImageModels(input));
handle('images:generate',input=>workspace.generateImage(input));
handle('videos:list',accountId=>workspace.listAccountVideos(accountId));
handle('videos:download',input=>workspace.downloadVideo(input));
handle('local:session',async clear=>{if(clear)return localStudio.setSession(null);const result=await dialog.showOpenDialog(activeWindow(),{properties:['openFile'],filters:[{name:'Your exported account cookies',extensions:['txt']}]});if(!result.canceled)localStudio.setSession(result.filePaths[0]);});
handle('pc:state',()=>pcHelper.state());
handle('pc:scan',options=>pcHelper.scan({duplicates:!!options?.duplicates,minMB:Number(options?.minMB)||100}));
handle('pc:folder',async options=>{const selected=await dialog.showOpenDialog(activeWindow(),{properties:['openDirectory']});return selected.canceled?pcHelper.state():pcHelper.scan({duplicates:!!options?.duplicates,minMB:Number(options?.minMB)||100,folder:selected.filePaths[0]})});
handle('pc:cancel',()=>pcHelper.cancel());
handle('pc:trash',ids=>pcHelper.remove(ids));
handle('pc:apps',()=>pcHelper.listApps());
handle('pc:app-files',id=>pcHelper.appFiles(id));
handle('pc:uninstall',id=>pcHelper.openNativeUninstaller(id));
handle('pc:models',async choose=>{if(modelScan)return modelScan;let folder;if(choose){const selected=await dialog.showOpenDialog(activeWindow(),{properties:['openDirectory']});if(selected.canceled)return pcHelper.state();folder=selected.filePaths[0]}modelScan=pcHelper.scanModels(folder).finally(()=>modelScan=null);return modelScan});
handle('pc:use-model',id=>{const model=pcHelper.modelInfo(id);return model.kind==='chat'?modelHub.importGGUF(model.file,true,model.name):localStudio.attachModel(model.modelId,model.file)});
handle('downloads:state',()=>downloads.state());
handle('downloads:cancel',id=>downloads.cancel(id));
handle('downloads:retry',id=>downloads.retry(id));
handle('downloads:pause',id=>downloads.pause(id));
handle('downloads:clear',()=>downloads.clear());
handle('models:search',query=>modelHub.search(query));
handle('models:files',repo=>modelHub.remoteFiles(repo));
handle('models:remote',input=>modelHub.installRemote(input));
handle('models:benchmark',id=>modelHub.benchmark(id));
handle('models:hardware',async()=>{const hardware=await require('./hardware.cjs').detectHardware(app);modelHub.setHardware(hardware);return hardware});
handle('router:state',()=>({...aiRouter.state(),oauth:nativeAuth.state(),tunnel:routerTunnel.state()}));
handle('router:account',input=>{const id=aiRouter.saveAccount(input);void aiRouter.test(id).catch(()=>{});return id});
handle('router:remove-account',id=>aiRouter.removeAccount(id));
handle('router:route',input=>aiRouter.saveRoute(input));
handle('router:remove-route',name=>aiRouter.removeRoute(name));
handle('router:test',id=>aiRouter.test(id));
handle('router:check',()=>aiRouter.check());
handle('router:refresh',()=>aiRouter.refresh());
handle('router:sign-in',input=>nativeAuth.login(input));
handle('router:cancel-sign-in',()=>nativeAuth.cancel());
handle('router:auto-start',value=>aiRouter.setAutoStart(value));
handle('router:start',port=>aiRouter.start(port));
handle('router:stop',async()=>{routerTunnel.stop();await aiRouter.stop()});
handle('router:copy-key',()=>clipboard.writeText(aiRouter.key()));
handle('router:rotate-key',()=>aiRouter.rotateKey());
handle('router:use',async name=>{if(!aiRouter.state().availableModels.some(r=>r.id===name))throw Error('Choose a saved route.');await aiRouter.start();return workspace.saveAI({provider:'openai',baseURL:aiRouter.state().baseURL,model:name,key:aiRouter.key()})});
handle('router:tunnel-file',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{title:'Choose cloudflared executable',properties:['openFile']});if(!result.canceled)routerTunnel.setExecutable(result.filePaths[0]);return routerTunnel.state()});
handle('router:tunnel-save',input=>routerTunnel.save(input));
handle('router:tunnel-start',()=>routerTunnel.start());
handle('router:tunnel-stop',()=>routerTunnel.stop());
handle('models:state',()=>modelHub.state());
handle('models:install',id=>modelHub.install(id));
handle('models:remove',id=>modelHub.remove(id));
handle('models:unload',()=>modelHub.unload());
handle('models:cancel',()=>modelHub.cancel());
handle('models:generate',input=>modelHub.generate(input));
handle('models:import',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{properties:['openFile'],filters:[{name:'GGUF chat model',extensions:['gguf']}]});return result.canceled?null:modelHub.importGGUF(result.filePaths[0]);});
handle('production:state',()=>production.state());
handle('production:start',input=>production.start(input));
handle('production:stop',()=>production.stop());
handle('recorder:sources',async()=>{const sources=await desktopCapturer.getSources({types:['screen','window'],thumbnailSize:{width:480,height:270}});return sources.map(s=>({id:s.id,name:s.name,displayId:s.display_id,thumbnail:s.thumbnail.toDataURL()}))});
handle('recorder:arm',function(input){captureOwner=this.webContents;captureUntil=Date.now()+60000;captureSource=typeof input.source==='string'?input.source:'';captureSystemAudio=!!input.systemAudio;return true});
handle('recorder:begin',input=>production.beginRecording(input));
handle('recorder:append',(id,chunk,track)=>production.appendRecording(id,chunk,track));
handle('recorder:finish',id=>{captureUntil=0;const result=production.finishRecording(id);captureOwner=null;return result});
handle('recorder:abort',id=>{captureUntil=0;captureOwner=null;return production.abortRecording(id)});
handle('recorder:state',()=>({...recorderCapture.projects.state(),shortcut:desktopSettings.state().shortcuts.screenshot,recordingShortcut:desktopSettings.state().shortcuts.recording}));
handle('recorder:settings',input=>recorderCapture.projects.settings(input));
handle('recorder:project',id=>{localStudio.file(id);return recorderCapture.projects.get(id)});
handle('recorder:save-project',(id,input)=>{localStudio.file(id);return recorderCapture.projects.save(id,input)});
handle('recorder:screenshot',input=>recorderCapture.capture(input));
handle('recorder:area',function(id){return recorderCapture.selectArea(id)});
handle('recorder:rendered-image',input=>recorderCapture.rendered(input));
handle('recorder:export',input=>localStudio.recordingExport(input));
handle('recorder:pointer',function(displayId){if(this.webContents!==captureOwner||!production.state().recording)return null;const display=screen.getAllDisplays().find(d=>String(d.id)===displayId);if(!display)return null;const point=screen.getCursorScreenPoint(),b=display.bounds;return {x:(point.x-b.x)/b.width,y:(point.y-b.y)/b.height}});
handle('recorder:minimize',function(){this.minimize();return true});
handle('recorder:restore',function(){this.restore();this.show();return true});

handle('local:captions',input=>localStudio.captions(input));
handle('local:state',()=>localStudio.state());
handle('storage:state',()=>storageLocation.state());
handle('storage:choose',async()=>{const choice=await dialog.showOpenDialog(activeWindow(),{title:'Choose a shared download location',properties:['openDirectory','createDirectory']});return choice.canceled?storageLocation.state():storageLocation.choose(choice.filePaths[0])});
handle('storage:cancel',()=>storageLocation.cancel());
handle('storage:open',()=>shell.openPath(storageLocation.state().directory));
handle('storage:restart',()=>{const p=production?.state();if(downloads?.state().some(d=>d.status==='active')||localStudio?.state().active||modelHub?.state().active||modelHub?.state().benchmarking||dictation?.busy()||workAgent?.state().busy||pets?.state().busy||p?.recording||p?.starting||['connecting','sending','stopping'].includes(p?.live?.status)||workspace?.snapshot().jobs.some(j=>['creating','processing','publishing'].includes(j.status)))throw Error('Pause downloads and finish active work before moving storage.');if(app.isPackaged){app.relaunch();app.quit()}else{app.quit()}return {restartManually:!app.isPackaged}});
handle('local:acceleration',input=>localStudio.acceleration(input?.model,input?.repair===true));
handle('local:gpu',()=>localStudio.checkGPU());
handle('local:install',id=>localStudio.install(id));
handle('local:cancel',()=>localStudio.cancel());
handle('files:download',input=>fileDownloader.download(input));
handle('files:images',url=>fileDownloader.images(url));
handle('files:reveal',id=>shell.showItemInFolder(localStudio.file(id)));
handle('local:download',input=>localStudio.download(input));
handle('local:voice',input=>localStudio.voice(input));
handle('local:transcribe',id=>localStudio.transcribe(id));
handle('local:clip',input=>localStudio.clip(input));
handle('local:prepare',(id,accountId)=>workspace.prepareMedia(localStudio.file(id),accountId));
handle('local:import',async kind=>{if(!['audio','image','video'].includes(kind))throw Error('Choose a media type.');const audio=kind==='audio',image=kind==='image';const result=await dialog.showOpenDialog(activeWindow(),{properties:['openFile'],filters:[{name:audio?'Audio':image?'Image':'Video',extensions:audio?['wav','mp3','m4a','flac']:image?['png','jpg','jpeg']:['mp4','mov','webm','mkv']}]});return result.canceled?null:localStudio.import(result.filePaths[0],kind);});
handle('local:mesh',async id=>{if(!localStudio.state().assets.some(a=>a.id===id&&a.kind==='3d'))throw Error('Choose a generated 3D asset.');const source=localStudio.file(id),fs=require('node:fs/promises');if((await fs.stat(source)).size>40*1024*1024)throw Error('This mesh is too large to preview. Export it to a 3D editor.');return fs.readFile(source)});
handle('local:spatial',input=>{modelHub.unload();return localStudio.generateSpatial(input)});
handle('local:save',async id=>{const source=localStudio.file(id);const result=await dialog.showSaveDialog(activeWindow(),{defaultPath:path.join(storageLocation.state().directory,'downloads',path.basename(source))});if(!result.canceled){await require('node:fs/promises').copyFile(source,result.filePath);return true}return false;});
handle('local:highlights',input=>workspace.suggestClips(input));
handle('ai:models',input=>workspace.listModels(input));
handle('drive:connect',input=>workspace.connectDrive(input));
handle('drive:disconnect',()=>workspace.disconnectDrive());
handle('drive:files',()=>workspace.listDriveFiles());
handle('drive:upload',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{properties:['openFile']});if(result.canceled)return null;return workspace.uploadDriveFile(result.filePaths[0]);});
handle('seo:state',()=>seo.state());
handle('seo:import',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{title:'Choose Google Desktop OAuth credentials',properties:['openFile'],filters:[{name:'Google OAuth JSON',extensions:['json']}]});if(result.canceled)return null;const fs=require('node:fs'),file=result.filePaths[0];if(fs.statSync(file).size>32000)throw Error('Choose a Google OAuth client JSON file under 32 KB.');let value;try{value=JSON.parse(fs.readFileSync(file,'utf8'))}catch{throw Error('This is not valid JSON. Download the Desktop OAuth client file from Google Cloud.')}return seo.importCredentials(value)});
handle('seo:connect',()=>seo.connect());
handle('seo:cancel',()=>seo.cancel());
handle('seo:disconnect',()=>seo.disconnect());
handle('seo:discover',()=>seo.discover());
handle('seo:report',input=>seo.report(input));
handle('seo:analyze',input=>seo.analysis(input));
handle('seo:add-action',input=>seo.addAction(input));
handle('seo:task',input=>seo.task(input));
handle('seo:export',async()=>{const report=seo.state().report;if(!report)throw Error('Load a report first.');const result=await dialog.showSaveDialog(activeWindow(),{defaultPath:'orvio-seo-report.json',filters:[{name:'SEO report',extensions:['json']}]});if(result.canceled)return false;await require('node:fs/promises').writeFile(result.filePath,JSON.stringify({report,analysis:seo.state().analysis,insight:seo.state().insight,plan:seo.state().plan.filter(t=>t.property===report.property&&t.site===report.site)},null,2));return true});
handle('ai:chat',function(input){const sender=this.webContents;return workspace.chat({...input,onProgress:step=>{if(!sender.isDestroyed())sender.send('chat:progress',{...step,requestId:input.requestId})}})});
handle('composio:state',()=>composio.state());
handle('composio:configure',key=>composio.configure(key));
handle('composio:catalog',input=>composio.catalog(input));
handle('composio:connect',id=>composio.connect(id));
handle('composio:disconnect',id=>composio.disconnect(id));
handle('composio:approve',(id,allow)=>composio.approve(id,allow));
handle('composio:forget',()=>composio.forget());

handle('chat:capabilities',model=>require('./chat-files.cjs').capabilities(workspace.chatConfig(model)));
handle('chat:files',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{title:'Attach to conversation',properties:['openFile','multiSelections'],filters:[{name:'Images, text and code',extensions:require('./chat-files.cjs').extensions}]});if(result.canceled)return [];if(result.filePaths.length>4)throw Error('Choose up to four files.');const store=require('./chat-files.cjs').createChatFiles(app.getPath('userData'));return result.filePaths.map(file=>store.add(file))});
handle('chat:mic',function(enabled){chatMicOwner=enabled?this.webContents:null;chatMicUntil=enabled?Date.now()+65000:0;if(enabled)petWindow?.listen(false);else petWindow?.listen(true);return true});
handle('chat:transcribe',async({bytes,model,language})=>{chatMicUntil=0;petWindow?.listen(false);try{return await localStudio.petTranscribe(bytes,model,language||'auto')}finally{petWindow?.listen(true)}});
handle('chat:speak',async input=>{if(typeof input?.text!=='string'||!input.text.trim()||input.text.length>4000)throw Error('Speak up to 4,000 characters at a time.');if(!localStudio.state().models.some(m=>m.id===input.model&&m.engine==='piper'))throw Error('Choose an installed Piper voice.');petWindow?.listen(false);try{return await localStudio.petVoice(input)}finally{petWindow?.listen(true)}});

handle('meta:connect',input=>workspace.connect(input));
handle('meta:disconnect',id=>workspace.disconnect(id));
handle('jobs:schedule',input=>{const result=workspace.schedule(input);setImmediate(()=>workspace.tick().catch(()=>{}));return result;});
handle('jobs:bulk',inputs=>{const result=workspace.scheduleBulk(inputs);setImmediate(()=>workspace.tick().catch(()=>{}));return result;});
handle('social:connect',input=>workspace.connectSocial(input));
handle('social:caption',input=>workspace.generatePostCaption(input));
handle('social:creator',id=>workspace.refreshCreator(id));
handle('social:models',async()=>{const {supportsVision}=require('./social-caption.cjs');const config=workspace.chatConfig('');const models=config.provider==='local'?[]:await workspace.listModels(config);return models.map(id=>({id:'provider:'+id,name:id,vision:supportsVision({...config,model:id})}));});
handle('social:media',async()=>{const result=await dialog.showOpenDialog(activeWindow(),{title:'Add posts to your queue',properties:['openFile','multiSelections'],filters:[{name:'Images and videos',extensions:['jpg','jpeg','png','webp','mp4','mov','webm']}]});if(result.canceled)return [];if(result.filePaths.length>50)throw Error('Choose up to 50 files at once.');const media=[];for(const file of result.filePaths)media.push(await workspace.stageMedia(file));return media;});
handle('social:prepare',id=>workspace.stageMedia(localStudio.file(String(id).replace(/^local:/,''))));
handle('social:openPost',value=>{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||!['www.instagram.com','instagram.com','www.facebook.com','facebook.com','www.youtube.com','youtube.com','youtu.be','www.tiktok.com','tiktok.com'].includes(url.hostname))throw Error('Invalid social post link.');return shell.openExternal(url.href);});
handle('jobs:cancel',id=>workspace.cancel(id));
handle('jobs:edit',(id,input)=>workspace.editJob(id,input));
handle('social:refreshPost',id=>workspace.refreshPost(id));
handle('workspace:preferences',input=>{if(typeof input.startAtLogin==='boolean'){if(!app.isPackaged)throw new Error('Startup settings are available in the installed app.');app.setLoginItemSettings({openAtLogin:input.startAtLogin});}return workspace.preferences(input);});
handle('ai:save',input=>workspace.saveAI(input));
handle('ai:generate',prompt=>workspace.generate(prompt));
handle('creative:enhance',async input=>{const prompt=require('./creative-prompts.cjs').enhancementPrompt(input);return (await workspace.generate(prompt,true,input.chatModel)).slice(0,input.kind==='voice'?5000:2000)});
ipcMain.handle('updates:check',()=>updates.check());
ipcMain.handle('updates:state',()=>updates.getState());
handle('updates:install',()=>{const p=production?.state();if(dictation?.busy()||workAgent?.state().busy||pets?.state().busy||p?.recording||p?.starting||['connecting','sending','stopping'].includes(p?.live?.status)||localStudio?.state().active||downloads?.state().some(d=>d.status==='active'&&d.kind!=='update')||workspace?.snapshot().jobs.some(j=>['creating','processing','publishing'].includes(j.status)))throw Error('Finish or pause active work before restarting.');return updates.install()});
ipcMain.handle('updates:releases',()=>shell.openExternal(RELEASES_URL));
ipcMain.handle('app:version',()=>app.getVersion());
app.whenReady().then(async()=>{
 storageLocation=require('./storage-location.cjs').createStorageLocation(app.getPath('userData'));
 if(storageLocation.state().pending){
  movingWindow=new BrowserWindow({width:620,height:398,title:'Orvio Studio',icon:path.join(__dirname,'startup-assets/orvio-logo.png'),backgroundColor:'#111113',frame:false,resizable:false,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'storage-progress-preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false}});
  await movingWindow.loadFile(path.join(__dirname,'storage-progress.html'));movingWindow.show();movingWindow.focus();
  movingWindow.on('close',event=>{if(!quitting){event.preventDefault();movingWindow.minimize()}});
 }
 try{await storageLocation.apply(message=>{console.log('[storage]',message);if(movingWindow&&!movingWindow.isDestroyed()){const percent=message.match(/(\d+)%/),stage=message.startsWith('Verifying')?'Verifying your files':message.includes('model-hub')?'Moving your models':'Moving runtimes & creations';movingWindow.setProgressBar(percent?Number(percent[1])/100:2);void movingWindow.webContents.executeJavaScript(`(()=>{const message=${JSON.stringify(message)},percent=${percent?Number(percent[1]):'null'};document.getElementById("progress").textContent=message;document.getElementById("progress").title=message;document.getElementById("stage").textContent=${JSON.stringify(stage)};document.getElementById("amount").textContent=percent===null?'Please wait':percent+'%';document.getElementById("track").classList.toggle('waiting',percent===null);document.getElementById("fill").style.width=percent===null?'30%':percent+'%';if(percent!==null)document.getElementById("track").setAttribute('aria-valuenow',percent)})()`).catch(()=>{})}})}catch(error){movingWindow?.destroy();const answer=await dialog.showMessageBox({type:'error',title:'Storage location unavailable',message:error.message,detail:'Connect the storage drive and restart to retry. Original files are preserved until each folder is verified.',buttons:['Quit','Cancel pending change']});if(answer.response===1){try{storageLocation.cancel()}catch{}}app.quit();return}finally{if(movingWindow&&!movingWindow.isDestroyed())movingWindow.destroy();movingWindow=null}
 for(const name of ['package-cache','runtime-temp','downloads'])require('node:fs').mkdirSync(path.join(app.getPath('userData'),name),{recursive:true});
 process.env.PIP_CACHE_DIR=require('node:fs').realpathSync(path.join(app.getPath('userData'),'package-cache'));process.env.TMPDIR=process.env.TEMP=process.env.TMP=require('node:fs').realpathSync(path.join(app.getPath('userData'),'runtime-temp'));

 const resources=app.isPackaged?path.join(process.resourcesPath,'runtime'):path.join(__dirname,'../runtime');
 const python=path.join(app.isPackaged?process.resourcesPath:path.join(__dirname,'../.runtime-cache',`${process.platform}-${process.arch}`),'python',process.platform==='win32'?'python.exe':'bin/python3');
 pcHelper=require('./pc-helper.cjs').createPCHelper({directory:app.getPath('userData'),knownFolders:['desktop','documents','downloads'].map(name=>app.getPath(name)),trash:file=>shell.trashItem(file),open:url=>shell.openExternal(url),notify:state=>{broadcast('pc:changed',state)}});
 downloads=require('./downloads.cjs').createDownloads({directory:app.getPath('userData'),notify:state=>{const active=state.filter(d=>d.status==='active');if(active.length&&downloadBlocker===null)downloadBlocker=powerSaveBlocker.start('prevent-app-suspension');else if(!active.length&&downloadBlocker!==null){powerSaveBlocker.stop(downloadBlocker);downloadBlocker=null}if(active.length!==lastDownloadCount){lastDownloadCount=active.length;refreshTray()}tray?.setToolTip(active.length?`Orvio Studio · ${active.length} downloads in progress`:'Orvio Studio');if(!quitting&&pendingDevRestart&&!active.length){pendingDevRestart=false;setTimeout(()=>{if(downloads.state().some(d=>d.status==='active'))pendingDevRestart=true;else app.quit()},300)}refreshIsland();broadcast('downloads:changed',state)}});
 localStudio=require('./local-studio.cjs').createLocalStudio({directory:app.getPath('userData'),resources,python,downloads,notify:state=>{petWindow?.refresh();if(pets)broadcast('pets:changed',pets.state());broadcast('local:changed',state)}});
 modelHub=require('./model-hub.cjs').createModelHub({directory:app.getPath('userData'),python,localStudio,downloads,notify:state=>{petWindow?.refresh();if(pets)broadcast('pets:changed',pets.state());broadcast('models:changed',state)}});
 fileDownloader=require('./file-downloader.cjs').createFileDownloader({directory:app.getPath('userData'),downloads,register:(...args)=>localStudio.registerDownload(...args)});
 app.on('before-quit',()=>fileDownloader.shutdown());
 downloads.registerRetry('gpu-runtime',input=>downloads.queue.lock('gpu-recovery',()=>localStudio.acceleration(input.id,true)));
 downloads.registerRetry('model',({id})=>modelHub.state().models.some(m=>m.id===id)?modelHub.install(id):localStudio.install(id));downloads.registerRetry('video',input=>localStudio.download(input));
 require('./hardware.cjs').detectHardware(app).then(hardware=>modelHub.setHardware(hardware)).catch(()=>{});
 production=require('./production.cjs').createProduction({directory:app.getPath('userData'),localStudio,notify:state=>{const working=!!state.recording||state.starting||['connecting','sending','stopping'].includes(state.live?.status);if(working&&productionBlocker===null)productionBlocker=powerSaveBlocker.start('prevent-display-sleep');else if(!working&&productionBlocker!==null){powerSaveBlocker.stop(productionBlocker);productionBlocker=null}const status=String(state.recording?.id||'')+String(state.live?.status||'');if(status!==lastProductionStatus){lastProductionStatus=status;refreshTray();refreshIsland()}broadcast('production:changed',state)}});
 protocol.handle('orvio-media',async request=>{try{const url=new URL(request.url);if(!['asset','social'].includes(url.hostname))throw Error();const response=await net.fetch(require('node:url').pathToFileURL(url.hostname==='social'?workspace.socialFile(url.pathname.slice(1)):localStudio.file(url.pathname.slice(1))).href,{headers:request.headers});const headers=new Headers(response.headers);headers.set('Access-Control-Allow-Origin','*');return new Response(response.body,{status:response.status,headers})}catch{return new Response('Not found',{status:404})}});

 composio=require('./composio.cjs').createComposio({directory:app.getPath('userData'),safeStorage,openExternal:url=>shell.openExternal(url),notify:state=>broadcast('composio:changed',state)});
 workspace=createWorkspace({composio,modelHub,localStudio,seoSummary:()=>seo.summary(),directory:app.getPath('userData'),downloadsDirectory:path.join(app.getPath('userData'),'downloads'),safeStorage,openExternal:url=>shell.openExternal(url),notify:state=>{refreshTray();refreshIsland();broadcast('workspace:changed',state);}});
 tray=new Tray(nativeImage.createFromPath(path.join(__dirname,'../dist/orvio-logo.png')).resize({width:process.platform==='darwin'?22:32,height:process.platform==='darwin'?22:32}));
 void downloads.resumeInterrupted();
 tray.setToolTip('Orvio Studio • Free tools');tray.on('double-click',showWindow);refreshTray();
 nativeAuth=require('./native-auth.cjs').createNativeAuth({directory:app.getPath('userData'),safeStorage,openExternal:url=>shell.openExternal(oauthExternalURL(url)),onConnected:async input=>{const id=aiRouter.attachOAuth(input);void aiRouter.test(id).catch(()=>{});},notify:()=>broadcast('router:changed')});
 aiRouter=require('./ai-router.cjs').createAIRouter({directory:app.getPath('userData'),safeStorage,modelHub,nativeAuth,notify:()=>{broadcast('router:changed')}});
 routerTunnel=require('./router-tunnel.cjs').createRouterTunnel({directory:app.getPath('userData'),safeStorage,router:aiRouter,notify:()=>{broadcast('router:changed')}});
 if(aiRouter.state().autoStart)void aiRouter.start().catch(()=>{});
 workAgent=require('./work-agent.cjs').createWorkAgent({directory:app.getPath('userData'),modelHub,completeWork:(payload,signal)=>workspace.completeWork(payload,signal),browser:require('./work-browser.cjs').createWorkBrowser({BrowserWindow}),generateImage:input=>modelHub.generate(input),notify:state=>broadcast('work:changed',state)});
 pets=require('./pets.cjs').createPets({directory:app.getPath('userData'),modelHub,localStudio,notify:state=>{petWindow?.refresh();broadcast('pets:changed',state)}});
 petWindow=require('./pet-window.cjs').createPetWindow({app,BrowserWindow,screen,ipcMain,pets,open:page=>{showWindow();mainWindow.webContents.send('workspace:navigate',page)}});
 recorderCapture=require('./recorder-capture.cjs').createRecorderCapture({directory:app.getPath('userData'),desktopCapturer,screen,nativeImage,clipboard,localStudio,BrowserWindow,ipcMain,onCapture:(asset,edit)=>{broadcast('recorder:screenshot-ready',{asset,edit});if(edit){showWindow();activeWindow()?.webContents.send('workspace:navigate','Recorder')}},onError:message=>{showWindow();activeWindow()?.webContents.send('workspace:navigate','Recorder');broadcast('recorder:error',message)}});
 desktopSettings=require('./desktop-settings.cjs').createDesktopSettings({directory:app.getPath('userData'),globalShortcut,actions:{assistant:()=>{showWindow();mainWindow.webContents.send('workspace:navigate','Chat')},pet:()=>{if(pets.state().settings.enabled)petWindow.show();else{showWindow();mainWindow.webContents.send('workspace:navigate','Pets')}},dictation:()=>dictation.toggle().catch(()=>{}),screenshot:()=>recorderCapture.quick(),recording:()=>{if(production.state().recording)broadcast('recorder:stop');else{showWindow();activeWindow()?.webContents.send('workspace:navigate','Recorder')}}}});
 dictation=require('./dictation.cjs').createDictation({app,BrowserWindow,screen,ipcMain,clipboard,systemPreferences,localStudio,modelHub,settings:desktopSettings,pausePet:()=>petWindow.listen(false),resumePet:()=>{if(!quitting)petWindow.listen(true)}});
 seo=require('./seo.cjs').createSEO({directory:app.getPath('userData'),safeStorage,openExternal:url=>shell.openExternal(oauthExternalURL(url)),analyze:(prompt,structured)=>workspace.generate(prompt,structured),notify:state=>{broadcast('seo:changed',state)}});
 updateNotification=require('./update-notifications.cjs').createUpdateNotifications({directory:app.getPath('userData'),show:({title,body,onClick})=>{if(!Notification.isSupported())return false;const n=new Notification({title,body,icon:path.join(__dirname,'../dist/orvio-logo.png')});n.on('click',onClick);n.show();return true},open:()=>{showWindow();const openUpdates=()=>{if(mainWindow&&!mainWindow.isDestroyed()){mainWindow.webContents.send('workspace:navigate','Settings');mainWindow.webContents.send('update:open')}};if(mainWindow.webContents.isLoadingMainFrame())mainWindow.webContents.once('did-finish-load',openUpdates);else openUpdates()}});
 workspaceReady=true;if(pendingBot)openBot(pendingBot);else openWindow();petWindow.show();desktopSettings.register();
 const run=()=>workspace.tick().catch(()=>{});setInterval(run,30000).unref();setTimeout(run,3000).unref();powerMonitor.on('resume',run);
 if(app.isPackaged){setTimeout(()=>updates.check(),8000).unref();setInterval(()=>updates.check(),4*60*60*1000).unref();}
 app.on('activate',showWindow);
}).catch(async error=>{console.error('Orvio startup failed:',error);await dialog.showMessageBox({type:'error',title:'Orvio could not start',message:error.message,detail:'Your files have not been reset. Close Orvio and retry.'});app.quit()});
app.on('window-all-closed',()=>{});
