const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),net=require('node:net');
const {spawn}=require('node:child_process'),{randomUUID,createHash}=require('node:crypto'),{Readable,Transform}=require('node:stream'),{pipeline}=require('node:stream/promises');
const catalog=require('../runtime/models.json');
const {baseHardware,recommendation}=require('./hardware.cjs');
const engines={
 'darwin-arm64':['macos-arm64.tar.gz','1ad3f9eff80edb9dbef4259ad564d1720612ef7eea48fa4afed0e54f5f3d5711'],
 'darwin-x64':['macos-x64.tar.gz','305f0e3a17d2c01eb205cd0a62128357f1ec3b55329cb084d94e5ec0115d7a3b'],
 'win32-x64':['win-cpu-x64.zip','14cf1303ca9ac3abd94816850532f9f9a69ac66fbaca3776fc6f9061c2fac1d1']};
function createModelHub({directory,python,localStudio,downloads,hardware=baseHardware(),notify=()=>{},fetchImpl=fetch}){
 const root=path.join(directory,'model-hub');fs.mkdirSync(root,{recursive:true});const importsFile=path.join(root,'imports.json');let imports=[];try{imports=JSON.parse(fs.readFileSync(importsFile,'utf8'))}catch{}const context=new (require('node:async_hooks').AsyncLocalStorage)(),tasks=new Set(),installs=new Map(),queue=downloads?.queue||require('./download-queue.cjs').createDownloadQueue(3),current=()=>context.getStore();let server=null,loading=null,loadedId='',address='',apiKey='',idleTimer=null,inFlight=0;
 let benchmarking=null;let benchmarks={};const benchmarkFile=path.join(root,'benchmarks.json');try{benchmarks=JSON.parse(fs.readFileSync(benchmarkFile,'utf8'))}catch{}
 const all=()=>[...catalog,...localStudio.state().models.filter(m=>['piper','chatterbox'].includes(m.engine)).map(m=>({...m,kind:'voice',ramGB:m.engine==='piper'?2:8,description:m.engine==='piper'?'Natural local speech with a compact downloadable voice.':'Multilingual speech and reference voice cloning in 23 languages.',repo:m.engine==='piper'?'rhasspy/piper-voices':'ResembleAI/chatterbox'})),...imports];const modelPath=m=>m.importedPath||path.join(root,m.id,m.filename);
 const installed=m=>m.engine==='llama'?(m.files||[m.filename]).every(name=>fs.existsSync(m.importedPath||path.join(root,m.id,name))):!!localStudio.state().models.find(x=>x.id===m.id)?.installed;
 const state=()=>({hardware:{...hardware,freeGB:Number((os.freemem()/1024**3).toFixed(1))},benchmarks,benchmarking,active:[...tasks][0]?.progress||localStudio.state().active,loadedId,models:all().map(m=>({...m,importedPath:undefined,installed:installed(m),recommendation:recommendation(m,hardware),benchmark:benchmarks[m.id],fitsMemory:os.totalmem()/1024**3>=m.ramGB,url:'https://huggingface.co/'+m.repo}))});
 function report(info){const ctx=current();if(!ctx)return;const progress=typeof info==='string'?{message:info,total:null,received:0,speed:null,eta:null}:info;ctx.progress={...ctx.progress,...progress};if(ctx.transferId)downloads?.update(ctx.transferId,progress);notify(state())}
 async function task(name,fn){const ctx={abort:new AbortController(),transferId:null,progress:{name,message:'Queued · waiting for a download slot…'}};tasks.add(ctx);notify(state());return context.run(ctx,async()=>{try{return await fn()}finally{tasks.delete(ctx);notify(state())}})}
 async function download(url,dest,hash){fs.mkdirSync(path.dirname(dest),{recursive:true});const partial=dest+'.part';let initial=fs.existsSync(partial)?fs.statSync(partial).size:0;const response=await fetchImpl(url,{headers:initial?{Range:`bytes=${initial}-`}:{},signal:current()?.abort.signal});if(!response.ok)throw Error(`Model download failed (${response.status}). Please retry.`);if(response.status!==206)initial=0;let received=initial,total=response.headers.get('content-length')?initial+Number(response.headers.get('content-length')):null,last=0;const started=Date.now();report({message:'Downloading file…',file:path.basename(dest),stage:'file',received:initial,total,speed:null,eta:null});const progress=new Transform({transform(chunk,_encoding,callback){received+=chunk.length;if(Date.now()-last>500){last=Date.now();const speed=(received-initial)/Math.max(.001,(Date.now()-started)/1000);report({message:'Downloading file…',file:path.basename(dest),stage:'file',received,total,speed,eta:total&&speed?(total-received)/speed:null})}callback(null,chunk)}});await pipeline(Readable.fromWeb(response.body),progress,fs.createWriteStream(partial,{flags:initial?'a':'w',mode:0o600}));report({message:hash?'Checking download…':'File downloaded',file:path.basename(dest),received,total:total||received,speed:null,eta:null});if(hash){const digest=createHash('sha256');for await(const chunk of fs.createReadStream(partial))digest.update(chunk);if(digest.digest('hex')!==hash){fs.unlinkSync(partial);throw Error('Engine checksum did not match. Retry the download.')}}fs.renameSync(partial,dest)}
 function execute(file,args){return new Promise((resolve,reject)=>{const child=spawn(file,args,{windowsHide:true});let error='';child.stderr.on('data',d=>error=(error+d).slice(-1200));child.on('error',reject);child.on('close',code=>code===0?resolve():reject(Error(error||'Could not prepare local engine')));current()?.abort.signal.addEventListener('abort',()=>child.kill(),{once:true})})}
 function binary(folder){if(!fs.existsSync(folder))return null;for(const entry of fs.readdirSync(folder,{withFileTypes:true})){const file=path.join(folder,entry.name);if(entry.isFile()&&['llama-server','llama-server.exe'].includes(entry.name))return file;if(entry.isDirectory()){const found=binary(file);if(found)return found}}return null}
 async function engine(){return queue.lock('engine:llama',()=>engineFiles())}
 async function engineFiles(){const dest=path.join(root,'engine-b11146');let executable=binary(dest);if(executable&&fs.existsSync(path.join(dest,'.ready')))return executable;if(current().abort.signal.aborted)throw Error('Cancelled');const spec=engines[`${process.platform}-${process.arch}`];if(!spec)throw Error('Local chat is available on Windows x64 and macOS Intel/Apple Silicon.');if(!fs.existsSync(python))throw Error('Install the current Orvio app with bundled Python. Developers: run npm run runtime:prepare.');const archive=path.join(root,spec[0]);await download(`https://github.com/ggml-org/llama.cpp/releases/download/b11146/llama-b11146-bin-${spec[0]}`,archive,spec[1]);report('Preparing built-in chat engine…');fs.mkdirSync(dest,{recursive:true});await execute(python,['-c',"import sys,zipfile,tarfile; archive,dest=sys.argv[1:]; zipfile.ZipFile(archive).extractall(dest) if archive.endswith('.zip') else tarfile.open(archive).extractall(dest,filter='data')",archive,dest]);executable=binary(dest);if(!executable)throw Error('Chat engine executable was not found.');fs.writeFileSync(path.join(dest,'.ready'),'b11146');fs.unlinkSync(archive);return executable}
 async function install(id){if(installs.has(id))return installs.get(id);const job=installFiles(id).finally(()=>installs.delete(id));installs.set(id,job);return job}
 async function installFiles(id){const model=all().find(m=>m.id===id);if(!model)throw Error('Choose a model from the library.');if(model.engine!=='llama')return localStudio.install(id);return task('Download chat model',async()=>{current().transferId=downloads?.begin({title:model.name,kind:'model',modelId:id,cancel:((ctx)=>()=>ctx.abort.abort())(current())});report('Queued · waiting for a download slot…');try{await queue.run(async()=>{await engine();if(!installed(model)){for(const name of model.files||[model.filename]){if(!fs.existsSync(path.join(root,model.id,name)))await download(`https://huggingface.co/${model.repo}/resolve/main/${name}`,path.join(root,model.id,name),model.sha256);}}},current().abort.signal);downloads?.finish(current().transferId,'completed',{message:'Installed and ready'});return state()}catch(error){downloads?.finish(current().transferId,current()?.abort.signal.aborted?'cancelled':'failed',{message:current()?.abort.signal.aborted?'Download cancelled':error.message});throw error}finally{current().transferId=null}})}
 function unload(){if(inFlight)throw Error('Wait for the current chat response before unloading.');clearTimeout(idleTimer);if(server){server.kill();server=null}loadedId='';address='';apiKey='';notify(state())}
 async function load(id){if(loadedId===id&&server)return;if(loading){await loading;if(loadedId===id)return}loading=(async()=>{const model=all().find(m=>m.id===id&&m.engine==='llama');if(!model||!installed(model))throw Error('Download a chat model from Models first.');unload();const executable=(fs.existsSync(path.join(root,'engine-b11146/.ready'))&&binary(path.join(root,'engine-b11146')))||await task('Download chat engine',()=>queue.run(()=>engine(),current().abort.signal));const port=await new Promise((resolve,reject)=>{const socket=net.createServer();socket.on('error',reject);socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p))})});apiKey=randomUUID();address=`http://127.0.0.1:${port}`;let failure='';server=spawn(executable,['-m',modelPath(model),'--host','127.0.0.1','--port',String(port),'--api-key',apiKey,'--ctx-size','8192','--threads','2','--parallel','1','--jinja','--no-webui'],{windowsHide:true,cwd:path.dirname(executable)});const child=server;child.stdout.on('data',()=>{});child.stderr.on('data',d=>failure=(failure+d).slice(-1500));child.on('error',()=>{failure='The built-in chat engine could not start.'});child.on('close',()=>{if(server===child){server=null;loadedId='';notify(state())}});for(let i=0;i<180;i++){if(!server)throw Error('The model could not load. It may require more memory or a newer engine.');try{const r=await fetchImpl(address+'/health',{headers:{Authorization:'Bearer '+apiKey},signal:AbortSignal.timeout(1000)});if(r.ok){loadedId=id;notify(state());return}}catch{}await new Promise(r=>setTimeout(r,500))}unload();throw Error('The model took too long to load. Try a smaller model.')})();try{await loading}finally{loading=null}}
 const api={state,install,unload,setHardware(value){hardware=value;notify(state())},
 async benchmark(id){const model=all().find(m=>m.id===id);if(!model||!installed(model))throw Error('Download this model before benchmarking.');if(benchmarking||tasks.size||localStudio.state().active||inFlight)throw Error('Wait for the current task before benchmarking.');benchmarking=id;notify(state());try{const start=performance.now();let extra={};if(model.kind==='chat'){const response=await api.complete(id,{messages:[{role:'user',content:'Write a short paragraph about a peaceful garden.'}],max_tokens:64,temperature:0});if(!response.ok)throw Error('Chat benchmark failed. Try a smaller model.');const result=await response.json();extra={tokens:result.usage?.completion_tokens||null,tokensPerSecond:result.timings?.predicted_per_second||null};}else if(model.kind==='voice'){await localStudio.voice({model:id,text:'Welcome to Orvio Studio. This is a short local voice benchmark.',language:'en'});}else{await localStudio.generateModel({model:id,prompt:'A peaceful garden in soft morning light',seed:42});}const seconds=(performance.now()-start)/1000;benchmarks[id]={...extra,seconds:Number(seconds.toFixed(2)),at:new Date().toISOString(),kind:model.kind,includesLoading:true};fs.writeFileSync(benchmarkFile,JSON.stringify(benchmarks));notify(state());return benchmarks[id]}finally{benchmarking=null;notify(state())}},shutdown(){inFlight=0;unload();for(const ctx of tasks)ctx.abort.abort()},cancel(){const ctx=[...tasks][0];if(ctx)ctx.abort.abort();else localStudio.cancel()},
 async search(query){const q=String(query||'').trim().slice(0,100);if(q.length<2)throw Error('Enter at least two characters.');const response=await fetchImpl('https://huggingface.co/api/models?filter=gguf&sort=downloads&direction=-1&limit=16&search='+encodeURIComponent(q),{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Model search is unavailable. Try again later.');const list=await response.json();return list.map(m=>({repo:m.id,downloads:m.downloads||0,likes:m.likes||0}))},
 async remoteFiles(repo){if(!/^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/.test(repo))throw Error('Choose a Hugging Face model repository.');const response=await fetchImpl('https://huggingface.co/api/models/'+repo+'?blobs=true',{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('This repository is unavailable or requires an account. Choose a public model.');const info=await response.json();return {repo,license:info.cardData?.license||'Check model license',files:(info.siblings||[]).filter(f=>/^[^/\\]+\.gguf$/i.test(f.rfilename)&&!/-\d{5}-of-\d{5}\.gguf$/.test(f.rfilename)).map(f=>({name:f.rfilename,bytes:f.size||f.lfs?.size||null,sha256:f.lfs?.sha256||null}))}},
 async installRemote(input){const result=await api.remoteFiles(String(input.repo));const file=result.files.find(f=>f.name===input.filename);if(!file)throw Error('Choose an available single-file GGUF model.');const id='hub-'+createHash('sha256').update(result.repo+'/'+file.name).digest('hex').slice(0,20);if(!imports.some(m=>m.id===id)){imports.push({id,name:file.name.replace(/\.gguf$/i,''),kind:'chat',engine:'llama',size:file.bytes?(file.bytes/1024**3).toFixed(1)+' GB':'Size unknown',ramGB:file.bytes?Math.ceil(file.bytes/1024**3*1.5+2):16,description:'Community GGUF. Compatibility depends on its architecture and template; benchmark after downloading.',filename:file.name,sha256:file.sha256,repo:result.repo,license:result.license});fs.writeFileSync(importsFile,JSON.stringify(imports));notify(state())}return install(id)},
 async importGGUF(file){const fd=fs.openSync(file,'r'),magic=Buffer.alloc(4);try{fs.readSync(fd,magic,0,4,0)}finally{fs.closeSync(fd)}if(magic.toString()!=='GGUF')throw Error('Choose a valid GGUF chat model.');const id='import-'+randomUUID(),dest=path.join(root,id,path.basename(file));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(file,dest);imports.push({id,name:path.basename(file),kind:'chat',engine:'llama',size:(fs.statSync(file).size/1024**3).toFixed(1)+' GB',ramGB:Math.ceil(fs.statSync(file).size/1024**3*1.5+2),description:'Imported GGUF. Architecture and chat template support depend on the built-in llama.cpp engine.',filename:path.basename(file),importedPath:dest,repo:'ggml-org',license:'Check the original model license'});fs.writeFileSync(importsFile,JSON.stringify(imports));notify(state());return state()},
 async remove(id){if(tasks.size||localStudio.state().active)throw Error('Wait for the active model operation.');const model=all().find(m=>m.id===id);if(!model||model.engine!=='llama')throw Error('Only chat models can be removed here.');if(loadedId===id)unload();fs.rmSync(path.join(root,id),{recursive:true,force:true});imports=imports.filter(m=>m.id!==id);fs.writeFileSync(importsFile,JSON.stringify(imports));notify(state());return state()},
 async complete(id,payload){await load(id);inFlight++;clearTimeout(idleTimer);try{const response=await fetchImpl(address+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+apiKey},body:JSON.stringify({...payload,model:id,stream:false,max_tokens:Math.min(Number(payload.max_tokens)||1024,2048)}),signal:AbortSignal.timeout(300000)});return new Response(await response.text(),{status:response.status,headers:response.headers})}finally{inFlight--;idleTimer=setTimeout(()=>{if(!inFlight)unload()},120000);idleTimer.unref()}},
 generate:input=>localStudio.generateModel(input)
 };return api;
}
module.exports={createModelHub};
