const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const configs={
 openrouter:{authorize:'https://openrouter.ai/auth',token:'https://openrouter.ai/api/v1/auth/keys',baseURL:'https://openrouter.ai/api/v1'},
 gemini:{authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scope:'https://www.googleapis.com/auth/cloud-platform',baseURL:'https://generativelanguage.googleapis.com/v1beta/openai'},
 antigravity:{authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scope:'https://www.googleapis.com/auth/cloud-platform',baseURL:'https://daily-cloudcode-pa.googleapis.com'},
};
function createNativeAuth({directory,safeStorage,openExternal,fetchImpl=fetch,onConnected,notify=()=>{}}){
 const file=path.join(directory,'router-oauth.json');let saved={};try{saved=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}let pending=null;const refreshing=new Map();
 const seal=data=>{if(!safeStorage.isEncryptionAvailable())throw Error('OS credential encryption is unavailable.');return safeStorage.encryptString(JSON.stringify(data)).toString('base64')};
 const read=id=>{if(!saved[id])throw Error('Sign in again to reconnect this account.');return JSON.parse(safeStorage.decryptString(Buffer.from(saved[id],'base64')))};
 const write=(id,data)=>{saved[id]=seal(data);fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(saved),{mode:0o600});fs.renameSync(file+'.tmp',file)};
 async function exchange(provider,fields){const special=provider==='openrouter';const r=await fetchImpl(configs[provider].token,{method:'POST',redirect:'error',headers:{'Content-Type':special?'application/json':'application/x-www-form-urlencoded'},body:special?JSON.stringify(fields):new URLSearchParams(fields).toString(),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`Provider authorization failed (HTTP ${r.status}). Please sign in again.`);const body=await r.json();if(!(body.access_token||body.key))throw Error('Provider returned no access token.');return body}
 const state=()=>pending?{providerId:pending.providerId,status:'Waiting for browser sign-in'}:null;
 function cancel(){pending?.finish(Error('Sign-in cancelled.'))}
 async function login(input){if(pending)throw Error('Finish or cancel the current sign-in first.');const config=configs[input.providerId];if(!config)throw Error('Native sign-in is not implemented for this provider.');if(input.providerId!=='openrouter'&&!String(input.clientId||'').trim())throw Error('Enter your Orvio desktop OAuth client ID.');if(String(input.clientId||'').length>500||String(input.clientSecret||'').length>4000)throw Error('OAuth client details are too long.');if(input.providerId==='antigravity'&&!/^[a-zA-Z0-9:_-]{1,120}$/.test(input.project||''))throw Error('Enter the Google project ID authorized for this service.');seal({});
  const verifier=crypto.randomBytes(32).toString('base64url'),nonce=crypto.randomBytes(24).toString('hex'),callbackPath='/oauth/callback/'+nonce;let server,timer,done=false;
  const completion=new Promise((resolve,reject)=>{
   const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);server?.close();server?.closeIdleConnections();pending=null;notify();error?reject(error):resolve(value)};
   pending={providerId:input.providerId,finish};
   server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(req.method!=='GET'||url.pathname!==callbackPath){res.writeHead(404);res.end();return}if(input.providerId!=='openrouter'&&url.searchParams.get('state')!==nonce){res.writeHead(400);res.end('Invalid sign-in state.');return}if(done){res.writeHead(410);res.end();return}
    if(url.searchParams.has('error')){res.end('Sign-in declined. Return to Orvio.');finish(Error('Provider sign-in was declined.'));return}
    const code=url.searchParams.get('code');if(!code||code.length>4096){res.writeHead(400);res.end('Missing authorization code.');return}if(pending.exchanging){res.writeHead(409);res.end();return}pending.exchanging=true;
    try{const fields=input.providerId==='openrouter'?{code,code_verifier:verifier,code_challenge_method:'S256'}:{grant_type:'authorization_code',code,client_id:input.clientId,...(input.clientSecret?{client_secret:input.clientSecret}:{}),redirect_uri:pending.redirect,code_verifier:verifier};const tokens=await exchange(input.providerId,fields);if(done){res.end('Sign-in cancelled.');return}const id=crypto.randomUUID();write(id,{providerId:input.providerId,clientId:input.clientId,clientSecret:input.clientSecret||'',project:input.project||'',accessToken:tokens.access_token||tokens.key,refreshToken:tokens.refresh_token||'',expiresAt:tokens.expires_in?Date.now()+Number(tokens.expires_in)*1000:0});try{await onConnected({authId:id,providerId:input.providerId,name:input.name||input.providerId,baseURL:config.baseURL,project:input.project||''})}catch(error){delete saved[id];fs.writeFileSync(file,JSON.stringify(saved));throw error}res.setHeader('Content-Type','text/plain');res.end('Sign-in saved. Return to Orvio to check whether this account can access models.');finish(null,{connected:true});}catch(error){res.writeHead(400);res.end('Sign-in failed. Return to Orvio for details.');finish(error)}
   });server.on('error',()=>finish(Error('Could not open the local sign-in callback.')));server.listen(0,'127.0.0.1',()=>{if(done)return;const redirect=`http://127.0.0.1:${server.address().port}${callbackPath}`;pending.redirect=redirect;const url=new URL(config.authorize);url.searchParams.set(input.providerId==='openrouter'?'callback_url':'redirect_uri',redirect);url.searchParams.set('code_challenge',crypto.createHash('sha256').update(verifier).digest('base64url'));url.searchParams.set('code_challenge_method','S256');if(input.providerId!=='openrouter'){url.searchParams.set('response_type','code');url.searchParams.set('client_id',input.clientId);url.searchParams.set('scope',config.scope);url.searchParams.set('state',nonce);url.searchParams.set('access_type','offline');url.searchParams.set('prompt','consent')}Promise.resolve().then(()=>{if(!done)return openExternal(url.href)}).catch(()=>finish(Error('Could not open the sign-in browser.')));notify()});timer=setTimeout(()=>finish(Error('Sign-in timed out. Please try again.')),300000);timer.unref();
  });return completion;
 }
 async function token(id){const current=read(id);if(!current.expiresAt||current.expiresAt>Date.now()+60000)return current.accessToken;if(refreshing.has(id))return refreshing.get(id);const job=(async()=>{if(!current.refreshToken)throw Error('Session expired. Sign in again.');const result=await exchange(current.providerId,{grant_type:'refresh_token',refresh_token:current.refreshToken,client_id:current.clientId,...(current.clientSecret?{client_secret:current.clientSecret}:{})});if(!saved[id])throw Error('Account disconnected.');write(id,{...current,accessToken:result.access_token,refreshToken:result.refresh_token||current.refreshToken,expiresAt:Date.now()+(Number(result.expires_in)||3600)*1000});return result.access_token})();refreshing.set(id,job);try{return await job}finally{refreshing.delete(id)}}
 function remove(id){delete saved[id];fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(file,JSON.stringify(saved))}
 return {login,cancel,state,token,remove};
}
module.exports={createNativeAuth};
