const fs=require('node:fs'),fsp=fs.promises,path=require('node:path'),os=require('node:os'),{randomUUID,createHash}=require('node:crypto'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const execute=promisify(execFile);
const ignored=new Set(['node_modules','.git','.Trash','$RECYCLE.BIN','Windows','System Volume Information']);
async function walk(roots,visit,{signal,limit=50000,depth=10,followFileLinks=false}={}){
 let count=0,truncated=false;const seen=new Set();
 async function folder(dir,level){if(signal?.aborted)throw Error('Scan cancelled');if(level>depth||count>=limit){truncated=true;return}let canonical;try{canonical=await fsp.realpath(dir)}catch{return}if(seen.has(canonical))return;seen.add(canonical);let entries;try{entries=await fsp.readdir(dir,{withFileTypes:true})}catch{return}for(const entry of entries){if(signal?.aborted)throw Error('Scan cancelled');if(count>=limit){truncated=true;break}if(ignored.has(entry.name))continue;const file=path.join(dir,entry.name);if(entry.isSymbolicLink()){if(followFileLinks){try{const stat=await fsp.stat(file);if(stat.isFile()){count++;await visit(file,stat,count)}}catch{}}continue;}if(entry.isDirectory()){await folder(file,level+1)}else if(entry.isFile()){count++;try{const stat=await fsp.lstat(file);await visit(file,stat,count)}catch(error){if(signal?.aborted)throw error}}}}
 for(const root of roots)await folder(root,0);return {count,truncated};
}
function createPCHelper({directory,trash,open,notify=()=>{}}){
 const home=os.homedir();let scanning=false,controller=null,items=[],apps=[],foundModels=[],message='',scanned=0;const allowed=new Map(),models=new Map();
 const state=()=>({scanning,message,scanned,items,apps,models:foundModels});
 const report=text=>{message=text;notify(state())};
 function add(file,stat,kind,extra={}){const id=randomUUID();allowed.set(id,{file,size:stat.size,mtimeMs:stat.mtimeMs,ino:stat.ino,...extra});const item={id,path:file,name:path.basename(file),size:stat.size,modified:stat.mtime.toISOString(),kind,...extra};items.push(item);return item}
 async function scan({duplicates=false,minMB=100,folder}={}){if(scanning)throw Error('A scan is already running.');scanning=true;controller=new AbortController();items=[];allowed.clear();scanned=0;report('Scanning files…');try{const roots=folder?[folder]:['Downloads','Documents','Desktop','Movies','Videos'].map(name=>path.join(home,name));const candidates=[];const result=await walk(roots,async(file,stat,count)=>{scanned=count;if(stat.size>=Math.max(1,Number(minMB)||100)*1024**2)add(file,stat,'large');if(duplicates&&stat.size>=1024**2&&stat.size<20*1024**3)candidates.push({file,stat});if(count%500===0)report(`Checked ${count.toLocaleString()} files…`)},{signal:controller.signal});if(duplicates){const groups=new Map();for(const item of candidates){const list=groups.get(item.stat.size)||[];list.push(item);groups.set(item.stat.size,list)}let checked=0;for(const group of groups.values()){if(group.length<2)continue;const hashes=new Map();for(const entry of group){if(controller.signal.aborted)throw Error('Scan cancelled');report(`Comparing duplicate contents · ${++checked} files…`);const hash=createHash('sha256');for await(const chunk of fs.createReadStream(entry.file)){if(controller.signal.aborted)throw Error('Scan cancelled');hash.update(chunk)}const digest=hash.digest('hex'),list=hashes.get(digest)||[];list.push(entry);hashes.set(digest,list)}for(const [digest,entries] of hashes)if(entries.length>1){for(const entry of entries){const existing=items.find(i=>i.path===entry.file);if(existing){existing.kind='duplicate';existing.group=digest}else add(entry.file,entry.stat,'duplicate',{group:digest})}}}}
 const tempRoot=os.tmpdir();if(!folder)await walk([tempRoot],async(file,stat)=>{if(Date.now()-stat.mtimeMs>7*86400000&&stat.size>1024**2&&!file.startsWith(directory+path.sep))add(file,stat,'old-temp')},{signal:controller.signal,limit:5000,depth:3});items.sort((a,b)=>b.size-a.size);report(`${result.count.toLocaleString()} files checked. ${items.length} review candidates.${result.truncated?' Scan limit reached; select a smaller folder for a complete scan.':''}`);return state()}finally{scanning=false;notify(state())}}
 async function remove(ids){if(scanning)throw Error('Wait for the scan to finish.');if(!Array.isArray(ids)||!ids.length||ids.length>500)throw Error('Select up to 500 files to move to Trash.');const result=[];for(const id of ids){const entry=allowed.get(id);if(!entry)throw Error('Scan again before removing this file.');const stat=await fsp.lstat(entry.file);if(stat.isSymbolicLink()||stat.size!==entry.size||stat.mtimeMs!==entry.mtimeMs||stat.ino!==entry.ino)throw Error('A selected file changed since the scan. Scan again before removing it.');await trash(entry.file);allowed.delete(id);items=items.filter(i=>i.id!==id);result.push(id)}report(`Moved ${result.length} items to Trash.`);return state()}
 async function listApps(){apps=[];if(process.platform==='darwin'){for(const root of ['/Applications',path.join(home,'Applications')]){let names=[];try{names=await fsp.readdir(root)}catch{}for(const name of names.filter(n=>n.endsWith('.app'))){const file=path.join(root,name);try{const stat=await fsp.lstat(file);if(stat.isSymbolicLink())continue;const id=randomUUID();allowed.set(id,{file,size:stat.size,mtimeMs:stat.mtimeMs,ino:stat.ino,app:true});apps.push({id,name:name.slice(0,-4),path:file})}catch{}}}}else if(process.platform==='win32'){const script="$roots=@('HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*','HKLM:\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*','HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*'); Get-ItemProperty $roots -ErrorAction SilentlyContinue | Where-Object {$_.DisplayName} | Select-Object DisplayName,InstallLocation,PSChildName | ConvertTo-Json -Compress";const {stdout}=await execute('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,maxBuffer:4*1024**2});const rows=JSON.parse(stdout||'[]');for(const row of Array.isArray(rows)?rows:[rows])apps.push({id:randomUUID(),name:row.DisplayName,path:row.InstallLocation||'',productId:/^\{[0-9A-F-]{36}\}$/i.test(row.PSChildName)?row.PSChildName:null})}notify(state());return state()}
 async function appFiles(id){const app=apps.find(a=>a.id===id);if(!app)throw Error('Refresh the applications list.');if(process.platform==='win32'){items=[];const names=[app.name,app.name.replace(/\s+\d.*$/,'')];const roots=[process.env.APPDATA,process.env.LOCALAPPDATA].filter(Boolean);const candidates=[...new Set(roots.flatMap(root=>names.filter(name=>name&&!/[\\/:]/.test(name)).map(name=>path.join(root,name))))];for(const file of candidates){try{const stat=await fsp.lstat(file);if(!stat.isSymbolicLink())add(file,stat,'app-data')}catch{}}notify(state());return {app,items,native:false}}if(process.platform!=='darwin')return {app,items:[],native:true};items=[];const entry=allowed.get(id);if(!entry)throw Error('Refresh the applications list.');let bundle='';try{bundle=(await execute('/usr/bin/plutil',['-extract','CFBundleIdentifier','raw','-o','-',path.join(app.path,'Contents/Info.plist')])).stdout.trim()}catch{}const appStat=await fsp.lstat(app.path);const main=add(app.path,appStat,'application',{app:true});const candidates=[path.join(home,'Library/Application Support',app.name),path.join(home,'Library/Caches',bundle),path.join(home,'Library/Preferences',bundle+'.plist'),path.join(home,'Library/Saved Application State',bundle+'.savedState'),path.join(home,'Library/Logs',app.name)];if(!/^[a-zA-Z0-9.-]+$/.test(bundle))candidates.splice(1,3);for(const file of candidates){try{const stat=await fsp.lstat(file);if(!stat.isSymbolicLink())add(file,stat,'app-data')}catch{}}notify(state());return {app,items,mainId:main.id,native:false}}
 return {state,scan,remove,listApps,appFiles,cancel(){controller?.abort()},async openNativeUninstaller(id){const app=apps.find(a=>a.id===id);if(!app||process.platform!=='win32')throw Error('Select a Windows app.');if(app.productId){await new Promise((resolve,reject)=>{const child=require('node:child_process').spawn('msiexec.exe',['/x',app.productId],{detached:true,stdio:'ignore'});child.once('error',reject);child.once('spawn',()=>{child.unref();resolve()})})}else await open('ms-settings:appsfeatures')},
 async scanModels(folder){if(scanning)throw Error('Wait for the current scan.');scanning=true;scanned=0;controller=new AbortController();foundModels=[];models.clear();report('Looking for downloaded models…');try{const roots=folder?[folder]:['Downloads','Documents','Desktop','.cache/huggingface','.ollama/models','.lmstudio/models','Library/Caches/huggingface'].map(name=>path.join(home,name));const seen=new Set();const result=await walk(roots,async(file,stat,count)=>{scanned=count;const name=path.basename(file);const voice=require('./local-studio.cjs').catalog.find(m=>m.engine==='piper'&&name===m.id+'.onnx');const image=name==='model_index.json'?(file.includes('models--stabilityai--sd-turbo')?'sd-turbo':file.includes('models--stable-diffusion-v1-5--stable-diffusion-v1-5')?'sd15':null):null;if((voice&&fs.existsSync(file+'.json'))||image){const source=path.dirname(file),key=(voice?.id||image)+':'+source;if(!seen.has(key)){seen.add(key);const id=randomUUID(),kind=voice?'voice':'image';models.set(id,{file:source,kind,modelId:voice?.id||image});foundModels.push({id,name:voice?.name||image,path:source,size:stat.size,kind})}return}if(!(/\.gguf$/i.test(file)||/[/\\]blobs[/\\](?:sha256-)?[a-f0-9]{64}$/.test(file))||stat.size<1024)return;const handle=await fsp.open(file,'r');const magic=Buffer.alloc(4);try{await handle.read(magic,0,4,0)}finally{await handle.close()}if(magic.toString()!=='GGUF')return;const real=await fsp.realpath(file);if(seen.has(real))return;seen.add(real);const id=randomUUID();models.set(id,{file:real,kind:'chat'});foundModels.push({id,name:path.basename(file),path:real,size:stat.size,kind:'chat'});if(count%100===0)report(`Found ${foundModels.length} GGUF models…`)},{signal:controller.signal,limit:60000,depth:12,followFileLinks:true});report(`Found ${foundModels.length} existing GGUF models.${result.truncated?' Select a specific folder to scan further.':''}`);return state()}finally{scanning=false;notify(state())}},modelFile(id){const file=models.get(id);if(!file)throw Error('Scan for this model again.');return file.file},modelInfo(id){const model=models.get(id);if(!model)throw Error('Scan for this model again.');return model}};
}
module.exports={createPCHelper,walk};
