const fs=require('node:fs'),path=require('node:path');
const defaults={enabled:false,live:true,animal:'cat',name:'Orvio',wakePhrase:'Hello Orvio',model:'qwen-small',voice:'en_US-amy-medium',language:'en',speak:true,corner:'right'};
const normalize=text=>String(text).normalize('NFKC').toLocaleLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
function wakeCommand(text,phrase){const wake=normalize(phrase).split(' ');const heard=normalize(text);const words=(wake.includes('orvio')?heard.replace(/\bor (?:vio|vo|view|v o)\b/g,'orvio'):heard).split(' ');if(!wake[0])return null;for(let i=0;i<=words.length-wake.length;i++)if(wake.every((w,j)=>w===words[i+j]))return words.slice(i+wake.length).join(' ');return null}
function createPets({directory,modelHub,localStudio,notify=()=>{}}){
 const settingsFile=path.join(directory,'pet-settings.json'),historyFile=path.join(directory,'pet-history.json');let settings={...defaults},history=[],busy=false;
 try{settings={...defaults,...JSON.parse(fs.readFileSync(settingsFile,'utf8'))}}catch{}try{history=JSON.parse(fs.readFileSync(historyFile,'utf8')).filter(m=>['user','assistant'].includes(m.role)&&typeof m.content==='string').slice(-24)}catch{}
 const state=()=>({settings:{...settings},messages:history.map(m=>({...m})),busy,models:modelHub.state().models.filter(m=>m.kind==='chat').map(({id,name,installed})=>({id,name,installed})),voices:localStudio.state().models.filter(m=>['piper','chatterbox'].includes(m.engine)).map(({id,name,installed,unsupported})=>({id,name,installed,unsupported})),transcriptionReady:!!localStudio.state().models.find(m=>m.id==='whisper')?.installed});
 const emit=()=>notify(state());const persist=()=>fs.writeFileSync(historyFile,JSON.stringify(history),{mode:0o600});
 function save(input){if(busy)throw Error('Wait for your pet to finish before changing its setup.');const next={...settings};for(const key of ['enabled','speak','live'])if(typeof input?.[key]==='boolean')next[key]=input[key];if(input?.animal!==undefined){if(!['cat','dog','fox'].includes(input.animal))throw Error('Choose a pet.');next.animal=input.animal}if(input?.corner!==undefined){if(!['left','right'].includes(input.corner))throw Error('Choose a screen corner.');next.corner=input.corner}for(const key of ['name','wakePhrase'])if(input?.[key]!==undefined){const value=String(input[key]).trim();if(!value||value.length>40||!normalize(value))throw Error('Use a name and wake phrase between 1 and 40 characters.');next[key]=value}if(input?.language!==undefined){if(!/^[a-z]{2}$/.test(input.language))throw Error('Use a two-letter speech language.');next.language=input.language}if(input?.model!==undefined){if(!state().models.some(m=>m.id===input.model))throw Error('Choose a chat model from Models.');next.model=input.model}if(input?.voice!==undefined){if(!state().voices.some(m=>m.id===input.voice&&!m.unsupported))throw Error('Choose a supported voice.');next.voice=input.voice}settings=next;fs.writeFileSync(settingsFile,JSON.stringify(settings),{mode:0o600});emit();return state()}
 async function chat(text){if(busy)throw Error('Your pet is still thinking.');if(typeof text!=='string'||!text.trim()||text.length>2000)throw Error('Enter a message of up to 2,000 characters.');if(!state().models.find(m=>m.id===settings.model)?.installed)throw Error('Download your pet’s chat model in Pets or Models first.');busy=true;emit();try{const recent=history.slice(-12);while(recent.reduce((n,m)=>n+m.content.length,0)>14000)recent.shift();const messages=[...recent,{role:'user',content:text.trim()}];const response=await modelHub.complete(settings.model,{messages:[{role:'system',content:`You are ${settings.name}, a friendly ${settings.animal} desktop companion inside Orvio Studio. Reply naturally in the user's language, in up to 3 short sentences. You are an AI, not a human. You can chat and help think through ideas. You cannot perform app actions in this pet conversation; offer to use Orvio Assistant for tools. Never claim to have changed files or published anything.`},...messages],max_tokens:256,temperature:0.7});if(!response.ok)throw Error('The local model could not answer. Try a smaller model.');const result=await response.json();const answer=result.choices?.[0]?.message?.content;if(typeof answer!=='string'||!answer.trim())throw Error('The model returned an empty reply. Try again.');history=[...messages,{role:'assistant',content:answer.slice(0,4000)}].slice(-24);persist();return {text:answer.slice(0,4000)}}finally{busy=false;emit()}}
 return {state,save,chat,clear(){if(busy)throw Error('Wait for the reply before clearing this chat.');history=[];persist();emit();return state()},async speech(text){if(!settings.speak)return null;if(typeof text!=='string'||text.length>4000)throw Error('Invalid speech text');return localStudio.petVoice({model:settings.voice,text,language:settings.language})},transcribe:bytes=>localStudio.petTranscribe(bytes)};
}
module.exports={createPets,wakeCommand,defaults};
