const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('studio',Object.freeze({
 platform:process.platform,
 petState:()=>ipcRenderer.invoke('pets:state'),savePet:input=>ipcRenderer.invoke('pets:save',input),showPet:()=>ipcRenderer.invoke('pets:show'),onPets:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('pets:changed',listener);return()=>ipcRenderer.removeListener('pets:changed',listener)},
 onNavigate:callback=>{const listener=(_event,page)=>callback(page);ipcRenderer.on('workspace:navigate',listener);return()=>ipcRenderer.removeListener('workspace:navigate',listener)},
 onOpenDownloads:callback=>{ipcRenderer.on('downloads:open',callback);return()=>ipcRenderer.removeListener('downloads:open',callback)},
 pcState:()=>ipcRenderer.invoke('pc:state'),
 scanPC:input=>ipcRenderer.invoke('pc:scan',input),
 scanPCFolder:input=>ipcRenderer.invoke('pc:folder',input),
 cancelPCScan:()=>ipcRenderer.invoke('pc:cancel'),
 trashPCFiles:ids=>ipcRenderer.invoke('pc:trash',ids),
 installedApps:()=>ipcRenderer.invoke('pc:apps'),
 appLeftovers:id=>ipcRenderer.invoke('pc:app-files',id),
 uninstallApp:id=>ipcRenderer.invoke('pc:uninstall',id),
 scanExistingModels:choose=>ipcRenderer.invoke('pc:models',choose),
 useExistingModel:id=>ipcRenderer.invoke('pc:use-model',id),
 onPC:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('pc:changed',listener);return()=>ipcRenderer.removeListener('pc:changed',listener)},
 retryDownload:id=>ipcRenderer.invoke('downloads:retry',id),
 pauseDownload:id=>ipcRenderer.invoke('downloads:pause',id),
 downloads:()=>ipcRenderer.invoke('downloads:state'),
 cancelDownload:id=>ipcRenderer.invoke('downloads:cancel',id),
 clearDownloads:()=>ipcRenderer.invoke('downloads:clear'),
 onDownloads:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('downloads:changed',listener);return()=>ipcRenderer.removeListener('downloads:changed',listener)},
 localSession:clear=>ipcRenderer.invoke('local:session',clear),
 onStopRecording:callback=>{ipcRenderer.on('recorder:stop',callback);return()=>ipcRenderer.removeListener('recorder:stop',callback)},
 searchOnlineModels:query=>ipcRenderer.invoke('models:search',query),
 onlineModelFiles:repo=>ipcRenderer.invoke('models:files',repo),
 installOnlineModel:input=>ipcRenderer.invoke('models:remote',input),
 benchmarkModel:id=>ipcRenderer.invoke('models:benchmark',id),
 refreshHardware:()=>ipcRenderer.invoke('models:hardware'),
 modelHub:()=>ipcRenderer.invoke('models:state'),
 installModel:id=>ipcRenderer.invoke('models:install',id),
 removeModel:id=>ipcRenderer.invoke('models:remove',id),
 unloadModel:()=>ipcRenderer.invoke('models:unload'),
 cancelModel:()=>ipcRenderer.invoke('models:cancel'),
 generateLocal:input=>ipcRenderer.invoke('models:generate',input),
 importModel:()=>ipcRenderer.invoke('models:import'),
 onModels:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('models:changed',listener);return()=>ipcRenderer.removeListener('models:changed',listener)},
 productionState:()=>ipcRenderer.invoke('production:state'),
 startBroadcast:input=>ipcRenderer.invoke('production:start',input),
 stopBroadcast:()=>ipcRenderer.invoke('production:stop'),
 captureSources:()=>ipcRenderer.invoke('recorder:sources'),
 armCapture:input=>ipcRenderer.invoke('recorder:arm',input),
 beginRecording:()=>ipcRenderer.invoke('recorder:begin'),
 appendRecording:(id,chunk)=>ipcRenderer.invoke('recorder:append',id,chunk),
 finishRecording:id=>ipcRenderer.invoke('recorder:finish',id),
 abortRecording:id=>ipcRenderer.invoke('recorder:abort',id),
 renderCaptions:input=>ipcRenderer.invoke('local:captions',input),
 onProduction:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('production:changed',listener);return()=>ipcRenderer.removeListener('production:changed',listener)},
 localState:()=>ipcRenderer.invoke('local:state'),
 localInstall:id=>ipcRenderer.invoke('local:install',id),
 localCancel:()=>ipcRenderer.invoke('local:cancel'),
 localDownload:input=>ipcRenderer.invoke('local:download',input),
 localVoice:input=>ipcRenderer.invoke('local:voice',input),
 localTranscribe:id=>ipcRenderer.invoke('local:transcribe',id),
 localClip:input=>ipcRenderer.invoke('local:clip',input),
 localImport:kind=>ipcRenderer.invoke('local:import',kind),
 localSave:id=>ipcRenderer.invoke('local:save',id),
 localPrepare:(id,accountId)=>ipcRenderer.invoke('local:prepare',id,accountId),
 localHighlights:input=>ipcRenderer.invoke('local:highlights',input),
 onLocal:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('local:changed',listener);return()=>ipcRenderer.removeListener('local:changed',listener)},
 minimize:()=>ipcRenderer.invoke('window:minimize'),
 maximize:()=>ipcRenderer.invoke('window:maximize'),
 closeWindow:()=>ipcRenderer.invoke('window:close'),
 saveMedia:input=>ipcRenderer.invoke('media:save',input),
 chooseMedia:accountId=>ipcRenderer.invoke('media:choose',accountId),
 prepareGenerated:(id,accountId)=>ipcRenderer.invoke('media:generated',id,accountId),
 listImageModels:input=>ipcRenderer.invoke('images:models',input),
 generateImage:input=>ipcRenderer.invoke('images:generate',input),
 listAccountVideos:accountId=>ipcRenderer.invoke('videos:list',accountId),
 downloadVideo:input=>ipcRenderer.invoke('videos:download',input),
 listModels:input=>ipcRenderer.invoke('ai:models',input),
 connectDrive:input=>ipcRenderer.invoke('drive:connect',input),
 disconnectDrive:()=>ipcRenderer.invoke('drive:disconnect'),
 listDriveFiles:()=>ipcRenderer.invoke('drive:files'),
 uploadDriveFile:()=>ipcRenderer.invoke('drive:upload'),
 chat:input=>ipcRenderer.invoke('ai:chat',input),
 connectMeta:input=>ipcRenderer.invoke('meta:connect',input),
 disconnectMeta:id=>ipcRenderer.invoke('meta:disconnect',id),
 getWorkspace:()=>ipcRenderer.invoke('workspace:state'),
 schedule:input=>ipcRenderer.invoke('jobs:schedule',input),
 cancelJob:id=>ipcRenderer.invoke('jobs:cancel',id),
 editJob:(id,input)=>ipcRenderer.invoke('jobs:edit',id,input),
 savePreferences:input=>ipcRenderer.invoke('workspace:preferences',input),
 saveAI:input=>ipcRenderer.invoke('ai:save',input),
 generateCaption:prompt=>ipcRenderer.invoke('ai:generate',prompt),
 onWorkspace:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('workspace:changed',listener);return()=>ipcRenderer.removeListener('workspace:changed',listener);},
 checkUpdates:()=>ipcRenderer.invoke('updates:check'),
 getUpdateState:()=>ipcRenderer.invoke('updates:state'),
 installUpdate:()=>ipcRenderer.invoke('updates:install'),
 openReleases:()=>ipcRenderer.invoke('updates:releases'),
 getVersion:()=>ipcRenderer.invoke('app:version'),
 onUpdate:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('update:status',listener);return()=>ipcRenderer.removeListener('update:status',listener);}
}));
