const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('studio',Object.freeze({
 platform:process.platform,
 isDevelopment:process.argv.includes("--orvio-development"),
 storageState:()=>ipcRenderer.invoke('storage:state'),chooseStorage:()=>ipcRenderer.invoke('storage:choose'),cancelStorage:()=>ipcRenderer.invoke('storage:cancel'),openStorage:()=>ipcRenderer.invoke('storage:open'),restartStorage:()=>ipcRenderer.invoke('storage:restart'),
 seoState:()=>ipcRenderer.invoke('seo:state'),seoImport:()=>ipcRenderer.invoke('seo:import'),seoConnect:()=>ipcRenderer.invoke('seo:connect'),seoCancel:()=>ipcRenderer.invoke('seo:cancel'),seoDisconnect:()=>ipcRenderer.invoke('seo:disconnect'),seoDiscover:()=>ipcRenderer.invoke('seo:discover'),seoReport:input=>ipcRenderer.invoke('seo:report',input),seoAnalyze:input=>ipcRenderer.invoke('seo:analyze',input),seoAddAction:input=>ipcRenderer.invoke('seo:add-action',input),seoTask:input=>ipcRenderer.invoke('seo:task',input),seoExport:()=>ipcRenderer.invoke('seo:export'),onSEO:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('seo:changed',listener);return()=>ipcRenderer.removeListener('seo:changed',listener)},onUpdateOpen:callback=>{ipcRenderer.on('update:open',callback);return()=>ipcRenderer.removeListener('update:open',callback)},
 routerSignIn:input=>ipcRenderer.invoke('router:sign-in',input),routerCancelSignIn:()=>ipcRenderer.invoke('router:cancel-sign-in'),routerRefresh:()=>ipcRenderer.invoke('router:refresh'),routerCheck:()=>ipcRenderer.invoke('router:check'),routerAutoStart:value=>ipcRenderer.invoke('router:auto-start',value),routerState:()=>ipcRenderer.invoke('router:state'),routerAccount:input=>ipcRenderer.invoke('router:account',input),routerRemoveAccount:id=>ipcRenderer.invoke('router:remove-account',id),routerRoute:input=>ipcRenderer.invoke('router:route',input),routerRemoveRoute:name=>ipcRenderer.invoke('router:remove-route',name),routerTest:id=>ipcRenderer.invoke('router:test',id),routerStart:port=>ipcRenderer.invoke('router:start',port),routerStop:()=>ipcRenderer.invoke('router:stop'),routerCopyKey:()=>ipcRenderer.invoke('router:copy-key'),routerRotateKey:()=>ipcRenderer.invoke('router:rotate-key'),routerUse:name=>ipcRenderer.invoke('router:use',name),routerTunnelFile:()=>ipcRenderer.invoke('router:tunnel-file'),routerTunnelSave:input=>ipcRenderer.invoke('router:tunnel-save',input),routerTunnelStart:()=>ipcRenderer.invoke('router:tunnel-start'),routerTunnelStop:()=>ipcRenderer.invoke('router:tunnel-stop'),onRouter:callback=>{const listener=()=>callback();ipcRenderer.on('router:changed',listener);return()=>ipcRenderer.removeListener('router:changed',listener)},

 downloadFile:input=>ipcRenderer.invoke('files:download',input),findPageImages:url=>ipcRenderer.invoke('files:images',url),revealDownload:id=>ipcRenderer.invoke('files:reveal',id),
 workPermissions:value=>ipcRenderer.invoke('work:permissions',value),workStopPreview:()=>ipcRenderer.invoke('work:stop-preview'),workBrowse:url=>ipcRenderer.invoke('work:browse',url),workState:()=>ipcRenderer.invoke('work:state'),workChoose:()=>ipcRenderer.invoke('work:choose'),workCreate:name=>ipcRenderer.invoke('work:create',name),workSelect:id=>ipcRenderer.invoke('work:select',id),workRun:input=>ipcRenderer.invoke('work:run',input),workCancel:()=>ipcRenderer.invoke('work:cancel'),workApprove:(id,allow)=>ipcRenderer.invoke('work:approve',id,allow),workReview:id=>ipcRenderer.invoke('work:review',id),workUndo:id=>ipcRenderer.invoke('work:undo',id),onWork:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('work:changed',listener);return()=>ipcRenderer.removeListener('work:changed',listener)},
 desktopSettings:()=>ipcRenderer.invoke('desktop:state'),saveDesktopSettings:input=>ipcRenderer.invoke('desktop:save',input),dictationAccess:()=>ipcRenderer.invoke('dictation:access'),
 petState:()=>ipcRenderer.invoke('pets:state'),savePet:input=>ipcRenderer.invoke('pets:save',input),showPet:()=>ipcRenderer.invoke('pets:show'),onPets:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('pets:changed',listener);return()=>ipcRenderer.removeListener('pets:changed',listener)},
 onNavigate:callback=>{const listener=(_event,page)=>callback(page);ipcRenderer.on('workspace:navigate',listener);return()=>ipcRenderer.removeListener('workspace:navigate',listener)},
 onOpenDownloads:callback=>{ipcRenderer.on('downloads:open',callback);return()=>ipcRenderer.removeListener('downloads:open',callback)},
 pcState:()=>ipcRenderer.invoke('pc:state'),
 scanPC:input=>ipcRenderer.invoke('pc:scan',input),
 scanPCFolder:input=>ipcRenderer.invoke('pc:folder',input),
 cancelPCScan:()=>ipcRenderer.invoke('pc:cancel'),
 trashPCFiles:ids=>ipcRenderer.invoke('pc:trash',ids),
 installedApps:()=>ipcRenderer.invoke('pc:apps'),
 appLeftovers:id=>ipcRenderer.invoke('pc:app-files',id),
 uninstallApp:id=>ipcRenderer.invoke('pc:uninstall',id),
 scanExistingModels:choose=>ipcRenderer.invoke('pc:models',choose),
 useExistingModel:id=>ipcRenderer.invoke('pc:use-model',id),
 onPC:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('pc:changed',listener);return()=>ipcRenderer.removeListener('pc:changed',listener)},
 retryDownload:id=>ipcRenderer.invoke('downloads:retry',id),
 pauseDownload:id=>ipcRenderer.invoke('downloads:pause',id),
 downloads:()=>ipcRenderer.invoke('downloads:state'),
 cancelDownload:id=>ipcRenderer.invoke('downloads:cancel',id),
 clearDownloads:()=>ipcRenderer.invoke('downloads:clear'),
 onDownloads:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('downloads:changed',listener);return()=>ipcRenderer.removeListener('downloads:changed',listener)},
 localSession:clear=>ipcRenderer.invoke('local:session',clear),
 onStopRecording:callback=>{ipcRenderer.on('recorder:stop',callback);return()=>ipcRenderer.removeListener('recorder:stop',callback)},
 searchOnlineModels:query=>ipcRenderer.invoke('models:search',query),
 onlineModelFiles:repo=>ipcRenderer.invoke('models:files',repo),
 installOnlineModel:input=>ipcRenderer.invoke('models:remote',input),
 benchmarkModel:id=>ipcRenderer.invoke('models:benchmark',id),
 refreshHardware:()=>ipcRenderer.invoke('models:hardware'),
 modelHub:()=>ipcRenderer.invoke('models:state'),
 installModel:id=>ipcRenderer.invoke('models:install',id),
 removeModel:id=>ipcRenderer.invoke('models:remove',id),
 unloadModel:()=>ipcRenderer.invoke('models:unload'),
 cancelModel:()=>ipcRenderer.invoke('models:cancel'),
 localMesh:id=>ipcRenderer.invoke('local:mesh',id),
 generateSpatial:input=>ipcRenderer.invoke('local:spatial',input),
 generateLocal:input=>ipcRenderer.invoke('models:generate',input),
 importModel:()=>ipcRenderer.invoke('models:import'),
 onModels:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('models:changed',listener);return()=>ipcRenderer.removeListener('models:changed',listener)},
 productionState:()=>ipcRenderer.invoke('production:state'),
 startBroadcast:input=>ipcRenderer.invoke('production:start',input),
 stopBroadcast:()=>ipcRenderer.invoke('production:stop'),
 captureSources:()=>ipcRenderer.invoke('recorder:sources'),
 armCapture:input=>ipcRenderer.invoke('recorder:arm',input),
 beginRecording:()=>ipcRenderer.invoke('recorder:begin'),
 appendRecording:(id,chunk)=>ipcRenderer.invoke('recorder:append',id,chunk),
 finishRecording:id=>ipcRenderer.invoke('recorder:finish',id),
 abortRecording:id=>ipcRenderer.invoke('recorder:abort',id),
 renderCaptions:input=>ipcRenderer.invoke('local:captions',input),
 onProduction:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('production:changed',listener);return()=>ipcRenderer.removeListener('production:changed',listener)},
 localAcceleration:input=>ipcRenderer.invoke('local:acceleration',input),localState:()=>ipcRenderer.invoke('local:state'),
 localInstall:id=>ipcRenderer.invoke('local:install',id),
 localCancel:()=>ipcRenderer.invoke('local:cancel'),
 localDownload:input=>ipcRenderer.invoke('local:download',input),
 localVoice:input=>ipcRenderer.invoke('local:voice',input),
 localTranscribe:id=>ipcRenderer.invoke('local:transcribe',id),
 localClip:input=>ipcRenderer.invoke('local:clip',input),
 localImport:kind=>ipcRenderer.invoke('local:import',kind),
 localSave:id=>ipcRenderer.invoke('local:save',id),
 localPrepare:(id,accountId)=>ipcRenderer.invoke('local:prepare',id,accountId),
 localHighlights:input=>ipcRenderer.invoke('local:highlights',input),
 onLocal:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('local:changed',listener);return()=>ipcRenderer.removeListener('local:changed',listener)},
 minimize:()=>ipcRenderer.invoke('window:minimize'),
 maximize:()=>ipcRenderer.invoke('window:maximize'),
 closeWindow:()=>ipcRenderer.invoke('window:close'),
 saveMedia:input=>ipcRenderer.invoke('media:save',input),
 chooseMedia:accountId=>ipcRenderer.invoke('media:choose',accountId),
 prepareGenerated:(id,accountId)=>ipcRenderer.invoke('media:generated',id,accountId),
 listImageModels:input=>ipcRenderer.invoke('images:models',input),
 generateImage:input=>ipcRenderer.invoke('images:generate',input),
 listAccountVideos:accountId=>ipcRenderer.invoke('videos:list',accountId),
 downloadVideo:input=>ipcRenderer.invoke('videos:download',input),
 listModels:input=>ipcRenderer.invoke('ai:models',input),
 connectDrive:input=>ipcRenderer.invoke('drive:connect',input),
 disconnectDrive:()=>ipcRenderer.invoke('drive:disconnect'),
 listDriveFiles:()=>ipcRenderer.invoke('drive:files'),
 uploadDriveFile:()=>ipcRenderer.invoke('drive:upload'),
 chatCapabilities:()=>ipcRenderer.invoke('chat:capabilities'),chatFiles:()=>ipcRenderer.invoke('chat:files'),chatMic:enabled=>ipcRenderer.invoke('chat:mic',enabled),chatTranscribe:input=>ipcRenderer.invoke('chat:transcribe',input),chatSpeak:input=>ipcRenderer.invoke('chat:speak',input),
 chat:input=>ipcRenderer.invoke('ai:chat',input),
 connectMeta:input=>ipcRenderer.invoke('meta:connect',input),
 disconnectMeta:id=>ipcRenderer.invoke('meta:disconnect',id),
 getWorkspace:()=>ipcRenderer.invoke('workspace:state'),
 schedule:input=>ipcRenderer.invoke('jobs:schedule',input),
 cancelJob:id=>ipcRenderer.invoke('jobs:cancel',id),
 editJob:(id,input)=>ipcRenderer.invoke('jobs:edit',id,input),
 savePreferences:input=>ipcRenderer.invoke('workspace:preferences',input),
 saveAI:input=>ipcRenderer.invoke('ai:save',input),
 enhancePrompt:input=>ipcRenderer.invoke('creative:enhance',input),
 generateCaption:prompt=>ipcRenderer.invoke('ai:generate',prompt),
 onWorkspace:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('workspace:changed',listener);return()=>ipcRenderer.removeListener('workspace:changed',listener);},
 checkUpdates:()=>ipcRenderer.invoke('updates:check'),
 getUpdateState:()=>ipcRenderer.invoke('updates:state'),
 installUpdate:()=>ipcRenderer.invoke('updates:install'),
 openReleases:()=>ipcRenderer.invoke('updates:releases'),
 getVersion:()=>ipcRenderer.invoke('app:version'),
 onUpdate:callback=>{const listener=(_event,state)=>callback(state);ipcRenderer.on('update:status',listener);return()=>ipcRenderer.removeListener('update:status',listener);}
}));
