const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{randomUUID}=require('node:crypto');
function createProduction({directory,localStudio,notify=()=>{}}){
 const root=path.join(directory,'recordings');fs.mkdirSync(root,{recursive:true});for(const name of fs.readdirSync(root)){if(!/^[0-9a-f-]{36}\.webm$/.test(name))continue;const file=path.join(root,name);try{if(fs.statSync(file).size)localStudio.import(file,'video');fs.unlinkSync(file)}catch{}}let recording=null,live=null,processHandle=null,starting=false;
 const state=()=>({recording:recording?{id:recording.id,bytes:recording.bytes,startedAt:recording.startedAt}:null,live,starting});
 function send(){notify(state())}
 function stop(){if(processHandle){if(process.platform==='win32')spawn('taskkill',['/pid',String(processHandle.pid),'/T','/F']);else try{process.kill(-processHandle.pid,'SIGTERM')}catch{processHandle.kill()}live={...live,status:'stopping'};send()}}
 return {state,stop,
 async start(input){if(starting||processHandle)throw Error('Stop the current stream first.');if(typeof input.key!=='string'||!/^[A-Za-z0-9_-]{6,200}$/.test(input.key))throw Error('Enter a valid YouTube stream key.');const source=localStudio.file(input.id);starting=true;send();try{const runtime=await localStudio.videoRuntime();live={status:'connecting',startedAt:new Date().toISOString(),time:'00:00:00',fps:'0',speed:'0x',bytes:0,error:''};const child=spawn(runtime.python,[runtime.worker],{windowsHide:true,detached:process.platform!=='win32',env:{...process.env,PYTHONUNBUFFERED:'1',OMP_NUM_THREADS:'2'}});processHandle=child;let buffer='';child.stdout.on('data',data=>{buffer+=data;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.startsWith('ORVIO_LIVE ')){const value=JSON.parse(line.slice(11));live={...live,status:value.out_time&&value.out_time!=='00:00:00.000000'?'sending':live.status,...(value.out_time?{time:value.out_time.split('.')[0]}:{}),...(value.fps?{fps:value.fps}:{}),...(value.speed?{speed:value.speed}:{}),...(value.total_size?{bytes:Number(value.total_size)||0}:{})};send()}else if(line.startsWith('ORVIO_ERROR ')){live={...live,status:'failed',error:JSON.parse(line.slice(12)).split(input.key).join('[hidden]')};send()}}});child.stderr.on('data',()=>{});child.on('error',()=>{live={...live,status:'failed',error:'The local streaming engine could not start.'};send()});child.on('close',code=>{processHandle=null;if(live.status!=='failed')live={...live,status:live.status==='stopping'||code===0?'stopped':'failed',error:code&&live.status!=='stopping'?'The streaming engine stopped unexpectedly.':''};send()});child.stdin.on('error',()=>{});child.stdin.end(JSON.stringify({source,key:input.key,resolution:input.resolution==='1080'?'1080':'720',loop:!!input.loop,mute:!!input.mute}));return state()}finally{starting=false;send()}},
 beginRecording(){if(recording)throw Error('A recording is already active.');const id=randomUUID();recording={id,file:path.join(root,id+'.webm'),bytes:0,startedAt:new Date().toISOString()};fs.writeFileSync(recording.file,'',{mode:0o600});send();return {id}},
 appendRecording(id,chunk){if(!recording||recording.id!==id)throw Error('Recording session ended.');if(!(chunk instanceof ArrayBuffer)&&!ArrayBuffer.isView(chunk))throw Error('Invalid recording data.');if(chunk.byteLength>16*1024*1024)throw Error('Recording chunk is too large.');const data=Buffer.from(chunk);if(data.length>16*1024*1024||recording.bytes+data.length>4*1024**3)throw Error('Recording size limit reached. Stop and save this recording.');fs.appendFileSync(recording.file,data);recording.bytes+=data.length;return {bytes:recording.bytes}},
 finishRecording(id){if(!recording||recording.id!==id)throw Error('Recording session ended.');const current=recording;recording=null;send();if(!current.bytes){fs.unlinkSync(current.file);throw Error('The recording did not contain video.')}const asset=localStudio.import(current.file,'video');fs.unlinkSync(current.file);return asset},
 abortRecording(id){if(recording?.id!==id)return;fs.rmSync(recording.file,{force:true});recording=null;send()},
 shutdown(){stop();if(recording){recording=null;send()}}
 };
}
module.exports={createProduction};
