const fs=require('node:fs');
const path=require('node:path');
const {Readable,Transform}=require('node:stream');
const {pipeline}=require('node:stream/promises');
const MAX_BYTES=250*1024*1024;
const videoHost=host=>['fbcdn.net','cdninstagram.com','fbsbx.com'].some(domain=>host===domain||host.endsWith('.'+domain));
function parseVideoLink(raw){let url;try{url=new URL(raw)}catch{throw new Error('Paste an Instagram or Facebook video link.')}if(url.protocol!=='https:'||url.username||url.password)throw new Error('Use an HTTPS Instagram or Facebook link.');const host=url.hostname.toLowerCase().replace(/^www\./,'');if(host==='instagram.com'){const match=url.pathname.match(/^\/(?:reel|p|tv)\/([A-Za-z0-9_-]+)\/?$/);if(!match)throw new Error('Paste a video or Reel link from Instagram.');return {platform:'instagram',key:match[1]}}if(host==='facebook.com'||host==='m.facebook.com'){const match=url.pathname.match(/\/(?:videos|reel)\/(\d+)/);const key=match?.[1]||url.searchParams.get('v');if(!/^\d+$/.test(key||''))throw new Error('Paste a Facebook video or Reel link.');return {platform:'facebook',key}}throw new Error('Only Instagram and Facebook video links are supported.');}
function matchesVideo(parsed,item){if(parsed.platform!==item.platform)return false;if(parsed.platform==='facebook'&&item.id===parsed.key)return true;try{const candidate=parseVideoLink(item.permalink);return candidate.platform===parsed.platform&&candidate.key===parsed.key}catch{return false}}
async function downloadSource({source,id,directory,fetchImpl=fetch}){let target=new URL(source);for(let redirect=0;redirect<4;redirect++){if(target.protocol!=='https:'||target.username||target.password||!videoHost(target.hostname.toLowerCase()))throw new Error('Meta returned an untrusted video host.');let response;try{response=await fetchImpl(target.href,{redirect:'manual',signal:AbortSignal.timeout(180000)})}catch{throw new Error('Video download failed. Check your network and try again.')}if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw new Error('Meta video redirect was incomplete.');target=new URL(location,target);continue}if(!response.ok||!response.body)throw new Error(`Video download failed (${response.status}). The link may have expired.`);const type=response.headers.get('content-type')||'';if(!/video\/|application\/octet-stream/.test(type))throw new Error('Meta did not return a video file.');const length=Number(response.headers.get('content-length')||0);if(length>MAX_BYTES)throw new Error('Video is over the 250 MB download limit.');const folder=path.join(directory,'Orvio Studio');await fs.promises.mkdir(folder,{recursive:true});const filename=`orvio-${String(id).replace(/[^0-9A-Za-z_-]/g,'').slice(0,60)}-${Date.now()}.mp4`;const dest=path.join(folder,filename);let received=0;try{await pipeline(Readable.fromWeb(response.body),new Transform({transform(chunk,_encoding,callback){received+=chunk.length;if(received>MAX_BYTES)callback(new Error('Video is over the 250 MB download limit.'));else callback(null,chunk)}}),fs.createWriteStream(dest,{flags:'wx',mode:0o600}));return {path:dest,name:filename,size:received}}catch(error){await fs.promises.rm(dest,{force:true});throw error}}throw new Error('Meta redirected the video too many times.')}
module.exports={parseVideoLink,matchesVideo,downloadSource};
