const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {openAsBlob}=fs;
const {graphClient}=require('./meta.cjs');
const {createDriveConnector}=require('./drive.cjs');
function createWorkspace({directory,safeStorage,fetchImpl=fetch,notify=()=>{},openExternal=()=>{throw new Error('Open the installed desktop app to connect Google Drive.')}}){
 const file=path.join(directory,'workspace-v3.json');
 let data={accounts:[],jobs:[],localMedia:[],drive:{clientId:'',refreshToken:'',connectedAt:'',lastError:''},ai:{provider:'openai',baseURL:'https://api.openai.com/v1',model:'',key:''},paused:false,startAtLogin:false,media:{cloudName:'',uploadPreset:''}};
 if(fs.existsSync(file))data={...data,...JSON.parse(fs.readFileSync(file,'utf8'))};
 const persist=()=>{fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(data),{mode:0o600});fs.renameSync(file+'.tmp',file);notify(snapshot());};
 const encrypt=value=>{if(!safeStorage.isEncryptionAvailable())throw new Error('Operating system credential encryption is unavailable.');return safeStorage.encryptString(value).toString('base64');};
 const decrypt=value=>safeStorage.decryptString(Buffer.from(value,'base64'));
 const snapshot=()=>({...data,localMedia:undefined,dataDirectory:directory,accounts:data.accounts.map(({token,pageToken,...account})=>account),drive:{clientId:data.drive.clientId,connected:!!data.drive.refreshToken,connectedAt:data.drive.connectedAt,lastError:data.drive.lastError},ai:{...data.ai,key:undefined,hasKey:!!data.ai.key}});
 const drive=createDriveConnector({getConfig:()=>data.drive,saveConfig:value=>{data.drive=value;persist()},decrypt,encrypt,fetchImpl,openExternal});
 const localPath=id=>{if(!/^[0-9a-f-]{36}\.(jpg|jpeg|png)$/.test(id||''))throw new Error('Choose the photo again.');return path.join(directory,'media',id)};
 const releaseLocal=id=>{if(!id)return;try{fs.unlinkSync(localPath(id))}catch{}data.localMedia=data.localMedia.filter(item=>item.id!==id)};
 const client=account=>graphClient({accessToken:decrypt(account.pageToken||account.token),version:account.version,fetchImpl});
 let running=false;
 async function tick(){
  if(running||data.paused)return;running=true;
  try{for(const job of data.jobs){
   if(data.paused)break;
   if(!['queued','processing','publishing'].includes(job.status)||Date.parse(job.scheduledAt)>Date.now())continue;
   const account=data.accounts.find(a=>a.id===job.accountId);if(!account){job.status='failed';job.error='Account disconnected. Create a new schedule after reconnecting.';persist();continue;}
   try{
    const api=client(account);
    if(job.status==='queued'){job.status='creating';persist();if(account.kind==='facebook'){job.status='publishing';persist();const result=job.localMediaId?await api.publishPagePhotoLocal({pageId:account.pageId,filePath:localPath(job.localMediaId),caption:job.caption}):await api.publishPage({...job,pageId:account.pageId});job.mediaId=result.id||result.post_id;job.status='published';job.publishedAt=new Date().toISOString();job.error='';releaseLocal(job.localMediaId);persist();continue;}const container=await api.createImageContainer(job);job.containerId=container.id;job.status='processing';persist();}
    if(account.kind==='facebook'){job.status='uncertain';job.error='Check the Page before scheduling again; the previous publish may have succeeded.';persist();continue;}
    const status=await api.containerStatus(job.containerId);
    if(status.status_code==='PUBLISHED'){job.status='published';job.error='';persist();continue;}
    if(job.status==='publishing'){job.status='uncertain';job.error='Publish outcome could not be confirmed. Check Instagram before scheduling again.';persist();continue;}
    if(['ERROR','EXPIRED'].includes(status.status_code))throw new Error('Meta could not process the image. Check the public JPEG URL and schedule again.');
    if(status.status_code!=='FINISHED')continue;
    job.status='publishing';persist();
    const result=await api.publishContainer({accountId:job.accountId,containerId:job.containerId});
    job.mediaId=result.id;job.status='published';job.publishedAt=new Date().toISOString();job.error='';persist();
   }catch(error){job.status=job.status==='publishing'?'uncertain':'failed';job.error=job.status==='uncertain'?`Publishing could not be confirmed. Check ${account.kind==='facebook'?'Facebook':'Instagram'} before scheduling again.`:(error.message.startsWith('Meta')?error.message:'Connection failed. Check your network, token and media.');persist();}
  }}finally{running=false;}
 }
 // A crash before a container ID is saved cannot have published anything. Never repeat an uncertain publish.
 for(const job of data.jobs)if(job.status==='creating'){job.status='failed';job.error='App stopped while preparing media. Schedule again.';}
 return {snapshot,tick,
  async connect({token,version}){if(typeof token!=='string'||token.length<10||token.length>10000)throw new Error('Enter your Meta user access token.');const encrypted=encrypt(token);const accounts=await graphClient({accessToken:token,version,fetchImpl}).listAccounts();if(!accounts.length)throw new Error('No Facebook Pages found. Check pages_show_list and pages_read_engagement permissions.');for(const a of accounts){const {pageToken,...publicAccount}=a;const item={...publicAccount,version,token:encrypted,pageToken:pageToken?encrypt(pageToken):''};const index=data.accounts.findIndex(x=>x.id===item.id);if(index<0)data.accounts.push(item);else data.accounts[index]=item;}persist();return snapshot();},
  saveMedia(input){if(typeof input.cloudName!=='string'||!/^[-a-zA-Z0-9_]{0,100}$/.test(input.cloudName)||typeof input.uploadPreset!=='string'||!/^[-a-zA-Z0-9_]{0,100}$/.test(input.uploadPreset))throw new Error('Enter a valid Cloudinary cloud name and unsigned upload preset.');data.media={cloudName:input.cloudName,uploadPreset:input.uploadPreset};persist();return snapshot();},
  connectDrive:({clientId})=>drive.connect(clientId),
  disconnectDrive:()=>{drive.disconnect();return snapshot()},
  listDriveFiles:()=>drive.list(),
  uploadDriveFile:filePath=>drive.upload(filePath),
  async prepareMedia(filePath,accountId){const account=data.accounts.find(a=>a.id===accountId);if(!account)throw new Error('Choose a destination before selecting a file.');const ext=path.extname(filePath).toLowerCase();if(account.kind==='facebook'&&['.jpg','.jpeg','.png'].includes(ext)){const info=fs.statSync(filePath);if(!info.isFile()||info.size===0||info.size>10*1024*1024)throw new Error('Facebook Page photos must be JPG or PNG and under 10 MB.');const id=randomUUID()+ext;fs.mkdirSync(path.join(directory,'media'),{recursive:true,mode:0o700});fs.copyFileSync(filePath,localPath(id));data.localMedia.push({id,accountId});persist();return {localMediaId:id,mediaType:'image',name:path.basename(filePath)};}return this.uploadFile(filePath);},
  async uploadFile(filePath){if(!data.media.cloudName||!data.media.uploadPreset)throw new Error('Configure Cloudinary media hosting in Settings to upload files from your PC.');const info=fs.statSync(filePath);const ext=path.extname(filePath).toLowerCase();const types={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.mp4':'video/mp4','.mov':'video/quicktime'};if(!types[ext]||info.size>100*1024*1024||info.size===0)throw new Error('Choose a JPG, PNG, MP4 or MOV under 100 MB.');const mediaType=ext==='.mp4'||ext==='.mov'?'video':'image';const body=new FormData();body.set('file',await openAsBlob(filePath,{type:types[ext]}),path.basename(filePath));body.set('upload_preset',data.media.uploadPreset);const url=`https://api.cloudinary.com/v1_1/${data.media.cloudName}/${mediaType}/upload`;let response;try{response=await fetchImpl(url,{method:'POST',body,redirect:'error',signal:AbortSignal.timeout(120000)});}catch{throw new Error('Media upload failed. Check your connection and Cloudinary settings.');}if(!response.ok)throw new Error(`Media upload failed (${response.status}). Check your unsigned upload preset.`);const result=await response.json();const secureURL=new URL(result.secure_url);if(secureURL.protocol!=='https:'||secureURL.hostname!=='res.cloudinary.com'||!secureURL.pathname.startsWith('/'+data.media.cloudName+'/'))throw new Error('Media host returned an unexpected URL.');return {url:ext==='.png'?secureURL.href.replace('/upload/','/upload/f_jpg/'):secureURL.href,mediaType,name:path.basename(filePath)};},
  disconnect(id){if(data.jobs.some(j=>j.accountId===id&&['creating','processing','publishing'].includes(j.status)))throw new Error('Wait for the active post to finish before disconnecting.');data.accounts=data.accounts.filter(a=>a.id!==id);persist();return snapshot();},
  schedule(input){const {accountId,imageUrl,localMediaId,caption,title,scheduledAt,mediaType='image'}=input;const account=data.accounts.find(a=>a.id===accountId);if(!account)throw new Error('Choose a connected account.');if(!['image','video'].includes(mediaType))throw new Error('Choose an image or video.');if(typeof caption!=='string'||caption.length>2200||typeof title!=='string'||!title.trim()||title.length>100)throw new Error('Add a title and caption of up to 2,200 characters.');if(!Number.isFinite(Date.parse(scheduledAt))||Date.parse(scheduledAt)<Date.now()-60000)throw new Error('Choose a future publishing time.');let url;if(localMediaId){if(account.kind!=='facebook'||mediaType!=='image'||!data.localMedia.some(item=>item.id===localMediaId&&item.accountId===accountId)||data.jobs.some(j=>j.localMediaId===localMediaId)||!fs.existsSync(localPath(localMediaId)))throw new Error('Choose the Facebook Page photo again.');}else{url=new URL(imageUrl);if(url.protocol!=='https:'||url.username||url.password)throw new Error('Enter a publicly accessible HTTPS media URL.');}const job={id:randomUUID(),accountId,imageUrl:url?.href||'',localMediaId:localMediaId||'',caption,title,scheduledAt,mediaType,status:'queued'};data.jobs.unshift(job);persist();return snapshot();},
  publishNow(input){return this.schedule({...input,scheduledAt:new Date().toISOString()});},
  cancel(id){const job=data.jobs.find(j=>j.id===id);if(!job||job.status!=='queued')throw new Error('Only queued posts can be cancelled.');job.status='cancelled';releaseLocal(job.localMediaId);persist();return snapshot();},
  preferences(input){if(typeof input.paused==='boolean')data.paused=input.paused;if(typeof input.startAtLogin==='boolean')data.startAtLogin=input.startAtLogin;persist();return snapshot();},
  saveAI(input){if(!['openai','gemini','ollama'].includes(input.provider))throw new Error('Choose an AI provider.');const url=new URL(input.provider==='ollama'?'http://127.0.0.1:11434/v1':input.baseURL||'https://api.openai.com/v1');if((url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname)))||url.username||url.password||url.search||url.hash)throw new Error('Use HTTPS, or a local HTTP endpoint.');if(typeof input.model!=='string'||!input.model.trim()||input.model.length>150)throw new Error('Enter your provider’s model ID.');let key=data.ai.key;if(input.provider!==data.ai.provider||url.href.replace(/\/$/,'')!==data.ai.baseURL)key='';if(input.key)key=encrypt(String(input.key));if(input.clearKey)key='';data.ai={provider:input.provider,baseURL:url.href.replace(/\/$/,''),model:input.model.trim(),key};persist();return snapshot();},
  async listModels(input){if(!['openai','gemini','ollama'].includes(input.provider))throw new Error('Choose an AI provider.');const endpoint=input.provider==='ollama'?'http://127.0.0.1:11434/api/tags':input.provider==='gemini'?'https://generativelanguage.googleapis.com/v1beta/models':String(input.baseURL||'https://api.openai.com/v1').replace(/\/$/,'')+'/models';const url=new URL(endpoint);if((url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname)))||url.username||url.password)throw new Error('Use a secure AI endpoint.');const same=input.provider===data.ai.provider&&(input.provider!=='openai'||String(input.baseURL||'https://api.openai.com/v1').replace(/\/$/,'')===data.ai.baseURL);const key=String(input.key||'')||(same&&data.ai.key?decrypt(data.ai.key):'');if(input.provider==='gemini'&&!key)throw new Error('Enter a Gemini API key to load models.');let response;try{response=await fetchImpl(url.href,{headers:key?{[input.provider==='gemini'?'x-goog-api-key':'Authorization']:input.provider==='gemini'?key:`Bearer ${key}`}:{},redirect:'error',signal:AbortSignal.timeout(15000)});}catch{throw new Error('Could not reach the model provider. Check the key, endpoint, or local Ollama service.');}if(!response.ok)throw new Error(`Could not load models (${response.status}). Check your key and provider.`);const body=await response.json();const models=input.provider==='ollama'?body.models?.map(item=>item.name):input.provider==='gemini'?body.models?.filter(item=>item.supportedGenerationMethods?.includes('generateContent')).map(item=>item.name?.replace(/^models\//,'')):body.data?.map(item=>item.id);const filtered=[...new Set((models||[]).filter(value=>typeof value==='string'&&value.length<150&&((input.provider==='gemini')?/^(gemini-|gemma-)/.test(value)&&!/image|tts|transcribe|omni|robotics|computer|live|audio/i.test(value):true)))];return filtered.sort((a,b)=>{if(input.provider==='gemini'){const rank=x=>x==='gemini-2.5-flash'?0:x==='gemini-flash-latest'?1:x.includes('flash')?2:x.includes('pro')?3:4;return rank(a)-rank(b)||a.localeCompare(b);}return a.localeCompare(b)}).slice(0,300);},
  async chat({messages,agent='studio'}){
   if(!Array.isArray(messages)||messages.length>30||!['studio','caption','planner'].includes(agent))throw new Error('Choose a valid chat agent.');
   const turns=messages.map(m=>{if(!['user','assistant'].includes(m.role)||typeof m.content!=='string'||m.content.length>4000)throw new Error('Message is too long.');return {role:m.role,content:m.content};});
   if(!turns.length)throw new Error('Write a message first.');
   const config=data.ai;if(!config.model)throw new Error('Configure an AI model in Settings first.');const key=config.key?decrypt(config.key):'';const gemini=config.provider==='gemini';if(gemini&&!key)throw new Error('Add a Gemini API key in Settings.');
   const schema={type:'object',properties:{title:{type:'string'},caption:{type:'string'},accountId:{type:'string'},imageUrl:{type:'string'},mediaType:{type:'string',enum:['image','video']},publishMode:{type:'string',enum:['now','later']},scheduledAt:{type:'string'}},required:['title','caption']};
   const definitions=[
    {name:'list_accounts',description:'Read connected Facebook Pages and Instagram profiles.',parameters:{type:'object',properties:{}}},
    {name:'list_posts',description:'Read recent and upcoming publishing jobs.',parameters:{type:'object',properties:{}}},
    {name:'publishing_status',description:'Check whether automatic publishing is paused.',parameters:{type:'object',properties:{}}},
    {name:'list_drive_files',description:'List files the user added to Orvio in Google Drive.',parameters:{type:'object',properties:{}}},
    {name:'prepare_post',description:'Open an editable post in chat. Use when asked to schedule or publish. The user reviews and confirms the final post and chooses a local file if needed.',parameters:schema},
    {name:'open_calendar',description:'Show the publishing calendar in chat.',parameters:{type:'object',properties:{}}},
    {name:'connect_meta',description:'Open the Meta account connection dialog.',parameters:{type:'object',properties:{}}},
    {name:'open_drive',description:'Open the Google Drive connector in chat.',parameters:{type:'object',properties:{}}}
   ];
   const context=JSON.stringify({accounts:data.accounts.map(a=>({id:a.id,name:a.username,platform:a.kind})),upcoming:data.jobs.filter(j=>j.status==='queued').slice(0,20).map(j=>({title:j.title,scheduledAt:j.scheduledAt,accountId:j.accountId}))});
   const instructions='You are Orvio Studio assistant. You can use the provided tools to inspect connected accounts, posts, Drive files, and prepare a post or open tools. Never claim an action succeeded until a tool confirms it. A prepared post opens for user review; the user confirms the final publish. Do not say you cannot use tools or direct the user to another page for these actions. Answer concisely. Agent role: '+agent+'. Workspace: '+context;
   const actions=[];
   async function invoke(name,args){
    if(name==='list_accounts')return {accounts:data.accounts.map(a=>({id:a.id,name:a.username,platform:a.kind}))};
    if(name==='list_posts')return {posts:data.jobs.slice(0,20).map(j=>({title:j.title,status:j.status,scheduledAt:j.scheduledAt,accountId:j.accountId}))};
    if(name==='publishing_status')return {paused:data.paused,queued:data.jobs.filter(j=>j.status==='queued').length};
    if(name==='list_drive_files'){try{return {files:(await drive.list()).map(f=>({name:f.name,id:f.id,mimeType:f.mimeType}))}}catch(error){return {error:error.message}}}
    if(name==='prepare_post'){const accountId=data.accounts.some(a=>a.id===args.accountId)?args.accountId:'';actions.push({type:'prepare_post',draft:{title:String(args.title||'').slice(0,100),caption:String(args.caption||'').slice(0,2200),accountId,imageUrl:/^https:\/\//.test(args.imageUrl||'')?String(args.imageUrl):'',mediaType:args.mediaType==='video'?'video':'image',publishMode:args.publishMode==='now'?'now':'later',scheduledAt:String(args.scheduledAt||'')}});return {status:'opened_for_review',message:'The post composer is open in chat. User must confirm to publish.'}}
    if(['open_calendar','connect_meta','open_drive'].includes(name)){actions.push({type:name});return {status:'opened_in_chat'}}
    return {error:'Unknown tool'};
   }
   const url=gemini?`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(config.model)}:generateContent`:config.baseURL+'/chat/completions';
   const headers={'Content-Type':'application/json',...(gemini?{'x-goog-api-key':key}:key?{Authorization:`Bearer ${key}`}:{})};
   const history=gemini?turns.map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]})):[{role:'system',content:instructions},...turns];
   for(let round=0;round<3;round++){
    const payload=gemini?{system_instruction:{parts:[{text:instructions}]},contents:history,tools:[{functionDeclarations:definitions.map(d=>({name:d.name,description:d.description,parameters:d.parameters}))}]}:{model:config.model,messages:history,tools:definitions.map(d=>({type:'function',function:d})),tool_choice:'auto'};
    let response;try{response=await fetchImpl(url,{method:'POST',redirect:'error',headers,body:JSON.stringify(payload),signal:AbortSignal.timeout(90000)});}catch{throw new Error('Chat connection failed. Check the configured AI provider.');}
    if(!response.ok)throw new Error(`Chat request failed (${response.status}). Check your model, key, or provider tool support.`);
    const result=await response.json();
    if(gemini){const content=result.candidates?.[0]?.content;const calls=content?.parts?.filter(p=>p.functionCall)||[];if(!calls.length){const answer=content?.parts?.map(p=>p.text||'').join('').trim();return {text:(answer||(actions.length?'Ready for your review.':'The model returned no answer.')).slice(0,12000),actions};}history.push(content);const replies=[];for(const part of calls){const name=part.functionCall.name;const output=await invoke(name,part.functionCall.args||{});replies.push({functionResponse:{name,...(part.functionCall.id?{id:part.functionCall.id}:{}),response:output}})}history.push({role:'user',parts:replies});}
    else{const message=result.choices?.[0]?.message;if(!message)throw new Error('The model returned no answer.');const calls=message.tool_calls||[];if(!calls.length)return {text:String(message.content|| (actions.length?'Ready for your review.':'The model returned no answer.')).slice(0,12000),actions};history.push(message);for(const call of calls){let args={};try{args=JSON.parse(call.function?.arguments||'{}')}catch{}const output=await invoke(call.function?.name,args);history.push({role:'tool',tool_call_id:call.id,content:JSON.stringify(output)})}}
   }
   return {text:actions.length?'I opened that in chat for your review.':'I checked the connected tools.',actions};
  },
  async generate(prompt){if(typeof prompt!=='string'||!prompt.trim()||prompt.length>6000)throw new Error('Describe your post in up to 6,000 characters.');const config={...data.ai};if(!config.model)throw new Error('Configure AI in Settings first.');const key=config.key?decrypt(config.key):'';const gemini=config.provider==='gemini';if(gemini&&!key)throw new Error('Add a Gemini API key in Settings.');const instruction='Write one social media caption, at most 2200 characters. Return only the caption. Do not invent facts. Post brief: '+prompt;const url=gemini?`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(config.model)}:generateContent`:config.baseURL+'/chat/completions';let response;try{response=await fetchImpl(url,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',...(gemini?{'x-goog-api-key':key}:key?{Authorization:`Bearer ${key}`}:{})},body:JSON.stringify(gemini?{contents:[{parts:[{text:instruction}]}]}:{model:config.model,messages:[{role:'user',content:instruction}]}),signal:AbortSignal.timeout(60000)});}catch{throw new Error('AI connection failed. Check your endpoint and network.');}if(!response.ok)throw new Error(`AI request failed (${response.status}). Check the key, model and provider quota.`);const result=await response.json();const text=gemini?result.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join(''):result.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())throw new Error('The provider returned no caption. Try another brief.');return text.trim().slice(0,2200);}
 };
}
module.exports={createWorkspace};
