// Isolated development fixture. No desktop capture, clipboard writes or real devices.
import React from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource-variable/unbounded';
import '../src/theme.css';
import {RecorderStudio} from '../src/RecorderStudio';
const assets:any[]=[{id:'11111111-1111-4111-8111-111111111111',kind:'video',title:'Product walkthrough',preview:'/.runtime-cache/recorder-smoke/source.mp4',duration:4},{id:'22222222-2222-4222-8222-222222222222',kind:'image',title:'Screenshot preview',preview:'/.runtime-cache/recorder-smoke/source.png'}];
const projects:Record<string,unknown>={};let settings={editScreenshot:true,shortcutArea:true},shotCallback:any=()=>{},localCallback:any=()=>{};
const source={id:'screen:1:0',name:'Studio display',displayId:'1',thumbnail:assets[1].preview};
(window as any).studio={platform:'darwin',recorderState:async()=>({settings,shortcut:'CommandOrControl+Shift+S',recordingShortcut:'CommandOrControl+Shift+R',recent:[]}),recorderSettings:async(patch:any)=>settings={...settings,...patch},recorderProject:async(id:string)=>projects[id]||null,saveRecorderProject:async(id:string,options:any)=>projects[id]=options,localState:async()=>({assets}),onLocal:(fn:any)=>{localCallback=fn;return()=>{}},onScreenshot:(fn:any)=>{shotCallback=fn;return()=>{}},onRecorderError:()=>()=>{},onStopRecording:()=>()=>{},captureSources:async()=>[source],selectCaptureArea:async()=>({sourceId:source.id,crop:{x:.15,y:.15,width:.7,height:.7}}),takeScreenshot:async(input:any)=>{const result=input.edit?assets[1]:{copied:true};shotCallback({asset:result,edit:input.edit});return result},saveDesktopSettings:async()=>({errors:[]}),renderScreenshot:async(input:any)=>{if(!input.data.startsWith('data:image/png;base64,'))throw Error('No rendered image');return {id:crypto.randomUUID(),kind:'image',title:'Styled screenshot',preview:input.data}},localSave:async()=>true,localImport:async(kind:string)=>assets.find(a=>a.kind===kind),exportRecording:async()=>({id:crypto.randomUUID(),kind:'video',title:'Edited video',preview:'/.runtime-cache/recorder-smoke/styled.mp4'}),localCancel:async()=>{},armCapture:async()=>{},minimizeRecorder:async()=>{},restoreRecorder:async()=>{},capturePointer:async()=>({x:.75,y:.4})};
// MediaRecorder still encodes real frames; inputs are a synthetic canvas for safe UI testing.
const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d')!;let frame=0;setInterval(()=>{ctx.fillStyle='#13233c';ctx.fillRect(0,0,640,360);ctx.fillStyle='#81b8ed';ctx.fillRect(40+frame++%350,120,100,100);ctx.fillStyle='white';ctx.font='24px sans-serif';ctx.fillText('Recorder test source',40,60)},33);
Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:async()=>canvas.captureStream(30)});
Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async(input:any)=>input.video?canvas.captureStream(30):new MediaStream()});
const chunks:BlobPart[]=[];Object.assign((window as any).studio,{beginRecording:async()=>{chunks.length=0;return {id:'test-session'}},appendRecording:async(_id:string,bytes:ArrayBuffer,track:string)=>{if(track==='screen')chunks.push(bytes);return {bytes:chunks.reduce((n:any,c:any)=>n+c.byteLength,0)}},finishRecording:async()=>{const asset={id:crypto.randomUUID(),kind:'video',title:'Synthetic screen recording',preview:URL.createObjectURL(new Blob(chunks,{type:'video/webm'}))};assets.unshift(asset);localCallback({assets});return asset},abortRecording:async()=>{}});
createRoot(document.getElementById('root')!).render(<div style={{padding:28,maxWidth:1360,margin:'auto'}}><RecorderStudio onUse={()=>{}}/></div>);
