const {app,clipboard}=require('electron'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let copied='';clipboard.writeText=value=>{copied=value};
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'orvio-router-ui-'));app.setPath('userData',profile);const project=path.join(profile,'project');fs.mkdirSync(project);fs.writeFileSync(path.join(profile,'work-projects.json'),JSON.stringify({selectedId:'router-test',projects:[{id:'router-test',name:'Router project',root:project,turns:[],changes:[],events:[]}]}));let window;const errors=[],calls=[];
app.on('browser-window-created',(_,win)=>{if(window)return;window=win;win.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message)})});
const upstream=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.url==='/v1/models')return res.end(JSON.stringify({data:[{id:'fixture-model'}]}));let body='';req.on('data',d=>body+=d);req.on('end',()=>{calls.push(JSON.parse(body));res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'Router connection verified.'},finish_reason:'stop'}]}))})});
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),js=code=>window.webContents.executeJavaScript(code);
async function until(fn,label){const end=Date.now()+12000;while(Date.now()<end){if(await fn())return;await sleep(75)}throw Error('Timed out: '+label)}
async function click(text){await js(`Array.from(document.querySelectorAll('.router-settings button')).find(b=>b.textContent===${JSON.stringify(text)}).click()`);await sleep(100)}
async function input(label,value){await js(`(()=>{const el=document.querySelector('[aria-label="${label}"]');const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}))})()`);await sleep(50)}
(async()=>{await new Promise(r=>upstream.listen(0,'127.0.0.1',r));require('../electron/main.cjs');await app.whenReady();await until(()=>window&&!window.webContents.isLoading(),'window');await sleep(1500);await js(`localStorage.setItem('orvio.v2.preferences',JSON.stringify({onboarded:true,name:'Test',workspace:'Router verification'}));sessionStorage.setItem('orvio.v2.ready','true');location.reload()`);await sleep(1000);
 window.webContents.send('workspace:navigate','Settings');await sleep(400);await js(`Array.from(document.querySelectorAll('.settings-menu button')).find(b=>b.textContent.includes('Unified API')).click()`);await until(()=>js(`document.body.innerText.includes('One API for your AI connections.')`),'router settings');
 await click('Add connection');await input('Router connection name','Local test provider');await input('Router connection URL',`http://127.0.0.1:${upstream.address().port}/v1`);await click('Save connection');await until(()=>js(`document.body.innerText.includes('Connection saved.')`),'saved account');await click('Test & find models');await until(()=>js(`document.body.innerText.includes('1 models found')`),'discovered models');await click('Model routes');await click('Add connection to route');await input('Route model 1','fixture-model');await click('Save route');await until(()=>js(`document.body.innerText.includes('Model route saved.')`),'saved route');
 // Avoid conflicting with an actual user API already running on the default port.
 const reservation=http.createServer();await new Promise(r=>reservation.listen(0,'127.0.0.1',r));const port=reservation.address().port;await new Promise(r=>reservation.close(r));await js(`window.studio.routerStart(${port})`);await click('Check API');await until(()=>js(`document.body.innerText.includes('API verified')`),'API check');
 await js(`document.querySelector('.router-route .primary').click()`);await until(()=>js(`window.studio.getWorkspace().then(s=>s.ai.model==='work')`),'workspace routing');const ai=await js('window.studio.getWorkspace().then(s=>s.ai)');assert.equal(ai.baseURL,`http://127.0.0.1:${port}/v1`);
 await js('window.studio.routerCopyKey()');const key=copied;
 const response=await fetch(ai.baseURL+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:'work',messages:[{role:'user',content:'Verify router'}]})});assert.equal(response.status,200);assert.equal((await response.json()).choices[0].message.content,'Router connection verified.');assert.equal(calls[0].model,'fixture-model');
 await js(`localStorage.setItem('orvio.assistant.mode','work');localStorage.setItem('orvio.work.model','configured')`);window.webContents.send('workspace:navigate','Chat');await until(()=>js(`!!document.querySelector('[aria-label="Coding task"]')`),'work');await js(`document.querySelector('[aria-label="Coding task"]').focus()`);await window.webContents.insertText('Explain the connection');await js(`document.querySelector('[aria-label="Coding task"]').closest('form').requestSubmit()`);await until(()=>js(`document.body.innerText.includes('Router connection verified.')`),'work completion');
 window.webContents.send('workspace:navigate','Settings');await sleep(250);await click('Connections');await sleep(500);if(process.env.ORVIO_VERIFY_SCREENSHOT)fs.writeFileSync(process.env.ORVIO_VERIFY_SCREENSHOT,(await window.webContents.capturePage()).toPNG());assert.deepEqual(errors,[]);await js('window.studio.routerStop()');upstream.closeAllConnections();upstream.close();console.log('PASS: save connection, discover models, build route, authenticated real HTTP gateway, configure Work, and Work UI completion through router.');app.exit(0);
})().catch(e=>{console.error(e,errors);upstream.closeAllConnections();upstream.close();app.exit(1)});
setTimeout(()=>{console.error('Router UI verification timed out',errors);app.exit(1)},50000);
