import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {playCue} from './feedback';
export function AppFeedback(){
 const [tip,setTip]=useState<{text:string;anchor:HTMLElement;host:HTMLElement}|null>(null),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const hide=()=>{clearTimeout(timer);setTip(null)};
 const prepare=(root:ParentNode)=>root.querySelectorAll<HTMLElement>('[title]').forEach(el=>{const title=el.getAttribute('title');if(title){el.dataset.tooltip=title;el.removeAttribute('title')}});
 prepare(document);const observer=new MutationObserver(()=>prepare(document));observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['title']});
 const show=(event:Event)=>{const target=event.target as Element;const anchor=target.closest<HTMLElement>('[data-tooltip],button[aria-label],a[aria-label]');if(!anchor||!anchor.isConnected){hide();return}const text=anchor.dataset.tooltip||anchor.getAttribute('aria-label');if(!text)return;hide();timer=setTimeout(()=>{if(anchor.isConnected)setTip({text,anchor,host:anchor.closest('dialog[open]')||document.body})},event.type==='focusin'?150:450)};
 const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')hide()};document.addEventListener('pointerover',show);document.addEventListener('pointerout',hide);document.addEventListener('focusin',show);document.addEventListener('focusout',hide);document.addEventListener('pointerdown',hide);document.addEventListener('keydown',escape);window.addEventListener('scroll',hide,true);window.addEventListener('resize',hide);
 return()=>{hide();observer.disconnect();document.removeEventListener('pointerover',show);document.removeEventListener('pointerout',hide);document.removeEventListener('focusin',show);document.removeEventListener('focusout',hide);document.removeEventListener('pointerdown',hide);document.removeEventListener('keydown',escape);window.removeEventListener('scroll',hide,true);window.removeEventListener('resize',hide)}},[]);
 useLayoutEffect(()=>{if(!tip||!ref.current)return;const anchor=tip.anchor,b=anchor.getBoundingClientRect(),r=ref.current.getBoundingClientRect();ref.current.style.left=Math.max(8,Math.min(innerWidth-r.width-8,b.left+b.width/2-r.width/2))+'px';ref.current.style.top=(b.bottom+r.height+14<innerHeight?b.bottom+9:Math.max(8,b.top-r.height-9))+'px';const previous=anchor.getAttribute('aria-describedby');anchor.setAttribute('aria-describedby',[(previous||''),'orvio-tooltip'].filter(Boolean).join(' '));return()=>{if(previous)anchor.setAttribute('aria-describedby',previous);else anchor.removeAttribute('aria-describedby')}},[tip]);
 useEffect(()=>{const api=(window as any).studio;if(!api)return;let downloads:Map<string,string>|null=null,active=false,ready=false;let phase='';
 const a=api.onDownloads?.((items:any[])=>{if(downloads){if(items.some(i=>downloads!.get(i.id)==='active'&&i.status==='failed'))void playCue('error');else if(items.some(i=>downloads!.get(i.id)==='active'&&i.status==='completed'))void playCue('complete')}downloads=new Map(items.map(i=>[i.id,i.status]))});
 const b=api.onLocal?.((s:any)=>{if(ready&&active&&!s.active&&s.assets?.[0]?.id!==asset){void playCue('success')}active=!!s.active;asset=s.assets?.[0]?.id;ready=true});let asset:string|undefined;
 const c=api.onUpdate?.((s:any)=>{if(['manual','ready'].includes(s.phase)&&phase!==s.phase)void playCue('update');phase=s.phase});return()=>{a?.();b?.();c?.()}},[]);
 return tip?createPortal(<div ref={ref} id="orvio-tooltip" role="tooltip" className="pointer-events-none fixed z-[9999] max-w-[min(320px,calc(100vw-16px))] rounded-xl border border-white/10 bg-[#202936] px-3.5 py-2.5 text-[10px] leading-5 text-white shadow-xl [overflow-wrap:anywhere]">{tip.text}</div>,tip.host):null;
}
