import {useState} from 'react';
import {Icon} from './icons';
import type {Workspace} from './Connected';
export function AssistantModelPicker({workspace,value,onChange,disabled}:{workspace:Workspace;value:string;onChange:(value:string)=>void;disabled:boolean}){
 const [open,setOpen]=useState(false),[models,setModels]=useState<{id:string;name:string;group:string}[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const refresh=async()=>{setLoading(true);setError('');const api=(window as any).studio;try{const results=await Promise.allSettled([api.modelHub(),workspace.ai.provider!=='local'?api.listModels(workspace.ai):Promise.resolve([])]);const local=results[0].status==='fulfilled'?results[0].value.models.filter((m:any)=>m.kind==='chat'&&m.installed).map((m:any)=>({id:'local:'+m.id,name:m.name,group:'On this device'})):[];const remote=results[1].status==='fulfilled'?results[1].value.map((id:string)=>({id:'provider:'+id,name:id,group:workspace.ai.provider})):[];setModels([...local,...remote]);if(results.some(r=>r.status==='rejected'))setError('Some models could not be loaded. Check your provider in Settings and retry.')}catch{setError('Open the desktop app to load models.')}finally{setLoading(false)}};
 const selected=models.find(m=>m.id===value)?.name||value.replace(/^(local|provider):/,'')||workspace.ai.model||'Choose model';
 return <div className="relative min-w-0 flex-1"><button disabled={disabled} aria-label="Choose assistant model" aria-expanded={open} className="flex max-w-full items-center gap-2 rounded-full px-3 py-2 text-[10px] hover:bg-[var(--hover)]" onClick={()=>{setOpen(!open);if(!open)void refresh()}}><span className="truncate">{selected}</span><Icon name="arrow" size={13}/></button>{open&&<><button className="fixed inset-0 z-30 cursor-default" aria-label="Close model menu" onClick={()=>setOpen(false)}/><div role="dialog" aria-label="Assistant models" className="absolute left-0 top-full z-40 mt-2 w-[min(340px,75vw)] rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-3 shadow-xl"><input autoFocus aria-label="Search models" placeholder="Search models…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="mt-2 max-h-72 overflow-y-auto"><button onClick={()=>{onChange('');setOpen(false)}} className="block w-full rounded-xl p-3 text-left text-[10px] hover:bg-[var(--hover)]">Use default · {workspace.ai.model||'Not configured'}</button>{models.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())).map(m=><button key={m.id} aria-pressed={value===m.id} onClick={()=>{onChange(m.id);setOpen(false)}} className="block w-full rounded-xl p-3 text-left hover:bg-[var(--hover)]"><span className="block break-words text-[10px]">{m.name}</span><span className="text-[8px] text-[var(--muted)]">{m.group}</span></button>)}</div>{loading&&<p role="status" className="p-3 text-[10px]">Loading models…</p>}{error&&<p role="alert" className="p-3 text-[10px] text-red-500">{error}</p>}<button disabled={loading} onClick={()=>void refresh()} className="p-3 text-[10px] text-[var(--accent)]">Refresh models</button></div></>}</div>
}
