import {playCue,captureSound} from './feedback';
import {useEffect,useRef,useState} from 'react';
import {Icon} from './icons';
import {bridge,friendlyError} from './Connected';
import {DownloadButton,useDownloads} from './Downloads';
import languages from './whisper-languages.json';
const small='rounded-full px-3 py-2 text-[10px] hover:bg-[var(--hover)] disabled:opacity-40';
export function useChatVoice({onText,onError,visible=true}:{onText:(text:string)=>void;onError:(text:string)=>void;visible?:boolean}){
 const [models,setModels]=useState<any[]>([]),[model,setModel]=useState(()=>localStorage.getItem('orvio.chat.asr')||'whisper'),[voice,setVoice]=useState(()=>localStorage.getItem('orvio.chat.voice')||''),[language,setLanguage]=useState(()=>localStorage.getItem('orvio.chat.language')||'auto'),[open,setOpen]=useState(false),[recording,setRecording]=useState(false),[working,setWorking]=useState(false),[speaking,setSpeaking]=useState(false),[autoSpeak,setAutoSpeak]=useState(()=>localStorage.getItem('orvio.chat.autoSpeak')==='true');
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),session=useRef(0),audio=useRef<HTMLAudioElement|null>(null),audioURL=useRef(''),occupied=useRef(false),downloads=useDownloads();
 useEffect(()=>{const api=(window as any).studio;if(!api)return;const update=(s:any)=>setModels(s.models||[]);api.localState().then(update).catch(()=>{});return api.onLocal(update)},[]);
 const voices=models.filter(m=>m.engine==='piper'),speechModels=models.filter(m=>m.engine==='whisper');
 const selectedVoice=voices.find(m=>m.id===voice)||voices.find(m=>m.installed)||voices[0];const selectedModel=speechModels.find(m=>m.id===model);
 useEffect(()=>{localStorage.setItem('orvio.chat.asr',model);localStorage.setItem('orvio.chat.voice',voice);localStorage.setItem('orvio.chat.language',language);localStorage.setItem('orvio.chat.autoSpeak',String(autoSpeak))},[model,voice,language,autoSpeak]);
 function releaseMic(){captureSound(false);if(timer.current)clearTimeout(timer.current);timer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;void (window as any).studio?.chatMic(false).catch(()=>{});setRecording(false)}
 function stopAudio(){audio.current?.pause();audio.current=null;if(audioURL.current)URL.revokeObjectURL(audioURL.current);audioURL.current='';setSpeaking(false)}
 function cancel(){session.current++;if(recorder.current){recorder.current.onstop=null;if(recorder.current.state==='recording')recorder.current.stop();recorder.current=null;}releaseMic();stopAudio();setWorking(false);occupied.current=false;}
 useEffect(()=>{if(!visible)cancel();return()=>cancel()},[visible]);
 async function speak(text:string){if(occupied.current)return;cancel();if(!selectedVoice?.installed){setOpen(true);onError('Choose and download a voice to read aloud.');return;}const epoch=++session.current;occupied.current=true;setWorking(true);onError('');try{const bytes=await bridge().chatSpeak({text:text.slice(0,4000),model:selectedVoice.id});if(epoch!==session.current)return;await bridge().chatMic(true);if(epoch!==session.current){await bridge().chatMic(false);return;}const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'audio/wav'}));audioURL.current=url;const sound=new Audio(url);audio.current=sound;setWorking(false);setSpeaking(true);sound.onended=()=>{stopAudio();occupied.current=false;void bridge().chatMic(false)};sound.onerror=()=>{cancel();onError('Audio playback failed. Check your output device.')};await sound.play();}catch(e){if(epoch===session.current){cancel();onError(friendlyError(e))}}finally{if(epoch===session.current){setWorking(false);if(!audio.current)occupied.current=false}}}
 async function microphone(){if(recording){recorder.current?.stop();return;}if(occupied.current)return;if(!selectedModel?.installed){setOpen(true);onError('Download a transcription model here to use your microphone.');return;}cancel();const epoch=++session.current;occupied.current=true;onError('');try{await bridge().chatMic(true);const input=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(epoch!==session.current){input.getTracks().forEach(t=>t.stop());return;}stream.current=input;const r=new MediaRecorder(input,{mimeType:'audio/webm',audioBitsPerSecond:64000});recorder.current=r;const chunks:Blob[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onerror=()=>{cancel();onError('The microphone stopped unexpectedly. Please try again.')};r.onstop=async()=>{releaseMic();void playCue('stop');if(epoch!==session.current)return;setWorking(true);try{const bytes=await new Blob(chunks,{type:'audio/webm'}).arrayBuffer();const result=await bridge().chatTranscribe({bytes,model,language});if(epoch!==session.current)return;const text=result.segments.map((s:any)=>s.text).join(' ').trim();if(text)onText(text);else onError('No speech detected. Try again closer to your microphone.');}catch(e){if(epoch===session.current)onError(friendlyError(e))}finally{if(epoch===session.current){setWorking(false);occupied.current=false}}};await playCue('listen');if(epoch!==session.current)return;captureSound(true);r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},60000);}catch(e){if(epoch===session.current){cancel();onError(friendlyError(e))}}}
 const settings=open&&<section className="absolute bottom-full right-0 z-30 mb-3 max-h-[65vh] w-[min(360px,80vw)] overflow-y-auto rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-xl" aria-label="Assistant voice settings"><div className="mb-4 flex items-center justify-between"><strong className="text-xs">Voice & transcription</strong><button type="button" className={small} aria-label="Close voice settings" onClick={()=>setOpen(false)}><Icon name="close" size={16}/></button></div><label className="!text-[10px]">Transcription model<select className="!mt-2 !text-[10px]" value={model} onChange={e=>setModel(e.target.value)} disabled={recording||working}>{speechModels.map(m=><option key={m.id} value={m.id}>{m.name}{m.installed?'':' · download'}</option>)}</select></label><p className="my-3 text-[9px] leading-5 text-[var(--muted)]">Tiny is fastest on lighter PCs. Small favors accuracy; Turbo suits stronger devices. Audio is transcribed on your computer.</p>{selectedModel&&!selectedModel.installed&&<DownloadButton item={downloads.find(d=>d.modelId===model&&d.status==='active')} onClick={()=>void bridge().localInstall(model).catch((e:any)=>onError(friendlyError(e)))}>Download {selectedModel.name}</DownloadButton>}<label className="mt-4 !text-[10px]">Language<select className="!mt-2 !text-[10px]" value={language} onChange={e=>setLanguage(e.target.value)}><option value="auto">Detect automatically</option>{languages.map(code=><option key={code} value={code}>{new Intl.DisplayNames(['en'],{type:'language'}).of(code)||code}</option>)}</select></label><label className="mt-4 !text-[10px]">Read-aloud voice<select className="!mt-2 !text-[10px]" value={selectedVoice?.id||''} onChange={e=>setVoice(e.target.value)}>{voices.map(m=><option key={m.id} value={m.id}>{m.name}{m.installed?'':' · download'}</option>)}</select></label>{selectedVoice&&!selectedVoice.installed&&<div className="mt-3"><DownloadButton item={downloads.find(d=>d.modelId===selectedVoice.id&&d.status==='active')} onClick={()=>void bridge().localInstall(selectedVoice.id).catch((e:any)=>onError(friendlyError(e)))}>Download voice</DownloadButton></div>}<label className="mt-4 !flex !flex-row !items-center !gap-3 !text-[10px]"><input type="checkbox" className="!w-auto" checked={autoSpeak} onChange={e=>setAutoSpeak(e.target.checked)}/>Read replies aloud</label><p className="mt-3 text-[9px] leading-5 text-[var(--muted)]">Record up to 60 seconds, then review your words before sending. Read-aloud plays up to 4,000 characters.</p></section>;
 return {settings,openSettings:()=>setOpen(v=>!v),recording,working,speaking,autoSpeak,speak,microphone,cancel};
}
