import {LocalStudio} from './LocalStudio';
import {useEffect,useState,type FormEvent} from 'react';
import {Icon} from './icons';
import {bridge,friendlyError} from './Connected';

export type GeneratedImage={id:string;name:string;model:string;seed:number;size:number;prompt:string;preview:string};
export function ImageStudio({onUse}:{onUse:(image:GeneratedImage)=>void}){
 const [port,setPort]=useState(8188),[models,setModels]=useState<string[]>([]),[model,setModel]=useState(''),[prompt,setPrompt]=useState(''),[negative,setNegative]=useState(''),[size,setSize]=useState(512),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[image,setImage]=useState<GeneratedImage|null>(null);
 const load=async()=>{setLoading(true);setError('');try{const list:string[]=await bridge().listImageModels({port});setModels(list);setModel(current=>list.includes(current)?current:list[0]||'');if(!list.length)setError('ComfyUI is connected, but no checkpoint models are installed.')}catch(e){setModels([]);setError(friendlyError(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{setImage(await bridge().generateImage({port,model,prompt,negative,size}))}catch(e){setError(friendlyError(e))}finally{setBusy(false)}};
 return <div className="creative-layout"><section className="panel creative-editor"><div className="creative-heading"><span className="creative-icon"><Icon name="image" size={24}/></span><div><span className="mini-label">ON YOUR COMPUTER</span><h2>Image Studio</h2></div></div><p>Use an installed ComfyUI checkpoint to make a new image. Generation runs locally; it may take a few minutes on smaller computers.</p><form onSubmit={submit}><label>ComfyUI port<div className="inline-control"><input type="number" min="1024" max="65535" value={port} onChange={e=>setPort(Number(e.target.value))}/><button className="secondary" type="button" disabled={loading} onClick={()=>void load()}>{loading?'Checking…':'Connect & refresh'}</button></div></label><label>Installed checkpoint<select value={model} onChange={e=>setModel(e.target.value)} required><option value="">{loading?'Finding models…':'Choose an installed model'}</option>{models.map(name=><option value={name} key={name}>{name}</option>)}</select></label><label>Describe your image<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={3000} placeholder="A vivid product photo on a warm studio backdrop…" required/></label><label>Things to avoid<input value={negative} onChange={e=>setNegative(e.target.value)} maxLength={1000} placeholder="Optional"/></label><label>Resolution<select value={size} onChange={e=>setSize(Number(e.target.value))}><option value={512}>512 × 512 · faster</option><option value={768}>768 × 768</option><option value={1024}>1024 × 1024 · more memory</option></select></label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary" disabled={busy||!model||!prompt.trim()}>{busy?'Generating image…':'Generate image'}<Icon name="sparkles" size={16}/></button></form></section><section className="panel creative-result"><span className="mini-label">YOUR RESULT</span>{image?<><img src={image.preview} alt={image.prompt} className="generated-preview"/><div className="generated-meta"><b>{image.model}</b><span>Seed {image.seed} · {image.size} × {image.size}</span></div><button className="primary" onClick={()=>onUse(image)}>Use in a post <Icon name="arrow" size={16}/></button></>:<div className="creative-placeholder"><Icon name="image" size={31}/><h3>Your image will appear here</h3><p>Start ComfyUI, choose a checkpoint and describe what you want to make.</p></div>}</section></div>
}

export function VideoDownloader(_props:{accounts:{id:string;kind:'instagram'|'facebook';username:string}[]}){return <LocalStudio mode="Downloader"/>}
