import {SpatialStudio} from './SpatialStudio';
import {useEffect,useRef,useState} from 'react';
import {bridge,friendlyError} from './Connected';
import {DownloadButton,useDownloads} from './Downloads';
import {useModelHub,useCreativeAssets,type Model,type LocalCreation} from './model-data';
import {ModelArtwork} from './ModelArtwork';
import rawSettings from '../runtime/creative-settings.json';
import './creative-studio.css';
type Profile={resolutions:{label:string;width:number;height:number}[];steps:{min:number;max:number;default:number};fixedSteps:boolean;guidance:{min:number;max:number;default:number};negativePrompt:boolean;frames:number[];fps:number[];samplers:string[]};
type Recipe={id:string;name:string;description:string;model:string;prompt:string;style:string;resolution?:number;negativePrompt?:string;steps?:number;guidance?:number;frames?:number;fps?:number;sampler?:string;seed?:string};
const settings=rawSettings as {profiles:Record<string,Profile>;styles:{id:string;name:string;prompt:string}[];workflows:Recipe[]};
const inspiration='A sculptural terracotta arch beside a turquoise pool in a quiet desert, afternoon light';
function storedRecipes():Recipe[]{try{const saved=JSON.parse(localStorage.getItem('orvio.creative.workflows')||'[]');return Array.isArray(saved)?saved.filter((r:any)=>r&&typeof r.id==='string'&&typeof r.model==='string'&&typeof r.name==='string'&&typeof r.description==='string'&&typeof r.prompt==='string').slice(0,30):[]}catch{return []}}
function ImageVideoStudio({initialKind='image',onUse}:{initialKind?:'image'|'video';onUse:(asset:LocalCreation)=>void}){
 const {hub,error,setError}=useModelHub(),assets=useCreativeAssets(),downloads=useDownloads();
 const [kind,setKind]=useState(initialKind),[tab,setTab]=useState<'create'|'workflows'|'gallery'>('create'),[modelId,setModelId]=useState(''),[prompt,setPrompt]=useState(''),[negative,setNegative]=useState(''),[style,setStyle]=useState('none'),[resolution,setResolution]=useState(0),[steps,setSteps]=useState(20),[guidance,setGuidance]=useState(7.5),[frames,setFrames]=useState(16),[fps,setFps]=useState(8),[seed,setSeed]=useState(''),[sampler,setSampler]=useState('default'),[batch,setBatch]=useState(1),[running,setRunning]=useState(false),[batchIndex,setBatchIndex]=useState(0),[result,setResult]=useState<LocalCreation|null>(null),[recipes,setRecipes]=useState(storedRecipes),[recipeName,setRecipeName]=useState(''),[notice,setNotice]=useState('');
 const stop=useRef(false),fileInput=useRef<HTMLInputElement>(null),pendingRecipe=useRef<Recipe|null>(null);
 const models=hub.models.filter(m=>m.kind===kind&&m.parameterProfile),model=models.find(m=>m.id===modelId),profile=model?settings.profiles[model.parameterProfile!]:undefined;
 useEffect(()=>setKind(initialKind),[initialKind]);
 useEffect(()=>{if(models.length&&!models.some(m=>m.id===modelId)){const saved=localStorage.getItem('orvio.model.'+kind);setModelId(models.find(m=>m.id===saved)?.id||models.find(m=>m.installed)?.id||models[0].id)}},[kind,models.map(m=>m.id).join(','),modelId]);
 useEffect(()=>{if(!model||!profile)return;const recipe=pendingRecipe.current?.model===model.id?pendingRecipe.current:null;pendingRecipe.current=null;
 setResolution(recipe?.resolution!==undefined&&profile.resolutions[recipe.resolution]?recipe.resolution:0);setSteps(profile.fixedSteps?model.steps||4:Math.min(profile.steps.max,Math.max(profile.steps.min,recipe?.steps||model.steps||profile.steps.default)));setGuidance(Math.min(profile.guidance.max,Math.max(profile.guidance.min,recipe?.guidance??model.guidance??profile.guidance.default)));setFrames(profile.frames.includes(recipe?.frames||0)?recipe!.frames!:model.frames||16);setFps(profile.fps.includes(recipe?.fps||0)?recipe!.fps!:model.fps||8);setSampler(profile.samplers.includes(recipe?.sampler||'')?recipe!.sampler!:'default');setNegative(profile.negativePrompt?recipe?.negativePrompt||'':'');localStorage.setItem('orvio.model.'+kind,model.id);
 },[modelId,kind]);
 useEffect(()=>{try{localStorage.setItem('orvio.creative.workflows',JSON.stringify(recipes))}catch{setError('Workflow storage is full. Export your workflow to keep it.')}},[recipes]);
 useEffect(()=>()=>{stop.current=true},[]);
 const busy=running||!!hub.benchmarking||!!hub.active&&!/download/i.test(hub.active.name);
 async function run(fn:()=>Promise<unknown>){setError('');try{await fn()}catch(e){setError(friendlyError(e))}}
 function recipe():Recipe{return {id:crypto.randomUUID(),name:recipeName.trim()||'My '+kind+' workflow',description:'Saved studio settings',model:modelId,prompt,negativePrompt:negative,style,resolution,steps,guidance,frames,fps,sampler,seed}}
 function applyRecipe(value:Recipe){const next=hub.models.find(m=>m.id===value.model&&m.parameterProfile);if(!next){setError('This workflow needs a model that is not in this library.');return}pendingRecipe.current=value;setKind(next.kind as 'image'|'video');setModelId(next.id);setPrompt(String(value.prompt||'').slice(0,2000));setStyle(settings.styles.some(s=>s.id===value.style)?value.style:'none');setSeed(String(value.seed??''));setTab('create');setNotice('Workflow loaded. Review settings, then generate.');
 if(next.id===modelId){const p=settings.profiles[next.parameterProfile!];setResolution(p.resolutions[value.resolution||0]?value.resolution||0:0);setSteps(p.fixedSteps?next.steps||4:Math.max(p.steps.min,Math.min(p.steps.max,value.steps||next.steps||p.steps.default)));setGuidance(Math.max(p.guidance.min,Math.min(p.guidance.max,value.guidance??next.guidance??p.guidance.default)));setNegative(p.negativePrompt?value.negativePrompt||'':'');setFrames(p.frames.includes(value.frames||0)?value.frames!:next.frames||16);setFps(p.fps.includes(value.fps||0)?value.fps!:next.fps||8);setSampler(p.samplers.includes(value.sampler||'')?value.sampler!:'default');pendingRecipe.current=null;}}
 function exportRecipe(){const blob=new Blob([JSON.stringify({format:'orvio-workflow',version:1,recipe:recipe()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='orvio-workflow.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function importRecipe(file:File){if(file.size>64000)throw Error('Choose an Orvio workflow under 64 KB.');const value=JSON.parse(await file.text());if(value.format!=='orvio-workflow'||value.version!==1||!value.recipe||typeof value.recipe.model!=='string'||typeof value.recipe.prompt!=='string')throw Error('Choose an Orvio workflow JSON file. ComfyUI node graphs are not supported by this runner.');applyRecipe(value.recipe)}
 async function generate(){if(!model||!profile||running)return;setError('');setNotice('');stop.current=false;setRunning(true);const chosen=profile.resolutions[resolution]||profile.resolutions[0];const request={model:model.id,prompt,negativePrompt:profile.negativePrompt&&guidance>1?negative:'',style,width:chosen.width,height:chosen.height,steps,guidance,frames,fps,sampler};try{for(let i=0;i<batch;i++){if(stop.current)break;setBatchIndex(i+1);const asset=await bridge().generateLocal({...request,seed:seed===''?undefined:(Number(seed)+i)%4294967296});setResult(asset)}if(!stop.current)setNotice('Generation saved to your gallery.')}catch(e){setError(stop.current?'Generation cancelled. Completed results remain in your gallery.':friendlyError(e))}finally{setRunning(false)}}
 const download=downloads.find(d=>d.modelId===modelId&&d.status==='active');const matching=assets.filter(a=>a.kind===kind);const preview=(result?.kind===kind?result:null)||assets.find(a=>a.modelId===modelId||a.model===model?.name);
 return <div className="creation-studio">
 <div className="creation-toolbar"><div className="creation-tabs" role="tablist" aria-label="Studio views">{(['create','workflows','gallery'] as const).map(value=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{value==='create'?'Create':value==='workflows'?'Workflow apps':'Gallery'}</button>)}</div><div className="creation-toggle" role="group" aria-label="Generation type">{(['image','video'] as const).map(value=><button key={value} aria-pressed={kind===value} disabled={running} onClick={()=>{setKind(value);setResult(null)}}>{value==='image'?'Image':'Video'}</button>)}</div></div>
 {error&&<p role="alert" className="error-message">{error}</p>}{notice&&<p role="status" className="creation-notice">{notice}</p>}
 {tab==='create'&&<div className="creation-layout"><section className="creation-controls"><div className="creation-section-title"><h2>Create an {kind==='image'?'image':'animation'}</h2><span>Local generation</span></div>
 <label>Model<select aria-label="Creative model" value={modelId} disabled={running} onChange={e=>{setModelId(e.target.value);setResult(null)}}>{!models.length&&<option value="">Loading models…</option>}{models.map(m=><option key={m.id} value={m.id}>{m.name}{m.installed?'':' · download'}</option>)}</select></label>
 {model&&<div className="creation-model"><ModelArtwork model={model} assets={assets}/><div><strong>{model.name}</strong><p>{model.size} · {model.ramGB} GB RAM</p><small>{model.unsupported||model.recommendation?.label}</small></div></div>}
 {model&&!model.installed&&<div className="creation-install"><DownloadButton item={download} disabled={!!model.unsupported} onClick={()=>void run(()=>bridge().installModel(model.id))}>Download model · {model.size}</DownloadButton><p>{model.recommendation?.detail}</p></div>}
 <label>Prompt<textarea aria-label="Generation prompt" rows={4} maxLength={2000} value={prompt} disabled={running} onChange={e=>setPrompt(e.target.value)} placeholder={kind==='image'?'Describe the subject, setting and light…':'Describe a scene and simple movement…'}/></label>
 <div className="creation-two"><label>Style<select value={style} disabled={running} onChange={e=>setStyle(e.target.value)}>{settings.styles.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Aspect ratio<select aria-label="Aspect ratio" value={resolution} disabled={running||!profile} onChange={e=>setResolution(Number(e.target.value))}>{profile?.resolutions.map((r,i)=><option key={i} value={i}>{r.label} · {r.width} × {r.height}</option>)}</select></label></div>
 {profile?.negativePrompt&&guidance>1?<label>Negative prompt<textarea aria-label="Negative prompt" rows={2} maxLength={1500} value={negative} disabled={running} onChange={e=>setNegative(e.target.value)} placeholder="What should the model avoid?"/></label>:<p className="creation-help">This model’s guidance setting does not use a negative prompt.</p>}
 <details className="creation-advanced"><summary>Generation settings</summary><div className="creation-two"><label>Steps<input aria-label="Inference steps" type="number" disabled={running||profile?.fixedSteps} min={profile?.steps.min} max={profile?.steps.max} value={steps} onChange={e=>setSteps(Number(e.target.value))}/></label><label>Guidance<input aria-label="Guidance" type="number" step="0.5" min={profile?.guidance.min} max={profile?.guidance.max} disabled={running||profile?.guidance.min===profile?.guidance.max} value={guidance} onChange={e=>setGuidance(Number(e.target.value))}/></label></div>{profile?.fixedSteps&&<p className="creation-help">Step count is fixed to this Lightning checkpoint.</p>}
 {kind==='video'&&<div className="creation-two"><label>Frames<select value={frames} disabled={running} onChange={e=>setFrames(Number(e.target.value))}>{profile?.frames.map(n=><option key={n}>{n}</option>)}</select></label><label>Playback FPS<select value={fps} disabled={running} onChange={e=>setFps(Number(e.target.value))}>{profile?.fps.map(n=><option key={n}>{n}</option>)}</select></label><p className="creation-help">{(frames/fps).toFixed(1)} seconds · FPS changes playback speed.</p></div>}
 <div className="creation-two"><label>Seed<input aria-label="Generation seed" type="number" min="0" max="4294967295" placeholder="Random" value={seed} disabled={running} onChange={e=>setSeed(e.target.value)}/></label><label>Variations<select value={batch} disabled={running} onChange={e=>setBatch(Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label></div>{profile&&profile.samplers.length>1&&<label>Sampler<select value={sampler} disabled={running} onChange={e=>setSampler(e.target.value)}>{profile.samplers.map(s=><option key={s} value={s}>{s==='default'?'Model default':s==='dpm'?'DPM Solver':'Euler'}</option>)}</select></label>}<p className="creation-help">Styles add words to your prompt. Variations run one at a time to limit memory use.</p></details>
 <button className="primary creation-generate" disabled={busy||!model?.installed||!prompt.trim()||!!model?.unsupported} onClick={()=>void generate()}>{running?`Generating ${batchIndex} of ${batch}…`:!model?.installed?'Download model to generate':`Generate ${kind}`}</button>
 {running?<div className="creation-progress" role="status"><progress/><p>{hub.active?.message||'Starting generation…'}</p><button className="secondary" onClick={()=>{stop.current=true;void run(()=>bridge().localCancel())}}>Cancel generation</button></div>:hub.active&&!/download/i.test(hub.active.name)&&<p className="creation-help">Another local task: {hub.active.message}</p>}
 <details className="creation-advanced"><summary>Save this setup as a workflow app</summary><label>Workflow name<input maxLength={60} value={recipeName} onChange={e=>setRecipeName(e.target.value)} placeholder="My creative workflow"/></label><div className="creation-actions"><button className="secondary" disabled={!model||!recipeName.trim()||recipes.length>=30} onClick={()=>{setRecipes(list=>[recipe(),...list]);setNotice('Workflow saved. Find it in Workflow apps.')}}>Save workflow</button><button className="secondary" disabled={!model} onClick={exportRecipe}>Export JSON</button></div></details>
 </section><section className="creation-output"><div className="creation-section-title"><h2>{preview?'Your output':'A starting point for your imagination'}</h2><span>{preview?preview.kind:'Inspiration'}</span></div>{preview?<><div className="creation-preview">{preview.kind==='video'?<video controls loop preload="metadata" src={preview.preview}/>:<img src={preview.preview} alt={preview.prompt}/>}</div><div className="creation-output-info"><strong>{preview.model}</strong><span>{preview.width} × {preview.height} · Seed {preview.seed}</span><p>{preview.prompt}</p></div><div className="creation-actions"><button className="primary" onClick={()=>onUse(preview)}>Use in a post</button><button className="secondary" onClick={()=>void run(()=>bridge().localSave(preview.id))}>Save file</button><button className="secondary" disabled={running} onClick={()=>{setPrompt(preview.prompt);setSeed(String(preview.seed));if(preview.parameters&&preview.modelId)applyRecipe({...preview.parameters,id:'reuse',name:'Previous result',description:'',model:preview.modelId,prompt:preview.prompt,style:preview.parameters.style||'none',resolution:settings.profiles[hub.models.find(m=>m.id===preview.modelId)?.parameterProfile||'image'].resolutions.findIndex(r=>r.width===preview.width&&r.height===preview.height),seed:String(preview.seed)})}}>Reuse settings</button></div></>:<><img className="creation-inspiration" src="./studio-inspiration.png" alt="Terracotta architecture beside a turquoise desert pool"/><p className="creation-help">AI-generated inspiration artwork. This is not an output sample from the selected model.</p><button className="secondary" onClick={()=>setPrompt(inspiration)}>Try this prompt</button><div className="creation-pipeline"><span>Prompt</span><i>→</i><span>Model</span><i>→</i><span>Settings</span><i>→</i><span>Output</span></div></>}
 {model&&<p className="creation-help">{model.description} <a href={model.url} target="_blank" rel="noreferrer">Model card & license ↗</a></p>}
 {matching.length>0&&<div className="creation-strip">{matching.slice(0,6).map(a=><button aria-label={'Preview '+a.title} key={a.id} onClick={()=>setResult(a)}>{a.kind==='image'?<img loading="lazy" src={a.preview} alt={a.prompt}/>:<span>▶ {a.title}</span>}</button>)}</div>}
 </section></div>}
 {tab==='workflows'&&<section><div className="creation-workflow-heading"><div><h2>Small apps for repeatable ideas.</h2><p>Choose a workflow, customize its inputs, then generate. These use Orvio’s local pipelines.</p></div><button className="secondary" onClick={()=>fileInput.current?.click()}>Import workflow</button><input hidden ref={fileInput} type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>importRecipe(file));e.target.value=''}}/></div><div className="creation-workflows">{[...recipes,...settings.workflows].map(w=>{const m=hub.models.find(m=>m.id===w.model);return <article key={w.id}>{m&&<ModelArtwork model={m} assets={assets}/>}<div className="creation-workflow-body"><span>{m?.kind||'Workflow'} · {m?.installed?'Ready':'Download required'}</span><h3>{w.name}</h3><p>{w.description}</p><div className="creation-pipeline"><span>Prompt</span><i>→</i><span>{m?.name||w.model}</span><i>→</i><span>Output</span></div><button className="primary" disabled={running} onClick={()=>applyRecipe(w)}>Open workflow</button>{recipes.some(r=>r.id===w.id)&&<button className="text-button" onClick={()=>setRecipes(list=>list.filter(r=>r.id!==w.id))}>Remove saved workflow</button>}</div></article>})}</div></section>}
 {tab==='gallery'&&<section><div className="creation-workflow-heading"><div><h2>Your {kind==='image'?'images':'videos'}</h2><p>Actual generations saved on this computer.</p></div><span>{matching.length} results</span></div>{matching.length?<div className="creation-gallery">{matching.slice(0,36).map(a=><button key={a.id} onClick={()=>{setResult(a);setTab('create')}}>{a.kind==='image'?<img src={a.preview} alt={a.prompt} loading="lazy"/>:<video src={a.preview} preload="metadata" muted/>}<strong>{a.title}</strong><small>{a.model} · Seed {a.seed}</small></button>)}</div>:<div className="creation-empty"><h3>No generations yet</h3><p>Create your first {kind} or choose a workflow to get started.</p><button className="secondary" onClick={()=>setTab('workflows')}>Explore workflows</button></div>}</section>}
 </div>
}

export function CreativeStudio({initialKind='image',onUse}:{initialKind?:'image'|'video'|'lipsync'|'3d';onUse:(asset:LocalCreation)=>void}){
 const [mode,setMode]=useState(initialKind);useEffect(()=>setMode(initialKind),[initialKind]);
 return <div className="min-w-0 space-y-6"><nav aria-label="Creative studios" className="flex flex-wrap gap-2 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-2">{([{id:'image',label:'Images & motion'},{id:'lipsync',label:'Lip-sync'},{id:'3d',label:'3D objects'}] as const).map(item=><button key={item.id} aria-pressed={item.id===mode||item.id==='image'&&mode==='video'} className={'rounded-xl px-5 py-3 text-xs '+(item.id===mode||item.id==='image'&&mode==='video'?'bg-[var(--accent-soft)] text-[var(--accent)]':'text-[var(--muted)] hover:bg-[var(--hover)]')} onClick={()=>setMode(item.id)}>{item.label}</button>)}</nav>{mode==='lipsync'||mode==='3d'?<SpatialStudio key={mode} kind={mode} onUse={onUse}/>:<ImageVideoStudio initialKind={mode} onUse={onUse}/>}</div>
}
