import {Icon} from './icons';
import type {Workspace} from './Connected';
import type {Draft} from './store';

type Props={workspace:Workspace;drafts:Draft[];name:string;onPublish:()=>void;onConnect:()=>void;onChat:()=>void;onCalendar:()=>void;onIntegrations:()=>void;onDraft:()=>void};
export function Dashboard({workspace,drafts,name,onPublish,onConnect,onChat,onCalendar,onIntegrations,onDraft}:Props){
 const scheduled=workspace.jobs.filter(job=>['queued','creating','processing','publishing'].includes(job.status)).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt));
 const connected=workspace.accounts.length;
 const recent=[...workspace.jobs].sort((a,b)=>b.scheduledAt.localeCompare(a.scheduledAt)).slice(0,4);
 return <div className="dashboard">
  <section className="dashboard-hero"><div><span className="hero-kicker"><i/> YOUR WORKSPACE</span><h2>{name?`Good to see you, ${name}.`:'Make something worth sharing.'}</h2><p>Plan, create and publish from one calm place. Your next step is right here.</p><div className="hero-actions"><button className="primary" onClick={onPublish}><Icon name="plus" size={18}/>Create a post</button><button className="hero-secondary" onClick={onChat}><Icon name="sparkles" size={18}/>Ask the assistant</button></div></div><div className="hero-mark" aria-hidden="true"><img src="./orvio-logo.png" alt=""/></div></section>
  <div className="dashboard-stats"><button onClick={connected?onIntegrations:onConnect}><span className="stat-icon"><Icon name="link"/></span><span><b>{connected}</b><small>Connected accounts</small></span><Icon name="arrow" size={16}/></button><button onClick={onCalendar}><span className="stat-icon"><Icon name="calendar"/></span><span><b>{scheduled.length}</b><small>Posts in queue</small></span><Icon name="arrow" size={16}/></button><button onClick={onDraft}><span className="stat-icon"><Icon name="edit"/></span><span><b>{drafts.length}</b><small>Local drafts</small></span><Icon name="arrow" size={16}/></button></div>
  <div className="dashboard-columns"><section className="dashboard-card"><div className="dashboard-card-head"><div><span className="mini-label">UP NEXT</span><h3>Publishing queue</h3></div><button className="text-button" onClick={onCalendar}>View calendar <Icon name="arrow" size={16}/></button></div>{scheduled.length?<div className="upcoming-list">{scheduled.slice(0,3).map(job=><div className="upcoming-item" key={job.id}><span className="upcoming-date">{new Date(job.scheduledAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><div><b>{job.title||'Untitled post'}</b><small>{new Date(job.scheduledAt).toLocaleString(undefined,{hour:'numeric',minute:'2-digit'})}</small></div><span className="status-pill">Scheduled</span></div>)}</div>:<div className="dashboard-empty"><span><Icon name="calendar" size={25}/></span><b>Nothing scheduled yet</b><p>Prepare a post now or choose a time for later.</p><button className="secondary" onClick={onPublish}>Create a post <Icon name="arrow" size={15}/></button></div>}</section><section className="dashboard-card"><div className="dashboard-card-head"><div><span className="mini-label">QUICK START</span><h3>Your next move</h3></div></div><div className="quick-links"><button onClick={onPublish}><span className="quick-icon"><Icon name="plus"/></span><span><b>Write and publish</b><small>Share to Instagram, Facebook, TikTok or YouTube</small></span><Icon name="arrow" size={16}/></button><button onClick={onChat}><span className="quick-icon"><Icon name="sparkles"/></span><span><b>Create with AI</b><small>Plan a post or ask an agent to prepare one</small></span><Icon name="arrow" size={16}/></button><button onClick={connected?onIntegrations:onConnect}><span className="quick-icon"><Icon name="link"/></span><span><b>{connected?'Manage connections':'Connect an account'}</b><small>Social channels, media and Google Drive</small></span><Icon name="arrow" size={16}/></button></div></section></div>
  {recent.length>0&&<section className="dashboard-card recent-card"><div className="dashboard-card-head"><div><span className="mini-label">RECENT ACTIVITY</span><h3>Your posts</h3></div><button className="text-button" onClick={onCalendar}>See all <Icon name="arrow" size={16}/></button></div><div className="recent-list">{recent.map(job=><div key={job.id}><span className={'recent-dot '+job.status}/><b>{job.title||'Untitled post'}</b><small>{job.status}</small><time>{new Date(job.scheduledAt).toLocaleDateString()}</time></div>)}</div></section>}
 </div>;
}
