import {captureSound} from './feedback';
import {useEffect,useRef,useState} from 'react';
import {Icon} from './icons';
import {pcmWave} from './dictation-audio';
export function Dictation(){
 const api=(window as any).dictation,[status,setStatus]=useState('Getting ready…'),[text,setText]=useState(''),[recording,setRecording]=useState(false),[done,setDone]=useState(false),[level,setLevel]=useState(0),finishRef=useRef(()=>{});
 useEffect(()=>{document.documentElement.style.background='transparent';document.body.style.background='transparent';document.body.style.overflow='hidden';let alive=true,stopping=false,released=false,stream:MediaStream|null=null,context:AudioContext|null=null,node:AudioWorkletNode|null=null,timer:ReturnType<typeof setInterval>|null=null,closeTimer:ReturnType<typeof setTimeout>|null=null,pending:Promise<void>|null=null,flush:()=>void=()=>{};const samples:Float32Array[]=[];let began=0,lastSpeech=0,lastPartial=0;let config:any={};
 const clean=()=>{captureSound(false);if(timer)clearInterval(timer);stream?.getTracks().forEach(t=>t.stop());void context?.close().catch(()=>{})};
 async function finish(){released=true;if(!context||stopping)return;stopping=true;setRecording(false);setStatus('Finishing your words…');if(timer)clearInterval(timer);await new Promise<void>(resolve=>{let settled=false;const complete=()=>{if(!settled){settled=true;resolve()}};flush=complete;node?.port.postMessage('flush');setTimeout(complete,300)});clean();if(!alive)return;if(!samples.length){setStatus('No speech captured.');setDone(true);return}try{if(pending)await pending;const message=await api.finish(pcmWave(samples));if(alive){setStatus(message);setDone(true);if(/Inserted|Paste requested|Edit command applied/.test(message))closeTimer=setTimeout(()=>void api.close(),1400)}}catch(e){if(alive){setStatus((e as Error).message);setDone(true)}}}
 finishRef.current=()=>void finish();const off=api.onFinish(()=>void finish()),notice=api.onNotice((message:string)=>{if(alive)setStatus(message)});
 const init=setTimeout(()=>void(async()=>{try{config=await api.arm();if(!alive)return;if(config.released||released){setStatus('Hold the shortcut while you speak.');setDone(true);return}stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,channelCount:1},video:false});if(!alive||released){clean();if(alive){setDone(true);setStatus('Released before the microphone was ready. Try again.')}return}context=new AudioContext({sampleRate:16000});await context.audioWorklet.addModule(new URL('./dictation-worklet.js',location.href).href);if(!alive||released){clean();setDone(true);setStatus('Hold the shortcut while you speak.');return}node=new AudioWorkletNode(context,'dictation-pcm');const source=context.createMediaStreamSource(stream),silent=context.createGain();silent.gain.value=0;source.connect(node);node.connect(silent);silent.connect(context.destination);node.port.onmessage=e=>{if(e.data==='flushed'){flush();return}const chunk=e.data as Float32Array;samples.push(chunk);let energy=0;for(const value of chunk)energy+=value*value;const rms=Math.sqrt(energy/chunk.length);if(rms>.012)lastSpeech=Date.now();if(alive)setLevel(Math.min(1,rms*12))};await context.resume();captureSound(true);began=Date.now();setRecording(true);setStatus(config.warning|| (config.hold?'Listening · release to insert':'Listening · press your shortcut to finish'));
 timer=setInterval(()=>{const now=Date.now();if(now-began>60000||(!config.hold&&config.autoStop&&lastSpeech&&now-lastSpeech>1600)){void finish();return}if(!config.supportsLive||pending||now-lastPartial<2000||!lastSpeech||!samples.length)return;lastPartial=now;const audio=pcmWave(samples);pending=api.partial(audio).then((result:any)=>{if(!alive||stopping)return;setText(result.text);if(result.liveUnavailable&&config.liveInsert)setStatus(config.hold?'Live preview · release to paste':'Live preview · finish to paste')}).catch(()=>{if(alive&&!stopping)setStatus('Listening · final transcript will follow')}).finally(()=>{pending=null})},200);
 }catch(e){clean();if(alive){setStatus((e as Error).message);setDone(true)}}})(),30);
 return()=>{alive=false;clearTimeout(init);if(closeTimer)clearTimeout(closeTimer);off();notice();clean()};},[]);
 return <div className="flex h-dvh items-end p-2"><div className="w-full rounded-2xl border border-white/10 bg-[#17171d] px-5 py-4 text-white shadow-lg"><div className="flex items-center gap-3"><Icon name="mic" size={19}/><div className="flex h-5 items-center gap-1" aria-hidden="true">{[.5,.9,.7,1,.6].map((n,i)=><i key={i} style={{height:recording?4+level*20*n:4}} className="w-1 rounded bg-violet-400 transition-all"/>)}</div><span role="status" className="flex-1 text-[9px] leading-5">{status}</span>{recording&&<button className="text-[9px]" onClick={()=>finishRef.current()}>Finish</button>}<button aria-label={done?'Close dictation':'Cancel dictation'} onClick={()=>void api.close()}><Icon name="close" size={15}/></button></div>{text&&<p className="mt-3 max-h-14 overflow-auto text-[11px] leading-6 !text-white/90" aria-live="polite">{text}</p>}</div></div>;
}
