import {DownloadThumbnail} from './DownloadThumbnail';
import {useEffect,useState} from 'react';
import {bridge,friendlyError} from './Connected';
import {Icon} from './icons';
import {useDownloads} from './Downloads';
import './download-manager.css';
const bytes=(n=0)=>n>=1024**3?(n/1024**3).toFixed(2)+' GB':n>=1024**2?(n/1024**2).toFixed(1)+' MB':Math.round(n/1024)+' KB';
export function DownloadManager(){
 const items=useDownloads(),[mode,setMode]=useState('video'),[urls,setURLs]=useState(''),[quality,setQuality]=useState('1080'),[rate,setRate]=useState('0'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[images,setImages]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[scanning,setScanning]=useState(false),[session,setSession]=useState(false);
 useEffect(()=>{let live=true;void bridge().localState().then((s:any)=>{if(live)setSession(s.hasSession)}).catch(()=>{});return()=>{live=false}},[]);
 async function run(action:()=>Promise<unknown>){setError('');try{await action()}catch(e){setError(friendlyError(e))}}
 function enqueue(list:string[],image=false){setError('');setNotice('');const unique=[...new Set(list.map(s=>s.trim()).filter(Boolean))];if(!unique.length||unique.length>30){setError('Add between 1 and 30 links per batch.');return}try{for(const value of unique){const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error()}}catch{setError('Each line must contain an HTTP or HTTPS link without credentials.');return}
  setNotice(`${unique.length} download${unique.length===1?'':'s'} added. Progress appears below; you can keep working.`);
  for(const url of unique)void (mode==='video'||mode==='audio'?bridge().localDownload({url,quality:Number(quality),audio:mode==='audio',rate:Number(rate)}):bridge().downloadFile({url,image:mode==='images'||image,rate:Number(rate)})).catch((e:unknown)=>setError(friendlyError(e)));
 }
 const active=items.filter(d=>d.status==='active'),shown=items.filter(d=>(filter==='all'||filter==='active'&&d.status==='active'||filter==='paused'&&['paused','interrupted'].includes(d.status)||filter==='completed'&&d.status==='completed'||filter==='failed'&&['failed','cancelled'].includes(d.status))&&d.title.toLowerCase().includes(query.toLowerCase()));
 return <div className="download-manager"><section className="download-composer"><div className="download-panel-heading"><span className="download-heading-icon"><Icon name="link" size={20}/></span><div><h2>New download</h2><p>Choose a source and add your links.</p></div></div><div className="download-modes" role="group" aria-label="Download type">{[['video','Website video'],['audio','Audio only'],['file','Direct file'],['images','Page images']].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>{setMode(id);setImages([]);setSelected([])}}>{label}</button>)}</div>
 <label>{mode==='images'?'Webpage URL':'Links · one per line'}<textarea aria-label="Download links" value={urls} onChange={e=>setURLs(e.target.value)} rows={4} placeholder={mode==='images'?'https://example.com/gallery':'Paste up to 30 links…'}/></label>
 <div className="download-options">{['video','audio'].includes(mode)&&<label>Output<select aria-label="Download quality" value={quality} disabled={mode==='audio'} onChange={e=>setQuality(e.target.value)}>{[360,480,720,1080,2160].map(n=><option key={n} value={n}>{mode==='audio'?'MP3 audio':n+'p · MP4'}</option>)}</select></label>}<label>Speed limit<select aria-label="Download speed limit" value={rate} onChange={e=>setRate(e.target.value)}>{[['0','Unlimited'],['256','256 KB/s'],['1024','1 MB/s'],['5120','5 MB/s'],['10240','10 MB/s']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className="primary" disabled={!urls.trim()||scanning} onClick={()=>{if(mode==='images'){setScanning(true);void run(async()=>{const found=await bridge().findPageImages(urls.trim());setImages(found);setSelected([]);setNotice(found.length?`${found.length} image links found. Select the images to download.`:'No images found in this page’s HTML. Try a direct image URL in Direct file mode.')}).finally(()=>setScanning(false))}else enqueue(urls.split(/\r?\n/))}}>{scanning?'Finding images…':mode==='images'?'Find images':'Add to queue'}</button></div>
 <p className="download-help">{mode==='images'?'Finds image links exposed in page HTML. Pages that load images only through scripts may need direct image links.':mode==='file'?'Download any file type from a direct HTTP/HTTPS URL. Resume is available when the server supports it.':'Available quality depends on the website. Up to 2 GB per source stream.'}</p>
 {['video','audio'].includes(mode)&&<details><summary>Account access</summary><p className="download-help">Import an exported Netscape cookie file when a supported website requires sign-in. The session stays in memory until cleared or the app closes.</p><button className="secondary" onClick={()=>void run(async()=>{await bridge().localSession(false);const state=await bridge().localState();setSession(state.hasSession)})}>{session?'Replace session file':'Import session file'}</button>{session&&<button className="secondary" onClick={()=>void run(async()=>{await bridge().localSession(true);setSession(false)})}>Clear session</button>}</details>}
 {images.length>0&&<div className="download-image-picker"><div className="download-actions"><button className="secondary" onClick={()=>setSelected(images.slice(0,30))}>Select first 30</button><button className="secondary" onClick={()=>setSelected([])}>Clear selection</button><button className="primary" disabled={!selected.length} onClick={()=>enqueue(selected,true)}>Download {selected.length} images</button></div><div className="download-image-grid">{images.map(url=><label key={url}><input type="checkbox" checked={selected.includes(url)} onChange={e=>setSelected(list=>e.target.checked?[...list,url]:list.filter(u=>u!==url))}/><span title={url}>{new URL(url).pathname.split('/').pop()||new URL(url).hostname}</span><small>{new URL(url).hostname}</small></label>)}</div></div>}
 {error&&<p role="alert" className="error-message">{error}</p>}{notice&&<p role="status" className="download-notice">{notice}</p>}</section>
 <section className="download-list"><div className="download-queue-heading"><div><h2>Download queue <span className="download-count">{items.length}</span></h2><p>{active.length?`${active.length} active or queued`:'All transfers in one place'}</p></div><span className="download-speed"><Icon name="download" size={15}/>{bytes(active.reduce((n,d)=>n+(d.speed||0),0))}/s</span></div><header><div className="download-filters">{['all','active','paused','completed','failed'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f==='active'?'In progress':f==='failed'?'Needs attention':f}</button>)}</div><input aria-label="Search downloads" placeholder="Search downloads…" value={query} onChange={e=>setQuery(e.target.value)}/></header><div className="download-actions download-bulk"><button className="secondary" disabled={!active.some(d=>d.cancellable)} onClick={()=>void run(()=>Promise.all(active.filter(d=>d.cancellable).map(d=>bridge().pauseDownload(d.id))))}>Pause all</button><button className="secondary" disabled={!items.some(d=>d.retryable&&['paused','interrupted'].includes(d.status))} onClick={()=>{for(const d of items.filter(d=>d.retryable&&['paused','interrupted'].includes(d.status)))void run(()=>bridge().retryDownload(d.id))}}>Resume paused</button><button className="secondary" onClick={()=>void run(()=>bridge().clearDownloads())}>Clear history</button></div>
 {shown.map(d=><article className="download-row" key={d.id}><DownloadThumbnail item={d}/><div className="download-file-detail"><div className="download-file-heading"><strong>{d.title}</strong><span>{d.kind} · {d.status}</span></div><p>{d.message}</p>{d.status==='active'&&<progress aria-label={'Progress for '+d.title} max={100} value={d.percent??undefined}/>}<small>{bytes(d.received)}{d.total?` / ${bytes(d.total)}`:''}{d.speed?` · ${bytes(d.speed)}/s`:''}{d.eta?` · ${Math.ceil(d.eta)} seconds remaining`:''}</small></div><div className="download-row-actions">{d.cancellable&&<><button onClick={()=>void run(()=>bridge().pauseDownload(d.id))}>Pause</button><button onClick={()=>void run(()=>bridge().cancelDownload(d.id))}>Cancel</button></>}{d.retryable&&<button onClick={()=>void run(()=>bridge().retryDownload(d.id))}>{['paused','interrupted'].includes(d.status)?'Resume':'Retry'}</button>}{d.status==='completed'&&d.assetId&&<><button onClick={()=>void run(()=>bridge().revealDownload(d.assetId))}>Show in folder</button><button onClick={()=>void run(()=>bridge().localSave(d.assetId))}>Save as…</button></>}</div></article>)}{!shown.length&&<div className="download-empty"><span className="download-empty-icon"><Icon name="download" size={30}/></span><h3>{query?'No matching downloads':'Your queue is clear'}</h3><p>Add your first link to get started. You can keep working while it downloads.</p></div>}
 <footer className="download-queue-note"><Icon name="check" size={14}/><span>Downloads continue as you work. Paused transfers are saved for later.</span></footer></section></div>
}
