import {useEffect,useState} from 'react';
import {bridge,friendlyError} from './Connected';
import {Icon} from './icons';
import type {CaptureAsset} from './RecorderEditor';
export function EditorStock({onUse}:{onUse:(asset:CaptureAsset,background:boolean)=>void}){
 const [provider,setProvider]=useState('pexels'),[configured,setConfigured]=useState<Record<string,boolean>>({}),[key,setKey]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false);
 useEffect(()=>{void bridge().stockState().then(setConfigured).catch((e:unknown)=>setError(friendlyError(e)))},[]);
 async function search(){setBusy(true);setError('');try{setResults(await bridge().stockSearch(provider,query))}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 async function use(item:any,background:boolean){setBusy(true);setError('');try{onUse(await bridge().stockImport(provider,item.id),background)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 const name=provider==='pexels'?'Pexels':'Pixabay';
 return <div className="ed-stock"><div className="ed-choice">{['pexels','pixabay'].map(id=><button disabled={busy} className={provider===id?'active':''} key={id} onClick={()=>{setProvider(id);setResults([]);setKey('');setError('')}}>{id==='pexels'?'Pexels':'Pixabay'}</button>)}</div><button className="ed-link" onClick={()=>void bridge().stockOpen(provider,provider==='pexels'?'https://www.pexels.com':'https://pixabay.com')}>Photos provided by {name} <Icon name="external" size={12}/></button>{(!configured[provider]||settings)&&<><label>{name} API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste your API key"/></label><button className="ed-outline" disabled={!key.trim()||busy} onClick={async()=>{try{setConfigured(await bridge().stockSave(provider,key));setKey('');setSettings(false);setError('')}catch(e){setError(friendlyError(e))}}}><Icon name="lock" size={14}/>Save key securely</button><button className="ed-link" onClick={()=>void bridge().stockOpen(provider,provider==='pexels'?'https://www.pexels.com/api/':'https://pixabay.com/api/docs/')}>Get an API key</button></>}<form onSubmit={e=>{e.preventDefault();void search()}}><label>Search photos<input maxLength={100} placeholder="Nature, studio, city…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="ed-outline" disabled={busy||!configured[provider]||!query.trim()}><Icon name="search" size={15}/>{busy?'Working…':'Search photos'}</button></form>{error&&<p role="alert">{error}</p>}<div className="ed-stock-results">{results.map(item=><article key={item.id}><img src={item.preview} alt={item.title} loading="lazy"/><button className="ed-link" onClick={()=>void bridge().stockOpen(provider,item.page)}>Photo by {item.creator}</button><div><button disabled={busy} onClick={()=>void use(item,false)}>Add layer</button><button disabled={busy} onClick={()=>void use(item,true)}>Backdrop</button></div></article>)}</div>{configured[provider]&&<button className="ed-link" onClick={()=>setSettings(v=>!v)}>Change API key</button>}</div>
}
