import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {bridge,friendlyError} from './Connected';
export default function MeshViewer({id}:{id:string}){
 const host=useRef<HTMLDivElement>(null),actions=useRef({reset:()=>{},wire:()=>{}}),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const element=host.current;if(!element)return;let alive=true,scene:THREE.Scene|undefined,renderer:THREE.WebGLRenderer|undefined,controls:OrbitControls|undefined,observer:ResizeObserver|undefined;
 const dispose=(root:THREE.Object3D)=>root.traverse(node=>{const mesh=node as THREE.Mesh;if(mesh.geometry)mesh.geometry.dispose();const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];materials.filter(Boolean).forEach(material=>{for(const value of Object.values(material))if(value instanceof THREE.Texture)value.dispose();material.dispose()})});
 setLoading(true);setError('');void (async()=>{try{const bytes=await bridge().localMesh(id);const gltf=await new GLTFLoader().parseAsync(new Uint8Array(bytes).buffer,'');if(!alive){dispose(gltf.scene);return}scene=new THREE.Scene();scene.background=new THREE.Color('#eef1f5');const model=gltf.scene;scene.add(model);const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();if(!Number.isFinite(size)||size===0)throw Error('This mesh has no visible geometry.');model.position.sub(center);const camera=new THREE.PerspectiveCamera(40,1,size/1000,size*100);camera.position.set(size*.8,size*.4,size*1.4);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.domElement.setAttribute('aria-label','Generated 3D model. Drag to rotate, scroll to zoom.');renderer.domElement.tabIndex=0;element.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x667085,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(3,5,4);scene.add(light);controls=new OrbitControls(camera,renderer.domElement);controls.minDistance=size*.2;controls.maxDistance=size*8;controls.saveState();const render=()=>{if(alive&&renderer&&scene)renderer.render(scene,camera)};controls.addEventListener('change',render);const resize=()=>{const width=element.clientWidth,height=element.clientHeight;camera.aspect=width/Math.max(1,height);camera.updateProjectionMatrix();renderer!.setSize(width,height);render()};observer=new ResizeObserver(resize);observer.observe(element);actions.current={reset:()=>{controls?.reset();render()},wire:()=>{model.traverse(node=>{const m=node as THREE.Mesh;for(const material of Array.isArray(m.material)?m.material:[m.material])if(material&&'wireframe' in material)(material as THREE.MeshStandardMaterial).wireframe=!(material as THREE.MeshStandardMaterial).wireframe});render()}};resize();setLoading(false)}catch(e){if(alive){setError(friendlyError(e));setLoading(false)}}})();return()=>{alive=false;observer?.disconnect();controls?.dispose();if(scene)dispose(scene);renderer?.dispose();renderer?.domElement.remove();actions.current={reset:()=>{},wire:()=>{}}}},[id]);
 return <div><div className="relative overflow-hidden rounded-2xl bg-[#eef1f5]"><div ref={host} className="h-[380px] w-full max-w-full"/>{(loading||error)&&<p role={error?'alert':'status'} className="absolute inset-x-0 top-1/2 px-6 text-center text-xs text-slate-700">{error||'Loading your 3D preview…'}</p>}</div><div className="mt-3 flex flex-wrap items-center gap-3"><button className="secondary" disabled={loading||!!error} onClick={()=>actions.current.reset()}>Reset view</button><button className="secondary" disabled={loading||!!error} onClick={()=>actions.current.wire()}>Toggle wireframe</button><p className="text-[10px] text-[var(--muted)]">Drag to orbit · scroll to zoom</p></div></div>
}
