import {ExistingModels} from './PCHelper';
import {DownloadButton} from './Downloads';
import {useDownloads} from './download-data';
import {useEffect,useRef,useState,lazy} from 'react';
import {bridge,friendlyError} from './Connected';
import {Icon} from './icons';
import {useModelHub as useHub,useCreativeAssets,type Kind,type Model,type LocalCreation} from './model-data';
export type {LocalCreation} from './model-data';
import {ModelArtwork} from './ModelArtwork';
const UnifiedStudio=lazy(()=>import('./CreativeStudio').then(m=>({default:m.CreativeStudio})));
const softButton='min-w-0 max-w-full whitespace-normal rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-2.5 text-xs font-medium transition hover:bg-[var(--hover)] disabled:opacity-40';
const panel='min-w-0 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5';
function ModelInfo({model:m,onClose,children}:{model:Model;onClose:()=>void;children:React.ReactNode}){
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const element=dialog.current;if(element&&!element.open)element.showModal()},[]);
 return <dialog ref={dialog} aria-labelledby="model-info-title" onClose={onClose} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}} className="fixed inset-0 m-auto max-h-[85dvh] w-[560px] max-w-[calc(100%_-_2rem)] overflow-y-auto rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 text-[var(--text)] backdrop:bg-black/60">
 <header className="flex items-start justify-between gap-4"><h2 id="model-info-title" className="text-lg">{m.name}</h2><button className="icon-button" aria-label="Close model details" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></header>
 <p className="mt-5 text-xs leading-7">{m.description}</p>{m.kind==='image'&&<p className="mt-3 text-xs text-[var(--accent)]">{m.imageInput==='edit'?'Text to image + reference image editing':m.imageInput==='img2img'?'Text to image + image to image':'Text to image'}</p>}
 <dl className="my-5 grid grid-cols-2 gap-4 rounded-xl bg-[var(--bg)] p-4 text-xs"><div><dt className="text-[var(--muted)]">Download</dt><dd className="mt-2">{m.size}</dd></div><div><dt className="text-[var(--muted)]">Memory guidance</dt><dd className="mt-2">{m.ramGB} GB RAM</dd></div><div><dt className="text-[var(--muted)]">Engine</dt><dd className="mt-2">{m.engine}</dd></div><div><dt className="text-[var(--muted)]">Status</dt><dd className="mt-2">{m.installed?'On this device':'Not downloaded'}</dd></div></dl>
 {m.downloadBytes&&<p className="text-[10px] leading-6">{m.downloadBytes.toLocaleString()} bytes across {m.downloadFileCount} files. Verified {m.sizeCheckedAt?.slice(0,10)}.</p>}
 <p className="text-[10px] leading-6 text-[var(--muted)]">{m.sizeNote||'Engine/CUDA setup is additional. Cached files are reused.'}</p>
 <section className="my-5 border-y border-[var(--line)] py-4"><h3 className="text-xs">{m.unsupported||m.recommendation?.label||'Compatibility'}</h3><p className="mt-2 text-xs leading-6">{m.recommendation?.detail}</p>{m.benchmark&&<p className="mt-2 text-xs">Benchmark: {m.benchmark.seconds.toFixed(1)}s including loading{m.benchmark.tokensPerSecond?` · ${m.benchmark.tokensPerSecond.toFixed(1)} tokens/sec`:''}</p>}</section>
 <a href={m.url} target="_blank" rel="noreferrer" className="text-xs text-[var(--accent)] underline">{m.license} · Model source ↗</a>
 <div className="mt-6 flex flex-wrap gap-2">{children}</div></dialog>
}
export function ModelLibrary({onOpen}:{onOpen:(page:'Chat'|'Images'|'Videos'|'Voice'|'Studio',kind?:'voice'|'lipsync'|'3d')=>void}){
 const assets=useCreativeAssets(),downloads=useDownloads(),{hub,error,setError}=useHub();
 const [tab,setTab]=useState<'catalogue'|'device'|'online'>('catalogue'),[kind,setKind]=useState<Kind|'all'>('all'),[query,setQuery]=useState(''),[availability,setAvailability]=useState<'downloaded'|'available'>('available'),[fits,setFits]=useState(false),[notice,setNotice]=useState(''),[info,setInfo]=useState<string|null>(null);
 const [onlineQuery,setOnlineQuery]=useState(''),[online,setOnline]=useState<{repo:string;downloads:number}[]>([]),[searching,setSearching]=useState(false),[remote,setRemote]=useState<{repo:string;license:string;files:{name:string;bytes:number}[]}|null>(null),[file,setFile]=useState(''),[remoteBusy,setRemoteBusy]=useState(false);
 async function run(fn:()=>Promise<unknown>){setError('');try{await fn()}catch(e){setError(friendlyError(e))}}
 const busy=!!hub.active||!!hub.benchmarking,selected=hub.models.find(m=>m.id===info);
 const matchingModels=hub.models.filter(m=>(kind==='all'||m.kind===kind)&&(!fits||m.recommendation?.level==='good')&&(m.name+' '+m.description).toLowerCase().includes(query.toLowerCase()));
 const downloadedCount=matchingModels.filter(m=>m.installed).length,availableCount=matchingModels.length-downloadedCount;
 const models=matchingModels.filter(m=>availability==='downloaded'?m.installed:!m.installed);
 async function useModel(m:Model){if(m.kind==='chat')await bridge().saveAI({provider:'local',model:m.id});else localStorage.setItem('orvio.model.'+m.kind,m.id);setInfo(null);onOpen(m.kind==='lipsync'||m.kind==='3d'||m.kind==='voice'?'Studio':m.kind==='chat'?'Chat':m.kind==='image'?'Images':'Videos',m.kind==='lipsync'||m.kind==='3d'||m.kind==='voice'?m.kind:undefined)}
 return <div className="min-w-0 w-full space-y-5 [overflow-wrap:anywhere]">
 <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Model library</h1><p className="mt-2 text-xs text-[var(--muted)]">Find a model, download it, and start creating.</p></div><button className={softButton} disabled={busy} onClick={()=>void run(()=>bridge().importModel())}>Import GGUF</button></header>
 <nav aria-label="Model library views" className="!flex !flex-row flex-wrap !gap-2 border-b border-[var(--line)] pb-3">{(['catalogue','device','online'] as const).map(value=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)} className={`!w-auto !rounded-xl !px-4 !py-3 !text-xs ${tab===value?'bg-[var(--accent-soft)] text-[var(--accent)]':'hover:bg-[var(--hover)]'}`}>{value==='catalogue'?'Browse models':value==='device'?'On this device':'Search online'}</button>)}</nav>
 {tab!=='online'&&<input className="!w-full" type="search" placeholder={tab==='device'?'Search models on this device…':'Search models by name or capability…'} aria-label="Search models" value={query} onChange={e=>setQuery(e.target.value)}/>}
 <details className={panel+' !py-3'}><summary className="cursor-pointer text-xs font-medium">PC hardware · {hub.hardware.ramGB||'—'} GB RAM</summary>
    <div className="mt-6 grid grid-cols-1 gap-3 md:grid-cols-3">
    <div className="rounded-xl bg-[var(--bg)] p-4"><span className="text-[9px] tracking-wider text-[var(--muted)]">PROCESSOR</span><p className="mt-2 text-[11px] font-medium leading-6">{hub.hardware.cpu||'Detecting processor…'}</p><small className="text-[9px] text-[var(--muted)]">{hub.hardware.threads||'—'} logical cores · {hub.hardware.arch}</small></div>
    <div className="rounded-xl bg-[var(--bg)] p-4"><span className="text-[9px] tracking-wider text-[var(--muted)]">MEMORY</span><p className="mt-2 text-lg font-semibold">{hub.hardware.ramGB||'—'} GB</p><small className="text-[9px] text-[var(--muted)]">{hub.hardware.freeGB??'—'} GB currently free · system RAM</small></div>
    <div className="rounded-xl bg-[var(--bg)] p-4"><span className="text-[9px] tracking-wider text-[var(--muted)]">GRAPHICS</span>{hub.hardware.gpus?.length?hub.hardware.gpus.map((gpu,i)=><div key={i}><p className="mt-2 text-[11px] font-medium leading-6">{gpu.name}</p><small className="text-[9px] text-[var(--muted)]">{gpu.unified?'Shared Apple memory':gpu.vramGB?`${gpu.vramGB} GB dedicated memory`:'Dedicated memory not reported'}</small></div>):<p className="mt-2 text-[11px] leading-6">{hub.hardware.detected?'Graphics details unavailable · CPU remains available':'Detecting graphics…'}</p>}</div>
   </div>

 <button className={softButton+' mt-4'} onClick={()=>void run(()=>bridge().refreshHardware())}>Refresh hardware</button></details>
 {tab==='catalogue'&&<><div className="flex flex-wrap items-center gap-2" aria-label="Model categories">{(['all','chat','image','video','voice','lipsync','3d'] as const).map(k=><button key={k} aria-pressed={kind===k} className={`rounded-lg px-3 py-2 text-xs capitalize ${kind===k?'bg-[var(--accent-soft)] text-[var(--accent)]':'hover:bg-[var(--hover)]'}`} onClick={()=>setKind(k)}>{k==='all'?'All models':k==='chat'?'Text & chat':k==='lipsync'?'Lip-sync':k==='3d'?'3D':k}</button>)}</div><div className="flex flex-wrap items-center gap-3 text-[10px]"><div role="group" aria-label="Model availability" className="flex flex-wrap gap-1 rounded-xl border border-[var(--line)] bg-[var(--surface)] p-1">{(['downloaded','available'] as const).map(value=><button key={value} aria-pressed={availability===value} onClick={()=>setAvailability(value)} className={`flex items-center gap-2 rounded-lg px-4 py-2.5 text-xs font-medium transition ${availability===value?'bg-[var(--accent-soft)] text-[var(--accent)]':'text-[var(--muted)] hover:bg-[var(--hover)]'}`}><Icon name={value==='downloaded'?'check':'download'} size={15}/>{value==='downloaded'?'Downloaded':'Available to download'}<span className="rounded-md bg-[var(--bg)] px-2 py-0.5 text-[10px] tabular-nums">{value==='downloaded'?downloadedCount:availableCount}</span></button>)}</div><button aria-pressed={fits} className={softButton} onClick={()=>setFits(!fits)}>Fits this PC{fits?' ✓':''}</button><span className="text-[var(--muted)]">{models.length} models</span>{hub.loadedId&&<button className={softButton} onClick={()=>void run(()=>bridge().unloadModel())}>Unload chat model</button>}</div></>}
 {hub.active&&<div className="flex flex-wrap justify-between gap-3 rounded-xl bg-[var(--accent-soft)] p-4 text-xs" role="status"><span>{hub.active.name} · {hub.active.message}</span><button onClick={()=>void run(()=>bridge().cancelModel())}>Cancel</button></div>}
 {error&&<p role="alert" className="error-message">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-[var(--accent-soft)] p-4 text-xs">{notice}</p>}
 {tab==='catalogue'&&<><div className="grid grid-cols-[repeat(auto-fill,minmax(min(100%,230px),1fr))] gap-4">{models.map(m=><article key={m.id} className={panel+' model-library-card flex flex-col !p-4'}><ModelArtwork model={m} assets={assets}/><h3 className="mt-4 text-xs font-semibold leading-6">{m.name}</h3><p className="mb-4 mt-2 text-[10px] text-[var(--muted)]">{m.size}{m.installed?' · Ready':''}</p><div className="mt-auto flex items-center gap-2">{m.installed?<button className="primary flex-1 !px-3 !py-2.5 !text-xs" disabled={busy} onClick={()=>void run(()=>useModel(m))}>Use model</button>:<DownloadButton item={downloads.find(d=>d.modelId===m.id&&d.status==='active')} className="flex-1 !px-3 !py-2.5 !text-xs" disabled={!!m.unsupported} onClick={()=>void run(()=>bridge().installModel(m.id))}>Download</DownloadButton>}<button className={softButton+' !px-3'} aria-label={'Info about '+m.name} onClick={()=>setInfo(m.id)}>Info</button></div></article>)}</div>{!models.length&&<p className="p-12 text-center text-xs">{availability==='downloaded'?'No downloaded models match these filters. Choose Available to download to find a model.':'No available models match these filters. Try another search or check Downloaded.'}</p>}<p className="text-[10px] text-[var(--muted)]">Sizes include required model files. Engine/CUDA setup is additional; cached files are reused.</p></>}
 {tab==='device'&&<ExistingModels query={query}/>}
   {tab==='online'&&<section className={panel}><span className="text-[9px] tracking-[.2em] text-[var(--accent)]">DISCOVER ONLINE</span><h3 className="mt-3 text-lg">More models from Hugging Face</h3><p className="mt-3 text-xs leading-6">Search public GGUF models and choose a quantized file. Community models use different licenses and architectures; support depends on the included llama.cpp engine.</p><form className="mt-5 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setSearching(true);void run(async()=>{try{setOnline(await bridge().searchOnlineModels(onlineQuery));setRemote(null)}finally{setSearching(false)}})}}><input className="!min-w-0 !w-auto flex-[1_1_200px]" placeholder="Try Qwen, Llama or Gemma…" aria-label="Search online models" value={onlineQuery} onChange={e=>setOnlineQuery(e.target.value)}/><button className={softButton} disabled={searching||onlineQuery.trim().length<2}>{searching?'Searching…':'Search'}</button></form><div className="mt-4 grid grid-cols-1 gap-2 md:grid-cols-2">{online.map(item=><button key={item.repo} className="flex items-center justify-between gap-4 rounded-xl border border-[var(--line)] p-4 text-left hover:bg-[var(--hover)]" disabled={remoteBusy} onClick={()=>{setRemoteBusy(true);void run(async()=>{try{const result=await bridge().onlineModelFiles(item.repo);setRemote(result);setFile(result.files[0]?.name||'')}finally{setRemoteBusy(false)}})}}><span className="min-w-0 flex-1 [overflow-wrap:anywhere] text-[10px] leading-5">{item.repo}<small className="block text-[9px] text-[var(--muted)]">{item.downloads.toLocaleString()} downloads</small></span><Icon name="arrow" size={15}/></button>)}</div>{remote&&<div className="mt-5 rounded-xl bg-[var(--bg)] p-5"><h4 className="break-words text-xs">{remote.repo}</h4><p className="my-3 text-[10px]">License: {remote.license} · <a className="underline" href={'https://huggingface.co/'+remote.repo} target="_blank" rel="noreferrer">Read model card ↗</a></p>{remote.files.length?<><label>Choose a file<select className="min-w-0 w-full max-w-full truncate" title={file} value={file} onChange={e=>setFile(e.target.value)}>{remote.files.map(f=><option key={f.name} value={f.name}>{f.name}{f.bytes?` · ${(f.bytes/1024**3).toFixed(1)} GB`:''}</option>)}</select></label><p className="mt-2 text-[9px] leading-5 [overflow-wrap:anywhere]">{file}</p><button className="primary mt-4 max-w-full whitespace-normal" disabled={remoteBusy} onClick={()=>{setRemoteBusy(true);void run(async()=>{try{await bridge().installOnlineModel({repo:remote.repo,filename:file});setNotice('Model downloaded. Select it above to chat or benchmark.')}finally{setRemoteBusy(false)}})}}>{remoteBusy?'Downloading · see progress above':'Download selected model'}</button></>:<p className="text-xs">No supported single-file GGUF downloads found. Gated, split and non-GGUF weights cannot be added from this search.</p>}</div>}</section>}

 {selected&&<ModelInfo key={selected.id} model={selected} onClose={()=>setInfo(null)}>{selected.installed?<><button className="primary" disabled={busy} onClick={()=>void run(()=>useModel(selected))}>Use model</button>{!['lipsync','3d'].includes(selected.kind)&&<button className={softButton} disabled={busy||!!selected.unsupported} onClick={()=>void run(async()=>{const result=await bridge().benchmarkModel(selected.id);setNotice(`${selected.name}: ${result.seconds.toFixed(1)} seconds including loading.`)})}>{hub.benchmarking===selected.id?'Benchmarking…':'Benchmark'}</button>}{selected.kind==='chat'&&<button className={softButton} disabled={busy} onClick={()=>void run(()=>bridge().removeModel(selected.id))}>Remove</button>}</>:<DownloadButton item={downloads.find(d=>d.modelId===selected.id&&d.status==='active')} disabled={!!selected.unsupported} onClick={()=>void run(()=>bridge().installModel(selected.id))}>Download · {selected.size}</DownloadButton>}</ModelInfo>}
 </div>
}
export function CreateStudio({kind,onUse}:{kind:'image'|'video';onUse:(asset:LocalCreation)=>void}){return <UnifiedStudio initialKind={kind} onUse={onUse}/> }
