import {useState} from 'react';
import {providers,type Provider} from './provider-catalog-data';
export function ProviderLogo({provider}:{provider?:Provider}){
 const [failed,setFailed]=useState(false);
 return <span className="provider-logo">{provider?.logo&&!failed?<img src={provider.logo} alt={`${provider.name} logo`} loading="lazy" width="32" height="32" onError={()=>setFailed(true)}/>:<span aria-hidden="true">{provider?.name.slice(0,2)||'AI'}</span>}</span>;
}
export function ProviderCatalog({accounts,onChoose,disabled}:{accounts:{providerId?:string;enabled:boolean;models?:string[];health?:{ok:boolean}}[];onChoose:(p:Provider)=>void;disabled:boolean}){
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all');
 const groups=[['oauth','OAuth & subscription accounts'],['free','Free tiers & trial access'],['api','API key providers'],['local','Local & custom endpoints']];
 const matches=providers.filter(p=>(group==='all'||p.group===group)&&p.name.toLowerCase().includes(search.toLowerCase()));
 return <section className="provider-browser" aria-label="Provider catalog"><div className="router-section-heading"><div><h3>Find your provider</h3><p>Connect accounts once. Their discovered models appear in Orvio and your unified API.</p></div><span className="provider-count">{providers.length} options</span></div><div className="provider-filters"><input type="search" aria-label="Search providers" placeholder="Search providers…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Provider category" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">All providers</option>{groups.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div>{groups.map(([id,name])=>{const list=matches.filter(p=>p.group===id);return list.length>0&&<section key={id} className="provider-group"><h4>{name}<span>{list.length}</span></h4>{id==='oauth'&&<p>Native account support varies by provider. Available sign-in flows run directly in Orvio; unsupported adapters are marked below.</p>}{id==='free'&&<p>Free access depends on the provider, account eligibility, and current quotas. Some services require a key or trial credits.</p>}<div className="provider-grid">{list.map(p=>{const connected=accounts.filter(a=>a.providerId===p.id&&a.enabled),count=connected.length;return <button type="button" className="provider-card" key={p.id} disabled={disabled} onClick={()=>onChoose(p)}><ProviderLogo provider={p}/><span className="provider-card-text"><strong>{p.name}</strong><small>{count?`${count} connection${count===1?'':'s'} · ${connected.some(a=>a.health?.ok===false)?'needs attention':connected.reduce((n,a)=>n+(a.models?.length||0),0)+' cached models'}`:p.mode==='unavailable'?'Not implemented':p.auth==='oauth'?'Native browser sign-in':p.protocol==='local'?'Use downloaded models':'Connect API endpoint'}</small></span><span className="provider-card-arrow" aria-hidden="true">+</span></button>})}</div></section>})}{!matches.length&&<p role="status">No matching providers. Choose Custom compatible API for another endpoint.</p>}</section>;
}
