import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {Icon,type IconName} from './icons';
import {bridge,friendlyError} from './Connected';
import {backgrounds,clamp,defaultOptions,outputSize,renderFrame,type RecorderOptions} from './recorder-render';
import {clipsFor,sourceAt,timelineAt,timelineDuration,splitClips,timecode,type TextLayer} from './recorder-timeline';
import './recorder-editor.css';
export type CaptureAsset={id:string;title:string;kind:string;preview:string;cameraId?:string;cameraPreview?:string;duration?:number};
const wallpapers=[{id:'silk',name:'Silk'},{id:'dunes',name:'Dunes'},{id:'midnight',name:'Midnight'}];
export const wallpaperURL=(id:string)=>new URL(`../recorder-backgrounds/${id}.png`,import.meta.url).href;
type Tool='clip'|'background'|'frame'|'camera'|'zoom'|'text'|'audio';
const tools:{id:Tool;icon:IconName;name:string}[]=[{id:'clip',icon:'video',name:'Video'},{id:'background',icon:'image',name:'Backdrop'},{id:'frame',icon:'focus',name:'Frame'},{id:'camera',icon:'camera',name:'Camera'},{id:'zoom',icon:'cursor',name:'Auto zoom'},{id:'text',icon:'text',name:'Text'},{id:'audio',icon:'volume',name:'Audio'}];
export function RecorderEditor({asset,onBack,onExport,detached=false}:{asset:CaptureAsset;onBack:()=>void;onExport:(asset:CaptureAsset)=>void;detached?:boolean}){
 const isVideo=asset.kind==='video';
 const [options,setOptions]=useState<RecorderOptions>({...defaultOptions,cameraId:asset.cameraId}),[duration,setDuration]=useState(asset.duration||0),[current,setCurrent]=useState(0),[playing,setPlaying]=useState(false),[tool,setTool]=useState<Tool>('background'),[ready,setReady]=useState(false),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[progress,setProgress]=useState(''),[selectedClip,setSelectedClip]=useState('original'),[selectedText,setSelectedText]=useState(''),[timelineScale,setTimelineScale]=useState(1),[exportOpen,setExportOpen]=useState(false),[historyTick,setHistoryTick]=useState(0),[thumbs,setThumbs]=useState<string[]>([]);
 const canvas=useRef<HTMLCanvasElement>(null),video=useRef<HTMLVideoElement|null>(null),camera=useRef<HTMLVideoElement|null>(null),picture=useRef<HTMLImageElement|null>(null),backdrop=useRef<HTMLImageElement|null>(null),size=useRef({width:1280,height:720}),oRef=useRef(options),time=useRef(0),sourceTime=useRef(0),sourceIndex=useRef(0),durationRef=useRef(duration),busyRef=useRef(false),loadedRef=useRef(false),revision=useRef(0),past=useRef<RecorderOptions[]>([]),future=useRef<RecorderOptions[]>([]),closeAction=useRef(()=>{}),track=useRef<HTMLDivElement>(null),drag=useRef<((e:PointerEvent)=>void)|null>(null),drawRef=useRef(()=>{});
 oRef.current=options;durationRef.current=duration;busyRef.current=busy;loadedRef.current=loaded;
 const clips=clipsFor(options,duration),total=timelineDuration(clips),clipIndex=Math.max(0,clips.findIndex(c=>c.id===selectedClip)),clip=clips[clipIndex],text=options.texts.find(t=>t.id===selectedText),shownTools=tools.filter(t=>isVideo||!['clip','camera','zoom','audio'].includes(t.id));
 const checkpoint=()=>{past.current=[...past.current.slice(-49),oRef.current];future.current=[];setHistoryTick(v=>v+1)};
 const replace=(next:RecorderOptions)=>{revision.current++;oRef.current=next;setOptions(next);setSaved(false);setNotice('')};
 const update=(patch:Partial<RecorderOptions>,remember=true)=>{if(remember)checkpoint();replace({...oRef.current,...patch})};
 const undo=(redo=false)=>{const from=redo?future:past,to=redo?past:future;if(!from.current.length)return;to.current.push(oRef.current);replace(from.current.pop()!);setHistoryTick(v=>v+1)};
 const pause=()=>{video.current?.pause();camera.current?.pause();setPlaying(false)};
 function draw(){const c=canvas.current,media=isVideo?video.current:picture.current;if(!c||!media||(isVideo&&video.current!.readyState<2))return;const out=outputSize(size.current.width,size.current.height,oRef.current);if(c.width!==out.width||c.height!==out.height){c.width=out.width;c.height=out.height}renderFrame(c,media,size.current.width,size.current.height,oRef.current,sourceTime.current,camera.current&&camera.current.readyState>=2?camera.current:undefined,backdrop.current||undefined,time.current)}drawRef.current=draw;
 function seek(value:number,stop=true){if(stop)pause();const list=clipsFor(oRef.current,durationRef.current),t=clamp(value,0,timelineDuration(list)),at=sourceAt(t,list);time.current=t;sourceTime.current=at.time;sourceIndex.current=at.index;setCurrent(t);if(video.current){video.current.currentTime=at.time;if(camera.current&&camera.current.readyState>=1)camera.current.currentTime=at.time}else draw()}
 async function play(){if(!video.current||busyRef.current)return;if(!video.current.paused){pause();return}try{if(time.current>=timelineDuration(clipsFor(oRef.current,durationRef.current))-.03)seek(0,false);await video.current.play();if(camera.current){camera.current.currentTime=video.current.currentTime;await camera.current.play()}setPlaying(true)}catch(e){setError(friendlyError(e))}}
 useEffect(()=>{let valid=true;void bridge().recorderProject(asset.id).then((p:RecorderOptions|null)=>{if(!valid)return;const next={...defaultOptions,...p,cameraId:p?.cameraId||asset.cameraId,zoomMode:p?.zoomMode||(p?.zooms?.length?'moments':'cursor')} as RecorderOptions;oRef.current=next;setOptions(next);if(p?.cursorDuration)setDuration(p.cursorDuration);setLoaded(true)}).catch((e:unknown)=>{if(valid){setError(friendlyError(e));setLoaded(true)}});return()=>{valid=false}},[asset.id]);
 useEffect(()=>{let valid=true;if(isVideo){const v=document.createElement('video');video.current=v;v.crossOrigin='anonymous';v.preload='auto';v.onloadeddata=()=>{if(!valid)return;size.current={width:v.videoWidth,height:v.videoHeight};setReady(true);if(Number.isFinite(v.duration)&&v.duration>0)setDuration(v.duration);else if(!durationRef.current){v.currentTime=1e9;v.addEventListener('timeupdate',()=>{if(Number.isFinite(v.duration))setDuration(v.duration);v.currentTime=0},{once:true})}drawRef.current()};v.onseeked=()=>drawRef.current();v.onerror=()=>setError('This recording could not be opened.');v.src=asset.preview;
 }else{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{if(valid){picture.current=img;size.current={width:img.naturalWidth,height:img.naturalHeight};setReady(true);drawRef.current()}};img.onerror=()=>setError('This image could not be opened.');img.src=asset.preview}
 return()=>{valid=false;for(const v of [video.current,camera.current]){v?.pause();v?.removeAttribute('src');v?.load()}video.current=null;picture.current=null};},[asset.id]);
 useEffect(()=>{if(!ready||!loaded)return;seek(0);},[ready,loaded]);
 useEffect(()=>{if(!options.cameraId)return;const v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.preload='auto';v.src=asset.cameraPreview||`orvio-media://asset/${options.cameraId}`;camera.current=v;v.onloadeddata=v.onseeked=()=>drawRef.current();v.onerror=()=>setError('Webcam footage is unavailable.');return()=>{v.pause();v.removeAttribute('src');v.load();if(camera.current===v)camera.current=null}},[options.cameraId]);
 useEffect(()=>{backdrop.current=null;if(options.background!=='image'||(!options.backgroundPreset&&!options.backgroundId)){drawRef.current();return}let valid=true;const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{if(valid){backdrop.current=img;drawRef.current()}};img.onerror=()=>setError('The background could not be loaded.');img.src=options.backgroundPreset?wallpaperURL(options.backgroundPreset):`orvio-media://asset/${options.backgroundId}`;return()=>{valid=false}},[options.background,options.backgroundPreset,options.backgroundId]);
 useEffect(()=>{if(video.current)video.current.volume=options.volume;if(ready)draw()},[options,ready]);
 useEffect(()=>{let raf=0;const loop=()=>{const v=video.current;if(v&&!v.paused){const list=clipsFor(oRef.current,durationRef.current),index=Math.min(sourceIndex.current,list.length-1),c=list[index];if(v.currentTime>=c.end-.015){if(index+1<list.length){sourceIndex.current=index+1;v.currentTime=list[index+1].start;if(camera.current)camera.current.currentTime=v.currentTime}else{pause();time.current=timelineDuration(list);setCurrent(time.current)}}else{sourceTime.current=v.currentTime;time.current=timelineAt(v.currentTime,index,list);setCurrent(time.current)}drawRef.current()}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[]);
 useEffect(()=>{const v=video.current;if(v)v.onended=()=>{const list=clipsFor(oRef.current,durationRef.current);if(sourceIndex.current+1<list.length){seek(list.slice(0,sourceIndex.current+1).reduce((n,c)=>n+c.end-c.start,0),false);void v.play()}else pause()};},[ready]);
 useEffect(()=>{if(!isVideo||!ready||!duration)return;let cancelled=false;const v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.src=asset.preview;const c=document.createElement('canvas');c.width=144;c.height=81;const ctx=c.getContext('2d')!;v.onloadeddata=async()=>{const frames:string[]=[];try{for(let i=0;i<8&&!cancelled;i++){await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Thumbnail timeout')),5000);v.onseeked=()=>{clearTimeout(timer);resolve()};v.currentTime=Math.min(duration-.02,Math.max(.001,duration*i/8))});ctx.drawImage(v,0,0,144,81);frames.push(c.toDataURL('image/jpeg',.55))}if(!cancelled)setThumbs(frames)}catch{}};return()=>{cancelled=true;v.pause();v.removeAttribute('src');v.load()}},[ready,duration,asset.id]);
 const save=async()=>{if(!loadedRef.current)throw Error('Project is still loading.');const version=revision.current;await bridge().saveRecorderProject(asset.id,oRef.current);if(version===revision.current)setSaved(true)};
 useEffect(()=>{if(saved||!loaded)return;const timer=setTimeout(()=>{void save().catch(e=>setError(friendlyError(e)))},650);return()=>clearTimeout(timer)},[options,saved,loaded]);
 closeAction.current=()=>{if(busyRef.current){setNotice('Finish or cancel the export before closing.');return}pause();void save().then(onBack).catch(e=>setError(friendlyError(e)))};
 useEffect(()=>{if(detached)return bridge().onCloseRecorderEditor(()=>closeAction.current())},[detached]);
 useEffect(()=>bridge().onLocal((s:any)=>setProgress(s.active?.message||'')),[]);
 useEffect(()=>{const move=(e:PointerEvent)=>drag.current?.(e),up=()=>{drag.current=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up)}},[]);
 function split(){const list=clipsFor(oRef.current,durationRef.current),at=sourceAt(time.current,list),next=splitClips(list,at.index,at.time,crypto.randomUUID());if(next===list){setNotice('Move the playhead inside a clip to split it.');return}pause();update({clips:next});setSelectedClip(next[at.index+1].id);setTool('clip')}
 function remove(){if(tool==='text'&&selectedText){update({texts:options.texts.filter(t=>t.id!==selectedText)});setSelectedText('');return}if(clips.length<=1){setNotice('Keep at least one video section. Drag its edges to trim it.');return}pause();update({clips:clips.filter(c=>c.id!==clip.id)});setSelectedClip(clips.find(c=>c.id!==clip.id)!.id);seek(Math.min(current,total-(clip.end-clip.start)))}
 function addText(){const id=crypto.randomUUID(),start=isVideo?Math.min(current,Math.max(0,total-.2)):0;update({texts:[...options.texts,{id,text:'Your text here',start,end:isVideo?Math.min(total,start+3):86400,x:.5,y:.82,size:42,color:'#ffffff',box:true}]});setSelectedText(id);setTool('text')}
 const changeText=(patch:Partial<TextLayer>,remember=true)=>{if(!selectedText)return;update({texts:oRef.current.texts.map(t=>t.id===selectedText?{...t,...patch}:t)},remember)};
 function startDrag(e:ReactPointerEvent,handler:(dx:number,dy:number)=>void){if(busy||!loaded)return;e.preventDefault();e.stopPropagation();pause();checkpoint();const x=e.clientX,y=e.clientY;e.currentTarget.setPointerCapture(e.pointerId);drag.current=event=>handler(event.clientX-x,event.clientY-y)}
 function trimClip(e:ReactPointerEvent,index:number,edge:'start'|'end'){const list=[...clips],c=list[index],pixels=track.current?.clientWidth||1,seconds=total;startDrag(e,dx=>{const value=clamp(c[edge]+dx/pixels*seconds,edge==='start'?0:c.start+.1,edge==='start'?c.end-.1:duration);update({clips:list.map((item,i)=>i===index?{...item,[edge]:value}:item)},false)})}
 function dragLayer(e:ReactPointerEvent,kind:'text'|'camera',id:string,edge:'move'|'start'|'end'){const layer=kind==='text'?options.texts.find(t=>t.id===id):{start:options.cameraStart,end:options.cameraEnd||total};if(!layer)return;const begin=layer.start,end=layer.end,pixels=track.current?.clientWidth||1,seconds=total;startDrag(e,dx=>{const delta=dx/pixels*seconds;let a=begin,b=end;if(edge==='move'){a=clamp(begin+delta,0,Math.max(0,seconds-(end-begin)));b=a+end-begin}else if(edge==='start')a=clamp(begin+delta,0,end-.1);else b=clamp(end+delta,begin+.1,seconds);if(kind==='camera')update({cameraStart:a,cameraEnd:b},false);else update({texts:oRef.current.texts.map(t=>t.id===id?{...t,start:a,end:b}:t)},false)})}
 function moveCanvas(e:ReactPointerEvent<HTMLCanvasElement>){if(!canvas.current)return;const rect=canvas.current.getBoundingClientRect();if(tool==='text'&&text){const x=text.x,y=text.y;startDrag(e,(dx,dy)=>changeText({x:clamp(x+dx/rect.width),y:clamp(y+dy/rect.height)},false))}else if(tool==='camera'&&options.cameraId){const x=options.cameraX??(options.cameraPosition.includes('left')?.16:.84),y=options.cameraY??(options.cameraPosition.includes('top')?.18:.82);startDrag(e,(dx,dy)=>update({cameraX:clamp(x+dx/rect.width),cameraY:clamp(y+dy/rect.height)},false))}}
 async function exportMedia(copy=false){pause();setBusy(true);setError('');try{await save();if(isVideo){const result=await bridge().exportRecording({id:asset.id,options:oRef.current});onExport(result);const savedFile=await bridge().localSave(result.id);setNotice(savedFile?'Video exported.':'Video saved to your library.')}else{draw();const result=await bridge().renderScreenshot({data:canvas.current!.toDataURL('image/png'),copy,save:!copy});if(!copy){onExport(result);await bridge().localSave(result.id)}setNotice(copy?'Image copied. Paste it anywhere.':'Image exported.')}setExportOpen(false)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable]')||busy)return;const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey)}else if(e.code==='Space'&&isVideo){e.preventDefault();void play()}else if(e.key.toLowerCase()==='s'&&!mod&&isVideo){e.preventDefault();split()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove()}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();seek(current+(e.key==='ArrowRight'?1:-1)*(e.shiftKey?1:1/30))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[options,current,tool,selectedClip,selectedText,busy,historyTick]);
 const editClip=(patch:{start?:number;end?:number})=>{pause();update({clips:clips.map(c=>c.id===clip.id?{...c,...patch}:c)})};
 const fieldRange=(label:string,key:'padding'|'radius'|'shadow'|'cameraSize'|'zoomStrength'|'volume',min:number,max:number,step=1)=><label>{label}<span className="ed-range"><input type="range" min={min} max={max} step={step} value={options[key]} onPointerDown={checkpoint} onChange={e=>update({[key]:Number(e.target.value)},false)}/><output>{key==='volume'?Math.round(options[key]*100)+'%':key==='zoomStrength'?options[key].toFixed(1)+'×':options[key]}</output></span></label>;
 const bar=(start:number,end:number)=>({left:`${start/(total||1)*100}%`,width:`${Math.max(.1,end-start)/(total||1)*100}%`});
 return <section className="ed-workspace">
  <header className="ed-topbar"><div className="ed-project"><Icon name="video" size={19}/><strong>{asset.title}</strong><span>{saved?'Saved':'Saving…'}</span></div><div className="ed-history"><button title="Undo (⌘Z)" aria-label="Undo" disabled={busy||!past.current.length} onClick={()=>undo()}><Icon name="undo" size={18}/></button><button title="Redo (⌘⇧Z)" aria-label="Redo" disabled={busy||!future.current.length} onClick={()=>undo(true)}><Icon name="redo" size={18}/></button></div><div className="ed-top-actions">{!isVideo&&<button disabled={!ready||busy} onClick={()=>void exportMedia(true)}><Icon name="copy" size={16}/>Copy</button>}<button disabled={busy||!loaded} onClick={()=>closeAction.current()}>Done</button><button className="ed-export" disabled={!ready||!loaded||busy} onClick={()=>{pause();setExportOpen(true)}}><Icon name="download" size={16}/>Export</button></div></header>
  <div className="ed-body"><nav className="ed-rail" aria-label="Editor tools">{shownTools.map(t=><button key={t.id} className={tool===t.id?'active':''} disabled={busy} onClick={()=>setTool(t.id)}><Icon name={t.icon} size={21}/><span>{t.name}</span></button>)}</nav>
  <aside className="ed-inspector"><h3>{tools.find(t=>t.id===tool)?.name}</h3><fieldset disabled={busy||!loaded}>
  {tool==='background'&&<><div className="ed-choice">{['none','gradient','solid','image'].map(b=><button key={b} className={options.background===b?'active':''} onClick={()=>update({background:b})}>{b==='none'?'None':b==='image'?'Images':b==='solid'?'Color':'Gradient'}</button>)}</div>{options.background==='image'&&<><div className="ed-wallpapers">{wallpapers.map(b=><button key={b.id} aria-label={`${b.name} background`} className={options.backgroundPreset===b.id?'active':''} onClick={()=>update({backgroundPreset:b.id,backgroundId:undefined})}><img src={wallpaperURL(b.id)} alt=""/><span>{b.name}</span></button>)}</div><button className="ed-outline" onClick={async()=>{try{const a=await bridge().localImport('image');if(a)update({backgroundId:a.id,backgroundPreset:undefined})}catch(e){setError(friendlyError(e))}}}><Icon name="plus" size={15}/>Your own image</button></>}{options.background==='gradient'&&<div className="ed-gradients">{backgrounds.map(b=><button key={b.name} aria-label={`${b.name} gradient`} style={{background:`linear-gradient(${b.color},${b.color2})`}} onClick={()=>update({color:b.color,color2:b.color2})}><span>{b.name}</span></button>)}</div>}{['solid','gradient'].includes(options.background)&&<div className="ed-fields"><label>Color<input type="color" value={options.color} onChange={e=>update({color:e.target.value})}/></label>{options.background==='gradient'&&<label>Second color<input type="color" value={options.color2} onChange={e=>update({color2:e.target.value})}/></label>}</div>}<p className="ed-hint">Your background fills the canvas around the recording.</p></>}
  {tool==='frame'&&<><label>Canvas<select value={options.aspect} onChange={e=>update({aspect:e.target.value})}>{[['auto','Original'],['16:9','Landscape 16:9'],['9:16','Portrait 9:16'],['1:1','Square 1:1'],['4:3','Classic 4:3']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>{fieldRange('Padding','padding',0,24)}{fieldRange('Corner radius','radius',0,60)}{fieldRange('Shadow','shadow',0,80)}<button className="ed-outline" onClick={()=>update({padding:8,radius:18,shadow:30,aspect:'auto'})}>Reset framing</button></>}
  {tool==='zoom'&&<><label className="ed-switch">Follow cursor<input type="checkbox" checked={options.autoZoom&&options.zoomMode==='cursor'} disabled={!options.cursor.length} onChange={e=>update({autoZoom:e.target.checked,zoomMode:'cursor'})}/></label>{fieldRange('Zoom strength','zoomStrength',1.2,3,.1)}<p className="ed-hint">{options.cursor.length?'Smooth automatic framing follows your recorded cursor. No keyframes needed.':'This video has no cursor track. Record a display or area in Orvio to use cursor follow.'}</p></>}
  {tool==='clip'&&clip&&<><p className="ed-hint">Section {clipIndex+1} of {clips.length}. Drag the clip edges below to trim.</p><div className="ed-fields"><label>Source in<input type="number" min={0} max={clip.end-.1} step={.1} value={Number(clip.start.toFixed(2))} onChange={e=>editClip({start:clamp(Number(e.target.value),0,clip.end-.1)})}/></label><label>Source out<input type="number" min={clip.start+.1} max={duration} step={.1} value={Number(clip.end.toFixed(2))} onChange={e=>editClip({end:clamp(Number(e.target.value),clip.start+.1,duration)})}/></label></div><button className="ed-outline" onClick={split}><Icon name="split" size={16}/>Split at playhead <kbd>S</kbd></button><button className="ed-outline" disabled={clips.length<=1} onClick={remove}><Icon name="delete" size={16}/>Remove section</button><div className="ed-fields">{[-1,1].map(direction=><button className="ed-outline" key={direction} disabled={clipIndex+direction<0||clipIndex+direction>=clips.length} onClick={()=>{pause();const next=[...clips];[next[clipIndex],next[clipIndex+direction]]=[next[clipIndex+direction],next[clipIndex]];update({clips:next});seek(0)}}>{direction<0?'Move earlier':'Move later'}</button>)}</div><button className="ed-link" onClick={()=>{update({clips:[],start:0,end:0});seek(0)}}>Restore full recording</button></>}
  {tool==='camera'&&(options.cameraId?<><label className="ed-switch">Show webcam<input type="checkbox" checked={options.showCamera} onChange={e=>update({showCamera:e.target.checked})}/></label>{fieldRange('Size','cameraSize',10,45)}<label>Shape<select value={options.cameraShape} onChange={e=>update({cameraShape:e.target.value})}><option value="circle">Circle</option><option value="rounded">Rounded rectangle</option></select></label><div className="ed-choice">{['top-left','top-right','bottom-left','bottom-right'].map(p=><button key={p} title={p} aria-label={`Webcam ${p}`} onClick={()=>update({cameraPosition:p,cameraX:undefined,cameraY:undefined})}><Icon name="camera" size={16}/>{p.split('-').map(s=>s[0].toUpperCase()).join('')}</button>)}</div><label className="ed-switch">Mirror<input type="checkbox" checked={options.cameraMirror} onChange={e=>update({cameraMirror:e.target.checked})}/></label><p className="ed-hint">Drag on the preview to position your webcam. Drag its timeline edges to control when it appears.</p></>:<p className="ed-hint">Enable webcam when recording to add an editable camera layer.</p>)}
  {tool==='text'&&<><button className="ed-outline" onClick={addText}><Icon name="plus" size={16}/>Add text</button>{options.texts.map(t=><button key={t.id} className={`ed-text-item ${selectedText===t.id?'active':''}`} onClick={()=>{setSelectedText(t.id);seek(t.start)}}><Icon name="text" size={15}/>{t.text||'Empty text'}</button>)}{text&&<><label>Text<textarea maxLength={500} value={text.text} onChange={e=>changeText({text:e.target.value})}/></label><label>Size<input type="range" min={16} max={120} value={text.size} onPointerDown={checkpoint} onChange={e=>changeText({size:Number(e.target.value)},false)}/></label><label>Color<input type="color" value={text.color} onChange={e=>changeText({color:e.target.value})}/></label><label className="ed-switch">Background pill<input type="checkbox" checked={text.box} onChange={e=>changeText({box:e.target.checked})}/></label><p className="ed-hint">Drag on the preview to place this text. Move and trim its timeline layer below.</p><button className="ed-link" onClick={remove}>Delete text</button></>}</>}
  {tool==='audio'&&<>{fieldRange('Recording volume','volume',0,1,.01)}<button className="ed-outline" onClick={()=>update({volume:options.volume?0:1})}><Icon name="volume" size={16}/>{options.volume?'Mute recording':'Unmute recording'}</button><p className="ed-hint">Applies to your microphone and any computer sound captured in this recording.</p></>}
  </fieldset></aside>
  <div className="ed-player"><div className="ed-player-top"><span>Preview</span><button onClick={()=>setTool('frame')}>{options.aspect==='auto'?'Original ratio':options.aspect}<Icon name="down" size={12}/></button></div><div className={`ed-canvas-area ${tool==='text'||tool==='camera'?'movable':''}`}><canvas ref={canvas} aria-label="Edited capture preview" onPointerDown={moveCanvas}/>{!ready&&<span>Loading capture…</span>}</div><div className="ed-player-controls">{isVideo?<><time>{timecode(current)} <span>/ {timecode(total)}</span></time><button aria-label={playing?'Pause':'Play'} disabled={!ready||busy} onClick={()=>void play()}><Icon name={playing?'pause':'play'} size={23}/></button><span className="ed-preview-note">{tool==='camera'?'Drag to move webcam':tool==='text'&&text?'Drag to move text':options.autoZoom&&options.cursor.length?'Cursor follow on':'Fit to canvas'}</span></>:<span>Drag a text layer on the preview to position it</span>}</div></div></div>
  {isVideo&&<div className="ed-timeline"><div className="ed-timeline-toolbar"><button title="Split at playhead (S)" aria-label="Split at playhead" disabled={busy||!ready} onClick={split}><Icon name="split" size={18}/></button><button title="Delete selected section or text" aria-label="Delete selection" disabled={busy} onClick={remove}><Icon name="delete" size={17}/></button><span>{clips.length} section{clips.length===1?'':'s'} · {timecode(total)}</span><div className="ed-timeline-zoom"><Icon name="search" size={14}/><input aria-label="Timeline zoom" type="range" min={1} max={5} step={.25} value={timelineScale} onChange={e=>setTimelineScale(Number(e.target.value))}/><button onClick={()=>setTimelineScale(1)}>Fit</button></div></div>
   <div className="ed-tracks-scroll"><div className="ed-tracks" style={{width:`${timelineScale*100}%`}}><div className="ed-track-labels"><span/><button onClick={()=>setTool('clip')}><Icon name="video" size={16}/>Video</button><button onClick={()=>setTool('camera')}><Icon name="camera" size={16}/>Camera</button><button onClick={()=>setTool('zoom')}><Icon name="cursor" size={16}/>Zoom</button><button onClick={()=>setTool('text')}><Icon name="text" size={16}/>Text</button><button onClick={()=>setTool('background')}><Icon name="image" size={16}/>Backdrop</button></div><div className="ed-track-content" ref={track}>
    <div className="ed-ruler" onPointerDown={e=>{const rect=e.currentTarget.getBoundingClientRect();seek(clamp((e.clientX-rect.left)/rect.width)*total);e.currentTarget.setPointerCapture(e.pointerId);drag.current=event=>seek(clamp((event.clientX-rect.left)/rect.width)*total)}}>{Array.from({length:11},(_,i)=><span key={i} style={{left:`${i*10}%`}}>{timecode(total*i/10)}</span>)}</div>
    <div className="ed-track-row">{clips.map((c,i)=>{const start=clips.slice(0,i).reduce((n,c)=>n+c.end-c.start,0);return <div key={c.id} className={`ed-clip ed-video-clip ${selectedClip===c.id&&tool==='clip'?'selected':''}`} style={bar(start,start+c.end-c.start)}><button className="ed-clip-body" onClick={()=>{setSelectedClip(c.id);setTool('clip');seek(start)}} aria-label={`Select video section ${i+1}`}><div className="ed-filmstrip">{thumbs.map((src,j)=><img key={j} src={src} alt=""/>)}</div><span>Section {i+1}</span></button><button className="ed-trim-handle start" aria-label={`Trim section ${i+1} start`} onPointerDown={e=>trimClip(e,i,'start')}/><button className="ed-trim-handle end" aria-label={`Trim section ${i+1} end`} onPointerDown={e=>trimClip(e,i,'end')}/></div>})}</div>
    <div className="ed-track-row">{options.cameraId?<div className={`ed-clip ed-camera-clip ${!options.showCamera?'muted':''}`} style={bar(options.cameraStart,Math.min(total,options.cameraEnd||total))}><button className="ed-clip-body" onClick={()=>setTool('camera')} onPointerDown={e=>{setTool('camera');dragLayer(e,'camera','','move')}}>Webcam overlay</button><button className="ed-trim-handle start" aria-label="Trim webcam start" onPointerDown={e=>dragLayer(e,'camera','','start')}/><button className="ed-trim-handle end" aria-label="Trim webcam end" onPointerDown={e=>dragLayer(e,'camera','','end')}/></div>:<span className="ed-empty-track">No webcam captured</span>}</div>
    <div className="ed-track-row"><button className={`ed-clip ed-zoom-clip ${!options.autoZoom?'muted':''}`} disabled={!options.cursor.length} style={bar(0,total)} onClick={()=>setTool('zoom')}><Icon name="cursor" size={14}/>{options.cursor.length?`Cursor follow · ${options.zoomStrength.toFixed(1)}×`:'No cursor track'}</button></div>
    <div className="ed-track-row">{options.texts.length?options.texts.map(t=><div key={t.id} className={`ed-clip ed-text-clip ${selectedText===t.id&&tool==='text'?'selected':''}`} style={bar(t.start,Math.min(total,t.end))}><button className="ed-clip-body" onPointerDown={e=>{setSelectedText(t.id);setTool('text');dragLayer(e,'text',t.id,'move')}}>{t.text}</button><button className="ed-trim-handle start" aria-label="Trim text start" onPointerDown={e=>dragLayer(e,'text',t.id,'start')}/><button className="ed-trim-handle end" aria-label="Trim text end" onPointerDown={e=>dragLayer(e,'text',t.id,'end')}/></div>):<button className="ed-empty-track" onClick={addText}>+ Add text layer</button>}</div>
    <div className="ed-track-row"><button className="ed-clip ed-bg-clip" style={{...bar(0,total),background:options.background==='image'&&options.backgroundPreset?`url(${wallpaperURL(options.backgroundPreset)}) center / cover`:options.color}} onClick={()=>setTool('background')}>{options.backgroundPreset||options.background} background</button></div><div className="ed-playhead" style={{left:`${current/(total||1)*100}%`}}><i/></div>
   </div></div></div><footer className="ed-timeline-footer"><span>Space · play / pause</span><span>S · split</span><span>⌘Z · undo</span><span>Drag clip edges to trim</span><span>Original footage preserved</span></footer></div>}
  {(error||notice)&&<div className={`ed-toast ${error?'error':''}`} role={error?'alert':'status'}>{error||notice}<button aria-label="Dismiss" onClick={()=>{setError('');setNotice('')}}><Icon name="close" size={15}/></button></div>}
  {exportOpen&&<div className="ed-modal-backdrop"><section className="ed-export-dialog" role="dialog" aria-modal="true" aria-label="Export capture"><header><h3>Export {isVideo?'video':'image'}</h3><button aria-label="Close export" disabled={busy} onClick={()=>setExportOpen(false)}><Icon name="close" size={18}/></button></header><p>{isVideo?`${timecode(total)} · MP4 with your edits and audio`:'PNG · styled screenshot'}</p><label>Resolution<select disabled={busy} value={options.resolution} onChange={e=>update({resolution:Number(e.target.value)})}><option value={720}>720p</option><option value={1080}>1080p · recommended</option><option value={1440}>1440p</option></select></label>{busy?<><p role="status">{progress||'Preparing export…'}</p><progress/><button className="ed-outline" onClick={()=>void bridge().localCancel()}>Cancel export</button></>:<button className="ed-export" onClick={()=>void exportMedia()}><Icon name="download" size={16}/>Export {isVideo?'MP4':'PNG'}</button>}</section></div>}
 </section>;
}
