import {useEffect,useRef,useState} from 'react';
import {bridge,friendlyError} from './Connected';
import {backgrounds,clamp,defaultOptions,elapsedLabel,frameRect,outputSize,renderFrame,type RecorderOptions,type Zoom} from './recorder-render';
export type CaptureAsset={id:string;title:string;kind:string;preview:string;cameraId?:string;cameraPreview?:string;duration?:number};
export function RecorderEditor({asset,onBack,onExport}:{asset:CaptureAsset;onBack:()=>void;onExport:(asset:CaptureAsset)=>void}){
 const [options,setOptions]=useState<RecorderOptions>({...defaultOptions,cameraId:asset.cameraId}),[duration,setDuration]=useState(asset.duration||0),[current,setCurrent]=useState(0),[playing,setPlaying]=useState(false),[tab,setTab]=useState('design'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selectedZoom,setSelectedZoom]=useState(-1),[ready,setReady]=useState(false),[progress,setProgress]=useState(''),[saved,setSaved]=useState(true);
 const stage=useRef<HTMLCanvasElement>(null),video=useRef<HTMLVideoElement|null>(null),camera=useRef<HTMLVideoElement|null>(null),image=useRef<HTMLImageElement|null>(null),background=useRef<HTMLImageElement|null>(null),optionsRef=useRef(options),timeRef=useRef(0),size=useRef({width:1280,height:720}),cancelAnalysis=useRef(false),analyzing=useRef(false),projectLoaded=useRef(false);
 const isVideo=asset.kind==='video';optionsRef.current=options;
 const update=(patch:Partial<RecorderOptions>)=>{setOptions(o=>({...o,...patch}));setSaved(false);setNotice('')};
 const draw=()=>{const canvas=stage.current,source=isVideo?video.current:image.current;if(!canvas||!source||(isVideo&&video.current!.readyState<2))return;const o=optionsRef.current;const out=outputSize(size.current.width,size.current.height,o);if(canvas.width!==out.width||canvas.height!==out.height){canvas.width=out.width;canvas.height=out.height}renderFrame(canvas,source,size.current.width,size.current.height,o,timeRef.current,camera.current?.readyState&&camera.current.readyState>=2?camera.current:undefined,background.current||undefined)};
 const pause=()=>{video.current?.pause();camera.current?.pause();setPlaying(false)};
 const seek=async(time:number)=>{pause();timeRef.current=time;setCurrent(time);if(video.current){video.current.currentTime=time;if(camera.current&&camera.current.readyState>=1)camera.current.currentTime=time}else draw()};
 useEffect(()=>{let frame=0;const loop=()=>{if(video.current&&!video.current.paused){timeRef.current=video.current.currentTime;setCurrent(timeRef.current);const end=optionsRef.current.end||duration;if(end&&timeRef.current>=end){pause();void seek(optionsRef.current.start)}}if(ready&&video.current&&!video.current.paused)draw();frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[ready,duration]);
 useEffect(()=>{let valid=true;projectLoaded.current=false;setReady(false);setError('');void bridge().recorderProject(asset.id).then((project:RecorderOptions|null)=>{if(valid){setOptions({...defaultOptions,...project,cameraId:project?.cameraId||asset.cameraId});projectLoaded.current=true}}).catch(()=>{projectLoaded.current=true});return()=>{valid=false}},[asset.id]);
 useEffect(()=>{let valid=true;const clean=()=>{for(const v of [video.current,camera.current]){v?.pause();v?.removeAttribute('src');v?.load()}video.current=null;camera.current=null;image.current=null};
 if(isVideo){const v=document.createElement('video');v.crossOrigin='anonymous';v.preload='auto';v.src=asset.preview;video.current=v;
 v.onloadeddata=()=>{if(!valid)return;size.current={width:v.videoWidth,height:v.videoHeight};setReady(true);if(Number.isFinite(v.duration)){setDuration(v.duration)}else{v.currentTime=1e9;v.addEventListener('timeupdate',()=>{if(!valid)return;if(Number.isFinite(v.duration))setDuration(v.duration);v.currentTime=0},{once:true})}};
 v.onseeked=draw;v.onended=pause;v.onerror=()=>setError('This video could not be opened. Try importing it again.');
 }else{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{if(valid){image.current=img;size.current={width:img.naturalWidth,height:img.naturalHeight};setReady(true)}};img.onerror=()=>setError('This screenshot could not be opened.');img.src=asset.preview}
 return()=>{valid=false;cancelAnalysis.current=true;clean()};},[asset.id]);
 useEffect(()=>{const id=options.cameraId;if(!id)return;const v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.preload='auto';v.src=asset.cameraPreview||`orvio-media://asset/${id}`;camera.current=v;v.onloadeddata=draw;v.onseeked=draw;v.onerror=()=>setError('The webcam footage could not be opened.');return()=>{v.pause();v.removeAttribute('src');v.load();if(camera.current===v)camera.current=null}},[options.cameraId]);
 useEffect(()=>{if(!options.backgroundId){background.current=null;return}const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{background.current=img;draw()};img.onerror=()=>setError('The background image could not be opened.');img.src=`orvio-media://asset/${options.backgroundId}`;return()=>{img.onload=null;background.current=null}},[options.backgroundId]);
 useEffect(()=>{if(ready)draw()},[options,ready]);
 useEffect(()=>{const off=bridge().onLocal((s:any)=>setProgress(s.active?.message||''));return()=>{off();cancelAnalysis.current=true;analyzing.current=false}},[]);
 const save=async()=>{if(!projectLoaded.current)throw Error('Wait for the project to load.');await bridge().saveRecorderProject(asset.id,options);setSaved(true)};
 async function exportMedia(copy=false){pause();setBusy(true);setError('');try{await save();if(isVideo){const result=await bridge().exportRecording({id:asset.id,options});onExport(result);await bridge().localSave(result.id);setNotice('MP4 is ready in your library.')}else{draw();if(!stage.current)throw Error('The screenshot is still loading.');const result=await bridge().renderScreenshot({data:stage.current.toDataURL('image/png'),copy,save:!copy});if(!copy){onExport(result);await bridge().localSave(result.id)}setNotice(copy?'Styled screenshot copied. Paste it anywhere.':'Styled PNG is ready in your library.')}}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 function addZoom(){const existing=options.zooms.findIndex(z=>current>=z.start&&current<z.end);if(existing>=0){setSelectedZoom(existing);setTab('zoom');setNotice('A zoom already covers this moment. Adjust it below.');return}const start=Math.min(current,Math.max(0,duration-.6)),next=options.zooms.filter(z=>z.start>start).sort((a,b)=>a.start-b.start)[0],end=Math.min(duration,start+3,next?.start??duration);if(end-start<.2)return;const z={start,end,x:.5,y:.5,scale:1.7};const index=options.zooms.length;update({autoZoom:true,zooms:[...options.zooms,z]});setSelectedZoom(index);setTab('zoom');setNotice('Click the preview to choose the focus area.');}
 const zoom=options.zooms[selectedZoom];
 const changeZoom=(patch:Partial<Zoom>)=>update({zooms:options.zooms.map((z,i)=>i===selectedZoom?{...z,...patch}:z)});
 async function analyze(){pause();setBusy(true);setError('');cancelAnalysis.current=false;analyzing.current=true;try{const v=video.current;if(!v||!duration)throw Error('Wait for the recording to load.');const canvas=document.createElement('canvas');canvas.width=96;canvas.height=54;const ctx=canvas.getContext('2d',{willReadFrequently:true})!;let previous:Uint8ClampedArray|null=null;const zooms:Zoom[]=[];const step=Math.max(.5,duration/3600);for(let time=options.start;time<(options.end||duration)&&!cancelAnalysis.current;time+=step){setProgress(`Finding focus areas · ${Math.round(time/duration*100)}%`);await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>{v.removeEventListener('seeked',done);reject(Error('Video analysis timed out.'))},10000);const done=()=>{clearTimeout(timeout);resolve()};v.addEventListener('seeked',done,{once:true});v.currentTime=Math.max(.001,time)});ctx.drawImage(v,0,0,96,54);const pixels=ctx.getImageData(0,0,96,54).data;if(previous){let sum=0,xsum=0,ysum=0,changed=0;for(let i=0;i<pixels.length;i+=4){const difference=Math.abs(pixels[i]-previous[i])+Math.abs(pixels[i+1]-previous[i+1])+Math.abs(pixels[i+2]-previous[i+2]);if(difference>90){sum+=difference;xsum+=(i/4%96)*difference;ysum+=Math.floor(i/4/96)*difference;changed++}}const last=zooms[zooms.length-1];if(changed>12&&changed<96*54*.22&&(!last||time>last.end+1)&&time+.8<(options.end||duration))zooms.push({start:time,end:Math.min(options.end||duration,time+2.8),x:clamp(xsum/sum/96),y:clamp(ysum/sum/54),scale:1.65})}previous=pixels.slice()}
 if(!cancelAnalysis.current){update({autoZoom:true,zooms});setSelectedZoom(-1);setNotice(zooms.length?`${zooms.length} zoom moments found. Review and adjust their focus.`:'No concentrated changes found. Add zoom moments where you want them.')}await seek(options.start);
 }catch(e){setError(friendlyError(e))}finally{analyzing.current=false;setBusy(false);setProgress('')}}
 return <section className="rec-editor">
 <header className="rec-editor-header"><div><span className="mini-label">{isVideo?'RECORDING EDITOR':'SCREENSHOT EDITOR'}</span><h2>Make it yours.</h2><p>{asset.title} · {saved?'Original preserved':'Unsaved changes'}</p></div><div className="rec-actions"><button className="secondary" disabled={busy} onClick={()=>{pause();void save().then(onBack).catch(e=>setError(friendlyError(e)))}}>Back to capture</button><button className="secondary" disabled={busy} onClick={()=>{void save().then(()=>setNotice('Project saved.')).catch(e=>setError(friendlyError(e)))}}>Save project</button>{!isVideo&&<button className="secondary" disabled={busy||!ready} onClick={()=>void exportMedia(true)}>Copy image</button>}<button className="primary" disabled={busy||!ready} onClick={()=>void exportMedia()}>{busy?'Exporting…':isVideo?'Export MP4':'Export PNG'}</button></div></header>
 <div className="rec-editor-grid"><div className="rec-editor-main"><div className={`rec-stage ${selectedZoom>=0?'focus-picking':''}`}><canvas ref={stage} aria-label="Styled capture preview" onClick={e=>{if(!zoom||!stage.current)return;const bounds=stage.current.getBoundingClientRect(),r=frameRect(stage.current.width,stage.current.height,size.current.width,size.current.height,options),x=(e.clientX-bounds.left)/bounds.width*stage.current.width,y=(e.clientY-bounds.top)/bounds.height*stage.current.height;changeZoom({x:clamp((x-r.x)/r.width),y:clamp((y-r.y)/r.height)});setNotice('Focus updated.')}}/>{!ready&&<p>Loading your capture…</p>}</div>
 {isVideo&&<div className="rec-timeline"><div className="rec-play-row"><button className="secondary" disabled={!ready||busy} onClick={async()=>{if(playing)pause();else if(video.current){try{if(video.current.currentTime<options.start||video.current.currentTime>=(options.end||duration))video.current.currentTime=options.start;await video.current.play();if(camera.current){camera.current.currentTime=video.current.currentTime;await camera.current.play()}setPlaying(true)}catch(e){pause();setError(friendlyError(e))}}}}>{playing?'Pause':'Play'}</button><time>{elapsedLabel(current)} / {elapsedLabel(duration)}</time><button className="text-button" disabled={!duration||busy} onClick={addZoom}>+ Zoom here</button></div><div className="rec-scrubber"><input aria-label="Recording playhead" type="range" min={0} max={duration||1} step={.01} value={Math.min(current,duration||1)} disabled={busy} onChange={e=>void seek(Number(e.target.value))}/><div className="rec-zoom-markers">{options.zooms.map((z,i)=><button key={i} aria-label={`Select zoom ${i+1}`} className={i===selectedZoom?'selected':''} style={{left:`${z.start/(duration||1)*100}%`,width:`${(z.end-z.start)/(duration||1)*100}%`}} onClick={()=>{setSelectedZoom(i);setTab('zoom');void seek(z.start+.5)}}/>)}</div></div><div className="rec-trim"><label>Trim start<input type="number" min={0} max={duration} step={.1} value={options.start} disabled={busy} onChange={e=>update({start:Number(e.target.value)})}/></label><label>Trim end<input type="number" min={0} max={duration} step={.1} value={options.end||Math.round(duration*100)/100} disabled={busy} onChange={e=>update({end:Number(e.target.value)})}/></label><small>Seconds · Your original stays in the library</small></div></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}{notice&&<p className="rec-notice" role="status">{notice}</p>}{busy&&<div className="rec-progress" role="status"><span>{progress||'Preparing export…'}</span><progress/><button className="text-button" onClick={()=>{cancelAnalysis.current=true;if(!analyzing.current)void bridge().localCancel()}}>Cancel</button></div>}</div>
 <aside className="rec-inspector"><div className="rec-tabs">{['design',...(isVideo?['zoom']:[])].map(t=><button key={t} disabled={busy} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='design'?'Design':'Zoom & focus'}</button>)}</div><fieldset disabled={busy}>
 {tab==='design'?<><label>Background<select value={options.background} onChange={e=>update({background:e.target.value})}><option value="none">Original / no background</option><option value="gradient">Gradient</option><option value="solid">Solid color</option><option value="image">Custom image</option></select></label>{options.background==='gradient'&&<div className="rec-backgrounds">{backgrounds.map(b=><button key={b.name} className={options.color===b.color?'selected':''} aria-label={`${b.name} background`} style={{background:`linear-gradient(145deg,${b.color},${b.color2})`}} onClick={()=>update({color:b.color,color2:b.color2})}><span>{b.name}</span></button>)}</div>}{options.background!=='none'&&options.background!=='image'&&<div className="rec-colors"><label>Color<input type="color" value={options.color} onChange={e=>update({color:e.target.value})}/></label>{options.background==='gradient'&&<label>Second color<input type="color" value={options.color2} onChange={e=>update({color2:e.target.value})}/></label>}</div>}{options.background==='image'&&<button className="secondary" onClick={async()=>{try{const image=await bridge().localImport('image');if(image)update({backgroundId:image.id})}catch(e){setError(friendlyError(e))}}}>Choose background image</button>}
 <label>Canvas shape<select value={options.aspect} onChange={e=>update({aspect:e.target.value})}>{[['auto','Original ratio'],['16:9','Landscape · 16:9'],['9:16','Portrait · 9:16'],['1:1','Square · 1:1'],['4:3','Classic · 4:3']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>
 {(['padding','radius','shadow'] as const).map(key=><label key={key}>{key==='padding'?'Space around capture':key==='radius'?'Rounded corners':'Shadow'}<span className="rec-range"><input type="range" min={0} max={key==='padding'?24:key==='radius'?60:80} value={options[key]} onChange={e=>update({[key]:Number(e.target.value)})}/><output>{options[key]}{key==='padding'?'%':''}</output></span></label>)}
 <label>Export quality<select value={options.resolution} onChange={e=>update({resolution:Number(e.target.value)})}><option value={720}>720p · smaller file</option><option value={1080}>1080p · recommended</option><option value={1440}>1440p · detailed</option></select></label>
 {!!options.cameraId&&<><label className="rec-check"><input type="checkbox" checked={options.showCamera} onChange={e=>update({showCamera:e.target.checked})}/>Show webcam</label><label>Webcam position<select value={options.cameraPosition} onChange={e=>update({cameraPosition:e.target.value})}>{['bottom-right','bottom-left','top-right','top-left'].map(p=><option key={p} value={p}>{p.replace('-',' ')}</option>)}</select></label><label>Webcam shape<select value={options.cameraShape} onChange={e=>update({cameraShape:e.target.value})}><option value="circle">Circle</option><option value="rounded">Rounded rectangle</option></select></label><label>Webcam size<input type="range" min={10} max={45} value={options.cameraSize} onChange={e=>update({cameraSize:Number(e.target.value)})}/></label><label className="rec-check"><input type="checkbox" checked={options.cameraMirror} onChange={e=>update({cameraMirror:e.target.checked})}/>Mirror webcam</label></>}
 </>:<><label className="rec-check"><input type="checkbox" checked={options.autoZoom} onChange={e=>update({autoZoom:e.target.checked})}/>Enable zoom moments</label><p className="rec-help">Screen and area recordings suggest zooms where your cursor pauses. Find focus areas analyzes visible changes in any video. Review the suggestions, then click the preview to adjust focus.</p><button className="secondary" disabled={!duration} onClick={()=>void analyze()}>Find focus areas</button><button className="secondary" disabled={!duration} onClick={addZoom}>Add zoom at playhead</button><div className="rec-zoom-list">{options.zooms.map((z,i)=><button key={i} className={selectedZoom===i?'selected':''} onClick={()=>{setSelectedZoom(i);void seek(z.start+.5)}}><b>Zoom {i+1}</b><small>{z.start.toFixed(1)}–{z.end.toFixed(1)}s · {z.scale.toFixed(1)}×</small></button>)}</div>{zoom?<><p className="rec-help">Click the preview to place the focus.</p><div className="rec-trim"><label>Start<input type="number" min={0} max={duration} step={.1} value={zoom.start} onChange={e=>changeZoom({start:Number(e.target.value)})}/></label><label>End<input type="number" min={0} max={duration} step={.1} value={zoom.end} onChange={e=>changeZoom({end:Number(e.target.value)})}/></label></div><label>Zoom amount<span className="rec-range"><input type="range" min={1} max={3} step={.1} value={zoom.scale} onChange={e=>changeZoom({scale:Number(e.target.value)})}/><output>{zoom.scale.toFixed(1)}×</output></span></label><button className="text-button" onClick={()=>{update({zooms:options.zooms.filter((_,i)=>i!==selectedZoom)});setSelectedZoom(-1)}}>Remove this zoom</button></>:<p className="rec-help">Select a zoom on the timeline to edit it.</p>}</>}
 </fieldset></aside></div></section>
}
