import {lazy,Suspense,useEffect,useState} from 'react';
import {bridge,friendlyError} from './Connected';
import {useModelHub,type LocalCreation} from './model-data';
import {DownloadButton,useDownloads} from './Downloads';
import {Icon} from './icons';
const MeshViewer=lazy(()=>import('./MeshViewer'));
const panel='min-w-0 rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 md:p-6';
type Asset=LocalCreation&{duration?:number;vertices?:number;faces?:number};
export function SpatialStudio({kind,onUse}:{kind:'lipsync'|'3d';onUse:(asset:LocalCreation)=>void}){
 const {hub,error,setError}=useModelHub(),downloads=useDownloads();const [assets,setAssets]=useState<Asset[]>([]),[modelId,setModelId]=useState(()=>localStorage.getItem('orvio.model.'+kind)||''),[source,setSource]=useState(''),[audio,setAudio]=useState(''),[prompt,setPrompt]=useState(''),[consent,setConsent]=useState(false),[duration,setDuration]=useState(10),[steps,setSteps]=useState(32),[seed,setSeed]=useState(''),[manual,setManual]=useState(false),[box,setBox]=useState([.2,.15,.6,.7]),[running,setRunning]=useState(false),[selected,setSelected]=useState('');
 const models=hub.models.filter(m=>m.kind===kind),model=models.find(m=>m.id===modelId),face=assets.find(a=>a.id===source),result=assets.find(a=>a.id===selected),library=assets.filter(a=>models.some(m=>m.id===a.modelId));
 useEffect(()=>{if(!models.some(m=>m.id===modelId))setModelId(models.find(m=>m.installed)?.id||models[0]?.id||'')},[models.map(m=>m.id).join(','),modelId]);
 useEffect(()=>{const api=(window as any).studio;if(!api)return;let live=true;const update=(s:any)=>{if(live)setAssets(s.assets||[])};api.localState().then(update).catch((e:unknown)=>setError(friendlyError(e)));const off=api.onLocal(update);return()=>{live=false;off()}},[]);
 const busy=running||!!hub.benchmarking||!!hub.active&&!/download/i.test(hub.active.name);
 async function run(fn:()=>Promise<unknown>){setError('');try{await fn()}catch(e){setError(friendlyError(e))}}
 async function importFile(type:'audio'|'video'|'image'){await run(async()=>{const a=await bridge().localImport(type);if(a){setAssets(list=>[a,...list.filter(x=>x.id!==a.id)]);if(type==='audio')setAudio(a.id);else{setSource(a.id);setConsent(false)}}})}
 async function generate(){if(running||!model)return;setRunning(true);await run(async()=>{const a=await bridge().generateSpatial({model:model.id,prompt,sourceId:source||undefined,audioId:audio||undefined,duration,steps,seed:seed===''?undefined:Number(seed),consent,box:manual?box:null});setAssets(list=>[a,...list.filter(x=>x.id!==a.id)]);setSelected(a.id)});setRunning(false)}
 const inputNeeded=kind==='lipsync'||model?.input==='image';
 return <div className="space-y-5 [overflow-wrap:anywhere]">{error&&<p className="error-message" role="alert">{error}</p>}<div className="grid min-w-0 items-start gap-5 xl:grid-cols-[minmax(0,360px)_minmax(0,1fr)]"><section className={panel+' space-y-5'}><div><span className="text-[9px] tracking-[.18em] text-[var(--accent)]">{kind==='lipsync'?'PORTRAIT + VOICE → VIDEO':'IDEA → OBJECT → MESH'}</span><h2 className="mt-3 text-lg">{kind==='lipsync'?'Bring a face to life':'Shape your next idea'}</h2><p className="mt-3 text-[11px] leading-6 text-[var(--muted)]">{kind==='lipsync'?'Choose a clear front-facing portrait or video, then add your speech audio. Start with a short clip.':'Create a colored concept mesh from one object description or image. Inspect it here, then export for your 3D editor.'}</p></div><label>Model<select disabled={busy} value={modelId} onChange={e=>{setModelId(e.target.value);localStorage.setItem('orvio.model.'+kind,e.target.value)}}>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{model&&<div className="rounded-2xl bg-[var(--bg)] p-4 text-[10px] leading-6"><p>{model.description}</p><p className="mt-2 text-[var(--muted)]">{model.size} · {model.ramGB} GB RAM recommended</p><p className="mt-2">{model.recommendation?.detail}</p>{!model.installed&&<div className="mt-3"><DownloadButton item={downloads.find(d=>d.modelId===modelId&&d.status==='active')} disabled={!!model.unsupported} onClick={()=>void run(()=>bridge().installModel(modelId))}>Download model</DownloadButton></div>}</div>}
 {inputNeeded&&<div className="space-y-3"><label>{kind==='lipsync'?'Face source':'Object image'}<select value={source} disabled={busy} onChange={e=>{setSource(e.target.value);setConsent(false)}}><option value="">Choose from your library</option>{assets.filter(a=>a.kind==='image'||kind==='lipsync'&&a.kind==='video').map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><div className="flex flex-wrap gap-2"><button className="secondary" disabled={busy} onClick={()=>void importFile('image')}>Upload image</button>{kind==='lipsync'&&<button className="secondary" disabled={busy} onClick={()=>void importFile('video')}>Upload video</button>}</div></div>}
 {kind==='3d'&&model?.input==='text'&&<label>Describe one object<textarea rows={4} value={prompt} maxLength={1000} disabled={busy} onChange={e=>setPrompt(e.target.value)} placeholder="A small red wooden chair with curved legs"/></label>}
 {kind==='lipsync'?<><label>Speech audio<select value={audio} disabled={busy} onChange={e=>setAudio(e.target.value)}><option value="">Choose audio, including Voice Studio output</option>{assets.filter(a=>a.kind==='audio').map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>void importFile('audio')}>Upload speech</button>{audio&&<audio className="w-full" controls src={assets.find(a=>a.id===audio)?.preview}/>}<label>Maximum duration · seconds<input type="number" min="1" max="30" value={duration} disabled={busy} onChange={e=>setDuration(Number(e.target.value))}/></label><p className="text-[10px] leading-6 text-[var(--muted)]">Uses the beginning of the recording. Short videos hold their last frame. Output: 25 fps, up to 720px. This experimental compositor uses feathered face blending.</p><label className="toggle-row"><input type="checkbox" checked={manual} disabled={busy} onChange={e=>setManual(e.target.checked)}/>Choose the face area manually</label>{manual&&<div className="grid grid-cols-2 gap-3">{['Left','Top','Width','Height'].map((label,i)=><label key={label}>{label} %<input type="number" min={i>1?8:0} max="100" value={Math.round(box[i]*100)} disabled={busy} onChange={e=>setBox(value=>value.map((n,j)=>i===j?Number(e.target.value)/100:n))}/></label>)}</div>}<label className="toggle-row"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>I have permission to animate this person.</label></>:<label>Quality steps<select value={steps} disabled={busy} onChange={e=>setSteps(Number(e.target.value))}><option value="16">16 · quick concept</option><option value="32">32 · balanced</option><option value="64">64 · more refinement</option></select></label>}
 <details><summary className="text-xs">Reproducibility</summary><label className="mt-4">Seed<input type="number" min="0" max="4294967295" value={seed} disabled={busy} placeholder="Random" onChange={e=>setSeed(e.target.value)}/></label></details><button className="primary w-full" disabled={busy||!model?.installed||!!model?.unsupported||(inputNeeded&&!source)||(kind==='lipsync'?(!audio||!consent):model?.input==='text'&&!prompt.trim())} onClick={()=>void generate()}>{running?'Creating…':kind==='lipsync'?'Generate lip-sync video':'Generate 3D mesh'}</button>{running&&<div role="status" className="space-y-3 rounded-2xl bg-[var(--bg)] p-4"><progress className="w-full"/><p className="text-[10px] leading-6">{hub.active?.message||'Preparing local generation…'}</p><button className="secondary" onClick={()=>void run(()=>bridge().localCancel())}>Cancel</button></div>}</section>
 <section className={panel+' space-y-5'}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-sm">{result?'Your result':'Source & preview'}</h3><span className="text-[10px] text-[var(--muted)]">{kind==='3d'?'Colored mesh · GLB':'Local video · MP4'}</span></div>{result?result.kind==='3d'?<Suspense fallback={<p>Loading 3D viewer…</p>}><MeshViewer id={result.id}/></Suspense>:<video className="max-h-[520px] w-full rounded-2xl bg-black" controls src={result.preview}/>:face?<div className="relative mx-auto w-fit max-w-full overflow-hidden rounded-2xl">{face.kind==='image'?<img className="max-h-[420px] max-w-full" src={face.preview} alt="Selected source"/>:<video className="max-h-[420px] max-w-full" controls src={face.preview}/>} {manual&&kind==='lipsync'&&<span className="pointer-events-none absolute rounded-xl border-2 border-[var(--accent)] bg-[var(--accent)]/10" style={{left:box[0]*100+'%',top:box[1]*100+'%',width:box[2]*100+'%',height:box[3]*100+'%'}}/>}</div>:<div className="grid min-h-80 place-content-center gap-4 rounded-2xl bg-[var(--bg)] px-6 text-center"><Icon name={kind==='3d'?'system':'image'} size={34}/><p className="max-w-sm text-xs leading-7">{kind==='3d'?'An object, imagined in three dimensions.':'Your face source and generated video appear here.'}</p></div>}
 {result&&<><p className="text-[10px] leading-6">{result.model} · Seed {result.seed}{result.vertices?` · ${result.vertices.toLocaleString()} vertices`:''}{result.duration?` · ${result.duration.toFixed(1)} seconds`:''}</p><div className="flex flex-wrap gap-3"><button className="primary" onClick={()=>void run(()=>bridge().localSave(result.id))}>Export {result.kind==='3d'?'GLB':'MP4'}</button>{result.kind==='video'&&<button className="secondary" onClick={()=>onUse(result)}>Use in a post</button>}<button className="secondary" onClick={()=>setSelected('')}>Show source</button></div></>}
 <div className="border-t border-[var(--line)] pt-5"><h3 className="mb-4 text-xs">Recent creations</h3>{!library.length&&<p className="text-[10px] text-[var(--muted)]">Your completed work will appear here.</p>}<div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{library.slice(0,20).map(a=><button key={a.id} className={'min-w-0 rounded-xl border p-4 text-left text-[10px] leading-5 '+(selected===a.id?'border-[var(--accent)] bg-[var(--accent-soft)]':'border-[var(--line)]')} onClick={()=>setSelected(a.id)}>{a.title}<span className="mt-1 block text-[var(--muted)]">{a.model}</span></button>)}</div></div></section></div></div>
}
