import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Icon} from './icons';
import {DownloadButton,type Download} from './Downloads';
import {friendlyError} from './Connected';
type Choice={id:string;name:string;detail?:string;modelId?:string;installed?:boolean;unsupported?:string};
export function StudioModelPicker({label,value,choices,onChange,downloads,onDownload,onRefresh}:{label:string;value:string;choices:Choice[];onChange:(id:string)=>void;downloads:Download[];onDownload:(id:string)=>Promise<unknown>;onRefresh?:()=>Promise<unknown>}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState<string[]>([]),[refreshing,setRefreshing]=useState(false),[position,setPosition]=useState({left:8,bottom:60,width:380,maxHeight:400});
 const trigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),id=useId();
 const close=()=>{setOpen(false);trigger.current?.focus()};
 useEffect(()=>{if(!open)return;const place=()=>{const rect=trigger.current!.getBoundingClientRect(),width=Math.min(420,window.innerWidth-16);setPosition({left:Math.max(8,Math.min(rect.left,window.innerWidth-width-8)),bottom:window.innerHeight-rect.top+8,width,maxHeight:Math.max(120,rect.top-16)})};place();const outside=(e:PointerEvent)=>{if(!panel.current?.contains(e.target as Node)&&!trigger.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',outside);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);panel.current?.querySelector('input')?.focus();return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true)}},[open]);
 const shown=choices.filter(c=>(c.name+' '+(c.detail||'')).toLowerCase().includes(query.toLowerCase()));
 async function download(modelId:string){setError('');setPending(p=>[...p,modelId]);try{await onDownload(modelId)}catch(e){setError(friendlyError(e))}finally{setPending(p=>p.filter(v=>v!==modelId))}}
 return <><button ref={trigger} type="button" aria-label={`${label}: ${choices.find(c=>c.id===value)?.name||'Choose model'}`} aria-haspopup="dialog" aria-expanded={open} aria-controls={open?id:undefined} className="!flex !min-w-0 !max-w-52 !items-center !gap-2 !rounded-full !px-3 !py-2 !text-[10px] text-[var(--muted)] hover:!bg-[var(--hover)]" onClick={()=>{setQuery('');setOpen(!open)}}><span className="truncate">{label==='Enhance model'?'Enhance · ':''}{choices.find(c=>c.id===value)?.name||'Choose model'}</span><Icon name="down" size={12}/></button>{open&&createPortal(<div ref={panel} id={id} role="dialog" aria-label={label} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close()}}} className="fixed z-[100] flex flex-col overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-2 text-[var(--text)] shadow-2xl" style={position}><div className="flex shrink-0 items-center justify-between px-2 py-2"><span className="text-xs font-medium">{label}</span><button aria-label="Close model picker" onClick={close}><Icon name="close" size={15}/></button></div><input className="!mb-2 !min-h-9 !rounded-xl !px-3 !py-2 !text-[11px]" aria-label={`Search ${label.toLowerCase()}`} placeholder="Search models…" value={query} onChange={e=>setQuery(e.target.value)}/>{error&&<p role="alert" className="px-2 py-2 text-[10px] text-red-400">{error}</p>}<div className="min-h-0 flex-1 overflow-y-auto overscroll-contain">{shown.map(c=>{const transfer=downloads.find(d=>d.modelId===c.modelId&&d.status==='active');return <div key={c.id} className={`flex items-center gap-2 rounded-xl p-2 ${value===c.id?'bg-[var(--accent-soft)]':'hover:bg-[var(--hover)]'}`}><button className="!min-w-0 !flex-1 !text-left" aria-pressed={value===c.id} onClick={()=>{onChange(c.id);close()}}><span className="block break-words text-[11px] leading-5">{c.name}</span><span className="block text-[9px] leading-5 text-[var(--muted)]">{c.unsupported||c.detail}{c.installed?' · Ready':''}</span></button>{c.modelId&&!c.installed&&<div className="w-32 shrink-0"><DownloadButton className="!w-full !rounded-lg !px-2 !py-2 !text-[10px]" item={transfer} disabled={!!c.unsupported||pending.includes(c.modelId)&&!transfer} onClick={()=>void download(c.modelId!)}>{pending.includes(c.modelId)&&!transfer?'Preparing…':'Download'}</DownloadButton></div>}</div>})}{!shown.length&&<p className="p-4 text-center text-[11px] text-[var(--muted)]">No matching models.</p>}</div>{onRefresh&&<button disabled={refreshing} className="mt-2 shrink-0 rounded-xl bg-[var(--hover)] px-3 py-2 text-[10px]" onClick={async()=>{setRefreshing(true);setError('');try{await onRefresh()}catch(e){setError(friendlyError(e))}finally{setRefreshing(false)}}}>{refreshing?'Loading…':'Refresh provider models'}</button>}</div>,document.body)}</>
}
