import {Children,isValidElement,useEffect,useRef,useState,type SelectHTMLAttributes} from 'react';
import {Icon} from './icons';
export function StudioSelect({children,value,onChange,disabled,...props}:SelectHTMLAttributes<HTMLSelectElement>){
 const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null);
 const options=Children.toArray(children).flatMap(child=>{if(!isValidElement(child)||child.type!=='option')return [];const option=child.props as {value?:string|number;children:React.ReactNode;disabled?:boolean};return [{value:String(option.value??option.children),label:option.children,disabled:option.disabled}]});
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',close);root.current?.querySelector<HTMLButtonElement>('[role=option][aria-selected=true]')?.focus();return()=>document.removeEventListener('pointerdown',close)},[open]);
 return <div ref={root} className="relative min-w-0" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);root.current?.querySelector('button')?.focus()}if(open&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const items=Array.from(root.current!.querySelectorAll<HTMLButtonElement>('[role=option]:not(:disabled)'));const i=items.indexOf(document.activeElement as HTMLButtonElement);items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus()}}}>
 <button type="button" disabled={disabled} aria-label={props['aria-label']||'Choose option'} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)} className="!flex !w-full !items-center !justify-between !gap-2 !rounded-xl !border !border-[var(--line)] !bg-[var(--surface)] !px-3 !py-2.5 !text-[11px]"><span className="truncate">{options.find(o=>o.value===String(value))?.label||'Choose…'}</span><Icon name="down" size={13}/></button>
 {open&&<div role="listbox" aria-label={props['aria-label']||'Options'} className="absolute left-0 right-0 top-full z-50 mt-1 max-h-60 overflow-y-auto rounded-xl border border-[var(--line)] bg-[var(--surface)] p-1 shadow-xl">{options.map(o=><button key={o.value} type="button" role="option" aria-selected={o.value===String(value)} disabled={o.disabled} className={`!block !w-full !rounded-lg !px-3 !py-2.5 !text-left !text-[11px] hover:!bg-[var(--hover)] focus:!bg-[var(--hover)] ${o.value===String(value)?'!text-[var(--accent)]':''}`} onClick={()=>{onChange?.({target:{value:o.value}} as any);setOpen(false);root.current?.querySelector('button')?.focus()}}>{o.label}</button>)}</div>}
 </div>
}
