import {useRef,useState} from 'react';
import {Icon} from './icons';
import {bridge,friendlyError} from './Connected';
export function UpdateIndicator({phase,message,percent,onSettings}:{phase:string;message:string;percent?:number;onSettings:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(!['downloading','ready','manual','error'].includes(phase))return null;
 const title=phase==='ready'?'Ready to install':phase==='manual'?'A new version is available':phase==='error'?'Update needs attention':'Downloading your update';
 async function action(){setBusy(true);setError('');try{if(phase==='ready')await bridge().installUpdate();else if(phase==='manual')await bridge().openReleases();else await bridge().checkUpdates()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 return <><button className="relative flex max-w-44 items-center gap-2 rounded-full bg-[var(--accent-soft)] px-3 py-2 text-[10px] text-[var(--accent)]" aria-label={title} data-tooltip={message} onClick={()=>dialog.current?.showModal()}><Icon name="download" size={17}/><span className="hidden sm:inline">{phase==='ready'?'Install update':phase==='manual'?'Update available':phase==='error'?'Update issue':Number.isFinite(percent)?`${percent}%`:'Updating…'}</span><span className="absolute right-0 top-0 h-2 w-2 rounded-full bg-[var(--accent)]"/></button><dialog ref={dialog} aria-labelledby="update-indicator-heading" className="m-auto w-[440px] max-w-[calc(100vw-24px)] rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6 text-[var(--text)] shadow-2xl backdrop:bg-black/30"><div className="flex items-start justify-between gap-4"><span className="rounded-2xl bg-[var(--accent-soft)] p-3 text-[var(--accent)]"><Icon name="download" size={25}/></span><button className="icon-button" aria-label="Close update details" onClick={()=>dialog.current?.close()}><Icon name="close" size={18}/></button></div><h2 id="update-indicator-heading" className="mt-5 text-lg">{title}</h2><p className="mt-4 text-xs leading-7">{message}</p>{phase==='downloading'&&<><progress className="mt-5 h-2 w-full accent-[var(--accent)]" max="100" value={percent}/><p className="mt-3 text-[10px] leading-6 text-[var(--muted)]">You can keep working. Orvio will notify you when installation is ready.</p></>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="mt-6 flex flex-wrap gap-3">{phase!=='downloading'&&<button className="primary" disabled={busy} onClick={()=>void action()}>{busy?'Please wait…':phase==='ready'?'Restart & install':phase==='manual'?'Download Mac installer':'Retry update'}</button>}<button className="secondary" onClick={()=>{dialog.current?.close();onSettings()}}>Update settings</button></div></dialog></>
}
