import {useEffect} from 'react';
import {PanelResize,usePanelWidth} from './PanelResize';
import {Brand} from './Onboarding';
import {Icon,type IconName} from './icons';
import {studioTools,type Page} from './tools';
import type {Preferences} from './store';
const primary:{name:Page;label:string;icon:IconName}[]=[{name:'Home',label:'Overview',icon:'home'},{name:'Chat',label:'Assistant',icon:'sparkles'},{name:'All tools',label:'All tools',icon:'grid'},{name:'Automations',label:'Publishing',icon:'calendar'},{name:'Models',label:'Model library',icon:'folder'},{name:'Integrations',label:'Connections',icon:'link'}];
export function WorkspaceSidebar({page,prefs,recent,paused,onOpen,onHelp,compact=false,onToggle}:{compact?:boolean;onToggle?:()=>void;page:Page;prefs:Preferences;recent:Page[];paused:boolean;onOpen:(page:Page)=>void;onHelp:()=>void}){
 const [width,setWidth]=usePanelWidth('orvio.navigation.width',245,205,360);
 useEffect(()=>{document.documentElement.style.setProperty('--navigation-width',width+'px')},[width]);
 const core=primary.some(item=>item.name===page)||page==='Settings';const current=studioTools.find(t=>t.name===page);const shortcuts=[...(!core&&current?[current]:[]),...[...new Set(recent.map(name=>name==='Images'||name==='Videos'||name==='Voice'?'Studio':name))].map(name=>studioTools.find(t=>t.name===name)).filter(t=>t&&t.name!==page&&!primary.some(p=>p.name===t.name))].filter(Boolean).slice(0,3) as typeof studioTools;
 return <aside className="sidebar !h-dvh !min-h-0 !overflow-hidden" data-compact={compact}>{!compact&&<PanelResize width={width} onChange={setWidth} side="right" label="Resize navigation" min={205} max={360}/>}<div className="shrink-0"><Brand/>{onToggle&&<button className="studio-sidebar-toggle" aria-label={compact?'Expand main sidebar':'Collapse main sidebar'} onClick={onToggle}><Icon name="menu" size={18}/></button>}<button className="workspace-switch !mb-5" onClick={()=>onOpen('Settings')}><span>{prefs.workspace.charAt(0).toUpperCase()}</span><div><b>{prefs.workspace}</b><small>Your creative workspace</small></div><Icon name="down" size={14}/></button></div><div className="min-h-0 w-full flex-1 overflow-y-auto overscroll-contain pb-5 [scrollbar-color:#45566a_transparent] [scrollbar-width:thin]"><div className="nav-group-label">WORKSPACE</div><nav aria-label="Main navigation" className="!mt-0">{primary.map(item=><button key={item.name} aria-current={page===item.name?'page':undefined} aria-label={item.label} title={item.label} className={page===item.name?'active':''} onClick={()=>onOpen(item.name)}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav>{shortcuts.length>0&&<><div className="nav-group-label !mt-7">RECENT TOOLS</div><nav aria-label="Recent tools" className="!mt-0">{shortcuts.map(tool=><button key={tool.id} title={tool.name} aria-label={tool.name} className={page===tool.name?'active':''} onClick={()=>onOpen(tool.name)}><Icon name={tool.icon}/><span>{tool.name==='Studio'?'Creative Studio':tool.name==='Downloader'?'Downloader':tool.name}</span></button>)}</nav></>}</div><div className="sidebar-bottom !mt-0 !shrink-0 !border-t !border-[#344353] !pt-3"><button className={'nav-secondary '+(page==='Settings'?'active':'')} title="Settings" aria-label="Settings" onClick={()=>onOpen('Settings')}><Icon name="settings"/><span>Settings</span></button><button className="nav-secondary" title="Help and resources" aria-label="Help and resources" onClick={onHelp}><Icon name="help"/><span>Help & resources</span></button><button className="profile !mt-2 !py-3" title={paused?'Publishing paused':'Open workspace settings'} onClick={()=>onOpen('Settings')}><span className="avatar">{(prefs.name||prefs.workspace).charAt(0).toUpperCase()}</span><div><b>{prefs.name||prefs.workspace}</b><small>{paused?'Publishing paused':'Orvio Studio · Free'}</small></div><Icon name="down" size={14}/></button></div></aside>
}
